### ISSUE TITLE
play-services-measurement provider ${applicationid} not being replaced

### ISSUE THREAD

**Issue by Disar** [googlesamples/unity-jar-resolver#1]
AndroidManifest.xml:36: Tag <provider> attribute authorities has invalid character '$'.

The docs mention this specifically but upon building the project the ${} is not replaced by the application bundle id.

I have no clue how to fix this. I know I can unpack the AAR file and adjust the manifest but I rather not. Any idea why this might happen?

Using unity 5.2.3 and the latest jar resolver.

**Comment by claywilkinson** [comment]
Is the bundle Id set in the player settings?  The way is should be working is that the play-services-measurement aar should be exploded into a directory, and then the AndroidManifest.xml should be updated.

And just to confirm:
 you have the latest version of the plugin?
The plugin exploded the the play-services-measurement.aar into a directory and removed the .aar?

**Comment by Disar** [comment]
Yes the bundle ID is set weeks ago =P.

So at first i was confused at why there was a folder being created every time, however it was empty no matter what.
I kept getting an error with "access denied" in the console about some zip stuff.
This might explain it all. So any idea why i'm getting the access denied?

**Comment by claywilkinson** [comment]
That sounds like the problem.  I don't know what is causing it, could it be that the directory is read-only, maybe from some version control?  If you can check the permissions of the Plugins/Android directory that would help, we could add the check and/or fix the permissions when processing the aar.

**Comment by Disar** [comment]
Alright, thanks will try that tomorrow. Ill give you an update.

**Comment by Disar** [comment]
So i just did a quick test and added the play-services-gcm  ( which automatically adds the measurement lib ) and while everything is fine : 
        Android Jar Dependencies: Resolution Complete
        Cleaning up exploded aars...

Nothing happens in the plugin folder. The aar is not removed and no additional folders are created.

**Comment by Disar** [comment]
ACK!

I think I found another error. it doesn't like the fact I have a space in one of my folder paths.

**Comment by claywilkinson** [comment]
Thanks for the update @Disar  - Which path contained spaces?  You mean your unity project like:
`C:\Projects\My Awesome Game\Assets\....`

**Comment by Disar** [comment]
It was more like

~c:\users\myusername\documents\**unity projects**\projectroot~
