### ISSUE TITLE
IOSResolver AssamblyName FileLoadException

### ISSUE THREAD

**Issue by abcjjy** [googlesamples/unity-jar-resolver#103]
https://github.com/googlesamples/unity-jar-resolver/blob/fbe00d8f0ae983912ad2320d5af24d7a653b1fdf/source/IOSResolver/src/IOSResolver.cs#L439

This will throw FileLoadException in case any code in the project trying to find a non existing assembly. I think it is better to catch the exception and return a null.

**Comment by stewartmiles** [comment]
@abcjjy what is the problem with throwing the exception?  I believe this should be caught by https://github.com/googlesamples/unity-jar-resolver/blob/fbe00d8f0ae983912ad2320d5af24d7a653b1fdf/source/IOSResolver/src/IOSResolver.cs#L510 if the Xcode API DLL isn't present?  Do you have a particular scenario you could share where this is problematic?

**Comment by abcjjy** [comment]
@stewartmiles ResolveUnityEditoriOSXcodeExtension is added to AppDomain.CurrentDomain.AssemblyResolve event. Indeed, IOSResolver itself won't cause any exception. 

However, the application code or third party code may try to resolve a non-exist assembly, which eventually triggers AssemblyResolve event and throw an exception.
