### ISSUE TITLE
(Firebase 4.4.2)  Version Handler "Update" Incorrectly renames generate_xml_from_google_services_json

### ISSUE THREAD

**Issue by PathToLife** [googlesamples/unity-jar-resolver#104]
Hi,
I found a silly bug in the version handler update (was updating due to firebase upgrade)

## Title sums it up,
Consequence: The project won't build, **and the build error mimics the _"Unable to find suitable JDK installation"_  error seen 2 years ago** so confuses the hell outta people trying the suggested fix!

## Reproduction steps:

1. Run the Update function seen below:
![image](https://user-images.githubusercontent.com/12622625/36607226-de2836d6-192a-11e8-9619-59845d2b98be.png)

2. Observe these two files go from this:
![image](https://user-images.githubusercontent.com/12622625/36607271-003c908c-192b-11e8-924a-ec22e6871257.png)
3. To this:
![image](https://user-images.githubusercontent.com/12622625/36607382-5f9ed88c-192b-11e8-96eb-0508c16c5de2.png)
(Console Log):
![image](https://user-images.githubusercontent.com/12622625/36607369-51e1b05c-192b-11e8-86dd-169b95845faf.png)

4. **RESTART UNITY to experience numbskull build error**
(Startup console log)
_\Assets\Firebase\Editor\generate_xml_from_google_services_json.exe required for Firebase Android resource generation._
![image](https://user-images.githubusercontent.com/12622625/36607609-f2b377fe-192b-11e8-9383-7e6e1c3c94f4.png)

5. Try to build
Observe this prompt Ok.
![image](https://user-images.githubusercontent.com/12622625/36624882-3e4a2d40-197a-11e8-9f52-6dec1ac5d318.png)
6. Set JDK
![image](https://user-images.githubusercontent.com/12622625/36607919-fe3e2488-192c-11e8-94d3-6cf8ab564234.png)
7. I'm sorry you what?
![image](https://user-images.githubusercontent.com/12622625/36607935-08f0aa2c-192d-11e8-930d-35642eb61664.png)
8. Rename the files back and restart unity.
9. Fixed. Go home for the weekend.

**Comment by stewartmiles** [comment]
@johnb003 did you see this in the most recent QA pass?

@PathToLife any chance there was something special about the version of Unity you're using here?  I'm surprised the Version Handler is touching that file :/

**Comment by stewartmiles** [comment]
Ah ok, it looks like the "Rename To Canonical Filenames" option is causing this :/  When changing from the default settings to:

<img width="299" alt="vhoptions" src="https://user-images.githubusercontent.com/6042948/36623320-65ec3f86-18b8-11e8-8ec7-3780ce2197f2.png">
 
Then running Version Handler > Update, *a load* of files get incorrectly renamed :(

**Comment by stewartmiles** [comment]
@PathToLife the workaround is to press the =Reset to Defaults= button for the moment.

**Comment by stewartmiles** [comment]
Problem is here https://github.com/googlesamples/unity-jar-resolver/blob/master/source/VersionHandlerImpl/src/VersionHandlerImpl.cs#L279 .  I guess if we're going to continue support parsing file metadata fields from filenames we should probably check that the fields are valid and actually fields rather than `just_a_filename_with_a_v_or_t_in_the_name`.

**Comment by johnb003** [comment]
@stewartmiles It looks like you already found the culprit, but to answer your question, no, it didn't come up in testing. We didn't have test coverage for that setting in version handler. I didn't have it enabled.

**Comment by stewartmiles** [comment]
@johnb003 it's always enabled :)  I guess the default config works fine, it's when the * Rename To Canonical Filenames* option is turned on where things go wrong.

**Comment by PathToLife** [comment]
Thanks for the help!

I wonder why * Rename To Canonical Filenames* option was turned on :/ was a fresh install..
(I had deleted play services resolver folder completely) settings must have been stored in a different directory.

**Comment by stewartmiles** [comment]
@PathToLife the settings can be applied globally (per Unity instance) or per project.  If you had global settings on that could have caused this to happen.  Regardless, this is definitely a bug that we need to fix.

**Comment by exzizt** [comment]
This is still an issue.
