### ISSUE TITLE
Resolver error when com.android.support:support-v4:+ Download v28.0.0-rc1

### ISSUE THREAD

**Issue by takaaptech** [googlesamples/unity-jar-resolver#106]
Hi!
I think the resolver now download the 28.0.0 rc1 file and then build error

Assets/Plugins/Android/com.android.support.appcompat-v7-28.0.0-alpha1.aar
....

https://stackoverflow.com/questions/49162538/cordova-build-android-unable-to-find-attribute-androidfontvariationsettings-a/49164398#49164398

**Comment by stewartmiles** [comment]
@takaaptech the resolver will download the library version(s) specified by a project's dependencies.  If a library is broken could you report the issue to the library owner?

If this is something specific to a Google Unity Plugin (e.g Firebase, Google Play Games, AdMob, Google Sign-in etc.) could you report the issue to the plugin owner?

**Comment by takaaptech** [comment]
Hi @stewartmiles Opp! I am sorry that not unity-jar-resolver problem!
So, Do you know a quick way to find what Google Unity Plugin require com.android.support:support-v4:+     ?
Or could you please help me where to find the logs file that can lead to that plugin?
Thank so much!

**Comment by stewartmiles** [comment]
Dependencies are managed via a couple of ways:
XML files https://github.com/googlesamples/unity-jar-resolver#usage
or the deprecated way (i.e code like this)
https://github.com/googlesamples/unity-jar-resolver/blob/master/sample/Assets/PlayServicesResolver/Editor/SampleDependencies.cs#L83

**Comment by takaaptech** [comment]
Hi @stewartmiles 
Thank so much!
After search code, I found OneSignal "Hard Code" the + inside the string 
   // Both are set to LATEST to ensure compability between other plugins.
   // PLAY_SERVICES_VERSION   - Tested with versions 10.2.1 to 11.2.0
   // ANDROID_SUPPORT_VERSION - Tested with versions 26.0.0 through 26.0.1
   private static readonly string PLAY_SERVICES_VERSION = "+";
   private static readonly string ANDROID_SUPPORT_VERSION = "+";
I just quick fix by pass the version into that value and can build now!
Thanks!
