### ISSUE TITLE
Readme mistake

### ISSUE THREAD

**Issue by TamaHobbit** [googlesamples/unity-jar-resolver#11]
"How it works" step 2c makes no sense: "If there"

**Comment by stewartmiles** [comment]
Fairly sure this is now fixed.

**Comment by TamaHobbit** [comment]
No, it's not. "If there" is the whole step, which does not make any sense.

Search for "If there are still possible versions to check" on [this page](https://github.com/googlesamples/unity-jar-resolver). It's step 2 ii c. I'd make a pull request but I don't know what that step is supposed to be.
