### ISSUE TITLE
'Resolution Successed' but all 'aar' files have been deleted

### ISSUE THREAD

**Issue by AndreyPostelzhuk** [googlesamples/unity-jar-resolver#110]
I've updated plugin to the latest version - '1.2.64'. I had an old version before that - '1.2.37'

1. Run 'resolve' first time an got an exception:
```NullReferenceException: Object reference not set to an instance of an object
GooglePlayServices.ResolverVer1_1.AarExplodeDataIsDirty (GooglePlayServices.AarExplodeData aarData)
GooglePlayServices.ResolverVer1_1.ProcessAars (System.String dir, System.Collections.Generic.HashSet`1 updatedFiles)
GooglePlayServices.ResolverVer1_1+<GradleResolution>c__AnonStorey14.<>m__1F (GooglePlayServices.Result result)
GooglePlayServices.ResolverVer1_1+<GradleResolution>c__AnonStorey14+<GradleResolution>c__AnonStorey15.<>m__28 ()
GooglePlayServices.PlayServicesResolver.PumpUpdateQueue ()
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:127)
```

2.  Need to restart Unity after that. Because 'Resolve' command doesn't work. 

3. Run 'resolve' again. It looks like all dependencies  are determinated correctly. All conflicts are resolved. But after that 'Deleting stale dependencies' deletes all 'aar' files.

**Comment by AndreyPostelzhuk** [comment]
I found a problem! The problem was with `plugins` directory. In our project directory named `plugins` with a small letter `p`. In plugin in one place is hardcoded `Plugins` with capital letter `P`. 
Because of that `copiedArtifactsSet.Contains()` always returns `false`.

**Comment by stewartmiles** [comment]
@AndreyPostelzhuk interesting, you're referring to the `Assets/Plugins/Android` directory?  Referenced on https://github.com/googlesamples/unity-jar-resolver/blob/038b5a60b9227a4c5901b1db58d7685984a6ae5d/source/PlayServicesResolver/src/SettingsDialog.cs#L96 ? Makes me wonder whether we should do case insensitive checks as well or spit out a warning.  It does seem a bit dangerous to me to assume that `Assets/Plugins/Android` and `Assets/plugins/Android` are the same directory.

**Comment by tallior** [comment]
@stewartmiles why do you think it's dangerous to assume that? i can't think of any developer that in his right mind will call the folder "plugins" instead of "Plugins" on purpose.

**Comment by AndreyPostelzhuk** [comment]
It's the same for Unity editor "plugins" and "Plugins". So I do call the folder "plugins" in my right mind on purpose.

**Comment by stewartmiles** [comment]
Ok I've "fixed" this now ;)

**Comment by mhm90** [comment]
Still having this issue with the latest version bundled in Firebase SDK unity package!
After Force Resolve it successfully copies all AARs, but then, it logs "Deleting stale dependencies:" and all the AARs deleted. 
I solved the issue by rename "plugins" folder to some other name and then renaming it to "Plugins" and the issue was resolved.

**Comment by Mecze** [comment]
In the process of updating my Project to Unity Version is 2019.1.2f1 I updated to version v1.2.109.0 (which came with the lastest Firebase Plugin):

When Resolving, the contents of "Assets/Plugins/Android/" (Which were resolved by previous Resolver version that was present on the project) gets deleted and it says "Resolution Succeded"
Of course, it does not build.

I tried to change the name of the folder "Plugins" as stated above with no use.

Could I get any help in this? Please?

**Comment by StijnPaladin** [comment]
I have the same issue, but when I tried multiple older versions to locate the problem, I saw this started happening from version `1.2.105` which has a log change:

> Android Resolver: If Plugins/Android/mainTemplate.gradle file is present and Gradle is selected as the build type, resolution will simply patch the file with Android dependencies specified by plugins in the project.

And indeed my `ProjectSettings/AndroidResolverDependencies.xml` has changed and now includes the dependencies there.

If you are using Gradle and have `Plugins/Android/mainTemplate.gradle` then this is probably the same for you.

**Comment by Mecze** [comment]
Sorry, didn't respond, my bad. Yes I saw that, the resolved added the 'compile' on the Gradle config file. It's working fine. It failed to compile because if other reasons, already corrected.
