### ISSUE TITLE
FAILURE: build failed with an exception.

### ISSUE THREAD

**Issue by AQaddora** [googlesamples/unity-jar-resolver#112]
Hey there!
Sorry if this matter is duplicated somewhere but I really couldn't find any solution for my problem. all of the solutions didn't work at all, I intended to use **facebook Sdk** with the **firebase authentication** plugin. and they both use the google jar resolver, it seems that the facebook sdk uses an older version of the Google-jar-resolver **1.62**, while firebase uses the latest **1.64**, I work on unity **2017.3** the latest version. and I keep getting this error: "`Error somewhere in the process of creating the gradle build, .. will copy the error in the end`"
I have downgraded the **Jdk to 1.8** version because of some other problem which was "Unable to list platform" and "Command Invoke failure", and I downgraded the sdk tools to 25.2.3 and deleted the build tool **28** from the sdk manager, as a part of that solution, now i have **25.0.3** and **27.0.3 Sdk** build tools

they are all common errors.
BUT I AM HAVING THEM ALL AT THE SAME TIME, I got really frustrated of this issue. this is holding me back... could anyone please help me!

`Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.

Error (-1):

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'GenGradle'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Traceback (most recent call last):
  File "<string>", line 475, in <module>
  File "<string>", line 468, in main
  File "<string>", line 260, in execute_gradle_build
RuntimeError: Failed running gradle build
generate_gradle_prebuild returned -1

UnityEngine.Debug:LogError(Object)
GooglePlayServices.<RunGenGradleScript>c__AnonStorey0:<>m__0(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
GooglePlayServices.CommandLineDialog:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
`

**Comment by stewartmiles** [comment]
It's hard to help diagnose what's going on without seeing your build logs in Unity (see https://docs.unity3d.com/Manual/LogFiles.html on how to get and share them)

Also, other things that may help:
- Share a minimal project (e.g take the Firebase Auth sample https://github.com/firebase/quickstart-unity/tree/master/auth/testapp , add the Facebook SDK, then Firebase SDK and see whether you can reproduce the problem).
- Share your operating system, Unity version etc.  Each Unity version comes with it's own special behavior.

It looks like you may be trying to use the Gradle prebuild - `generate_gradle_prebuild` is in your logs - have you tried to reset the Android Resolver settings to their default values under `Assets > Play Services Resolver > Android Resolver > Settings` ?

**Comment by AQaddora** [comment]
well, I use Unity2017.3.03f on windows 10.
I downloaded the test project, added the facebook sdl. add the fire base, deleted the obsolete jars by the respolver, I got an error about facebook.unity.settings.dll it says duplication when this happened before i deleted the Facebook folder in my Editor\Data\PlayBackEngine.
this time I have no folder to delete, although if i deleted the unityfasebook settings the error goes. and a bunch appears. anyways the same problem happened on the testapp you created  with the same error I will attach the Editor log file, so you can see.
isn't the Android resolver already on it's defaults!? I once messed up with the Version handler resolver, that's how i got it to delete the obsolete files. but i never played with the android resolver.. i will give that a shot.
mean while here is my  editor log. the same error as above heppenes
[Uploading Editor.log…]

**Comment by AQaddora** [comment]
[Editor.log](https://github.com/googlesamples/unity-jar-resolver/files/1885483/Editor.log)

**Comment by stewartmiles** [comment]
Yep you have Gradle prebuild enabled...

`Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.`

You need to restore the default settings of the Android resolver to disable this.

**Comment by AQaddora** [comment]
hey Resret Android resolver settings has worked for me (resolution succeeded).
But still I get this error, this one is strange it says: 
`Win32Exception: ApplicationName='cmd', CommandLine='/Cecho "xxx" | openssl base64', CurrentDirectory=''
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
Facebook.Unity.Editor.FacebookAndroidUtil.DoesCommandExist (System.String command)
Facebook.Unity.Editor.FacebookAndroidUtil.get_DebugKeyHash ()
Facebook.Unity.Editor.FacebookAndroidUtil.get_SetupProperly ()
Facebook.Unity.Editor.XCodePostProcess.OnPostProcessBuild (BuildTarget target, System.String path)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.Build.BuildPipelineInterfaces+AttributeCallbackWrapper.OnPostprocessBuild (BuildTarget target, System.String path) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:86)
UnityEditor.Build.BuildPipelineInterfaces.OnBuildPostProcess (BuildTarget platform, System.String path, Boolean strict) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:324)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`
what should I do in this situation
My android sdk works perfectly when it come to ordinary build, and the bundle ID is set in the player settings as in the firebase project. here is the new 
[Editor.log](https://github.com/googlesamples/unity-jar-resolver/files/1886024/Editor.log)

**Comment by AQaddora** [comment]
Well, thanks @stewartmiles for your help, I really appreciate it, everything is working perfectly fine now.. 💯
