### ISSUE TITLE
Is it possible to exclude Android dependency?

### ISSUE THREAD

**Issue by Silnar** [googlesamples/unity-jar-resolver#113]
I have an Android library `my-sdk` which depends on `facebook-android-sdk`.
When I import `Facebook Unity SDK`, Android build ends up with class duplicates.
How can I exclude `facebook-android-sdk` from `my-sdk` dependencies?
Something similar to gradle:
```gradle
compile("my-sdk:0.1.0") {
  exclude group: 'com.facebook.android'
}
```

**Comment by stewartmiles** [comment]
Hi @Silnar if your project is using this plugin (Android Resolver component) then you can remove dependencies by changing `*Dependencies.xml` in the project see https://github.com/googlesamples/unity-jar-resolver#usage .  If you wanted to do this non-destructively, we don't have a way to do this at the moment, we're happy to take pull requests though if you wanted to work on a solution.

**Comment by stewartmiles** [comment]
@Silnar I'm assuming you resolved your issue.  Please ping the issue if manually editing dependency files didn't work for you.
