### ISSUE TITLE
Resolve at build process command line export

### ISSUE THREAD

**Issue by Ekwav** [googlesamples/unity-jar-resolver#114]
I can't figure out how to invoke the resolution on my command line export.
I tried this example but it isn't possible to pass a void callback function as object:
https://github.com/googlesamples/unity-jar-resolver/blob/master/sample/Assets/PlayServicesResolver/Editor/ResolutionRunner.cs#L53

I also tried to invoke the function from the menu:
```
GooglePlayServices.PlayServicesResolver.Resolve(
			resolutionCompleteWithResult: (success) => {
				BuildYourApplication();
			},
			forceResolution: true);
```
But this didn't work either.
Can somebody please advise me on how to integrate a resolve into the build process?
Bit more detail about what I want to do.
I have mutiple quiz apps with the same unity code but different content and identifiers.
I want to switch the content and the identifiers and to change the identifiers in the aar files I need the solver.

**Comment by stewartmiles** [comment]
If you're already imported this plugin into the project (i.e you're not waiting for the VersionHandler to do its' thing) you can just call [PlayServicesResolver.Resolve](https://github.com/googlesamples/unity-jar-resolver/blob/a544b31fec9c2c05ac9fe7b77badd3793df7c891/source/PlayServicesResolver/src/PlayServicesResolver.cs#L865).

Cheers,
Stewart

**Comment by Ekwav** [comment]
Thanks Stewart, did turn out to be a version error. One Dependency had a wanted an older version than was imported. I am now using that `PlayServicesResolver.Resolve`. :smile:
