### ISSUE TITLE
PlayServicesResolver polling allocates 1.4kb every editor frame

### ISSUE THREAD

**Issue by jjlehtinen** [googlesamples/unity-jar-resolver#119]
## Issue
Even with auto-resolution disabled the polling functionality in PlayServicesResolver allocates 1.4kb of garbage every frame when the Unity editor is open and the user is not doing anything.

Following is a screenshot from the Unity profiler window:

![screen shot 2018-05-16 at 13 07 11](https://user-images.githubusercontent.com/31004317/40110987-1bf32ae2-590a-11e8-8fbe-6b32b55e8823.png)

and this happens on every frame.

Unity version: 2017.4.3f1
Play-Services-Resolver version: 1.2.62.0

## Expected result
With auto-resolution disabled no garbage will be generated by PlayServicesResolver.

## Actual result
With auto-resolution disabled PlayServicesResolver still keeps polling the build system and bundle ids on every editor frame and allocates garbage.

**Comment by stewartmiles** [comment]
@jjlehtinen even with auto-resolution disabled we have components that depend upon events that are triggered on bundle ID etc. changes.  Are you saying it's leaking 1.8Kb per frame?   AFAIK we don't hold onto anything that would cause that to happen.

**Comment by stewartmiles** [comment]
@jjlehtinen if you're still having an issue here lmk and we'll reopen this.
