### ISSUE TITLE
Register my aar in Dependencies.xml

### ISSUE THREAD

**Issue by viguysentertainment** [googlesamples/unity-jar-resolver#122]
Hi all,
I wrote an android plugin and export it to .aar file. But i don't know how to add my .aar file in Dependencies.xml as in the tutorial.
Has anybody got suggestions?
Thanks!
LinhVT

**Comment by stewartmiles** [comment]
https://github.com/googlesamples/unity-jar-resolver#usage

**Comment by stewartmiles** [comment]
@viguysentertainment haven't heard from you in a while, I'll assume my response solved your issue.
