### ISSUE TITLE
Mixed dependency versions resolve incorrectly.

### ISSUE THREAD

**Issue by JSC-Sparkling** [googlesamples/unity-jar-resolver#123]
(Using resolver v1.2.59)
When two different *Dependencies.xml each depend on different play-services AARs with a different version, the resolver simply takes the highest version available, but fails to correctly resolve all dependencies voor the lower version.

For example:

SomeDependencies.xml (snippet):
```
...
<androidPackage spec="com.google.android.gms:play-services-analytics:8.4+">
...
```
SomeOtherDependencies.xml (snippet):
```
...
<androidPackage spec="com.google.android.gms:play-services-ads:9.+">
...
```

When the resolver runs, it'll determine the highest version is 9.8.0 (due to the `SomeOtherDependencies.xml`) and it'll resolve all `play-services-ads` dependencies correctly, but the `play-services-analytics`, which only requires `8.4+` (according to `SomeDependencies.xml`), will be resolved as-if it were `8.4` instead of `9.8.0` (at least, that's the hunch I have).

I know for a fact¹ that between 8.4 and 9.8.0 a change has occured, specifically regarding the `play-services-analytics`. `play-services-analytics` received two new dependencies, one of which is `play-services-analytics-impl`.

Due to the resolver thinking it can resolve analytics as 8.4, and (later in its resolution process) deciding to bump all to 9.8 (without back-tracking earlier, possibly lower version, dependencies), the `play-services-analytics-impl` is incorrectly omitted from the dependency resolution, and if already present, it'll be incorrectly removed.

¹ Sources of the facts:
8.4 compile dependencies can be found here: https://mvnrepository.com/artifact/com.google.android.gms/play-services-analytics/8.4.0
9.8 compile dependencies can be found here:
https://mvnrepository.com/artifact/com.google.android.gms/play-services-analytics/9.8.0

**Comment by stewartmiles** [comment]
@JSC-Sparkling for versions of Google Play services below 15 (see https://github.com/googlesamples/unity-jar-resolver/blob/0c6493a7dc6daf644456fa98e337a475dc488678/source/PlayServicesResolver/scripts/download_artifacts.gradle#L392 ) all packages in Google Play services are pinned to the highest version specified (see the test case here https://github.com/googlesamples/unity-jar-resolver/blob/0c6493a7dc6daf644456fa98e337a475dc488678/source/PlayServicesResolver/scripts/download_artifacts.gradle#L867 ) if you're seeing other behavior then it may be that the resolved package(s) in your project are not being updated because they're not labeled with the "gpsr" label (see https://github.com/googlesamples/unity-jar-resolver/blob/0c6493a7dc6daf644456fa98e337a475dc488678/source/PlayServicesResolver/src/PlayServicesResolver.cs#L291).

**Comment by JSC-Sparkling** [comment]
After updating the resolver to v1.2.60 the issue resolved itself and the android jar resolution added the correct AARs to the project.
Therefore I think the solution is as simple as updating the resolver we're currently using to a newer version.

**Comment by JSC-Sparkling** [comment]
After some further investigation I've found that the latest version (v1.2.72) do has issues with resolving mixed dependencies while v1.2.60 does not have this issue.

[MixedDependencyVersionsBug.zip](https://github.com/googlesamples/unity-jar-resolver/files/2084143/MixedDependencyVersionsBug.zip)
This zip contains an example unity project that contains the bug.
What's in this project:
Two `*Dependencies.xml` files, one containing `ads 8.4`+ and one containing `analytics 8.4+` and one `ThirdPartyDependencies.cs` which'll register a dependency on `ads 9.+` through reflection.
Once running the resolver only the 8.4 aars are added. It looks like the 9.+ is completely ignored, although when looking at the `ProjectSettings/AndroidResolverDependencies.xml` the 9.+ package is correctly listed, yet it's being completely ignored by the resolver.

**Comment by stewartmiles** [comment]
Running the gradle script with my latest (yet to be published) changes to fix #127 I see the following:

```
$ ~/dev/src/unity-jar-resolver/gradlew -b ./download_artifacts.gradle -PPACKAGES_TO_COPY='com.google.android.gms:play-services-ads:9.+;com.google.android.gms:play-services-analytics:8.+' -PTARGET_DIR=download_artifacts_test_output/
:copyPackages
Copied artifacts:
com.android.support.support-annotations-24.0.0.jar
com.android.support.support-v4-24.0.0.aar
com.google.android.gms.play-services-ads-9.8.0.aar
com.google.android.gms.play-services-ads-lite-9.8.0.aar
com.google.android.gms.play-services-analytics-9.8.0.aar
com.google.android.gms.play-services-analytics-impl-9.8.0.aar
com.google.android.gms.play-services-base-9.8.0.aar
com.google.android.gms.play-services-basement-9.8.0.aar
com.google.android.gms.play-services-clearcut-9.8.0.aar
com.google.android.gms.play-services-gass-9.8.0.aar
com.google.android.gms.play-services-tasks-9.8.0.aar

Modified artifacts:
com.google.android.gms:play-services-analytics:8.+ --> com.google.android.gms:play-services-analytics:9.+


BUILD SUCCESSFUL

Total time: 3.091 secs
```

So it appears to be doing the right thing.  I'll take a look at the code that adds dependencies programmatically so see whether that could be causing a problem.

**Comment by stewartmiles** [comment]
The problem isn't in the C# component of the plugin, looks like everything added via reflection ends up in the list of dependencies in my test.  However, the order of dependencies on the command line does change such that...

```com.google.android.gms:play-services-games:9.+;com.google.android.gms:play-services-games:8.+```

resolves 8.+ and

```com.google.android.gms:play-services-games:8.+;com.google.android.gms:play-services-games:9.+```

resolves 9.+ :(

Taking a look.

**Comment by stewartmiles** [comment]
https://github.com/googlesamples/unity-jar-resolver/blob/0c6493a7dc6daf644456fa98e337a475dc488678/source/PlayServicesResolver/scripts/download_artifacts.gradle#L732 appears to be deduping the set of packages and taking the last version specified.

**Comment by JSC-Sparkling** [comment]
@stewartmiles From your replies it seems that each individual part (the gradle download, the de-duping etc) should be correctly, yet the project I've added in my previous post does not.

To help the bug investigation, these are the exact steps I've completed to encounter the bug:
1. Download & unzip the sample project
2. Force resolve android dependencies (Assets -> PSR -> Android -> Force Resolve)
3. It won't resolve, since the android platform was not selected
4. Change the project platform to Android (File -> Build Settings -> Select Android -> Switch Platform)
5. Force resolve android dependencies again (Assets -> PSR -> Android -> Force Resolve)
6. Inspect the Assets/Plugins/Android folder and notice only the 8.4 dependencies are present (9.8 are completely missing, although there is a C# file which adds such dependencies through reflection)

In recent days we've been looking again into this and we had a hunch that in this particular case it might have to do with the platform switching. Because Unity will reload and recompile scripts, I think the dependencies injected through reflection get lost somehow.

In another test case when updating the PSR to a higher version (e.g. 1.2.59 to 1.2.72), I've encountered similar (to the example project) issues.
The only workaround I've found so far was as following:
1. Delete the PSR folder
2. Close unity completely (to allow unloading of dlls that are loaded in memory)
3. Open unity again
4. Import the new PSR (using the unitypackage)
5. (Force) Resolve Android the dependencies

**Comment by stewartmiles** [comment]
@JSC-Sparkling oh it's definitely a problem and I believe I've fixed it.
