### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by sorencoder** [googlesamples/unity-jar-resolver#125]
> To build this plugin from source you need the following tools installed:
> 
> Unity (with iOS and Android modules installed)
> You can build the plugin by running the following from your shell (Linux / OSX):
> 
> ./gradlew build && ./gradlew postbuild
> or Windows:
> 
> ./gradlew.bat build & ./gradlew.bat postbuild
> The postbuild target packages the plugin for redistribution:
> 
> Updates play-services-resolver-*.unitypackage
> Copies the unpacked plugin to the exploded directory.

I'm on Windows 10. After entering the commands, it says that it cannot find Unity editor. But I have Unity installed. How can I solve this issue?

**Comment by stewartmiles** [comment]
You can set the `UNITY_EXE` variable to specify your Unity executable location. 
https://github.com/googlesamples/unity-jar-resolver/blob/master/build.gradle#L34
There are a load of other variables in there to configure other required options.
