### ISSUE TITLE
Does not bump pre-15 versions to 15+

### ISSUE THREAD

**Issue by jkasten2** [googlesamples/unity-jar-resolver#127]
## Issue
In Version 12.x and older of GMS and Firebase versions must match exactly with all modules under these groups. This pre-12 logic works correctly in version 1.2.72.0 of this resolver. However if one plugin uses 15 and another is still requesting version 12 or older than we get a mixture of versions. If one library goes to 15+ we need to bump all to 15+.
Semantic versioning schema the Google library team noted in this blog post for reference on the version 15+ changes;
https://android-developers.googleblog.com/2018/05/announcing-new-sdk-versioning.html

## Reproducing Issue
**1. Create `*Dependency.xml` files**
* 1A. `Assets/PluginA/Editor/PluginADependencies.xml`
```xml
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-games:12.0.1" />
  </androidPackages>
</dependencies>
```
* 1B. `Assets/PluginB/Editor/PluginBDependencies.xml`
```xml
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-gcm:15.0.1" />
  </androidPackages>
</dependencies>
```

2. Import [play-services-resolver-1.2.72.0.unitypackage](https://github.com/googlesamples/unity-jar-resolver/blob/master/play-services-resolver-1.2.72.0.unitypackage)
3. File > Build Settings... - Select Android and Press "Switch Platforms"
4. Run Assets > Play Services Resolver > Android Resolver > Force Resolve
5. Observer the `Asserts/Plugins/Android` folder.
6. **Problem** - We have `com.google.android.gms.play-services-gcm-15.0.1` and `com.google.android.gms.play-services-games-12.0.1`
![image](https://user-images.githubusercontent.com/645861/41565420-93063fc8-730b-11e8-9e97-0483cdb9b02f.png)
7. **Exepected** - All `com.google.android.gms.play-services-*` files should be version 15.0.0 or newer.

## Additional notes
This library was updated to loosen the version locking on 15+ in commit 0c6493a7dc6daf644456fa98e337a475dc488678 but it seems it did not account a mixture of below and above / at  15 in the same project.

Also, this should have the same effect for Firebase libraries.

**Comment by stewartmiles** [comment]
@jkasten2 thanks for the report, we definitely - and unfortunately - missed this case.  You're right if any components specify versions of Google Play Services > 15 everything should start using free floating versions as specified by module POM files.  We'll take a look.

**Comment by jkasten2** [comment]
@stewartmiles Thanks for the super quick turn around on implementing this! 👍

**Comment by stewartmiles** [comment]
@jkasten2 don't praise me yet ;) Are you sure it works for your use case?

**Comment by jkasten2** [comment]
@stewartmiles Just tested 1.2.75.0 in my example project and can confirm this scenario is now fixed
