### ISSUE TITLE
PlayResolver ask for jar which not exist !!

### ISSUE THREAD

**Issue by khaaaniii** [googlesamples/unity-jar-resolver#128]
the following error when I want to resolve !

 `FAILURE: Build failed with an exception.

* Where:
Build file '..\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle' line: 1222

* What went wrong:
A problem occurred evaluating root project 'PlayServicesResolverGradle'.
> Could not resolve all dependencies for configuration ':userPackagesToQuery2'.
   > Could not find play-services-tasks.jar (com.google.android.gms:play-services-tasks:15.0.1).
     Searched in the following locations:
         https://maven.google.com/com/google/android/gms/play-services-tasks/15.0.1/play-services-tasks-15.0.1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__24(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__2D()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()`

the "play-services-tasks-15.0.1.jar" not exist in the given url but the "play-services-tasks-15.0.1.aar
" exists.

**Comment by stewartmiles** [comment]
@khaaaniii how did you reproduce this problem?

The packaging in the POM (https://maven.google.com/com/google/android/gms/play-services-tasks/15.0.1/play-services-tasks-15.0.1.pom) points at the AAR so it should be fetching the AAR rather than the JAR.  Also, it's very odd this is failing on https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/scripts/download_artifacts.gradle#L1222 as this uses the lenient configuration which is not supposed to fail if an artifact is missing.

**Comment by stewartmiles** [comment]
When fetching that artifact manually using the script...

```
$ rm -rf tmp; ./gradlew -b ./source/PlayServicesResolver/scripts/download_artifacts.gradle -PPACKAGES_TO_COPY=com.google.android.gms:play-services-tasks:15.0.1 -PTARGET_DIR=tmp
:copy_android.arch.core.common-1.0.0.jar
:copy_android.arch.lifecycle.common-1.0.0.jar
:copy_android.arch.lifecycle.runtime-1.0.0.aar
:copy_com.android.support.support-annotations-26.1.0.jar
:copy_com.android.support.support-compat-26.1.0.aar
:copy_com.android.support.support-core-ui-26.1.0.aar
:copy_com.android.support.support-core-utils-26.1.0.aar
:copy_com.android.support.support-fragment-26.1.0.aar
:copy_com.android.support.support-media-compat-26.1.0.aar
:copy_com.android.support.support-v4-26.1.0.aar
:copy_com.google.android.gms.play-services-basement-15.0.1.aar
:copy_com.google.android.gms.play-services-tasks-15.0.1.aar
:copyPackages
Copied artifacts:
android.arch.core.common-1.0.0.jar
android.arch.lifecycle.common-1.0.0.jar
android.arch.lifecycle.runtime-1.0.0.aar
com.android.support.support-annotations-26.1.0.jar
com.android.support.support-compat-26.1.0.aar
com.android.support.support-core-ui-26.1.0.aar
com.android.support.support-core-utils-26.1.0.aar
com.android.support.support-fragment-26.1.0.aar
com.android.support.support-media-compat-26.1.0.aar
com.android.support.support-v4-26.1.0.aar
com.google.android.gms.play-services-basement-15.0.1.aar
com.google.android.gms.play-services-tasks-15.0.1.aar


BUILD SUCCESSFUL

Total time: 2.77 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
```

so it's working from the script.  Could you turn on verbose debugging in the *Android Resolver* settings and share the Unity log?

**Comment by stewartmiles** [comment]
@khaaaniii since I haven't heard from you, I'll assume your problem is solved.
