### ISSUE TITLE
Mixed Dependency Versions bugs 2.0

### ISSUE THREAD

**Issue by JSC-Sparkling** [googlesamples/unity-jar-resolver#130]
@stewartmiles The change previously marked as fixed in https://github.com/googlesamples/unity-jar-resolver/issues/123 (and released as resolver v1.2.75) seems to have broken something that wasn't broken in resolver v1.2.72.

Example project containing the bugs:
[MixedDependencyVersionBug_v1.2.75.zip](https://github.com/googlesamples/unity-jar-resolver/files/2145677/MixedDependencyVersionBug_v1.2.75.zip)

The example contains the following dependencies:
`<androidPackage spec="com.google.android.gms:play-services-ads:8.4+">`
`<androidPackage spec="com.google.android.gms:play-services-ads:9.+">`
`<androidPackage spec="com.google.android.gms:play-services-analytics:11.8+">`

The resolution actually failed completely with the following error:
```
Resolution failed

Failed to fetch the following dependencies:
com.google.android.gms:play-services-clearcut:11.8+
````

After some research (mainly looking at the dependencies listed in mvnrepository.com) I figured out that `clearcut` was added for `ads 9.8` (see: https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads/9.8.0) and removed again later on (somewere in version 11.1+ ; but added again at 15.0.1 but this addition is irrelevant in this particular case, source: https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads/11.8.0).

From your previous replies (in issue 123) I've learned that the resolver simply bumps to the highest version, which would be (looking at the 3 dependencies mentioned above) v11.8 ; which is correct and should indeed be used.
Yet the resolver forgets to actually check the required dependencies for the final version it has chosen to resolve.

What I believe that happens is that it find ads 9.8, looks up the dependencies of ads 9.8 and adds it to a list. Then later decides to has to bump the version to 11.8, without re-evaulating the actual dependencies of ads 11.8 and simply bumping the sub-dependencies (obtained based on 9.8) to 11.8. And then obviously clearcut 11.8 won't exist, because it simply isn't a dependency of ads 11.8 anymore in the first place.

Perhaps it could also have something to do with the fact that 2 version increments occur throughout the resolution process, first from 8.4+ to 9.+ (9.8) and then from 9.+ (9.8) to 11.8+

**Comment by JSC-Sparkling** [comment]
A similar issue (not bumping pre-15 to 15+, just like issue https://github.com/googlesamples/unity-jar-resolver/issues/127) occurs when a more than 2 different versions of dependencies are required.
For example when having the following dependencies:
```
com.google.android.gms:play-services-ads-lite:10.2.1+;com.google.android.gms:play-services-basement:10.2.1+;com.android.support:support-v4:24.2.0+;com.google.android.gms:play-services-basement:11.0.1+;com.google.firebase:firebase-analytics:16.0.1;com.google.firebase:firebase-core:16.0.1;com.google.firebase:firebase-analytics-unity:5.1.1;com.google.android.gms:play-services-base:15.0.1;com.google.firebase:firebase-common:16.0.0;com.google.firebase:firebase-app-unity:5.1.1;com.google.firebase:firebase-config:16.0.0;com.google.firebase:firebase-config-unity:5.1.1;com.google.android.gms:play-services-ads:12.0.1;com.android.support:support-v4:26.0.2;com.google.android.gms:play-services-ads-identifier:15.0.1.+
```

With all those dependencies, the resolution occurs incorrectly and ads:12.0.1 (and other aars too) is added instead of expected 15.0.1.

**Comment by stewartmiles** [comment]
@JSC-Sparkling thanks for the report.  I think it's due to https://github.com/googlesamples/unity-jar-resolver/blob/49653f10f751728819451ac4a190f1bdc648a7f7/source/PlayServicesResolver/scripts/download_artifacts.gradle#L627 , will need to write a test for this.  At the moment it looks like I'm adding transitive dependencies of version locked artifacts to the set to fetch and - as you point out - not removing transitive dependencies when conflicts are found and the version expression is made less restrictive.

**Comment by JSC-Sparkling** [comment]
@stewartmiles, this bug still persists in v1.2.80; Is there any ETA on when it'll be fixed?

**Comment by JSC-Sparkling** [comment]
With some more fidling around I have a hunch that I've narrowed it down to the fact that `9.+` is what actually breaks the resolution process, while it all resolves as expcted when using `9.0+` . It seems that that `+` cannot be placed just anywhere and as soon as It's located at a position where a number is expected, it goes wrong. `.+` and `.0+` should probably be considered the same thing.

**Comment by cometa93** [comment]
It's impossible to use JarResolver with it... for example when firebase is using version 16.0.2 then all google play services are tried to be resolved with same version...

**Comment by JSC-Sparkling** [comment]
@cometa93 The example is flawed, because not all play services have to be 16.0.2 ; they have to be atleast 15+ because from 15+ google has decided to change the versioning to SemVer (see release notes of May 2nd 2018: https://developers.google.com/android/guides/releases#may_2_2018).  
Because of this version change, a combination of play services below v15 and above v15 cannot, and should not occur because below v15, every aar has to be the same version (as you've mentioned). Atleast, that's how I understood how it should be working (correct me if I'm wrong).

**Comment by dfurmanGS** [comment]
Yeah, you got right about an versioning, but the jar resolver is trying to download, version equal like (before v15) and by requiring firebase 16.0.2 it's trying to download the same version for all play-services, which are not existing ( or at least not exists on Maven repository)

**Comment by JSC-Sparkling** [comment]
@dfurmanGS It only does that if your play service resolver's (PSR) version is too low. The particular bug/issue you're describing has been reported in https://github.com/googlesamples/unity-jar-resolver/issues/127 and fixed in v1.2.75 ; The bug related to mixed version I'm describing in this issue are actually different from what issue #127 describes.

**Comment by dfurmanGS** [comment]
yup but i did resolve on 1.2.79 and still that happened. It was included in newest Firebase.

**Comment by dfurmanGS** [comment]
yup but i did resolve on 1.2.79 and still that happened. It was included in newest Firebase.

EDIT:

When i'll have computer nearby, i'll update the plugin from scratch again. And will make sure ok?

**Comment by dfurmanGS** [comment]
@JSC-Sparkling I have to admit, on second computer everything resolved well. I think I had some garbage or wrong SDK configuration or something... sorry for misleading. 

Have a nice day.

**Comment by JSC-Sparkling** [comment]
@exzizt You're correct, it seems that you're also suffering from some form of mixed dependencies bug.  
As I've explained in a previous post, mixing 15+ and 15- versions doesn't work, and for some reason the PSR does decide to mix them (which is a bug).  
Your Auth is 11.8.0, while other dependencies are 15+ and that combination/mix is incompatible and indeed causes crashes.

**Comment by exzizt** [comment]
@JSC-Sparkling It is very strange though because none of my packages specify an Auth with version 11.
The packages with their dependency files (defaults) are below:

Firebase
---------
AppDependencies.xml
![image](https://user-images.githubusercontent.com/17113094/43606819-4ecf30ee-9651-11e8-96d9-e90662bff5c5.png)

AuthDependencies.xml
![image](https://user-images.githubusercontent.com/17113094/43606839-5bdb8e4a-9651-11e8-80b5-70521942c1f5.png)

DatabaseDependencies.xml
![image](https://user-images.githubusercontent.com/17113094/43606868-6ca0beb2-9651-11e8-996e-18792ed5ef86.png)


Google
--------
GoogleMobileAdsDependencies.xml
![image](https://user-images.githubusercontent.com/17113094/43606911-84214160-9651-11e8-8e5e-d168f1817e18.png)

GooglePlayGamesPluginDependencies.xml
![image](https://user-images.githubusercontent.com/17113094/43606930-92677226-9651-11e8-8fcd-7527338ff98a.png)

**Comment by ethan-tqa** [comment]
Another victim of wrong mixed dependencies reporting in. My setup is similar to exzizt, suffers from the same problem, player-services-* version 11 is selected instead of 15.

**Comment by JSC-Sparkling** [comment]
@exzizt google play games is your issue. If you'd check out that m2repository directory in your project, you'll find a `.pom` file which specifies sub-dependencies, which have a version of `11.6+`. Due to this mixed dependencies bug in the resolver, it decides to only go up to `11.8.0` and stick right there, instead of going all the way up to `15.0.1+` as it's supposed to do.  
  
Ideally you'd never want to mess with a plugin's dependencies in the first place and keep the vanilla files (simply because the next dev that comes around to update it, probably doesn't know about the custom changes made and will override your changes when importing the new unitypackage of the plugin).  
  
But there is a workaround by adding each dependency mentioned in the `.pom` file explicitly in the `GooglePlayGamesDependencies.xml` and changing the version from `11.6+` to `15.0.1+`, this'll trick the resolver into getting everything at `15.0.1+` as it's supposed to.

**Comment by exzizt** [comment]
@JSC-Sparkling 

Gonna try this out and I'll edit my post in a few minutes or so to see if I can get it working!

**Comment by WTF-Grinch** [comment]
Thanks guys it got me crazy at the beginning and then changed .pom files to 15.0.1+ and force resolve and yeaaayyy its works !

**Comment by stewartmiles** [comment]
Apologies for the radio silence, been fighting other fires.  I'll have a patch out shortly that should help with the couple of issues referenced in this bug.

1. Mixing version locked / non-version locked packages results in an incompatible set of libraries being selected.
1. Referencing a non-existent package (e.g `com.google.android.gms:play-services-ads-identifier:15.0.1.+`) causes conflict resolution to fail.

**Comment by JSC-Sparkling** [comment]
I've un-patched one of our projects to test resolver v1.2.83.0 and it seems that all issues mentioned in this topic have indeed been fixed.  
The weird `9.+` works fine and the resolver decides to take the correct version (aar's v11.8.0 for the example project attached in the first post)  
The second issue with mixing `15-` and `15+` dependencies is also properly fixed and the resolver does choose to take a 15+ version as expected.  
Even the GPGS issue for which I've posted a work-around for @exzizt's issue now works properly without the work-around applied.  
  
@stewartmiles I do have one concern remaining, the resolver now seems to make anything `15+` version to a `+` version and thus takes the latest version of those AARs. This might cause issues with plugins that request very specific versions, for example `Firebase Unity 5.2.0` has its own code, supplied through local folders/unity package you import, but adds dependency files for the native-android (gms) aars with specific versions. That 5.2.0 version code is probably tailored specifically to work with the mentioned versions in the relevant `*Dependencies.xml`, but probably isn't made to work with newer versions.

**Comment by stewartmiles** [comment]
@JSC-Sparkling yeah still not great at the moment when pre-15 and post-15 versions of gmscore are mixed.  w.r.t the Android libraries shipped with the Firebase Unity plugin, they use external APIs available in the Android Firebase SDK so things will continue to work until the next breaking change which is typically scheduled around once a year.  So as long as a user doesn't resolve again after the breaking change, things will be just fine (tm).

We're currently looking at adding Maven BOM support to Firebase's Android SDK which would make things a little better since it would be possible to at least scan through the range of Firebase SDKs available to see whether they are compatible with the other Google Play Services dependencies in the project.  This would minimize the chances of selecting a package that has a breaking change w.r.t the Unity SDK.

I guess another thing we could consider is adding support for rewriting `*Dependencies.xml` files with the versions of components that were resolved.  This would allow users to then run the resolver again without fear of it pulling a newer breaking version.

**Comment by JSC-Sparkling** [comment]
@stewartmiles This breaking change once a year sounds scary if the resolver always updates to the latest version of a specific aar. It would be less scary if the resolver would cap/stop at the specified version.  
  
Especially because the Firebase Unity SDK actually has `*Dependencies.xml` files without a `+` in the versioning, and yet the resolver goes beyond this version.  
Perhaps this is bug in the resolver?  
  
It's not only happening with the Firebase Unity SDK, but also occurs in the GPGS's Unity SDK where versions are listed as `Major.Minor+` which indicates that the minor can be bumped to the latest, but a major version should never be increased beyond the version listed in the dependency spec (except when 15+ and 15- are mixed, then it should go to the highest `15.x.y` (aka `[15.0.1, 16.0.0)`) but shouldn't go to 16+, which it currently does). - Please correct me if I'm wrong in my assumptions.

I wouldn't be a big fan of the resolver rewriting the `*Dependencies.xml` since those files are often delivered within a Unity package and personally I have an approach to not mess with plugin files unless there is absolutely no other option.  
Simply because any changes made, would need to be evaluated again every time the plugin is updated, which complicates the update process and increases the development time required to update a plugin.  
  
From what I've seen the resolver do, I think its approach to how ti handles 15+ versions should be adjusted/fixed, because it simply replaced them with `+` (aka `LATEST`) while it should more probably adhere better to the specified versions, even at 15+. As far as my own logic goes, any plugins that specifies a 15- version or dependency should be bumped to `[15.0.1, 16.0.0)` instead of `+` when there's ANY other dependency of 15+.

**Comment by stewartmiles** [comment]
@JSC-Sparkling the resolver bumping to the latest version in an attempt to produce *something* that works which addresses, I would estimate, about 90% of the developer audience's needs.  Many Unity devs have no idea what Android libraries are and having them hack around in xml files or code to change mystical version numbers is beyond many folks interest and abilities.

The Android Resolver reports warnings when it modifies the set of dependencies included to find a non-conflicting set.  More studious developers can use this as a signal to modify their *Dependencies.xml files to select the set they want or they can resolve once and not again until they add a new library.

I could imagine that adding support for a flag to turn off the logic that auto-upgrades dependencies may be useful though.

**Comment by JSC-Sparkling** [comment]
@stewartmiles I've seen that v1.2.88 attempts to fix some version issues, but it also re-introduces the bug I've described in the post of this topic.

**Comment by stewartmiles** [comment]
@JSC-Sparkling it sounds like this isn't covered by the tests in https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/scripts/download_artifacts_test.gradle .   We'll have to add tests for the specific packages in the original case you provided.  You're right that multiple version changes occur in the process, each time all top level dependencies end up at version "+", transitive dependencies start being modified and explicitly added which could lead to the scenario you've described.

**Comment by stewartmiles** [comment]
I have a fix pending for this, going through review at the moment.
