### ISSUE TITLE
Gradle failed to fetch dependencies.

### ISSUE THREAD

**Issue by InfiniteGamesStudio** [googlesamples/unity-jar-resolver#132]
**i am using**
**jdk1.8.0_172
Unity 2017.1.0p5**
and download latest admob SDK from this link
**https://github.com/googleads/googleads-mobile-unity/releases/tag/v3.14.0**
and after In the Unity editor, select **Assets > Play Services Resolver > Android Resolver > ForceResolve**
 below error comes in unity.
(Thanks in advance to Help)

**Error No 1**

Failed to run 'D:\Unity C\UnityProjects\RFPS Practice Game\AdsPakage\Temp\PlayServicesResolverGradle\gradlew.bat -b "D:\Unity C\UnityProjects\RFPS Practice Game\AdsPakage\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" --no-daemon "-PANDROID_HOME=C:/Users/HP/AppData/Local/Android/Sdk" "-PTARGET_DIR=D:\Unity C\UnityProjects\RFPS Practice Game\AdsPakage\Assets\Plugins\Android" "-PMAVEN_REPOS=https://maven.google.com/" "-PPACKAGES_TO_COPY=com.google.android.gms:play-services-ads:15.0.1"'
stdout:
Unzipping C:\Users\HP\.gradle\wrapper\dists\gradle-4.2.1-bin\dajvke9o8kmaxbu0kc5gcgeju\gradle-4.2.1-bin.zip to C:\Users\HP\.gradle\wrapper\dists\gradle-4.2.1-bin\dajvke9o8kmaxbu0kc5gcgeju

stderr:
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:215)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:75)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__24(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__2D()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Error No 2 is below**

Resolution failed

Failed to fetch the following dependencies:
com.google.android.gms:play-services-ads:15.0.1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.ResolverVer1_1:LogMissingDependenciesError(List`1)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey18:<>m__2B(List`1)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__24(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__2D()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by stewartmiles** [comment]
Looks like your gradle home directory isn't readable https://docs.gradle.org/current/userguide/gradle_wrapper.html

See the error
```
Unzipping C:\Users\HP.gradle\wrapper\dists\gradle-4.2.1-bin\dajvke9o8kmaxbu0kc5gcgeju\gradle-4.2.1-bin.zip to C:\Users\HP.gradle\wrapper\dists\gradle-4.2.1-bin\dajvke9o8kmaxbu0kc5gcgeju
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
```
either change `GRADLE_HOME` to a location the gradle wrapper can install to https://docs.gradle.org/current/userguide/installation.html#_step_3_configure_your_system_environment or change permissions on the directory `C:\Users\HP.gradle\`

**Comment by stewartmiles** [comment]
@InfiniteGamesStudio I'll assume you've solved your machine configuration problem, please let us know if this isn't the case.
