### ISSUE TITLE
Gradle fails to fetch transitive dependency with 'r' prefix in version

### ISSUE THREAD

**Issue by martino2k6** [googlesamples/unity-jar-resolver#133]
One of the libraries we're trying to pull down depends on [ExoPlayer](https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer), which has some funny versioning as some of their artifacts use the scheme 'rX.Y.Z' for the version.

This seems to trip the script up. I've managed to quickly workaround it by changing line 254 in the script to `def versionsList = versions.findAll { it != "null" }.collect { it.startsWith("r") ? it.substring(1) : it }`, however I get the feeling this is not a good solution. For some reason 'null' strings make it into the input, presumably coming from somewhere else in the script where these strange versions are throwing it off.

Full output for the error:
```Gradle failed to fetch dependencies.

Failed to run '/Users/user/Documents/unity-sdk/Temp/PlayServicesResolverGradle/gradlew -b "/Users/user/Documents/unity-sdk/Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle" --no-daemon "-PANDROID_HOME=/Users/user/Library/Android/sdk" "-PTARGET_DIR=/Users/user/Documents/unity-sdk/Assets/Plugins/Android" "-PMAVEN_REPOS=http://deltadna.bintray.com/android" "-PPACKAGES_TO_COPY=com.deltadna.android:deltadna-smartads-core:1.9.2;com.deltadna.android:deltadna-smartads-provider-admob:1.9.2;com.deltadna.android:deltadna-smartads-provider-facebook:1.9.2;com.deltadna.android:deltadna-smartads-provider-unity:1.9.2;com.deltadna.android:deltadna-smartads-provider-vungle:1.9.2;com.deltadna.android:deltadna-sdk-notifications:4.7.0"'
stdout:

stderr:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/user/Documents/unity-sdk/Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle' line: 258

* What went wrong:
A problem occurred evaluating root project 'PlayServicesResolverGradle'.
> For input string: "r2"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__24(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__2D()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

This is using Unity 5.6.5p1 with Unity Jar Resolver 1.2.75.

Thank you,

Martin

**Comment by stewartmiles** [comment]
Hey @martino2k6, yeah I agree adding a hack that just checks for the "r" prefix does seem wrong.  

According to
https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401
https://maven.apache.org/pom.html
it sounds like their versioning is a bit messed up which it looks like they've corrected since `2.6.0` and newer.

That said, the script should probably not blow up when it encounters a version number like this.  My first instinct is to hack around this by stripping all non-numeric characters from version number components when performing sorting / comparisons.

For the moment why not use `2.6.0` or above?

**Comment by martino2k6** [comment]
I can't directly use a different version as this is a transitive dependency of one of the libraries our library depends on: A (our library) -> B -> C (r2.4.2). I tried to add the group/module for C to an exclusion list and request a fixed version of C (2.6.1), however it seems like the original declaration of C is still being evaluated by the script.

I'm not sure whether the Resolver is not respecting the exclusions declarations, or whether it is correct for them to still be evaluated and they just get ignored later on.

Thank you.

**Comment by martino2k6** [comment]
I have re-run the command with `--info` added in: [output.txt](https://github.com/googlesamples/unity-jar-resolver/files/2227351/output.txt)

Not sure what you're looking for exactly, but there's a lot of logging in there...

**Comment by juyujuyu** [comment]
I meet the some problem when I use this: 
https://developers.google.com/admob/unity/mediation/facebook
