### ISSUE TITLE
The file GvhProjectSettings.xml seems to be useless

### ISSUE THREAD

**Issue by sdalexandre** [googlesamples/unity-jar-resolver#134]
I'm currently using the version v1.2.75 of the plugin.
The file GvhProjectSettings.xml is updated when changing the configuration from the editor. But, if i'm closing the editor, manually modifying the file GvhProjectSettings.xml and reopen the editor, the changes are not reflected in the editor settings window. It seems that settings are stored elsewhere.

I also tried to check/uncheck the option "use project settings" but that doesn't seem to change anything.

We are using a version control system. It break our automated build jobs since parameters have to be manually changed. I'm trying to set the "Cocoapods Integration" to "Xcode Workspace". I set the "Google.IOSResolver.CocoapodsIntegrationMethod" property to "2" but they is no workspace until i manually change the setting from the editor settings window.

Thanks!

**Comment by stewartmiles** [comment]
@sdalexandre it sounds like either something is broken in https://github.com/googlesamples/unity-jar-resolver/blob/master/source/VersionHandlerImpl/src/ProjectSettings.cs or you're doing something wrong.  You're right that the settings can be set either machine wide (in Unity's settings) or per project via `GvhProjectSettings.xml`.  It sounds like you're setting `Google.IOSResolver. CocoapodsIntegrationMethodPref` which should rewrite the settings file if things are working correctly.

**Comment by sdalexandre** [comment]
Thanks for pointing me out the ProjectSettings.cs script.
I have replaced the DLLs with the sources code and start debugging.
I can confirm that the xml is read properly!

I have tried to change a setting that was true to false, but because the defaultValue is false it use the EditorPrefs.GetBool() that return true!?

Same with the Google.IOSResolver.CocoapodsIntegrationMethod:
  defaultValue is 2,
  the value readed from the xml is 2
  since both values are the same, it decide to return the value from the EditorPrefs.GetInt() that return another value!!

Calling EditorPrefs.DeleteAll() resolve my issue. 
But i think that if UseProjectSettings is true and the value exist in the xml file, it shouldn't use the EditorPrefs value.

**Comment by stewartmiles** [comment]
@sdalexandre doh, indeed that is very wrong, it should not be comparing against the default value and falling back instead it should be checking to see whether the value is parsed from the XML file and then if it isn't falling back.

**Comment by stewartmiles** [comment]
@sdalexandre sorry about that I have a patch lined up for this.

**Comment by sdalexandre** [comment]
Thanks!
