### ISSUE TITLE
How to handle plugins that aren't integrated with the jar resolver?

### ISSUE THREAD

**Issue by JimmyDeemo** [googlesamples/unity-jar-resolver#136]
I use a mixture of plugins for the project a work on. Some of them use the jar resolver and some of them don't. Here is an example to illustrate my main problem;

- PluginA is integrated with the jar resolver.
- It has a dependency of com.some.package:1.2.3
- PluginB iis not integrated with the jar resolver.
- It has a dependency of com.some.package:2.3.4 and includes the relevant .aar file.
- Upon resolving dependencies I get com.some.package_1.2.3.aar added to the project, which clashes with the other one at build time.

Other than encouraging plugin developers to integrate with the resolver, what is the correct way to manage this problem? Any advice much appreciated.

**Comment by stewartmiles** [comment]
We do handle some of this with the redistribution of `google-play-services.jar` as it's pretty common for it to end up in multiple plugins (see https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/src/ResolverVer1_1.cs#L749 ).  If the naming of plugins was deterministic then it may be possible to derive what is already included in the project without unpacking AARs and looking at the contents of each package for conflicts.

In general, if you have an overlap in dependencies what you could do is remove the file with `com.some.package:2.3.4` from the project and replace it with a reference to the dependency via a `*Dependencies.xml` file instead that will allow the resolve to pick up the latest version across all plugins.

Now poking your plugin vendor to stop shipping Android libraries that can be transitively included in other Android packages is also a good thing to do.

**Comment by JimmyDeemo** [comment]
Thanks for the advice. I have already tried to get Pushwoosh and Helpshift onboard with the resolver, but their turn around time isn't really up to me.

For now I will try start adding `*Dependencies.xml` files to our project in order to manage this better.
