### ISSUE TITLE
iOS Pods subspecs

### ISSUE THREAD

**Issue by Hellfim** [googlesamples/unity-jar-resolver#137]
Hi there,
I'm using your tool and it works perfectly, but recently I discovered a need to integrate some iOS Plugins using CocoaPods. As I understood from IOSResolver.cs there are only 4 parameters which can be parsed from xml. I need to add subspecs parameter.
I also found an old issue with same problem (https://github.com/googlesamples/unity-jar-resolver/issues/61), so I'm wondering are you planning to add more parameters? Or is it possible that I add subspecs parameter and make a pull request?

**Comment by stewartmiles** [comment]
Could you provide an example of a podfile you're trying to generate?  At the moment the plugin can already reference subspecs, it's used all over the place in Firebase.  For example, Firebase/Analytics is a subspec of the Firebase pod (see the podspec linked from https://cocoapods.org/pods/Firebase)

**Comment by Hellfim** [comment]
Sure, I'm trying to generate something like this
pod "PluginA", :subspecs =>['Subspec1','Subspec2','Subspec3']

**Comment by stewartmiles** [comment]
Per https://guides.cocoapods.org/syntax/podfile.html#pod you can do...
```
pod "PluginA/Subspec1"
pod "PluginA/Subspec2"
pod "PluginA/Subspec3"
```
instead.

So this would be...

```
<iosPod name="PluginA/Subspec1" />
<iosPod name="PluginA/Subspec2" />
<iosPod name="PluginA/Subspec3" />
```

**Comment by Hellfim** [comment]
Oh, thank you I guess I missed that simple syntax =\
Sorry for the lame question
