### ISSUE TITLE
AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;

### ISSUE THREAD

**Issue by exzizt** [googlesamples/unity-jar-resolver#138]
I imported the AdMob package into a project that is using Firebase Auth, Firebase Database, and GPGS. Something is broken:

> 08-01 15:58:18.162  2230  2230 E AndroidRuntime: FATAL EXCEPTION: main
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime: Process: com.exzizt.Birdie, PID: 2230
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime: Unity version     : 2018.2.0f2
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime: Device model      : LGE LG-D852
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime: Device fingerprint: lge/g3_tls_ca/g3:6.0/MRA58K/162031018df96:user/release-keys
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
**> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source)**
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:382)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:279)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:506)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at android.app.Fragment.performResume(Fragment.java:2272)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at android.app.BackStackRecord.run(BackStackRecord.java:793)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5551)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/data/app/com.exzizt.Birdie-2/base.apk"],nativeLibraryDirectories=[/data/app/com.exzizt.Birdie-2/lib/arm, /data/app/com.exzizt.Birdie-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        ... 17 more
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.api.Api$zzf
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:                at java.lang.Class.classForName(Native Method)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:                ... 18 more
> 08-01 15:58:18.162  2230  2230 E AndroidRuntime:        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
> 08-01 15:58:18.174  2262  4226 W ActivityManager:   Force finishing activity com.exzizt.Birdie/com.unity3d.player.UnityPlayerActivity

Any tips?

Edit: It looks like it has something to do with the Auth plugin.

Edit 2: I bolded the line where it seems like it can't locate the required Authorization class. I am also using the latest version of the jar resolver (1.2.80).

![image](https://user-images.githubusercontent.com/17113094/43555545-a4c06358-95af-11e8-8d4c-732d184df99b.png)

**Comment by exzizt** [comment]
I am also getting this when I resolve:

> Some conflicting dependencies were found.
> The following dependency versions were modified:
> com.google.firebase:firebase-common:16.0.0 --> com.google.firebase:firebase-common:+
> com.google.android.gms:play-services-base:15.0.1 --> com.google.android.gms:play-services-base:+
> com.google.games:gpgs-plugin-support:0.9.50 --> com.google.games:gpgs-plugin-support:+
> com.google.firebase:firebase-core:16.0.1 --> com.google.firebase:firebase-core:+
> com.google.firebase:firebase-auth:16.0.2 --> com.google.firebase:firebase-auth:+
> com.google.firebase:firebase-database:16.0.1 --> com.google.firebase:firebase-database:+
> com.google.android.gms:play-services-ads:15.0.1 --> com.google.android.gms:play-services-ads:+
> 
> UnityEngine.Debug:LogWarning(Object)
> Google.Logger:Log(String, LogLevel)
> GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
> GooglePlayServices.<GradleResolution>c__AnonStorey13:<>m__23(Result)
> GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__2C()
> Google.RunOnMainThread:ExecuteNext()
> Google.RunOnMainThread:ExecuteAll()
> Google.RunOnMainThread:Run(Action, Boolean)
> GooglePlayServices.<GradleResolution>c__AnonStorey13:<>m__24(Result)
> GooglePlayServices.<GradleResolution>c__AnonStorey13:<>m__25(Result)
> GooglePlayServices.ProgressReporter:SignalComplete()
> GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
> GooglePlayServices.CommandLineDialog:Update()
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
>

**Comment by JimmyDeemo** [comment]
Re: `NoClassDefFoundError` error. This means that your app doesn't know a class at runtime when it should. You should check two things; is it in the project at all or is it being removed at build time. The easiest way to check the former is to export the project and open it in Android Studio. Hit `Ctrl`+`N` and then search for the class name (e.g. Api$zzf). If Android Studio can find it then check your ProGuard settings, it is possible that ProGuard is not keeping this class. Note: If you build with Android Studio, then ProGuard outputs logs to the 'mappings' folder under the build which explains what is removed.

The resolver looks like it's complaining that some of the dependencies specify a version, and other don't so it can't resolve.

```
com.google.firebase:firebase-common:16.0.0 --> com.google.firebase:firebase-common:+
```

This means that one of the dependencies says to use `16.0.0` but one says to use whatever is the latest. The latter should be avoided if possible. Check all of the `*Depencencies.xml` files in your project to see if you can spot this conflict.

**Comment by exzizt** [comment]
@JimmyDeemo 
I am not using Proguard. Although I did try it last night to try and "keep" that one class/file it is apparently missing but that didn't work.

The dependency files are their pure defaults and I can't spot any conflicts:

Firebase
--------
AppDependencies.xml
![image](https://user-images.githubusercontent.com/17113094/43607119-291bccee-9652-11e8-9b4d-77c66f979670.png)

AuthDependencies.xml
![image](https://user-images.githubusercontent.com/17113094/43607132-3268b6a4-9652-11e8-9fcc-6b7b0b57adc2.png)

DatabaseDependencies.xml
![image](https://user-images.githubusercontent.com/17113094/43607138-385027f0-9652-11e8-8b88-59a4db9c3b2d.png)

Google
-------
GoogleMobileAdsDependencies.xml
![image](https://user-images.githubusercontent.com/17113094/43607146-3f530e00-9652-11e8-89eb-056b4084bbc9.png)

GooglePlayGamesPluginDependencies.xml
![image](https://user-images.githubusercontent.com/17113094/43607151-42d85d8c-9652-11e8-84fb-71b1712c331c.png)

**Comment by exzizt** [comment]
If anyone can help, I am at my absolute wit's end. I've been working on this problem for a combined 30 hours and still cannot fix it.

**Comment by exzizt** [comment]
@JimmyDeemo 

I did try your suggestion to look in Android Studio to see if it has the missing class (Api$zzf) and it indeed does not:

![image](https://user-images.githubusercontent.com/17113094/43624353-a87205dc-969b-11e8-9ab8-abaaea6b58e2.png)

**Comment by JimmyDeemo** [comment]
I think that you need to resolve #139 before you see why this class isn't available.

**Comment by exzizt** [comment]
@JimmyDeemo  The #139 issue stopped happening actually and I'm not sure why.

**Comment by exzizt** [comment]
I received some help with this issue in #130 and thankfully I've been able to work around this problem.

**Comment by stewartmiles** [comment]
@exzizt glad you've resolved your issue, we have a patch lined up soon that will assist in this - a bit.  The main issue is that when incompatible dependencies are mixed there isn't much we can do except try upgrading all referenced packages.  If this still results in a set of incompatible libraries it's up to the developer (i.e folks like yourself) to hack the dependencies to resolve the issue.
