### ISSUE TITLE
Resolution failed (expecting version 16.1.1 for everything ???)

### ISSUE THREAD

**Issue by exzizt** [googlesamples/unity-jar-resolver#139]
![image](https://user-images.githubusercontent.com/17113094/43567378-6a87369e-95e6-11e8-9509-f4e5879d2484.png)

I have been plagued the past two days by  #138 and have been trying various things to fix it. I've encountered this now and have no idea why, as not a single dependency file has the version 16.1.1 listed anywhere.

**Comment by JimmyDeemo** [comment]
One thing to check, as you appear to have checked all the dependency .xml in #138, is whether you have .pom files in your project. For example, the GPG plugin builds it's own .aar file, using the Jar Resolver. For example, looking at the `gpgs-plugin-support-0.9.50.pom` I can see the following;

```xml
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-games</artifactId>
      <version>11.6+</version>
      <scope>compile</scope>
    </dependency>
```

These dependencies will also be picked up by the Jar Resolver, and can conflict with your other .aar files.

Also, it looks like your image link is broken. Suggest clipping the section of the Editor.log where the Jar Resolver starts working, and posting it in text form.

**Comment by exzizt** [comment]
@JimmyDeemo 
This issue isn't actually an issue anymore. I don't know why it happened a couple times, but it went away and doesn't come up anymore (the 16.1.1 thing).
