### ISSUE TITLE
Why resolver copy everythings into Unity?

### ISSUE THREAD

**Issue by SisadaR** [googlesamples/unity-jar-resolver#14]
After run resolver , it copy all unuse .arr to my build including firebase.

**Comment by stewartmiles** [comment]
Could you clarify the scenario you're running into?  We need to copy or expand aars referenced by your *Deps.cs files into your Unity project in order to have them included in the Android application build process.

**Comment by stewartmiles** [comment]
It needs to copy aars into Unity to have Unity's build system include them.  We only copy the aars that are required by each plugin included in the project.
