### ISSUE TITLE
Unable to find FirebaseCppApp-5.2.0

### ISSUE THREAD

**Issue by exzizt** [googlesamples/unity-jar-resolver#144]
My project previously used the 5.2.0 versions of the plugins Auth, Database, Invites, and AdMob. I am using the latest resolver (1.2.84.0). I'm regretting updating because now I'm getting more errors again. Note that auto-resolution is enabled, and I've done many "force resolves".

**EDIT**: While googling around I stumbled across this thread (https://stackoverflow.com/questions/51628906/android-firebase-unity-have-error-gradle-failed-to-fetch-dependencies-and-resol) that, while not entirely related to this issue, gave me the idea to un-delete the old "5.2.0" folders that I deleted after upgrading to 5.2.1. I deleted them because they were **empty** and I figured deleting them wouldn't impact anything. Strangely enough, I guess deleting them impacted something, hence the errors below. Anyway, un-deleting them and keeping the empty 5.2.0 folders has resolved the issue.

![image](https://user-images.githubusercontent.com/17113094/44320705-8269f880-a3f8-11e8-8399-91cb8a4ade64.png)

> 08-19 21:24:37.130 13165 13240 I Unity   : Firebase App initializing app com.exzizt.Birdie (default 1).
> 08-19 21:24:37.130 13165 13240 I Unity   :
> 08-19 21:24:37.130 13165 13240 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
> 08-19 21:24:37.130 13165 13240 I Unity   :
> 08-19 21:24:37.133 13165 13240 I Unity   : Firebase Analytics API Initializing
> 08-19 21:24:37.133 13165 13240 I Unity   :
> 08-19 21:24:37.133 13165 13240 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
> 08-19 21:24:37.133 13165 13240 I Unity   :
> 08-19 21:24:37.135 13165 13240 I Unity   : analytics API Initialized
> 08-19 21:24:37.135 13165 13240 I Unity   :
> 08-19 21:24:37.135 13165 13240 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
> 08-19 21:24:37.135 13165 13240 I Unity   :
> 08-19 21:24:37.175 13165 13240 I Unity   : Dynamic Links API Initialized
> 08-19 21:24:37.175 13165 13240 I Unity   :
> 08-19 21:24:37.175 13165 13240 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
> 08-19 21:24:37.175 13165 13240 I Unity   :
> 08-19 21:24:37.322 13165 13191 I Unity   : Firebase App initializing app com.exzizt.Birdie (default 1).
> 08-19 21:24:37.322 13165 13191 I Unity   :
> 08-19 21:24:37.322 13165 13191 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
> 08-19 21:24:37.322 13165 13191 I Unity   :
> 08-19 21:24:37.323 13165 13191 I Unity   : Firebase Analytics API Initializing
> 08-19 21:24:37.323 13165 13191 I Unity   :
> 08-19 21:24:37.323 13165 13191 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
> 08-19 21:24:37.323 13165 13191 I Unity   :
> 08-19 21:24:37.323 13165 13191 I Unity   : analytics API Initialized
> 08-19 21:24:37.323 13165 13191 I Unity   :
> 08-19 21:24:37.323 13165 13191 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
> 08-19 21:24:37.323 13165 13191 I Unity   :
> 08-19 21:24:37.336 13165 13191 I Unity   : Dynamic Links API Initialized
> 08-19 21:24:37.336 13165 13191 I Unity   :
> 08-19 21:24:37.336 13165 13191 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
> 08-19 21:24:37.336 13165 13191 I Unity   :
> 08-19 21:24:37.347 13165 13191 E Unity   : Unable to find FirebaseCppApp-5.2.0
> 08-19 21:24:37.423 13165 13191 E Unity   : InitializationException: Firebase's libApp.so was not found for this device's architecture
> 08-19 21:24:37.423 13165 13191 E Unity   : in your APK.
> 08-19 21:24:37.423 13165 13191 E Unity   : On Android, Firebase requires C/C++ and Java components
> 08-19 21:24:37.423 13165 13191 E Unity   : that are distributed with the Firebase and Android SDKs.
> 08-19 21:24:37.423 13165 13191 E Unity   :
> 08-19 21:24:37.423 13165 13191 E Unity   : It's likely the required dependencies for Firebase were not included
> 08-19 21:24:37.423 13165 13191 E Unity   : in your Unity project.
> 08-19 21:24:37.423 13165 13191 E Unity   : Assets/Plugins/Android/ in your Unity project should contain
> 08-19 21:24:37.423 13165 13191 E Unity   : AAR files in the form firebase-*.aar
> 08-19 21:24:37.423 13165 13191 E Unity   : You may have disabled the Android Resolver which would
> 08-19 21:24:37.423 13165 13191 E Unity   : have added the AAR dependencies for you.
> 08-19 21:24:37.423 13165 13191 E Unity   :
> 08-19 21:24:37.423 13165 13191 E Unity   : Do the following to enable the Android Resolver in Unity:
> 08-19 21:24:37.423 13165 13191 E Unity   : * Select the menu option 'Assets -> Play Services Resolver ->
> 08-19 21:24:37.423 13165 13191 E Unity   :   Android Resolver -> Settings'
> 08-19 21:24:37.423 13165 13191 E Unity   : * In the Android Resolver settings check
> 08-19 21:24:37.423 13165 13191 E Unity   :   'Enable Background Resolution'
> 08-19 21:24:37.423 13165 13191 E Unity   : * Select the menu option 'Assets -> Play Services Resolver ->
> 08-19 21:24:37.423 13165 13191 E Unity   :   Android Resolver -> Resolve Client Jars' to force Android
> 08-19 21:24:37.423 13165 13191 E Unity   :   dependency resolution.
> 08-19 21:24:37.423 13165 13191 E Unity   : * Rebuild your APK and deploy.
> 08-19 21:24:37.423 13165 13191 E Unity   :
> 08-19 21:24:37.423 13165 13191 E Unity   :   at Firebase.FirebaseApp.TranslateDllNotFoundException (System.Action closureToExecute) [0x00000] in <filename

**Comment by stewartmiles** [comment]
@exzizt it sounds like you're not including whatever version of the Firebase plugin required for your project.  I recommend starting with one of the sample projects, importing the plugins then comparing what you have with your project that has problems.  It sounds to me like you may have deleted a configuration file that is required for the Firebase plugin.

**Comment by exzizt** [comment]
@stewartmiles I fixed it (see my edit in my initial post). There must be an issue with the resolver where it requires me to have those empty 5.2.0 folders even though everything in my project references 5.2.1.

**Comment by stewartmiles** [comment]
@exzizt the resolver has no hard coded assumptions about the 5.2.0 folders in the project.  The m2repository folder is just used as a local maven repository for Gradle to read from.  Any chance you have the Unity.log file with the resolution failure, ideally with verbose logging enabled in the Android Resolver?

**Comment by stewartmiles** [comment]
@exzizt since we haven't heard from you, I'll close out this issue.  If you're still having problems I recommend contacting https://firebase.google.com/support

**Comment by exzizt** [comment]
@stewartmiles Sorry Stewart. I'll try to get to this as soon as I can!
