### ISSUE TITLE
Resolver causing 0.8-0.9 MB of GC Allocations per frame in Editor

### ISSUE THREAD

**Issue by benjaminOddGames** [googlesamples/unity-jar-resolver#146]
I'm having an issue where the Resolver is causing a large amount of garbage every frame. This occurs in the editor including when not in play mode, and causes frequent stuttering caused by frequent garbage collections. 

The version of Unity is 2018.2.5f1, with the latest Play Services Resolver.
The following profile screenshot was taken with Deep Profile and Profile Editor enabled. 

![2018-08-30_16-50-18](https://user-images.githubusercontent.com/42830944/44836760-f3ba6e80-ac76-11e8-91a9-dddc1deee2b1.png)

Other computers in the studio do not have the same issue, though all are using the same version of Unity and Play Services Resolver.

Expanding the profiler gives the following info:
![image](https://user-images.githubusercontent.com/42830944/44836967-7e02d280-ac77-11e8-911a-727203c2c960.png)

**Comment by stewartmiles** [comment]
Our code which reads the ABI to check for changes is getting hit each frame...

https://github.com/googlesamples/unity-jar-resolver/blob/16c9753e4b08da6051b8b2c1e952a99667d2292c/source/PlayServicesResolver/src/PlayServicesResolver.cs#L1106

even though an action won't be triggered for a few seconds..

https://github.com/googlesamples/unity-jar-resolver/blob/16c9753e4b08da6051b8b2c1e952a99667d2292c/source/PlayServicesResolver/src/PlayServicesResolver.cs#L273

Now we have `RunOnMainThread`, I guess this could be changed to batch up all property checks here https://github.com/googlesamples/unity-jar-resolver/blob/16c9753e4b08da6051b8b2c1e952a99667d2292c/source/PlayServicesResolver/src/PlayServicesResolver.cs#L647 to reduce the GC load.

**Comment by Nightro** [comment]
+1 - couple of us are suffering from this too

**Comment by VergilUa** [comment]
+1. Please fix this nonsense

**Comment by Ospanaattori** [comment]
The fact that this also takes ~10ms per frame on a decent PC is just not acceptable.

**Comment by stewartmiles** [comment]
Hi everyone, we know this is a problem and it's on the list of things we need to fix.  Compared to some other issues we're not getting to it any time soon.  So you have a couple of options:
- Send us a pull request with a fix.
- Turn off auto-resolution when you're not adding additional plugins to your project.  Run Android Resolution when importing plugins that use Android libraries.

**Comment by stewartmiles** [comment]
@oddgamesdaniel we're not ignoring this issue, it's just prioritized compared to the range of other issues that our team also has to deal with.  Remember this plugin is open source, you're free to send us a pull request.

**Comment by oddgamesdaniel** [comment]
Pull request submitted. It isn't going to remove the underlying cause of the issue, but it should mean that anybody turning off auto resolution won't have to deal with the massive CG allocations every frame

**Comment by stewartmiles** [comment]
FYI folks, this is what I have working locally.  It's down to about 200 bytes of allocation - which still seems a lot to me - every second rather than each frame.

![image](https://user-images.githubusercontent.com/6042948/50127113-95fd6280-0224-11e9-9e71-a5bb5cbc2177.png)

**Comment by oddgamesdaniel** [comment]
Thank you, much appreciated!
