### ISSUE TITLE
Crash with 12.0.0 google play services version

### ISSUE THREAD

**Issue by warzoku** [googlesamples/unity-jar-resolver#148]
In my project gms libs is 11.6.2 version but I need to use 12.0.0 because other plugins (firebase) uses this version. I get crash when i try to save game. So I can pass auth but when I try to run this code
 ((PlayGamesPlatform)Social.Active).SavedGame.OpenWithAutomaticConflictResolution(
                fileName,
                GooglePlayGames.BasicApi.DataSource.ReadCacheOrNetwork,
                ConflictResolutionStrategy.UseLongestPlaytime, SaveGameOpened);
 I get crush.

Crush message 
Can't find com/google/android/gms/games/snapshot/SnapshotMetadata.getTitle: java.lang.NoSuchMethodError: no non-static method "Lcom/google/android/gms/games/snapshot/SnapshotMetadata;.getTitle()Ljava/lang/String;".

**Comment by stewartmiles** [comment]
@warzoku did you file this bug against the wrong project?  I'm not sure how the resolver is related to this.

**Comment by stewartmiles** [comment]
Closing this out due to no response.
