### ISSUE TITLE
Google Resolver can not run with OneSignal 2.7.5, Firebase 5.2.1

### ISSUE THREAD

**Issue by takaaptech** [googlesamples/unity-jar-resolver#149]
Hi
Please help I am using play-services-resolver-1.2.89.0 to resolve One signal 2.7.5 and Firebase Analytics 5.2.1 but have the error when Resolver picking the wrong version

My setup:
One signal 2.7.5
Unity 2017.4.4f1
Firebase Analytics 5.2.1
play-services-resolver-1.2.89.0
Android SDK update to max
Java SDK 1.8
And the project for reproduce
https://drive.google.com/file/d/1kqTfGUUGtZ06VeShejKz7yPKEC89MoNo/view?usp=sharing

Link back to issue on One signal for reference and more information about detail log when Force Resolve
https://github.com/OneSignal/OneSignal-Unity-SDK/issues/146
Thank so much for the help!

**Comment by agrobost** [comment]
Same for with one signal and admob

**Comment by jkasten2** [comment]
@stewartmiles I have narrowed down exact minimum scenarios that are causing this problem in #151. It has to due with change in the `1.2.88.0` release of this plugin. Feel free to close this one in favor of this one.

**Comment by stewartmiles** [comment]
Thanks for narrowing this down @jkasten2 .  Could you use inclusive version ranges in OneSignal as a workaround for this in the meantime?

**Comment by jkasten2** [comment]
@stewartmiles Using `[` instead of `)` for the upper bound works to avoid the error. However the upper range isn't respected in some cases noted in #151. This is fine for OneSignal for now since it works with the latest Firebase versions. Thanks.

**Comment by takaaptech** [comment]
Using [ instead of ) works!
