### ISSUE TITLE
Jar Resolver restores old 8.4.0 aars instead of 9.6.1

### ISSUE THREAD

**Issue by Qbit86** [googlesamples/unity-jar-resolver#15]
Jar Resolver restores old 8.4.0 aars instead of 9.6.1. However in Editor scripts of some plugins all calls to `svcSupport.DependOn()` pass `"9+"`. This leads to this issue: https://github.com/playgameservices/play-games-plugin-for-unity/issues/1411

---

Unity 5.3.6p6 on Windows 10 Pro targeting Android. Latest Android SDK installed with all components updated via Android SDK Manager.

**Comment by Qbit86** [comment]
Added connected issue: <https://github.com/playgameservices/play-games-plugin-for-unity/issues/1423>

Any help would be very much appreciated!

**Comment by stewartmiles** [comment]
Was this resolved by the fix in https://github.com/playgameservices/play-games-plugin-for-unity/issues/1423 ?

**Comment by stewartmiles** [comment]
We've removed the cache so this is resolved by the latest release.
