### ISSUE TITLE
After resolving the apk is crashed 

### ISSUE THREAD

**Issue by shohan4556** [googlesamples/unity-jar-resolver#156]
I have imported google play service and admob then resolved successfully and build apk successfully but crashed. please tell me how to solve the issue.

**Comment by stewartmiles** [comment]
@shohan4556 & @Mecze this indeed sounds like an issue with the AdMob plugin so I recommend filing an issue there to give some visibility to the team.  FWIW: I've poked the team who maintains the AdMob team internally as well.

@Mecze you mentioned *of course@ disable Auto-Resolve, what's up with that?

**Comment by Mecze** [comment]
I meant, for the workaround to actually work. If you don't disable Auto-Resolve it will resolve again at some point and download 17.0.0 files again. I now realize that I **bolded** the wrong word and sounds real bad, sorry about that!

Thanks for the heads up!

**Comment by stewartmiles** [comment]
Ah @Mecze gotcha.  I was wondering if there was an issue with auto-resolution in general that needed to be fixed.  I'll close this out and assume that @shohan4556 will open an issue with the AdMob folks on their Unity plugin repo.

**Comment by PAHeartBeat** [comment]
Hi, @shohan4556  & @Mecze 

I face the same issue two day ago. you need to add one another meta tag AD_MANAGER_AP along with APPLICATION ID.

this second meta tag required for version 17.0.0 and newer library

```
<meta-data android:name = "com.google.android.gms.ads.AD_MANAGER_APP" android:value = "true" />
<meta-data android:name = "com.google.android.gms.ads.APPLICATION_ID" android:value = "ca-app-pub-<<APPLICATION_ID>>" />
```

Please add this two line in main AndroidManifest.xml, I also tried it to add sub AndroidMenifest.xml of GoogleMobileAds/Plugins/Android/ but it will not work, You must have to add these two lines in Main Manifest and it will work like magic.

**Comment by karishmapujara** [comment]
@PAHeartBeat 

I am unable to display ads.
Any solutions?
