### ISSUE TITLE
Crashes Unity 5.5+

### ISSUE THREAD

**Issue by yuriy-universal-ivanov** [googlesamples/unity-jar-resolver#16]
Hi unity-jar-resolver team,

Starting with Unity 5.5 (beta currently) there is no 11th BuildTarget (XBOX369), as result Unity crashes as soon as you import Play Services Resolver.

If you could fix it fast, it would be awesome.

Thanks in advance,
Yuriy.

**Comment by stewartmiles** [comment]
This is resolved in the latest release.
