### ISSUE TITLE
Play Services Resolver -> Version Handler -> Update does not work

### ISSUE THREAD

**Issue by Deepscorn** [googlesamples/unity-jar-resolver#163]
Steps to repro:
1. Import latest 0.9.5.0 plugin
2. See contents of Assets\PlayServicesResolver\Editor. There you will find dlls:
Google.IOSResolver_v1.2.61.0.dll
Google.JarResolver_v1.2.61.0.dll
Google.VersionHandler.dll
Google.VersionHandlerImpl_v1.2.61.0.dll
play-services-resolver_v1.2.61.0.txt
3. Run command. You'll get "Update complete" popup.
4. See directory again.
Expected: all updated to versions from here (1.2.95 at the moment of writing)
https://github.com/googlesamples/unity-jar-resolver/tree/master/exploded/Assets/PlayServicesResolver/Editor
Actual: versions are the same.

Please, fix updating mechanism.

Note: So, I get really old Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle
which fails to resolve for example firebase with version 17.3.4. But recent script from https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/scripts/download_artifacts.gradle
resolves ok. This is the actual problem, which I hope will be gone after updating dlls

Unity 2018.1.9f1
Windows 10

**Comment by stewartmiles** [comment]
@Deepscorn what `0.9.5.0` plugin are you referring to?

You'll end up with a really old `download_artifacts.gradle` script as it's the one in whatever plugin ended up being enabled.

To workaround the issue, you could remove the PlayServicesResolver directory and import the latest version from this repo instead.

**Comment by Deepscorn** [comment]
> @Deepscorn what 0.9.5.0 plugin are you referring to?
I was referring this https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v0.9.50
Oh, I see, it is another plugin. But it is bundled with this plugin, version 1.2.61. So I have a repro for old version... I'll suggest play-games-plugin-for-unity updating Play Services Resolver which they bundle, so in latest version there will be no issue with updating. You can close that issue, thank you!

**Comment by stewartmiles** [comment]
@Deepscorn ack
