### ISSUE TITLE
Version range parsing fails with whitespace in expressions

### ISSUE THREAD

**Issue by amjaliks** [googlesamples/unity-jar-resolver#164]
Version 1.2.95.0.

Resolver fails to resolve conflict for this set of dependencie:
```
<dependencies>
  <packages>
    <package>com.android.support:appcompat-v7:25.3.1</package>
    <package>com.android.support:cardview-v7:25.3.1</package>
    <package>com.android.support:customtabs:[26.0.0, 27.2.0)</package>
    <package>com.android.support:customtabs:25.3.1</package>
    <package>com.android.support:support-v4:[26.0.0, 27.2.0)</package>
    <package>com.android.support:support-v4:25.3.1</package>
    <package>com.google.android.gms:play-services-ads-identifier:[15.0.0, 15.0.1)</package>
    <package>com.google.android.gms:play-services-base:[10.2.1, 12.1.0)</package>
    <package>com.google.android.gms:play-services-location:[10.2.1, 12.1.0)</package>
    <package>com.google.firebase:firebase-messaging:[10.2.1, 12.1.0)</package>
    <package>com.google.games:gpgs-plugin-support:0.9.52</package>
  </packages>
  <!-- ... -->
</dependencies>
```

Download script fails:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/PathToProject/Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle' line: 747

* What went wrong:
A problem occurred evaluating root project 'PlayServicesResolverGradle'.
> For input string: " 15"
```

Can get around by editing  by trimming string passed to `Version` constructor:
```
  public Version(String version = null) {
    this.version = version != null ? version.trim() : version
  }
```

Unfortunately, this isn't a permanent solution as `PlayServicesResolver.scripts.download_artifacts.gradle` will be overwritten at some point.

**Comment by stewartmiles** [comment]
@amjaliks thanks for finding this.  We're happy to accept a patch to https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/scripts/download_artifacts.gradle :)  If, not we'll get around to fixing this soon.  You can also workaround this by removing the whitespace between the version ranges e.g `[15.0.0, 15.0.1)` --> `[15.0.0,15.0.1)`.

**Comment by amjaliks** [comment]
@stewartmiles I wasn't sure it is the [best] way/place to fix this. I didn't to have all this hassle with CLA because of one line. 😉

Thanks! Your workaround is much nicer. Now I feel stupid I didn't figure out myself. 😄
