### ISSUE TITLE
Mixed Dependency Versions bugs 2.0 #130 - still present

### ISSUE THREAD

**Issue by elmm** [googlesamples/unity-jar-resolver#165]
Trying to resolve some dependencies for firebase messaging and came across the bug that should be resolved in 1.2.90 when resolver bump's dependencies' version to version of original library (in my case firebase -messaging 17.3.4).

I'm using 1.2.95 version of the resolver.

My AndroidDependencies.xml looks like this:

```
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.firebase:firebase-messaging:17.3.4">
      <androidSdkPackageIds>
        <androidSdkPackageId>extra-google-m2repository</androidSdkPackageId>
      </androidSdkPackageIds>
    </androidPackage>    
    <androidPackage spec="com.google.android.gms:play-services-base:16.0.1">
      <androidSdkPackageIds>
        <androidSdkPackageId>extra-google-m2repository</androidSdkPackageId>
      </androidSdkPackageIds>
    </androidPackage>
    <androidPackage spec="com.android.support:support-v4:26.1.0">
      <androidSdkPackageIds>
        <androidSdkPackageId>extra-google-m2repository</androidSdkPackageId>
      </androidSdkPackageIds>
    </androidPackage>
    <androidPackage spec="com.android.support:appcompat-v7:26.1.0">
      <androidSdkPackageIds>
        <androidSdkPackageId>extra-google-m2repository</androidSdkPackageId>
      </androidSdkPackageIds>
    </androidPackage>
  </androidPackages>
</dependencies>
```

As the result resolver bump's version of most of the dependencies to 17.3.4

```
com.google.android.gms:play-services-base:17.3.4
com.google.android.gms:play-services-basement:17.3.4
com.google.android.gms:play-services-gcm:16.0.1
com.google.android.gms:play-services-stats:17.3.4
com.google.android.gms:play-services-tasks:17.3.4
com.google.firebase:firebase-common:17.3.4
com.google.firebase:firebase-iid-interop:17.3.4
com.google.firebase:firebase-iid:17.3.4
com.google.firebase:firebase-measurement-connector:17.3.4
com.google.firebase:firebase-messaging:17.3.4
```

**Comment by stewartmiles** [comment]
@elmm what is the issue here?  The resolver attempts to find the set of versions that satisfy all dependency requirements and if that fails it simply pulls the latest of everything.  Could you share the whole resolver log so that it's possible to understand what's going on here?

**Comment by elmm** [comment]
@stewartmiles 
Sorry, false alarm.
It's turned out that when I tried to update resolver to 1.2.95 I got a mix of files from 1.2.95 and older resolver that bundled to GooglePlayGamesPlugin.
New empty project or just deleting whole resolver folder and reimporting 1.2.95 leads to successful resolving of dependencies from my previous message.
