### ISSUE TITLE
Unnecessary editor log entry when entering play mode

### ISSUE THREAD

**Issue by Trisibo** [googlesamples/unity-jar-resolver#167]
A nitpick as a user of some plugin using this library: the text "Starting auto-resolution before scene build..." is sent to Unity's log every time you enter play mode, from `PlayServicesResolver.OnPostProcessScene`. Can get a bit annoying after a while, since it's just non-actionable information that always appears, and for which I don't even know the meaning.

The next log with the result appears to have a `level` parameter with the value `LogLevel.Verbose`, and it doesn't appear in the console (I guess unless you explicitly set the log level to see in the console), so I assume the previous log would be intended to have the same log level parameter, which I think would be the desirable behaviour instead of appearing every time.

**Comment by stewartmiles** [comment]
Yeah that's a buggy log statement, should be marked as verbose.

**Comment by stewartmiles** [comment]
https://github.com/googlesamples/unity-jar-resolver/blame/master/source/PlayServicesResolver/src/PlayServicesResolver.cs#L836

**Comment by killeriukas** [comment]
It's not just that statement, but it also does process every scene even in the playmode. It takes 5seconds to process one scene, and I'm loading 10, which means I have to wait for 50seconds just for the process to finish. It's completely unnecessary. Rolling back the version of Jar Resolver and hoping it's gonna be easy. Please do fix this, cuz the newest version is useless at the moment. Thanks.

**Comment by Trisibo** [comment]
Hi @killeriukas, I think you should open a new issue for that, to separate it from this one.

**Comment by killeriukas** [comment]
> Hi @killeriukas, I think you should open a new issue for that, to separate it from this one.

Done. Thanks. Here it is: https://github.com/googlesamples/unity-jar-resolver/issues/170
