### ISSUE TITLE
Can`t resolve android 

### ISSUE THREAD

**Issue by ShunzhiTang** [googlesamples/unity-jar-resolver#168]
Resolution attempt 1: packages [com.google.android.gms:play-services-ads:15.0.1]
Resolve failed due to com.google.android.gms:play-services-ads:15.0.1 missing for project :, attempted to use com.google.android.gms:play-services-ads:15.0.1, failed due to org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.google.android.gms:play-services-ads:15.0.1.
Resolution attempt: 1, conflicts detected: true, updated packages: true
Resolution attempt 2: packages [com.google.android.gms:play-services-ads:15.0.1+]
Resolve failed due to com.google.android.gms:play-services-ads:15.0.1+ missing for project :, attempted to use com.google.android.gms:play-services-ads:15.0.1+, failed due to org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.google.android.gms:play-services-ads:15.0.1+.

Resolution failed logs is:

Failed to fetch the following dependencies:
com.google.android.gms:play-services-ads-license:+
com.google.android.gms:play-services-ads-lite:+
com.google.android.gms:play-services-ads:+
com.google.android.gms:play-services-basement:+
com.google.android.gms:play-services-gass:+

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.ResolverVer1_1:LogMissingDependenciesError(List`1)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey1C:<>m__2E(List`1)
GooglePlayServices.<GradleResolution>c__AnonStorey18:<>m__31()
GooglePlayServices.ResolverVer1_1:ProcessAars(String, HashSet`1, Action)
GooglePlayServices.<GradleResolution>c__AnonStorey17:<>m__27(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey19:<>m__32()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAll>m__6()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
Google.RunOnMainThread:Run(Action, Boolean)
GooglePlayServices.<GradleResolution>c__AnonStorey17:<>m__28(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey

**Comment by stewartmiles** [comment]
@ShunzhiTang looking at https://maven.google.com/ and https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads/15.0.1 the missing module definitely exists.  Are you sure you don't have internet connectivity issues?

**Comment by ShunzhiTang** [comment]
@stewartmiles  hi, The internet connectivity is okay. but I need two version android support. fail log is "Resolve failed due to com.android.support:support-annotations:25.3.1 missing for com.google.android.exoplayer:exoplayer-core:r2.4.4, attempted to use com.android.support:support-annotations:26.1.0, failed due to org.gradle.internal.resolve.ModuleVersionResolveException"   ,  how to resolve it? How to specify the android support version number?  thank you
