### ISSUE TITLE
.meta files are being included in repacked AARs / JARs

### ISSUE THREAD

**Issue by stewartmiles** [googlesamples/unity-jar-resolver#169]
Originally reported in https://github.com/playgameservices/play-games-plugin-for-unity/issues/2004

**Comment by JimmyDeemo** [comment]
May I ask why this was closed @stewartmiles? I am assuming it wasn't fixed as there wasn't and commits referenced.

I have just experienced this issue and want to try and find a solution that doesn't involve opening the archive and editing it manually.

**Comment by Thaina** [comment]
@JimmyDeemo I haven't met this bug since around unity gpgs 0.9.5+

**Comment by stewartmiles** [comment]
@JimmyDeemo this was fixed in 12b868f see the comment that closed it.

**Comment by JimmyDeemo** [comment]
Ah, apologies for the mention. I see the link now; my unfamiliarity with GitHub.
