### ISSUE TITLE
Conflict: play-services-base-9.6.1 vs. play-services-measurement-8.4.0

### ISSUE THREAD

**Issue by Qbit86** [googlesamples/unity-jar-resolver#17]
When Jar Resolver resolves both `play-services-base-9.6.1.aar` and `play-services-measurement-8.4.0/` (`aar` exploded as folder), then build fails with conflict:

```
CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
...
stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzpz;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqa;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqa$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqb;
4 errors; aborting
]
```

---

Unity 5.3.6p6 on Windows 10 Pro targeting Android. Latest Android SDK installed with all components updated via Android SDK Manager.

**Comment by stewartmiles** [comment]
We update all aars across all Google Play Services packages in lock step, so attempting to mix and match two different versions (e.g 9.6.1 vs. 8.4.0) is likely to not work.  Could you update both packages to the same version and try again?
