### ISSUE TITLE
The @packaging is ignored by the Android resolver

### ISSUE THREAD

**Issue by sp-jordi-vilalta** [googlesamples/unity-jar-resolver#174]
Hi,

In some cases I want to specify the packaging (like `@jar`) in order to skip the POM file processing. This may be because I don't want its dependencies to be automatically downloaded, or because the POM file is just invalid.

While looking at older issues (like this: #128) it seems like at some point the process failed to download a package if the specified packaging didn't exist (which makes sense to me). Now it seems to always download the POM file, ignoring the specified packaging, and then it downloads the packaging specified in the POM (and it processes all the dependencies).

Trying to replicate the issue from #128 I get this result:
```
$ ./gradlew -b PlayServicesResolver.scripts.download_artifacts.gradle -PTARGET_DIR=. -PPACKAGES_TO_COPY=com.google.android.gms:play-services-tasks:15.0.1@jar

> Configure project :
MAVEN_REPOS: name=maven url=https://maven.google.com
MAVEN_REPOS: name=MavenLocal url=file:/Users/jvilalta/.m2/repository
MAVEN_REPOS: name=BintrayJCenter url=https://jcenter.bintray.com/
MAVEN_REPOS: name=MavenRepo url=https://repo.maven.apache.org/maven2/
PACKAGES_TO_COPY: com.google.android.gms:play-services-tasks:15.0.1
TARGET_DIR: /Users/jvilalta/PlayServicesResolverGradle/.
Resolution attempt 1: packages [com.google.android.gms:play-services-tasks:15.0.1]
Resolution attempt: 1, conflicts detected: false, updated packages: false
Resolution attempt 2: packages [com.google.android.gms:play-services-tasks:15.0.1]
version locked packages: [com.android.support:support-annotations:26.1.0, com.android.support:support-compat:26.1.0, com.android.support:support-core-ui:26.1.0, com.android.support:support-core-utils:26.1.0, com.android.support:support-fragment:26.1.0, com.android.support:support-media-compat:26.1.0, com.android.support:support-v4:26.1.0]
non-version locked packages: [com.google.android.gms:play-services-tasks:15.0.1]

> Task :copyPackages
Copied artifacts:
android.arch.core.common-1.0.0.jar
android.arch.lifecycle.common-1.0.0.jar
android.arch.lifecycle.runtime-1.0.0.aar
com.android.support.support-annotations-26.1.0.jar
com.android.support.support-compat-26.1.0.aar
com.android.support.support-core-ui-26.1.0.aar
com.android.support.support-core-utils-26.1.0.aar
com.android.support.support-fragment-26.1.0.aar
com.android.support.support-media-compat-26.1.0.aar
com.android.support.support-v4-26.1.0.aar
com.google.android.gms.play-services-basement-15.0.1.aar
com.google.android.gms.play-services-tasks-15.0.1.aar


BUILD SUCCESSFUL in 0s
13 actionable tasks: 13 executed
```

I would expect this to fail because I specified `@jar` and the jar file doesn't exist for this package, but it downloads the `.aar` file instead. Is this an expected behavior? Is there a way to make it behave as I expected? (like in the old releases)

Thanks!

**Comment by stewartmiles** [comment]
AFAIK the only place I messed with the packaging was to fallback to srcaar when "aar" is specified as the packaging.
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/scripts/download_artifacts.gradle#L1367
