### ISSUE TITLE
IOS build exception when appending (ArgumentOutOfRangeException)

### ISSUE THREAD

**Issue by kobyle69** [googlesamples/unity-jar-resolver#176]
Hello, 

I'm getting this exception after I switched to jar resolver v1.2.97.0.

It only happens when trying to append a build on iOS, when doing a clean build or choosing the 'replace' option instead of 'append' it works just fine, on the same exact project.

Haven't encountered this issue in previous versions.

![image](https://user-images.githubusercontent.com/6707227/50567185-8284e800-0d4a-11e9-96b3-65f55921b58c.png)

**Comment by kobyle69** [comment]
Any news on how fixing it? it's really time-consuming having to replace the project on small appends.

**Comment by stewartmiles** [comment]
This is fixed in 1.2.98
https://github.com/googlesamples/unity-jar-resolver/blob/master/play-services-resolver-1.2.98.0.unitypackage?raw=true
