### ISSUE TITLE
Failed to fetch com.google.games:gpgs-plugin-support:+

### ISSUE THREAD

**Issue by Jason-Zy** [googlesamples/unity-jar-resolver#177]
unity 2018.3.0f2 ，google play games plugin version 0.9.50

Resolution failed
Failed to fetch the following dependencies:
com.google.games:gpgs-plugin-support:+

if i ignore this ,my app will crash when try to sign in google

**Comment by stewartmiles** [comment]
@Jason-Zy it sounds like a problem with the gpgs plugin, I recommend opening an issue with that developer.
