### ISSUE TITLE
problem with unity-classes.jar

### ISSUE THREAD

**Issue by hpanahiird** [googlesamples/unity-jar-resolver#180]
high i am using unity jar resolver to get dependencies of my own sdk. in my sdk i have added a .jar file to use Unity classes and sending messages. then when i was trying to build the app in unity3d there was "error while merging dex archives unity". when i took a look at libs folder that was created for dependencies i found a unity-classes.jar file which was automatically added to project. can you tell me how t get rid of that file. even when i delete that it will appear again.

**Comment by stewartmiles** [comment]
@hpanahiird without knowing about your project's details, i.e set of Android dependencies it's hard to say why you're running into an issue.  I recommend adding dependencies one at a time to narrow down which package is causing the issue.

**Comment by hpanahiird** [comment]
i figured out why that problem was happening.
unity itself added that jar file to project and it was no way to prevent that. and i figured out that i can use "compileOnly" or "provided" in my .gradle file to ignore that jar dependency to be included in exported aar file.
thanks a lot for your attention. :)
