### ISSUE TITLE
GetUnityVersionMajorMinor is eating all my CPU

### ISSUE THREAD

**Issue by apautrot** [googlesamples/unity-jar-resolver#181]
Hi
Can you cache the call to GetUnityVersionMajorMinor ?

The code is
```
public static float GetUnityVersionMajorMinor() {
        try {
            var version = InvokeImplMethod("GetUnityVersionMajorMinor");
            return (float)version;
        } catch (Exception) {
            return 0.0f;
        }
    }
```

...and this method is called 3 times per frame under the editor, for a total of 15ms per frame !
The Unity version numbers won't changed until we restart Unity, right ?

![image](https://user-images.githubusercontent.com/4578723/51590349-dfa73000-1ee9-11e9-820d-8c6bcacc12e9.png)

Regards.

**Comment by stewartmiles** [comment]
Fixed by 7a0e0c3
