### ISSUE TITLE
Resolution failed on "com.google.android.gms.play:**" packages

### ISSUE THREAD

**Issue by rlewicki** [googlesamples/unity-jar-resolver#182]
Hi, there is an issue while trying to resolve any of the `com.google.android.gms.play:**` package. When executing resolve following message is displayed:
```
Missing Android component com.google.android.gms.play:play-services-tasks:+ (Android SDK Packages: (none))
```
which is followed by an error:
```
Resolution failed

Failed to fetch the following dependencies:
com.google.android.gms.play:play-services-tasks:+
```
Dependency file that is used by project:
```
<?xml version="1.0" encoding="utf-8"?>
<dependencies>
    <androidPackages>
        <androidPackage spec="android.arch.lifecycle:extensions:1.0.0"/>
        <androidPackage spec="android.arch.lifecycle:common:1.0.3"/>
        <androidPackage spec="android.arch.lifecycle:runtime:1.0.3"/>
        <androidPackage spec="android.arch.core:runtime:1.0.0"/>
        <androidPackage spec="android.arch.core:common:1.0.0"/>

        <androidPackage spec="com.android.support:support-annotations:26.1.0"/>
        <androidPackage spec="com.android.support:support-compat:26.1.0"/>
        <androidPackage spec="com.android.support:support-core-ui:26.1.0"/>
        <androidPackage spec="com.android.support:support-core-utils:26.1.0"/>
        <androidPackage spec="com.android.support:support-fragment:26.1.0"/>
        <androidPackage spec="com.android.support:support-media-compat:26.1.0"/>
        <androidPackage spec="com.android.support:support-v4:26.1.0"/>

        <androidPackage spec="com.google.android.gms.play:play-services-tasks:16.0.1"/>
    </androidPackages>
</dependencies>
```
Maven [repository](https://mvnrepository.com/artifact/com.google.android.gms/play-services-base/16.0.1) contains such library so this was a dead end.

What's worth noting is that there is one and only one dependency file, despite that resolver for some unknown reason replaces specified version with plus sign which causes resolution fail.

I'd love to hear your opinion on that and to find a solution to the issue.

Sample project attached, made with lateset unity-jar-resolver version and Unity 2018.3.0f2.

[jar-resolver-tests.zip](https://github.com/googlesamples/unity-jar-resolver/files/2796179/jar-resolver-tests.zip)

**Comment by stewartmiles** [comment]
@rlewicki the resolver will loosen dependencies (start wildcarding version numbers) when a set of packages is specified that conflict with each other at the specified versions.  This really is no different to resolving dependencies with Gradle.

**Comment by stewartmiles** [comment]
@rlewicki just circling back on this.  If you want to force dependencies to a specific version you can use the exact version specifier e.g for package `com.somewhere:some-package` you can use ``com.somewhere:some-package:[1.2.3]` to only use version `1.2.3`.
