### ISSUE TITLE
Ignoring invalid package specification

### ISSUE THREAD

**Issue by mahdi-malv** [googlesamples/unity-jar-resolver#186]
Hi.
I recently tried to add my library and it's dependencies to Unity via jar-resolver.
When resolving dependencies i get following warning and end with an error.
```
Ignoring invalid package specification 'core' while reading Assets/MyPlugin/Editor/MyPluginDependencies.xml
```
Generally why would a library be **ignored**?

Thanks in advance.

**Comment by stewartmiles** [comment]
@mahdi-malv perhaps your file is not formatted correctly?
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/src/AndroidXmlDependencies.cs#L87

Looks like you haven't specified a valid gradle / maven packet spec.

**Comment by stewartmiles** [comment]
Libraries are included using Gradle which uses the scheme here https://docs.gradle.org/current/userguide/dependency_management_terminology.html#sub:terminology_module_version 
Module can be searched / browsed on sites like https://mvnrepository.com/repos/central 
i.e
`organization:package:version`

where:
- "organization" is something like `com.google`
- "package" is something like `gson`
- "versions" is a version spec which can be a [dynamic](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sub:declaring_dependency_with_dynamic_version) or concrete version etc. e.g `2.1.0`
