### ISSUE TITLE
Resolver not doing anything

### ISSUE THREAD

**Issue by dickssonoliveira** [googlesamples/unity-jar-resolver#187]
Hello all,

I must be missing something while using the resolver, because I can't even get past the _Getting Started_ section. This is how I've done it:

1. Clone the `unity-jar-resolver` repository.
2. Inside the repository, execute Unity from the command line, passing the `play-services-resolver-1.2.100.0.unitypackage` to the `-importPackage` option, the folder of my plugin to the `-projectPath` option (as a relative path, haven't tried to pass the full name yet) and specifying a location to the `-exportPackage` option (with the other flags specified exactly like the _Getting Started_ section.

Nothing happens. It seems nothing is imported or exported, and the command line doesn't print anything.

I've tried skipping this section and follow the _ Android Resolver Usage_ (which is the relevant part to me). Nothing happens, either.

I tried searching for similar issues, but haven't found anything. Any help is greatly appreciated.

I'm running Unity 2018.3.3f1 on a macOS 10.14.

**Comment by dickssonoliveira** [comment]
Got it working! Closing this issue.

**Comment by pzmudzinski** [comment]
How did you solve it? :)
