### ISSUE TITLE
Android SDK path problem with Unity 2019.1

### ISSUE THREAD

**Issue by caglarenes** [googlesamples/unity-jar-resolver#188]
Hello, 

New 2019.1 beta version of Unity was released. With new version, we don't have to download Android SDK & NDK seperately. We can choose them and download via Unity Hub.

When I try to resolve my project I get an error because resolver looking for classic Android SDK path I think.
But Unity Hub downloads SDK to "C:\Program Files\Unity\Hub\Editor\2019.1.0b3\Editor\Data\PlaybackEngines\AndroidPlayer\SDK" for example.

I know it's a beta version but I think more and more people using this feature in the future. Maybe resolver can look for both paths for SDK. 

In Unity preference window, there is "Android SDK Tools Installed with Unity(recommended)" option. It was choosen. When I click, I can't choose another path for SDK. 'Preference > External Tools > Android SDK is return "{none}" in code side. I will also report it to Unity community.

Here my full error:

```
Android dependency resolution failed, your application will probably not run.

Android SDK path must be set to a valid directory ({none})
This must be configured in the 'Preference > External Tools > Android SDK'
menu option.

0x00007FF7ED60E11C (Unity) StackWalker::GetCurrentCallstack
0x00007FF7ED6115D1 (Unity) StackWalker::ShowCallstack
0x00007FF7EBD93BA5 (Unity) GetStacktrace
0x00007FF7EE020CC0 (Unity) DebugStringToFile
0x00007FF7ED63CB09 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x00000163498FD2FB (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x00000163498FCF2B (Mono JIT Code) [DebugLogHandler.cs:10] UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[]) 
0x00000163498FC5C1 (Mono JIT Code) [Logger.cs:61] UnityEngine.Logger:Log (UnityEngine.LogType,object) 
0x000001635D86E55D (Mono JIT Code) [Debug.bindings.cs:127] UnityEngine.Debug:LogError (object) 
0x00000163498EE003 (Mono JIT Code) Google.Logger:Log (string,Google.LogLevel)
0x0000016349965227 (Mono JIT Code) GooglePlayServices.PlayServicesResolver:Log (string,Google.LogLevel)
0x000001635D86E0E3 (Mono JIT Code) GooglePlayServices.ResolverVer1_1:DoResolutionUnsafe (Google.JarResolver.PlayServicesSupport,string,System.Action)
0x000001635D86DD3B (Mono JIT Code) GooglePlayServices.ResolverVer1_1/<DoResolution>c__AnonStorey1B:<>m__2C ()
0x000001635D86DACE (Mono JIT Code) GooglePlayServices.ResolverVer1_1:UpdateTryResolution ()
0x00000163498F7D9E (Mono JIT Code) Google.RunOnMainThread:ExecuteNext ()
0x00000163498F78C3 (Mono JIT Code) Google.RunOnMainThread:<ExecuteAll>m__6 ()
0x00000163498F770C (Mono JIT Code) Google.RunOnMainThread:RunAction (System.Action)
0x00000163498F75E3 (Mono JIT Code) Google.RunOnMainThread:ExecuteAll ()
0x00000163498F70CB (Mono JIT Code) Google.RunOnMainThread:Run (System.Action,bool)
0x000001635D86D6A3 (Mono JIT Code) GooglePlayServices.ResolverVer1_1:DoResolution (Google.JarResolver.PlayServicesSupport,string,System.Action)
0x00000163562EB77A (Mono JIT Code) GooglePlayServices.PlayServicesResolver:ResolveUnsafe (System.Action`1<bool>,bool)
0x00000163562EADB3 (Mono JIT Code) GooglePlayServices.PlayServicesResolver/<ScheduleResolve>c__AnonStorey12:<>m__1D ()
0x00000163562EAB4B (Mono JIT Code) GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob ()
0x00000163562E9D93 (Mono JIT Code) GooglePlayServices.PlayServicesResolver:ScheduleResolve (bool,System.Action`1<bool>,bool)
0x00000163562E909B (Mono JIT Code) GooglePlayServices.PlayServicesResolver:AutoResolve (System.Action)
0x00000163562E8E2B (Mono JIT Code) GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__13 ()
0x000001634BF15554 (Mono JIT Code) Google.RunOnMainThread/ScheduledJob:PollUntilExecutionTime ()
0x00000163498FAF6B (Mono JIT Code) Google.RunOnMainThread:ExecutePollingJobs ()
0x00000163498F791B (Mono JIT Code) Google.RunOnMainThread:<ExecuteAll>m__6 ()
0x00000163498F770C (Mono JIT Code) Google.RunOnMainThread:RunAction (System.Action)
0x00000163498F75E3 (Mono JIT Code) Google.RunOnMainThread:ExecuteAll ()
0x000001634BEDF987 (Mono JIT Code) (wrapper delegate-invoke) <Module>:invoke_void ()
0x000001634BEDF687 (Mono JIT Code) [EditorApplication.cs:200] UnityEditor.EditorApplication:Internal_CallUpdateFunctions () 
0x000001635632D3F5 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007FFD85F7BF9B (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FFD85F01F32 (mono-2.0-bdwgc) [object.c:2919] do_runtime_invoke 
0x00007FFD85F0AF3F (mono-2.0-bdwgc) [object.c:2966] mono_runtime_invoke 
0x00007FF7ED5979C1 (Unity) CallStaticMonoMethod
0x00007FF7ED5975C1 (Unity) CallStaticMonoMethod
0x00007FF7ED597341 (Unity) CallStaticMonoMethod
0x00007FF7EBB32B76 (Unity) SceneTracker::Update
0x00007FF7EBDDEF8A (Unity) Application::TickTimer
0x00007FF7EC09DDA3 (Unity) MainMessageLoop
0x00007FF7EC0A7747 (Unity) WinMain
0x00007FF7EE9B4EAE (Unity) __scrt_common_main_seh
0x00007FFDEA8281F4 (KERNEL32) BaseThreadInitThunk
0x00007FFDEAA1A251 (ntdll) RtlUserThreadStart
```

**Comment by stewartmiles** [comment]
@caglarenes is there a new API to retrieve the Android SDK in the latest version of Unity?  It sounds like the `AndroidSdkRoot` property (here https://github.com/googlesamples/unity-jar-resolver/blob/c05acb599a765937414f95529bc087fa3b4e9003/source/PlayServicesResolver/src/PlayServicesResolver.cs#L581 ) needs to be updated.

**Comment by Thanitsak** [comment]
> @caglarenes is there a new API to retrieve the Android SDK in the latest version of Unity? It sounds like the `AndroidSdkRoot` property (here
> 
> https://github.com/googlesamples/unity-jar-resolver/blob/c05acb599a765937414f95529bc087fa3b4e9003/source/PlayServicesResolver/src/PlayServicesResolver.cs#L581
> 
> ) needs to be updated.

I'm not quite understand. Could you please explain a bit more on how to solve this like what should I do. Many thanks!

**Comment by stewartmiles** [comment]
@Thanitsak this was fixed in https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.109 if you upgrade to the latest version this should be fixed.

**Comment by Thanitsak** [comment]
> @Thanitsak this was fixed in https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.109 if you upgrade to the latest version this should be fixed.

Thank you very much for the reply!
After I removed the old resolver and download the new one there is no error in the Unity console, but when I set up the Google Play Game by copying the resources from the console, it said that couldn't find SDK. Anyway after red error I just clear console and try to build apk file and get the result of success. I not quite sure if this is the right behaviour or not?

Do you know what is this sentence means from the Play Services Resolver "I did do the resolver: Assets ->PlayServiceResolver ->AndroidResolver -> ForceResolve. Then everything worked." I trying to fix the signing in problem so I saw his answer but couldn't find what is he talking about.
Again thank you very very much for the help!
