### ISSUE TITLE
Exported package contains all dependencies + usage with Asset Store Tools ?

### ISSUE THREAD

**Issue by pzmudzinski** [googlesamples/unity-jar-resolver#190]
I've used this command to prepare final package:
 ```
/Applications/Unity/Unity.app/Contents/MacOS/Unity -gvh_disable -batchmode -projectPath ~/... -exportPackage Assets MyPlugin.unitypackage -quit
```
Unity version: 2017.1.0f3

I created test project and imported MyPlugin.unitypackage I see it includes all Android dependencies:
![image](https://user-images.githubusercontent.com/1887653/53634098-90a39780-3c19-11e9-9072-1bae3c93818e.png)

I guess it shouldn't be case and it should be downloaded after importing this package? Am I missing something here?

In addition I see it's trying to import AssetStoreTools directory which also shouldn't be part of plugin on Asset Store.

Final question - how do I upload package generated by command line tool to Asset Store? I see only option is doing it through Unity UI which seems to generate package by itself. Should I use Asset Store Tools and its Package Upload or not?

This is me dependencies file:
```
<dependencies>
  <!-- Android dependencies are specified under the "androidPackages" element.
       Each "androidPackage" element contains the attributes of an Android
       dependency (e.g AAR, JAR reference). -->
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-base:16.1.0" />
    <androidPackage spec="com.google.android.gms:play-services-location:16.0.0" />
  </androidPackages>

</dependencies>
```

Resolver version: 1.2.102

**Comment by stewartmiles** [comment]
@pzmudzinski it sounds like `-gvh_disable` isn't being respected.  When you open Unity to import Asset Store Tools and use the UI to upload are you running Unity with the `-gvh_disable` flag set to make sure the Version Handler and Android Resolver do not run?

**Comment by pzmudzinski** [comment]
@stewartmiles when I upload package using Asset Store Tools I am not able to look into uploaded package content (terrible UX) so I cant say whats included there. However, when I use Unity CLI with command I posted (-ghv_disable) above I am getting dependencies included so I am assuming it gives the same result. So... what I should do now?

**Comment by pzmudzinski** [comment]
Can anyone help me with it? It's completely blocking me from plugin release. 
Also it seems this `gvh_disable` flag isn't documented anywhere - is it part of official Unity API?

**Comment by stewartmiles** [comment]
If you're having issues with Unity's asset store tools from the CLI you can run instead in interactive mode using the `-gvh_disable` command line argument.  The flag is not part of Unity it's part of the VersionHandler see https://github.com/googlesamples/unity-jar-resolver/blob/ecfc41a15f4be10e8b3c88aca4352c4c17e38a3e/source/VersionHandlerImpl/src/VersionHandlerImpl.cs#L1574

Since it's not possible to inspect what is being uploaded to Unity's asset store, could you create a new project temporarily publish it, download it to verify then unpublish if it's wrong or perhaps contact Unity support to help with this?

**Comment by pzmudzinski** [comment]
I've asked Unity support for help because I have no idea how to proceed. I cannot package my plugin with all those files:
```
com.android.support.support-compat-26.1.0.aar
com.android.support.support-core-ui-26.1.0.aar
com.android.support.support-core-utils-26.1.0.aar
com.android.support.support-fragment-26.1.0.aar
com.android.support.support-media-compat-26.1.0.aar
com.android.support.support-v4-26.1.0.aar
com.google.android.gms.play-services-base-16.1.0.aar
com.google.android.gms.play-services-basement-16.2.0.aar
com.google.android.gms.play-services-location-16.0.0.aar
com.google.android.gms.play-services-places-placereport-16.0.0.aar
com.google.android.gms.play-services-tasks-16.0.1.aar
```

Also I've noticed they changed submission guidelines and now you are supposed to put all of your plugin content under {yourPluginName}/Editor,Assets etc.

If I put `PlayServicesResolver` under my directory what will happens if user already has another instance of it via different package? 

Unity dependency management is true nightmare. 👎

**Comment by stewartmiles** [comment]
@pzmudzinski you could potentially move the PlayServicesResolver bits under {yourPluginName}/ and subsequent imports from different locations may *just work* (tm) as each release of the resolver updates all file GUIDs allowing the VersionHandler to clean up old versions of the plugin.  I think the only bit that may result in a conflict on import is the bootstrap module for the VersionHandler (i.e VersionHandler.dll).  This is indeed a real pain especially since - AFAIK - older versions of Unity simply won't work if everything is put under {yourPluginName}/.

**Comment by pzmudzinski** [comment]
So if you upload your package to Asset Store using version X users with versions lower than X won't be available to import it so it won't be such big issue (I think so ekhm).

However, I see four solutions here:
1. Include `PlayServicesResolver` as part of a plugin's directory and pray it will work for everyone,
2. Ask users to include `PlayServicesResolver` manually - is there some kind of release URL for latest `unity-jar-resolver.unitypackage`?
3. Do not include `PlayServicesResolver` but put 50 play-services `aar` files into a package and ask users to resolve dependency conflicts by themselves (sounds like fun!),
4. Wait next 5 years for Unity Support to come with some recommended solution. 

It seems 2) is best option so far. What do you think?

**Comment by stewartmiles** [comment]
I think it's worth trying option 1).  The only issue folks will run into when importing other plugins with the resolver is that they'll have to delete one of the VersionHandler.dll files in the project.  Have you taken a look at what Facebook's Unity SDK does?  They're also users of this package, I'm wondering how they're using it.

**Comment by pzmudzinski** [comment]
I was trying to understand their approach here: https://github.com/facebook/facebook-sdk-for-unity/blob/9389c5cfcaf1daa2a49fac39570e51b4563f37be/Facebook.Unity.Editor/android/AndroidSupportLibraryResolver.cs but I failed ;) 

It seems they dynamically download and import (via shell script) unity-jar-resolver.unitypackage and import it into Unity project as a boot script. But I cannot understand how are they resolving Android dependencies.

**Comment by pzmudzinski** [comment]
Btw. I've checked their package on Asset Store and while importing I see they include both unity-jar-resolver and all Android dependencies (!!!). 
![image](https://user-images.githubusercontent.com/1887653/53894623-b58c7600-4030-11e9-8a1d-805023469502.png)

**Comment by pzmudzinski** [comment]
Also importing two packages where both are including `PlayServicesResolver` causes error: 
```error CS1704: An assembly with the same name `Google.VersionHandler' has already been imported. Consider removing one of the references or sign the assembly```

😠 

Users using Asset Store are usually at beginner level so making them resolve conflicts like that might end up with 1 star ratings (for a package which was imported as second).

**Comment by stewartmiles** [comment]
@pzmudzinski it looks like Facebook's approach is *almost* ok, though I'm surprised they're include all Android libraries in their plugin as well.  If they're labelled correctly by the resolver they'll be deleted when auto-resolution occurs so it *may* be ok.

Interestingly, Facebook are including the `PlayServicesResolver` in the root directory of the plugin.  You mentioned Unity don't want folks doing that anymore but clearly some people are.  Perhaps it's worth submitting the plugin in a similar fashion to Facebook though excluding the Android libraries by running Unity with the `-gvh_disable` flag set?

**Comment by pzmudzinski** [comment]
Yeah, actually I updated Unity little bit (to 2017.3) and `gvh_disable` flag started being respected. 

I will try with this approach and will give Unity review team link to this issue as a reason why `PlayServicesResolver` must be in root folder. 

Thanks for active support.
