### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by brzGatsu** [googlesamples/unity-jar-resolver#192]
Version 1.2.102

When starting Unity my console is spammed with "Caching AAR 'path' state" and "Extracting 'path' to 'path'", even though verbose logging is disabled.

Callstack (Caching):

Caching AAR Assets/Plugins/Android/android.arch.core.common-1.0.0.jar state
Logger.Log()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:83

PlayServicesResolver.Log()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:699

ResolverVer1_1.LoadAarExplodeCache()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:256

GooglePlayServices.ResolverVer1_1..ctor()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:222

GooglePlayServices.PlayServicesResolver..cctor()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:616

EditorAssemblies.ProcessInitializeOnLoadAttributes()

Callstack (Extracting):

Extracting Assets/Plugins/Android/android.arch.lifecycle.runtime-1.0.0.aar ("AndroidManifest.xml" "jni" "classes.jar") to ... \Temp\ymoo2hji.705
Logger.Log()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:83

PlayServicesResolver.Log()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:699

PlayServicesResolver.ExtractZip()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1620

ResolverVer1_1.ShouldExplode()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:1476

ResolverVer1_1.LoadAarExplodeCache()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:258

GooglePlayServices.ResolverVer1_1..ctor()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:222

GooglePlayServices.PlayServicesResolver..cctor()    /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:616

EditorAssemblies.ProcessInitializeOnLoadAttributes()

**Comment by stewartmiles** [comment]
Hmm, it definitely sounds like you have verbose logging enabled:

https://github.com/googlesamples/unity-jar-resolver/blob/720cb92748eb06b4f373867d6a42ad45dfebbb1e/source/PlayServicesResolver/src/ResolverVer1_1.cs#L256

https://github.com/googlesamples/unity-jar-resolver/blob/c05acb599a765937414f95529bc087fa3b4e9003/source/PlayServicesResolver/src/PlayServicesResolver.cs#L699

https://github.com/googlesamples/unity-jar-resolver/blob/e629e49948f3e688ae325b0084effb9cfb99c976/source/VersionHandlerImpl/src/Logger.cs#L78

The only commit that could have affected this is https://github.com/googlesamples/unity-jar-resolver/commit/720cb92748eb06b4f373867d6a42ad45dfebbb1e

I just tried this out with a couple of different settings, no log messages..
![image](https://user-images.githubusercontent.com/6042948/53968786-84ea2200-40ac-11e9-9641-da678e9c9793.png)

![image](https://user-images.githubusercontent.com/6042948/53968880-b06d0c80-40ac-11e9-99f0-30ba69dae26d.png)

**Comment by stewartmiles** [comment]
Interestingly, when disabling "Use project settings" I end up seeing log spam and settings don't seem to be saved correctly anymore.

**Comment by brzGatsu** [comment]
The "Use project settings" setting makes no differences for me, however, it was enabled. I just verified that GvhProjectSettings.xml is both, correctly written and read.

**Comment by julio-gorge** [comment]
Same issue here. Log spam on every project load, no matter what is configured in the Android Resolver Settings dialog.
