### ISSUE TITLE
Failed to get Java version when running

### ISSUE THREAD

**Issue by shlighter** [googlesamples/unity-jar-resolver#197]
So I recently started to get the this warning,  which leads to another warning- "Some conflicting dependencies were found." and then an error "Resolution failed".
I noticed someone opened a similar issue 
https://github.com/googlesamples/unity-jar-resolver/issues/87
but their problem was with different versions and with openJDk...

I'm using **Unity 2018.3.9f1
Java version 12
Resolver- v1.2.102.0**
Full error:
Failed to get Java version when running C:\Program Files\Java\jdk-12\bin\java.exe
It is not be possible to verify your Java installation is new enough to compile with the latest Android SDK

Successfully executed 'C:\Program Files\Java\jdk-12\bin\java.exe -version'
stdout:

stderr:
java version "12" 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)

exit code: 0

UnityEngine.Debug:LogWarning(Object)
Google.Logger:Log(String, LogLevel) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:87)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:699)
GooglePlayServices.JavaUtilities:LogJdkVersionFailedWarning(String, String) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/JavaUtilities.cs:157)
GooglePlayServices.JavaUtilities:CheckJdkForApiLevel() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/JavaUtilities.cs:197)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1330)
GooglePlayServices.<ScheduleResolve>c__AnonStorey12:<>m__22() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1305)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1224)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Action`1, Boolean) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1316)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:906)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__27() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:885)
Google.RunOnMainThread:ExecutePollingJobs() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:286)
Google.RunOnMainThread:<ExecuteAll>m__16() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:400)
Google.RunOnMainThread:RunAction(Action) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by a-maurice** [comment]
Hi,

I believe the problem you are seeing is that the JDK version is being reported in a different format than we are expecting.  The code to parse it is here:
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/src/JavaUtilities.cs#L189
which is expecting <major>.<minor>.<revision>, while based on your logs it seems to just be getting the major, without a minor or revision.  We'll look into handling this case.

**Comment by stewartmiles** [comment]
This is fixed in release https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.99
