### ISSUE TITLE
Crashes Unity 5.0

### ISSUE THREAD

**Issue by jizc** [googlesamples/unity-jar-resolver#20]
This is a similar issue as [Issue #16](https://github.com/googlesamples/unity-jar-resolver/issues/16).

Unity 5.0 crashes due to there not being a build target 35.

![image](https://cloud.githubusercontent.com/assets/1404846/19627118/0181db94-9940-11e6-88f9-7b738ee2a152.png)

Happens on start-up of Unity, the second time I open a project. The exception is the first time I open a project. For example if I delete the Library folder and open the project, Unity will regenerate the Library and then open fine. But if I then close Unity and reopen the project, I get the error.

**Comment by stewartmiles** [comment]
@claywilkinson we've fixed this on another branch any chance we could get this merged upstream?

**Comment by stewartmiles** [comment]
We've resolved this in the latest release.
