### ISSUE TITLE
AndroidResolverDependencies files aren't matching up between projects

### ISSUE THREAD

**Issue by Baraphor** [googlesamples/unity-jar-resolver#200]
Hello,

I am having this issue with our projects where the resolver is bringing in the wrong versions of the files.

As you can see here and in the attached files I am not sure why it is pulling in the higher version.

packages:
com.google.android.gms:play-services-ads:16.0.0+</package>
com.google.android.gms:play-services-ads-identifier:16.0.0+</package>
com.google.android.gms:play-services-ads-lite:16.0.0+</package>

files:
Assets/Plugins/Android/com.google.android.gms.play-services-ads-17.2.0.aar
Assets/Plugins/Android/com.google.android.gms.play-services-ads-base-17.2.0.aar
Assets/Plugins/Android/com.google.android.gms.play-services-ads-identifier-16.0.0.aar
Assets/Plugins/Android/com.google.android.gms.play-services-ads-lite-17.2.0.aar

The thing is I setup all the sdk's we use in newer projects and this does not happen as you can see in the sample project file I have attached below, we are using v1.2.95.0.

Is there anyway to figure out why it is pulling in a different version?

[MainProject-AndroidResolverDependencies.txt](https://github.com/googlesamples/unity-jar-resolver/files/3060588/MainProject-AndroidResolverDependencies.txt)
[TestProject-AndroidResolverDependencies.txt](https://github.com/googlesamples/unity-jar-resolver/files/3060587/TestProject-AndroidResolverDependencies.txt)

Thanks

**Comment by stewartmiles** [comment]
@Baraphor did you generate those attached files from your project?  They're not in a format supported by the Android Resolver at the moment.

I think a good place to start looking is to pull in the latest version of this plugin and use the `Assets > PlayServicesResolver > Android Resolver > Display Libraries` menu option to dump the current set of dependencies included in the project.  That will show the loaded set and where they're read from.

In addition, it's worth turning on verbose logging and checking the output of the `download_artifacts.gradle` script, it can auto-upgrade dependencies when conflicts are found which could also be the source of this issue.

**Comment by chkuang-g** [comment]
@Baraphor Does the suggestion from @stewartmiles resolve your issue?

It's been awhile so I'll close this issue for now.  Let us know if it still happens to you.
