### ISSUE TITLE
Support for Development pods (cont)

### ISSUE THREAD

**Issue by sdolim** [googlesamples/unity-jar-resolver#201]
Issue/PR #171 added support for development pods by allowing the "path" attribute in the dependencies file.  This is working great for workspace integration mode, but not for project integration mode.  The problem is that the function IOSResolver.UpdateProjectDeps() only scans the Pods/ subdirectory of the build, while development pods may point to paths outside of that file tree.  Therefore the development pods don't get scanned, so their files don't get added to the project.  (These files *are* listed in the Pods *project*, but that list is only used to filter the files found by scanning the Pods/ directory.)

We have customers whose build systems preclude them from using workspace integration mode, hence this is a nontrivial issue for our SDK.

**Comment by stewartmiles** [comment]
@sdolim that does sound like a problem, any chance you're able to put a PR together for this?

**Comment by sdolim** [comment]
Sure, I'll give it a go.

**Comment by stewartmiles** [comment]
Fixed by pull #204 .
