### ISSUE TITLE
Source pods with Resources

### ISSUE THREAD

**Issue by sdolim** [googlesamples/unity-jar-resolver#202]
Source pods in project integration mode do not have their Resources directories scanned for resources.  In IOSResolver.UpdateProjectDeps(), only Resources directories inside .framework's are scanned.  (Our SDK is distributed in source form for business reasons.)

**Comment by sdolim** [comment]
Interesting:  There is a script called Pods-Unity-iPhone-resources.sh in the Pods/Target Support Files/Pods-Unity-iPhone/ directory.  In a workspace-integrated project, the main target (Unity-iPhone) has a step in the Build Phases called "[CP] Copy Pods Resources" which invokes this script to copy all the resources into the build.  There is no corresponding Build Phase rule in the project-integrated Xcode project.  This must be why the Resources are not getting included.

**Comment by sdolim** [comment]
Looks like this report is a dup of #71?

**Comment by stewartmiles** [comment]
Fixed by Pull #204
