### ISSUE TITLE
Gradle failed to fetch dependencies

### ISSUE THREAD

**Issue by ardangn** [googlesamples/unity-jar-resolver#203]
I started getting this error after I imported the latest 'Google Play Games' plugin.
I am able to even do a build but the apk doesn't respond on the phone.
and here is the complete error:

Gradle failed to fetch dependencies.

Failed to run 'C:\Users\Arun\Documents\ColorSwitch\Unity\ColorSwitch\Temp\PlayServicesResolverGradle\gradlew.bat -b "C:\Users\Arun\Documents\ColorSwitch\Unity\ColorSwitch\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" --daemon "-PANDROID_HOME=C:/AndroidSDK" "-PTARGET_DIR=C:\Users\Arun\Documents\ColorSwitch\Unity\ColorSwitch\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/Users/Arun/Documents/ColorSwitch/Unity/ColorSwitch/Assets/Firebase/m2repository;file:///C:/Users/Arun/Documents/ColorSwitch/Unity/ColorSwitch/Assets/GooglePlayGames/Editor/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-analytics:16.3.0;com.google.firebase:firebase-core:16.0.7;com.google.firebase:firebase-iid:[17.0.4];com.google.firebase:firebase-analytics-unity:5.5.0;com.google.firebase:firebase-common:16.0.4;com.google.firebase:firebase-app-unity:5.5.0;com.google.firebase:firebase-auth:16.1.0;com.google.firebase:firebase-auth-unity:5.5.0;com.google.firebase:firebase-config:16.3.0;com.google.firebase:firebase-config-unity:5.5.0;com.google.games:gpgs-plugin-support:0.9.63;com.google.android.gms:play-services-games:15.0+;com.google.android.gms:play-services-nearby:15.0+;com.google.firebase:firebase-messaging:17.3.4+;com.android.support:support-v4:27.1+;com.android.support:exifinterface:27.1+"'
stdout:
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

stderr:

FAILURE: Build failed with an exception.

* What went wrong:
Could not connect to the Gradle daemon.
Daemon uid: a01be169-ce46-4889-8028-fd7d59a7dcd7 with diagnostics:
Daemon pid: 1832
  log file: C:\Users\Arun\.gradle\daemon\4.10\daemon-1832.out.log
----- Last  20 lines from daemon log file - daemon-1832.out.log -----
22:49:59.026 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
22:49:59.027 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
22:49:59.028 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
22:49:59.029 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
22:49:59.029 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
22:49:59.030 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
22:49:59.031 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
22:49:59.031 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
22:49:59.032 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
22:50:09.018 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
22:50:09.019 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
22:50:09.019 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
22:50:09.020 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
22:50:09.021 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
22:50:09.021 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
22:50:09.021 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
22:50:09.022 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
22:50:09.026 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] The file lock is held by a different Gradle process (pid: 13876, lockId: -4964425795046430564). Pinged owner at port 60804
22:50:09.026 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
22:50:09.029 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
----- End of the daemon log -----

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:91)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:699)
GooglePlayServices.<GradleResolution>c__AnonStorey18:<>m__2F(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:619)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__3A() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:710)
Google.RunOnMainThread:ExecuteNext() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.RunOnMainThread:<ExecuteAll>m__16() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:394)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
Google.RunOnMainThread:Run(Action, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:349)
GooglePlayServices.<GradleResolution>c__AnonStorey18:<>m__30(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:711)
GooglePlayServices.<GradleResolution>c__AnonStorey18:<>m__31(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:762)
GooglePlayServices.ProgressReporter:SignalComplete() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:116)
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:107)
GooglePlayServices.<RunAsync>c__AnonStorey2:<>m__4() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLine.cs:136)
Google.RunOnMainThread:ExecuteNext() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.RunOnMainThread:<ExecuteAll>m__16() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:394)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by stewartmiles** [comment]
https://stackoverflow.com/questions/21523508/it-is-currently-in-use-by-another-gradle-instance ?

Also, you can disable the Gradle daemon under `Assets > Play Services Resolver > Android Resolver > Settings` if it's giving you trouble on your machine.

**Comment by stewartmiles** [comment]
@ardangn since we haven't heard from you, I'll assume your issue is resolved.  Feel free to ping this thread if that isn't the case.
