### ISSUE TITLE
Unity Editor freezes when opening due to ReplaceVariablesInAndroidManifest

### ISSUE THREAD

**Issue by henriqueranj** [googlesamples/unity-jar-resolver#206]
Hello, I am currently facing constant Unity Editor freezes when opening the Android project and even when running Unity Cloud Build builds.

The amount of times it freezes has not been deterministic so far, it may take 1-2 force closes of Unity for the project to open properly. In Unity Cloud Build, the builds may get stuck in this step and it forces me to cancel and perform a new build.

By assessing the Editor log (and having Verbose logging), it seems to freeze after:
```
Will apply attribute value replacements:
${applicationId} --> com.ranj.xxxxx
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Google.Logger:Log(String, LogLevel) (at Z:\tmp\tmp.2Fo4CfaKyh\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\Logger.cs:83)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at Z:\tmp\tmp.VWWf5QhVMz\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:699)
GooglePlayServices.PlayServicesResolver:ReplaceVariablesInAndroidManifest(String, String, Dictionary`2) (at Z:\tmp\tmp.VWWf5QhVMz\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:1045)
GooglePlayServices.PlayServicesResolver:PatchAndroidManifest(String, String) (at Z:\tmp\tmp.VWWf5QhVMz\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:1082)
GooglePlayServices.PlayServicesResolver:OnSettingsChanged() (at Z:\tmp\tmp.VWWf5QhVMz\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:1522)
GooglePlayServices.PlayServicesResolver:.cctor() (at Z:\tmp\tmp.VWWf5QhVMz\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:630)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
UnityEditor.EditorAssemblies:ProcessEditorInitializeOnLoad(Type) (at C:\buildslave\unity\build\Editor\Mono\EditorAssemblies.cs:93)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes() (at C:\buildslave\unity\build\Editor\Mono\EditorAssemblies.cs:131)
 
(Filename: /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs Line: 101)
```

I am currently using the GooglePlayServices Resolver for Firebase 5.6.1 with Cloud Messaging, Crashlytics, and Firebase Analytics, in Unity 2018.1.8f1.

These issues started happening after updating to the latest Firebase 5.6.1.

**Comment by stewartmiles** [comment]
Hi @henriqueranj which Unity editor version are you using and what host platform (Windows, MacOS, Linux)?

It's very odd you're seeing a freeze here the code is pretty simple https://github.com/googlesamples/unity-jar-resolver/blob/c05acb599a765937414f95529bc087fa3b4e9003/source/PlayServicesResolver/src/PlayServicesResolver.cs#L1045

**Comment by henriqueranj** [comment]
Helllo @stewartmiles , I am using Unity 2018.1.8f1 on Windows 10 and MacOS 10.14 (Mojave).

Thank you for pointing out the code, it is indeed very simple. Maybe the step after is freezing before any other log is printed to the console? This is the first project we are using with Firebase 5.6.1, and we do not have those freezes in our other projects.

Our Unity Cloud Build processes also randomly freeze in a Google PlayResolver step (in both Android and iOS builds). I noticed that there it happens in different Google PlayResolver steps, not always the attribute value replacements as in the local builds.

I will investigate this further as soon as I have some time.

**Comment by henriqueranj** [comment]
Hi @stewartmiles , with further investigation we found out that another plugin we used caused the Unity Editor to freeze upon startup. Somehow this freeze affected the GooglePlay Resolver during steps that would change/extract assets.

I think we have it solved now by updating the misbehaving plugin.

**Comment by stewartmiles** [comment]
@henriqueranj thanks for the follow up much appreciated.
