### ISSUE TITLE
Apk crashes after build 

### ISSUE THREAD

**Issue by MightyKnightt** [googlesamples/unity-jar-resolver#207]
Apk crashes after build
Hello, I'm trying to build an apk with admob but the apk kepps crashing on my android device. There is no error in console tab of Unity editor.But, when i ran adb logcat fo debugging i found these errors.

![Logcat](https://user-images.githubusercontent.com/50145073/56969137-2ad47d00-6b82-11e9-91e4-687ae9ff2191.PNG)

The code in my Androidmanifest xml is same as from the admob site, except for android name and app id, for which, i have entered my app id and android name.Any help would be appreciated.

**Comment by stewartmiles** [comment]
You've filed a bug with the wrong tracker.

Besides I'm pretty sure the log message describes what you need to do by following the short links in the log.

Want more help, file an issue with https://github.com/googleads/googleads-mobile-unity
