### ISSUE TITLE
Failed to fetch the following dependencies: com.google.android.gms:play-services-ads:17.2.0

### ISSUE THREAD

**Issue by srcsameer** [googlesamples/unity-jar-resolver#211]
i am using
Unity 2018.3.1f1
JDK jdk1.8.0_201
Google Mobile Ads Unity Plugin v3.16

when i am importing Google Mobile Ads in a fresh project i am getting an error:
Assets\GoogleMobileAds\Editor\PListProcessor.cs(5,19)
anyways i have solved it by following [this issue](https://github.com/googleads/googleads-mobile-unity/issues/882) but just after getting it solve resolving android dependencies window opens up and i get another error here.
(Thanks in advance to Help)

> Gradle failed to fetch dependencies.

Failed to run 'F:\Unity_prac\Pong\OnDevelopment\With Google API\r&d\R&D02\Temp\PlayServicesResolverGradle\gradlew.bat -b "F:\Unity_prac\Pong\OnDevelopment\With Google API\r&d\R&D02\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" --daemon "-PANDROID_HOME=C:\Users\Sameer\AppData\Local\Android\sdk" "-PTARGET_DIR=F:\Unity_prac\Pong\OnDevelopment\With Google API\r&d\R&D02\Assets\Plugins\Android" "-PMAVEN_REPOS=https://maven.google.com/" "-PPACKAGES_TO_COPY=com.google.android.gms:play-services-ads:17.2.0"'
stdout:

stderr:
The system cannot find the path specified.
'D02\Temp\PlayServicesResolverGradle\' is not recognized as an internal or external command,
operable program or batch file.
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:91)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:699)
GooglePlayServices.<GradleResolution>c__AnonStorey18:<>m__2F(Result) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:619)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__3A() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:710)
Google.RunOnMainThread:ExecuteNext() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.RunOnMainThread:<ExecuteAll>m__16() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:394)
Google.RunOnMainThread:RunAction(Action) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
Google.RunOnMainThread:Run(Action, Boolean) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:349)
GooglePlayServices.<GradleResolution>c__AnonStorey18:<>m__30(Result) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:711)
GooglePlayServices.<GradleResolution>c__AnonStorey18:<>m__31(Result) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:762)
GooglePlayServices.ProgressReporter:SignalComplete() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:116)
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:107)
GooglePlayServices.<RunAsync>c__AnonStorey2:<>m__4() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/CommandLine.cs:136)
Google.RunOnMainThread:ExecuteNext() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.RunOnMainThread:<ExecuteAll>m__16() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:394)
Google.RunOnMainThread:RunAction(Action) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

> Resolution failed

Failed to fetch the following dependencies:
com.google.android.gms:play-services-ads:17.2.0

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:91)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:699)
GooglePlayServices.ResolverVer1_1:LogMissingDependenciesError(List`1) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:463)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey1D:<>m__36(List`1) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:1058)
GooglePlayServices.<GradleResolution>c__AnonStorey18:<>m__2F(Result) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:623)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__3A() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:710)
Google.RunOnMainThread:ExecuteNext() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.RunOnMainThread:<ExecuteAll>m__16() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:394)
Google.RunOnMainThread:RunAction(Action) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
Google.RunOnMainThread:Run(Action, Boolean) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:349)
GooglePlayServices.<GradleResolution>c__AnonStorey18:<>m__30(Result) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:711)
GooglePlayServices.<GradleResolution>c__AnonStorey18:<>m__31(Result) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:762)
GooglePlayServices.ProgressReporter:SignalComplete() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:116)
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:107)
GooglePlayServices.<RunAsync>c__AnonStorey2:<>m__4() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/PlayServicesResolver/src/CommandLine.cs:136)
Google.RunOnMainThread:ExecuteNext() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.RunOnMainThread:<ExecuteAll>m__16() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:394)
Google.RunOnMainThread:RunAction(Action) (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /usr/local/google/home/cleoschneider/google-play-resolver/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by stewartmiles** [comment]
Try renaming the folder from `r&d` to something else?

**Comment by srcsameer** [comment]
I have renamed the project to `sample`
and reopened it in unity, nothing actually happened then i tried to resolve manually through android resolve option and i got resolution succeeded window in a blink, then i tried force resolve and i got the same error log with a bit of change that i noticed.
```
d\sample\Temp\PlayServicesResolverGradle\' is not recognized as an internal or external command,
operable program or batch file
```
then i have again created a new project on  the desktop and imported google mobile ads, this time after changing the script PListProcessor.cs,  resolver window started and completed successfully.  i don't know how but  it's done now.

one more problem minor issue i am  getting in unity is that whenever i am  switching my project to android i am getting a warning log which is...
```
Failed getting available Android API levels. Make sure your android sdk tools version is 25 or higher and you have internet connection.
System.Threading.ThreadHelper:ThreadStart()
```

thank you for your support @stewartmiles

**Comment by srcsameer** [comment]
Adding more info here... after resolution succeeded i have build the apk for test using gradle build system, But whenever i am running it on an emulator or on my android device, the app is crashing constantly. i tried to get the logcat while running it on an emulator.

> 05-14 19:44:17.159   365   720 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.ast.astest/com.unity3d.player.UnityPlayerActivity bnds=[35,596][165,850]} from uid 10024 on display 0
05-14 19:44:17.180  3503  3503 E libprocessgroup: failed to make and chown /acct/uid_10057: Read-only file system
05-14 19:44:17.180  3503  3503 W Zygote  : createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
05-14 19:44:17.181  3503  3503 W art     : Unexpected CPU variant for X86 using defaults: x86
05-14 19:44:17.182   365   610 I ActivityManager: Start proc 3503:com.ast.astest/u0a57 for activity com.ast.astest/com.unity3d.player.UnityPlayerActivity
05-14 19:44:17.207    84   116 D gralloc_intel: gralloc_alloc: Creating ashmem region of size 3686400
05-14 19:44:17.320   365   721 W ActivityManager: Slow operation: 78ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
05-14 19:44:17.352   365   977 W AppOps  : Finishing op nesting under-run: uid 10024 pkg com.microvirt.launcher code 24 time=0 duration=0 nesting=0
05-14 19:44:17.366  3503  3503 D AndroidRuntime: Shutting down VM
05-14 19:44:17.366  3503  3503 E AndroidRuntime: FATAL EXCEPTION: main
05-14 19:44:17.366  3503  3503 E AndroidRuntime: Process: com.ast.astest, PID: 3503
05-14 19:44:17.366  3503  3503 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException:
05-14 19:44:17.366  3503  3503 E AndroidRuntime:
05-14 19:44:17.366  3503  3503 E AndroidRuntime: ******************************************************************************
05-14 19:44:17.366  3503  3503 E AndroidRuntime: * Invalid application ID. Follow instructions here: https://goo.gl/fQ2neu to *
05-14 19:44:17.366  3503  3503 E AndroidRuntime: * find your app ID.                                                          *
05-14 19:44:17.366  3503  3503 E AndroidRuntime: ******************************************************************************
05-14 19:44:17.366  3503  3503 E AndroidRuntime:
05-14 19:44:17.366  3503  3503 E AndroidRuntime:
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:5858)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5447)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5386)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at android.app.ActivityThread.-wrap2(ActivityThread.java)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6121)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
05-14 19:44:17.366  3503  3503 E AndroidRuntime: Caused by: java.lang.IllegalStateException:
05-14 19:44:17.366  3503  3503 E AndroidRuntime:
05-14 19:44:17.366  3503  3503 E AndroidRuntime: ******************************************************************************
05-14 19:44:17.366  3503  3503 E AndroidRuntime: * Invalid application ID. Follow instructions here: https://goo.gl/fQ2neu to *
05-14 19:44:17.366  3503  3503 E AndroidRuntime: * find your app ID.                                                          *
05-14 19:44:17.366  3503  3503 E AndroidRuntime: ******************************************************************************
05-14 19:44:17.366  3503  3503 E AndroidRuntime:
05-14 19:44:17.366  3503  3503 E AndroidRuntime:
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at com.google.android.gms.internal.ads.zzabg.attachInfo(Unknown Source)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(Unknown Source)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:5855)
05-14 19:44:17.366  3503  3503 E AndroidRuntime:        ... 10 more
05-14 19:44:17.367   365   376 W ActivityManager:   Force finishing activity com.ast.astest/com.unity3d.player.UnityPlayerActivity
05-14 19:44:17.453   365  1463 I OpenGLRenderer: Initialized EGL, version 1.4
05-14 19:44:17.453   365  1463 D OpenGLRenderer: Swap behavior 1
05-14 19:44:17.453   365  1463 E EGL_adreno: CreateContext rcMajorVersion:3, minorVersion:1
05-14 19:44:17.453   365  1463 E EGL_adreno: rcMajorVersion = 3, minorVersion = 1
05-14 19:44:17.454   365  1463 D EGL_adreno: eglCreateContext: 0x98d74880: maj 3 min 1 rcv 3
05-14 19:44:17.490   365  1463 E EGL_adreno: tid 1463: eglSurfaceAttrib(1313): error 0x3009 (EGL_BAD_MATCH)
05-14 19:44:17.495   365  1463 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x9ac49b00, error=EGL_BAD_MATCH
05-14 19:44:17.880  3523  3523 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-14 19:44:17.881   365   389 W ActivityManager: Activity pause timeout for ActivityRecord{d009176 u0 com.ast.astest/com.unity3d.player.UnityPlayerActivity t48 f}
05-14 19:44:17.885  3523  3523 D AndroidRuntime: CheckJNI is OFF
05-14 19:44:17.915  3523  3523 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
05-14 19:44:17.927  3523  3523 W art     : Unexpected CPU variant for X86 using defaults: x86
05-14 19:44:17.933  3523  3523 W         : Failed to bind-mount /system/lib/x86/cpuinfo as /proc/cpuinfo: No such file or directory
05-14 19:44:17.954  3523  3523 E memtrack: Couldn't load memtrack module (No such file or directory)
05-14 19:44:17.954  3523  3523 E android.os.Debug: failed to load memtrack module: -2
05-14 19:44:17.955  3523  3523 I Radio-JNI: register_android_hardware_Radio DONE
05-14 19:44:17.970   883  1060 E EGL_adreno: tid 1060: eglSurfaceAttrib(1313): error 0x3009 (EGL_BAD_MATCH)
05-14 19:44:17.970   883  1060 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x969519e0, error=EGL_BAD_MATCH
05-14 19:44:17.984  3523  3523 D AndroidRuntime: Calling main entry com.android.commands.am.Am
05-14 19:44:17.989  3523  3523 D AndroidRuntime: Shutting down VM
05-14 19:44:18.016  3523  3540 E art     : Thread attaching to non-existent runtime: Binder:3523_1
05-14 19:44:18.016  3523  3540 I AndroidRuntime: NOTE: attach of thread 'Binder:3523_1' failed
05-14 19:44:18.276   365   400 W WindowManager: Failed looking up window
05-14 19:44:18.276   365   400 W WindowManager: java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@823fa6f does not exist
05-14 19:44:18.276   365   400 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9429)
05-14 19:44:18.276   365   400 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9420)
05-14 19:44:18.276   365   400 W WindowManager:         at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2394)
05-14 19:44:18.276   365   400 W WindowManager:         at com.android.server.wm.Session.remove(Session.java:202)
05-14 19:44:18.276   365   400 W WindowManager:         at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3290)
05-14 19:44:18.276   365   400 W WindowManager:         at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5927)
05-14 19:44:18.276   365   400 W WindowManager:         at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3626)
05-14 19:44:18.276   365   400 W WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:102)
05-14 19:44:18.276   365   400 W WindowManager:         at android.os.Looper.loop(Looper.java:154)
05-14 19:44:18.276   365   400 W WindowManager:         at android.os.HandlerThread.run(HandlerThread.java:61)
05-14 19:44:18.276   365   400 W WindowManager:         at com.android.server.ServiceThread.run(ServiceThread.java:46)
05-14 19:44:18.490   883  1060 W OpenGLRenderer: Incorrectly called buildLayer on View: ln, destroying layer...
05-14 19:44:18.550   883  1060 E EGL_adreno: tid 1060: eglSurfaceAttrib(1313): error 0x3009 (EGL_BAD_MATCH)
05-14 19:44:18.551   883  1060 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x966a3b40, error=EGL_BAD_MATCH
05-14 19:44:20.388   365   376 W ActivityManager:   Force finishing activity com.ast.astest/com.unity3d.player.UnityPlayerActivity
05-14 19:44:20.389   365   376 I ActivityManager: Killing 3503:com.ast.astest/u0a57 (adj 900): crash
05-14 19:44:20.390   365   376 D ActivityManager: cleanUpApplicationRecord -- 3503
05-14 19:44:20.391   365   392 W libprocessgroup: failed to open /acct/uid_10057/pid_3503/cgroup.procs: No such file or directory
05-14 19:44:20.410   365   721 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@31bd899 attribute=android.view.inputmethod.EditorInfo@e30075e, token = android.os.BinderProxy@92e9512
05-14 19:44:20.418   365   390 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
05-14 19:44:20.530   365   400 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0

anyone has any idea what's wrong here?

**Comment by stewartmiles** [comment]
@srcsameer the problems writing to the temp folder suggest an issue with file permissions or perhaps an anti-virus program on your machine?

The AdMob error is described in the log, see https://goo.gl/fQ2neu
