### ISSUE TITLE
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'

### ISSUE THREAD

**Issue by bklooster** [googlesamples/unity-jar-resolver#213]
We just updated to the latest play resolver and noticed a problem. 

The resolver should not use the "compile" flag when modifying the mainTemplate.gradle file. This API is outdated and Android Studio throws warnings at you. Please modify to use the implementation() or api() methods. 

Also, ideally, it would not duplicate dependencies in the mainTemplate.gradle and instead use the latest version requirements.

**Comment by stewartmiles** [comment]
@bklooster yes we know compile is obsolete, however older versions of Unity ship with old versions of Gradle so we need to really map the dependency inclusion function (e.g compile vs. implementation) to the Gradle version used by Unity.

**Comment by bklooster** [comment]
Can you not use the #if UNITY_2018_3_OR_NEWER compilation flag or similar to get to the correct version of Unity that does have the upgraded Gradle commands?

**Comment by stewartmiles** [comment]
@bklooster we ship recompiled code for these modules so it would need to happen at runtime.  Also, are you sure that 2018.3 is the earliest version of Unity that ships with the version of Gradle that supports "implementation" ?  TBH Most of the work is either figuring out the Unity version to whitelist for "implementation" or finding and running Gradle in the Unity installation to get the version number to figure out what it supports.

**Comment by bklooster** [comment]
There were some 2017.4 versions that now support newer versions of gradle. However, something like a 2018 check would help ensure it. Another option would be to have a checkbox in the settings for Android. Anything we can do to reduce the errors/warnings during builds helps us out a lot. Thanks!

**Comment by stewartmiles** [comment]
Since this is a warning at the moment it's pretty far down the list of things we need to tackle.  If you want to send a pull request, the code that emits this is here https://github.com/googlesamples/unity-jar-resolver/blob/4bdc8d82b0ce13745bf17bf05d27ee2687a0fcad/source/PlayServicesResolver/src/PlayServicesResolver.cs#L1727

As I mentioned, I don't think whitelisting Unity versions is the way to go here that inevitably breaks when a Unity patch release changes the behavior in some way.  Ideally, we should check the Gradle version packaged with Unity and change the behavior based upon that.

**Comment by chkuang-g** [comment]
@bklooster Does that resolve your concern?

**Comment by Thaina** [comment]
Not sure if it related but I got this error build failed


> stderr[
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all files for configuration ':releaseCompileClasspath'.
> > Could not find :facebook-android-wrapper-7.14.1:.
>   Required by:
>       project :
> > Could not find :facebook-applinks:.
>   Required by:
>       project :
> > Could not find :facebook-common:.
>   Required by:
>       project :
> > Could not find :facebook-core:.
>   Required by:
>       project :
> > Could not find :facebook-login:.
>   Required by:
>       project :
> > Could not find :facebook-marketing:.
>   Required by:
>       project :
> > Could not find :facebook-messenger:.
>   Required by:
>       project :
> > Could not find :facebook-places:.
>   Required by:
>       project :
> > Could not find :facebook-share:.
>   Required by:
>       project :
> > Could not find :firebase-app-unity-5.6.0:.
>   Required by:
>       project :
> > Could not find :firebase-auth-unity-5.6.0:.
>   Required by:
>       project :
> > Could not find :firebase-database-unity-5.6.0:.
>   Required by:
>       project :
> > Could not find :firebase-dynamic-links-unity-5.6.0:.
>   Required by:
>       project :
> > Could not find :onesignal-unity:.
>   Required by:
>       project :

**Comment by stewartmiles** [comment]
I have a patch lined up.  Ended up grabbing the gradle version from the gradle-core-*.jar filename that's part of the distribution shipped with Unity.  @Thaina regarding the build error, any chance you're using Unity 2019?

**Comment by Thaina** [comment]
@stewartmiles I use unity 2018.3.14f but I have been installed unity 2019 in my machine today, maybe that would be related because I can build this exact same project yesterday

**Comment by stewartmiles** [comment]
@Thaina I was testing with Unity 2019 yesterday and discovered they've changed the Gradle project layout in such a way that it breaks the addition of any repositories in the gradle template which breaks inclusion from maven repos referenced by the Android Resolver  I have a patch in review at the moment and will have a new release with the fix published probably later today.

The workaround is to change...

```
project {
  repositories {
```

to

```
([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
```

**Comment by Thaina** [comment]
Thanks. I will hope for tomorrow. Today I have left my workplace already

**Comment by Thaina** [comment]
@stewartmiles Well, this version still doesn't change `compile` to `implementation` and the change at `project.repositories` seem like it not related to my build error

**Comment by stewartmiles** [comment]
@Thaina looks like you're right, where Gradle is installed in different Unity versions appears to be different which results in falling back to use `compile`.

Regarding your compile error, it still sounds like repositories are being ignored by the Gradle build.  The Facebook components - I assume - are all on maven so those should at least be found.  Have you tried running the Gradle build manually from the command line to get better log output?

**Comment by stewartmiles** [comment]
Oh, looks like I broke the code when I made a change during code review :/ It's a one line fix.
https://github.com/googlesamples/unity-jar-resolver/blob/90e73703829f6b0df84714c56033019fa7c19eb5/source/PlayServicesResolver/src/PlayServicesResolver.cs#L449
should be `if (gradleVersion != null) return gradleVersion;`

**Comment by Thaina** [comment]
@stewartmiles What did that code means to allow gradle version `""` difference from `null` ?

**Comment by stewartmiles** [comment]
Oh, it's clearly late in the day for me.

It's actually because the AndroidPlaybackEngine directory is empty in Unity < 2019 :(.  So I've had to change the method to implement a more compatible way of doing this.  I'll have an update uploaded tomorrow.

**Comment by Thaina** [comment]
@stewartmiles I just think that we should have some code like this as raw C# to import instead of dll. So we could change a little things when necessary instead of waiting for dll release

**Comment by Thaina** [comment]
@stewartmiles I have fix the problem. The cause is the auto generated gradle template that auto generated in resolver version 1.2.109. And version 109 come with firebase 6.0.0

I need to revert resolver to my project old version 1.2.102 and revert my template to just this

![image](https://user-images.githubusercontent.com/1042507/58321726-26ca1100-7e49-11e9-8860-18ee3a315057.png)

While I can't use firebase version 5.6.0 to build, it cause another error so I need to update to firebase 6.0.0, I need to check out only the resolver to not be updated

**Comment by stewartmiles** [comment]
@Thaina glancing at your diff screenshot the set of repos imported in both cases are the same. I don't see why this would cause an issue for you.  Are you building with Gradle inside Unity or exporting?  Which version of Unity are you seeing issues in?

Also, you can turn off the Gradle template patching under settings.

**Comment by Thaina** [comment]
@stewartmiles Build inside unity version 2018.3.14f but with gradle from android studio. I have install android studio and set android SDK path in unity to use the same SDK, which it install buildtools 28.0.3

Also I have try 2019 too and it was the exact same error log

One thing I suspect is the ordering. With the patching it move jcenter() down below maven. And also it remove flatDir (I don't know what flatdir is though)

But currently now is not a good time. I have already leave my office and the project is in my office's machine. I live in GMT+7 zone though

**Comment by Thaina** [comment]
ps2. It also could build if I remove all plugin that error. Which is onesignal and facebook (and also voxelbusters, just a utilities plugins). Which I suspect that the resolver patching that insert a lot of `maven` before `jcenter` might pull a wrong repo or got interrupted and don't resolve an aar that plugin try to get

**Comment by stewartmiles** [comment]
@Thaina the plugin should just add the repos rather than replace what is there.    If it's replacing a chunk of your template, that sounds like a bug.

**Comment by Thaina** [comment]
@stewartmiles It really replaced everything there when using `force resolve`

**Comment by Thaina** [comment]
@stewartmiles I have clean my project and try to use force resolve again. Now it did not replace but it still have other problem if the template was patched. I will investigate more and might open another issue soon
