### ISSUE TITLE
Dialog with files to delete can be too long to fit the screen

### ISSUE THREAD

**Issue by olehkuznetsov** [googlesamples/unity-jar-resolver#215]
If number of obsolete files is too big it is possible the dialog will not fit the screen and buttons Yes, No are not visible on the screen at all.

Possible solutions:
1. May be it can be clamped to 20 or so files and added '...' as a sign of more files. And full files list can be logged.
2. Replace dialog by custom window with scrollable list of files.

The code part showing the dialog:
```
EditorUtility.DisplayDialog(
    PLUGIN_NAME,
    "Would you like to delete the following obsolete files " +
    "in your project?\n\n" +
    String.Join(
        "\n", new List<string>(
           obsoleteFiles.unreferencedExcludingManifests).ToArray()),
    "Yes", cancel: "No");
```

**Comment by stewartmiles** [comment]
Almost sounds like the TextAreaDialog from the Android Resolver DLL should be moved into the VersionHandler component and used for this instead, that way we can have a scrolling list of components perhaps even a way to check / uncheck files?
