### ISSUE TITLE
InvokeMethod regression with named arguments

### ISSUE THREAD

**Issue by sp-jordi-vilalta** [googlesamples/unity-jar-resolver#218]
There has been a regression in the InvokeMethod when using named arguments.
In my project I'm using it to call `GooglePlayServices.PlayServicesResolver.ResolveSync(true)`, which used to work with this call until 1.2.109, but on 1.2.111 it can't find the method:
```
return (bool)Google.VersionHandler.InvokeStaticMethod(
    Google.VersionHandler.FindClass("Google.JarResolver", "GooglePlayServices.PlayServicesResolver"),
    "ResolveSync", args: null,
    namedArgs: new Dictionary<string, object> {
        {
            "forceResolution", true
        }
    }
);
```
If I use positional arguments it works fine on 1.2.111:
```
return (bool)Google.VersionHandler.InvokeStaticMethod(
    Google.VersionHandler.FindClass("Google.JarResolver", "GooglePlayServices.PlayServicesResolver"),
    "ResolveSync", args: new object[]{ true }
);
```

**Comment by stewartmiles** [comment]
@sp-jordi-vilalta are you sure you have the VersionHandler.dll for 1.2.111 ?

I'm pretty sure this was fixed by e71269b2b7391efa72fe9675f706376f11a1e123

It's also tested by https://github.com/googlesamples/unity-jar-resolver/blob/e71269b2b7391efa72fe9675f706376f11a1e123/source/VersionHandler/test/reflection/Assets/PlayServicesResolver/Editor/TestReflection.cs#L232

**Comment by sp-jordi-vilalta** [comment]
I've tried it again in an empty Unity project and I could reproduce it by using this: https://github.com/googlesamples/unity-jar-resolver/blob/e703601cec96ff60883b8999ca9aaa3ef2e459d9/play-services-resolver-1.2.111.0.unitypackage

**Comment by stewartmiles** [comment]
@sp-jordi-vilalta in #209 the issue was still present as folks didn't restart Unity.  Are you sure you have imported the latest VersionHandler.dll ?  You appear to be the only person with the issue.

**Comment by sp-jordi-vilalta** [comment]
I've tried it again and I could reproduce it again in Unity 2018.2.21f1. Let me detail the steps:

1. Create an empty folder and download the 1.2.111 unitypackage:
`curl https://raw.githubusercontent.com/googlesamples/unity-jar-resolver/master/play-services-resolver-1.2.111.0.unitypackage -o play-services-resolver-1.2.111.0.unitypackage`
2. Create an empty Unity project importing the package:
`/Applications/Unity/Hub/Editor/2018.2.21f1/Unity.app/Contents/MacOS/Unity -quit -batchmode -createProject testProject -importPackage ../play-services-resolver-1.2.111.0.unitypackage`
3. Create a test script:
    ```
    mkdir testProject/Assets/Editor
    cat > testProject/Assets/Editor/ReflectionTest.cs << EOF
    using System.Collections.Generic;
    using UnityEngine;
    
    class ReflectionTest
    {
        public static void TestReflection()
        {
            bool result = (bool)Google.VersionHandler.InvokeStaticMethod(
                Google.VersionHandler.FindClass("Google.JarResolver", "GooglePlayServices.PlayServicesResolver"),
                "ResolveSync", args: null,
                namedArgs: new Dictionary<string, object> {
                    {
                        "forceResolution", true
                    }
                }
            );
            Debug.Log("Result = " + result);
        }
    }
    EOF
    ```
4. Open Unity interactively to make sure the resolver enables the assemblies and al the scripts are compiled:
`/Applications/Unity/Hub/Editor/2018.2.21f1/Unity.app/Contents/MacOS/Unity -projectPath testProject`
5. Close the project and launch the test method:
`/Applications/Unity/Hub/Editor/2018.2.21f1/Unity.app/Contents/MacOS/Unity -quit -batchmode -projectPath testProject -executeMethod ReflectionTest.TestReflection`

The Unity editor log contains this:
```
Exception: Method PlayServicesResolver.ResolveSync not found
  at Google.VersionHandler.InvokeMethod (System.Type type, System.Object objectInstance, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2 namedArgs) [0x00189] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandler/src/VersionHandler.cs:544 
  at Google.VersionHandler.InvokeStaticMethod (System.Type type, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2 namedArgs) [0x00000] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandler/src/VersionHandler.cs:481 
  at ReflectionTest.TestReflection () [0x0002e] in /Users/jvilalta/Downloads/deps/testProject/Assets/Editor/ReflectionTest.cs:8 
 
(Filename: /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandler/src/VersionHandler.cs Line: 544)

executeMethod method ReflectionTest.TestReflection threw exception.
 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Utilities/Argv.cpp Line: 301)


Aborting batchmode due to failure:
executeMethod method ReflectionTest.TestReflection threw exception.
```

Am I doing something wrong?

**Comment by sp-jordi-vilalta** [comment]
I just tried it again with the recent 1.2.112 release with the same result

**Comment by stewartmiles** [comment]
The arguments to the method in your code are wrong.  ResolveSync only takes a single boolean positional (i.e not-named) argument:

https://github.com/googlesamples/unity-jar-resolver/blob/90e73703829f6b0df84714c56033019fa7c19eb5/source/PlayServicesResolver/src/PlayServicesResolver.cs#L1383
