### ISSUE TITLE
Build target directory for AndroidPlayer does not exist

### ISSUE THREAD

**Issue by CrankyPeacock** [googlesamples/unity-jar-resolver#220]
Hello

I'm getting an error after importing the 1.2.111.0 of the resolver.

**On Unity 2019.1.2 and 2019.1.3:**

- Start new 2D project

- Immediately import play-services-resolver-1.2.111.0.unitypackage

- Observe that every second, the following error is reported: 

Build target directory for AndroidPlayer does not exist!
System.Reflection.MethodBase:Invoke(Object, Object[])
Google.VersionHandler:InvokeMethod(Type, Object, String, Object[], Dictionary`2) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandler/src/VersionHandler.cs:546)
Google.VersionHandler:InvokeStaticMethod(Type, String, Object[], Dictionary`2) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandler/src/VersionHandler.cs:481)
GooglePlayServices.PlayServicesResolver:get_AndroidPlaybackEngineDirectory()
GooglePlayServices.PlayServicesResolver:get_AndroidSdkRoot()
GooglePlayServices.PlayServicesResolver:.cctor()
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])

Note this also occurs when I download the latest version of the Firebase Unity SDK (which contains the resolver).

This happens with both the build target set to OSX and IOS.

This also happens regardless of if I select .NET 3.5 or .NET 4.x as the Scripting Runtime Version in Unity's Player settings.

Any help greatly appreciated.

**Comment by stewartmiles** [comment]
@CrankyPeacock it sounds like you've managed to select the Android build target and not have the Android player installed.

**Comment by stewartmiles** [comment]
I'll add a workaround but it sounds like your Unity installation is broken.

**Comment by CrankyPeacock** [comment]
Hi @stewartmiles thanks for your reply. I haven't selected Android as the target platform, as I only develop for iOS. Upon creating my empty project I changed platform in 'Build Settings' to iOS. I also changed the platform to OSX and back to iOS to see if something was amiss. I also tried this on a fresh install of 2019.1.3.  Let me remove both my Unity installations and re-install them, and I'll see if that fixes things. Have you ever encountered this error before? Thanks again!

**Comment by stewartmiles** [comment]
@CrankyPeacock looks like I missed your follow up.  I didn't realize you didn't have the Android target platform installed.

**Comment by stewartmiles** [comment]
Ok now I'm confused, this code can only be executed if the target platform is Android
https://github.com/googlesamples/unity-jar-resolver/blob/7feb88da7f7df5deb4ca393422662ad74143d32b/source/PlayServicesResolver/src/PlayServicesResolver.cs#L724

Is it possible you're running into a Unity bug here where the currently selected platform isn't being returned correctly?

**Comment by ErikDutch5** [comment]
I just pulled our android project on our new Mac and set everything up for an iOS build, found out that Firebase needed to be updated, so I downloaded the newest Firebase SDK for Unity (specifically the Firebase.Authentication unitypackage) and I get the same result as @CrankyPeacock, the same error every second.
The Firebase SDK does import everything into the project, though, so there are both a Google.JarResolver and a Google.IOSResolver in the project. We will need both, however, one for our Android builds and one for our iOS builds.

**Comment by stewartmiles** [comment]
Ok I've reproduced this, it's definitely specific to 2019.x as the new method for retrieving the Android Player directory, `BuildPipeline.GetPlaybackEngineDirectory`, now throws an exception when it's missing for the requested build target.
