### ISSUE TITLE
Replace the absolute path with a relative path in Android maintemplate resolve

### ISSUE THREAD

**Issue by vzlomvl** [googlesamples/unity-jar-resolver#221]
Hello everyone. I am absolutely happy with a new Gradle config path improvement.
But we still have one small inconvenience. Current resolve logic inserts the absolute path to maintemplate file(in the repositories maven url block). This require to rebuild maintemplate if developers have onether project folder of another OS(Windows/MacOS). What you think about replacing the absolute path with a relative path(with **DIR_UNITYPROJECT** unity constant or with  file('../../Assets').absolutePath)? Thanks.

**Comment by vzlomvl** [comment]
Unity using Temp\gradleOut folder for the building of Android.
So I am using this solution:
```
String projectPath = file('../../Assets').absolutePath

// Android Resolver Repos Start
allprojects {
    repositories {
        maven {
            url "https://maven.google.com"
        }
        maven {
            url "file:///" + projectPath + "/GooglePlayGames/Editor/m2repository" // Assets/GooglePlayGames/Editor/GooglePlayGamesPluginDependencies.xml:11
        }
        mavenLocal()
        jcenter()
        mavenCentral()
    }
}
```
Also Unity have DIR_UNITYPROJECT but looks like because of bug(https://issuetracker.unity3d.com/issues/android-windows-template-variable-dir-unityproject-on-windows-does-not-escape-slash-characters)  it will wotk only for Unity 2019.1+ users.

**Comment by stewartmiles** [comment]
@vzlomvl that is a great about injecting a file() function call in there to expand the absolute path instead .. very nice indeed.

**Comment by stewartmiles** [comment]
This is released in https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.111 .  I'm a little worried about how this could potentially break in some developer's workflows, I guess we'll see.
