### ISSUE TITLE
Bad patch of mainTemplate.gradle

### ISSUE THREAD

**Issue by huran438** [googlesamples/unity-jar-resolver#223]
Patching mainTemplate gradle generates wrong path string and then resolver not working.

Path contains **%20** characters,but expected **space** 

![rider64_Qw8ssjdqfb](https://user-images.githubusercontent.com/1672637/58420587-5588f700-8096-11e9-8f1b-f453b43c22b2.png)

**Comment by stewartmiles** [comment]
This is expected, the path needs to be a URI.

https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_in_a_URI

**Comment by huran438** [comment]
After enabling this setting 
![image](https://user-images.githubusercontent.com/1672637/58565432-62911c00-8237-11e9-9a78-dfd7689854e7.png)

 resolving stops working. Here's my log:

![image](https://user-images.githubusercontent.com/1672637/58565321-2cec3300-8237-11e9-8efb-7bfe2a584fa9.png)

**Comment by stewartmiles** [comment]
@huran438 resolution with the mainTemplate.gradle patcher simply adds references to the dependencies to the mainTemplate.gradle file.  Does your build fail?  If so, where are the logs?

**Comment by huran438** [comment]
Ok. Thanks. Nothing fails. Debug prints: Resolution Succeeded, but its not succeeded.

**Comment by stewartmiles** [comment]
@huran438 how do you know it didn't succeed?  What happens when you build?

**Comment by stewartmiles** [comment]
@huran438 since I haven't heard from you, I'll assume you've figure out your build issue.
