### ISSUE TITLE
Resolver ignores specific version

### ISSUE THREAD

**Issue by kobyle69** [googlesamples/unity-jar-resolver#225]
Hi,

Having this dependency:
` <androidPackage spec="com.google.android.gms:play-services-ads:17.2.0">
    </androidPackage> `

`Some conflicting dependencies were found.
The following dependency versions were modified:
com.android.support:appcompat-v7:25.3.1 --> com.android.support:appcompat-v7:26.1.0@aar
com.android.support:cardview-v7:25.3.1 --> com.android.support:cardview-v7:26.1.0@aar
com.android.support:customtabs:25.3.1 --> com.android.support:customtabs:26.1.0@aar
com.android.support:support-v4:25.3.1 --> com.android.support:support-v4:26.1.0@aar
com.google.android.gms:play-services-ads:17.2.0 --> com.google.android.gms:play-services-ads:17.2.+
com.google.android.gms:play-services-analytics:16.0.3 --> com.google.android.gms:play-services-analytics:16.0.+
com.google.firebase:firebase-analytics:16.5.0 --> com.google.firebase:firebase-analytics:16.5.+`

I couldn't find any reason for it to resolve the conflict to: "com.google.android.gms:play-services-ads:17.2.+"

Why is it happening and how can I force it to 17.2.0, now I get after the resolution a version of 17.2.1

Koby

**Comment by stewartmiles** [comment]
https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/VersionConstraint.html

In particular, this is a good description:
https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm


1.0 | It generally means 1.0 or a later version, if 1.0 is not available.Various Maven plug-ins may interpret this differently, so it is safer to use one of the other, more specific options.
-- | --
[1.0] | Exactly 1.0
-- | --

So you want `[17.2.0]`.

**Comment by kobyle69** [comment]
@stewartmiles thanks a lot, it worked.
