### ISSUE TITLE
Incorrect aar versions are resolved

### ISSUE THREAD

**Issue by stopiccot** [googlesamples/unity-jar-resolver#228]
I'm using PlayServicesResolver 1.2.109. My dependecies.xml file looks like this
```
<dependencies>
    <androidPackages>
        <androidPackage spec="com.google.android.gms:play-services-ads:17.1.2"/>
        <androidPackage spec="com.facebook.android:audience-network-sdk:5.3.0"/>
    </androidPackages>
</dependencies>
```

Resolution completes successfully.
But I get play-services-ads `17.2.1` instead of `17.1.2`
and audience-network-sdk `5.4.0-beta` instead of `5.3.0`

Any way to fix such a weird behaviour?

**Comment by stewartmiles** [comment]
@stopiccot have you tried enabling verbose logging in the settings menu?  My guess is that the two packages you've referenced require the same package at different versions which results in a fallback to the latest version of each package instead.  If you want to force to a particular version (things may not work) you could try doing `some.group:some-package:[a.b.c]` where `a.b.c` is the version.

**Comment by stopiccot** [comment]
I'm not very familiar with android dependencies system but according to maven website:
- `audience-network-sdk` requires `play-services-basement` to be [11.0.4 or newer](https://mvnrepository.com/artifact/com.facebook.android/audience-network-sdk/5.3.0)
- `play-services-ads` requires `play-services-basement` to be [16.0.1 or newer](https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads/17.1.2)
So I do not actually understand why we can't just resolve 16.0.1 version without changing versions of root packages.

**Comment by stewartmiles** [comment]
As I mentioned, if the packages share a common dependency that is required at _different_ versions (e.g a:1.2.3 requires b:1.0.0..1.9.9 and c:2.0.0 requires b:2.0.0..2.1.1) things aren't going to work, in which case the resolver falls back to grabbing the latest revision of each package.

**Comment by stopiccot** [comment]
Ok, how do I check the `play-services-basement` version range for `audience-network-sdk`?
Is it a `11.0.4 only` or `11.0.4 or higher`?

**Comment by stewartmiles** [comment]
You can either download each POM file for each package or browse them in a maven repo browser like https://mvnrepository.com/

**Comment by stopiccot** [comment]
So in `audience-networks-sdk` [pom](http://central.maven.org/maven2/com/facebook/android/audience-network-sdk/5.3.0/audience-network-sdk-5.3.0.pom) there is a section
```
<dependencies>
	<dependency>
		<groupId>com.google.android.gms</groupId>
		<artifactId>play-services-basement</artifactId>
		<version>11.0.4</version>
		<scope>compile</scope>
	</dependency>
</dependencies>
```
It means `11.0.4 only` or `11.0.4 or higher`?

**Comment by stewartmiles** [comment]
https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification
This is interpreted by Gradle as the min version.

**Comment by stopiccot** [comment]
So why then if one package declares `play-services-basement` min version as 11.0.4 and the other one declares min version as 16.0.1 we get the resolution conflict? Why we can't just resolve it to 16.0.1?

**Comment by stopiccot** [comment]
bump

**Comment by stewartmiles** [comment]
@stopiccot the only options you have right now are:
- Force the dependency in your *Dependencies.xml using `com.google.android.gms:play-services-basement:[11.0.4]`
- Send us a pull request to improve the resolution in https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/scripts/download_artifacts.gradle .
