### ISSUE TITLE
Using the built in unity test play

### ISSUE THREAD

**Issue by merrickt** [googlesamples/unity-jar-resolver#229]
Due to circumstances where I lack a physical device that is compatible to ARCore, I tried using Unity's built in test run to try out helloAR. However, I only get a white screen.
![image](https://user-images.githubusercontent.com/39343323/58973443-00cc3700-878e-11e9-849e-70362891de67.png)
My laptop does have a webcam, and it does work. I followed the instructions and have the proper ARCore and Android SDK installed. I'm not sure if there is something wrong with my computer, something that I forgot to add, or if helloAR was not built considering this. Any thoughts?

**Comment by stewartmiles** [comment]
@merrickt this isn't a general support channel for all Google Unity plugins.  I recommend asking the ARCore folks about this.
