### ISSUE TITLE
After importing latest package, ArgumentException: Requested value 'X86' was not found. KEEPS COMING AGAIN

### ISSUE THREAD

**Issue by elblogbruno** [googlesamples/unity-jar-resolver#230]
After importing latest package version 1.2.115 , ArgumentException: Requested value 'X86' was not found. KEEPS COMING AGAIN

```
ArgumentException: Requested value 'X86' was not found.
System.Enum+EnumResult.SetFailure (System.Enum+ParseFailureKind failure, System.String failureMessageID, System.Object failureMessageFormatArgument) (at <23c160f925be47d7a4fd083a3a62c920>:0)
System.Enum.TryParseEnum (System.Type enumType, System.String value, System.Boolean ignoreCase, System.Enum+EnumResult& parseResult) (at <23c160f925be47d7a4fd083a3a62c920>:0)
System.Enum.Parse (System.Type enumType, System.String value, System.Boolean ignoreCase) (at <23c160f925be47d7a4fd083a3a62c920>:0)
System.Enum.Parse (System.Type enumType, System.String value) (at <23c160f925be47d7a4fd083a3a62c920>:0)
GooglePlayServices.AndroidAbis.EnumValueStringToULong (System.Type enumType, System.String enumValueString) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/AndroidAbis.cs:220)
GooglePlayServices.AndroidAbis.get_Current () (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/AndroidAbis.cs:278)
GooglePlayServices.PlayServicesResolver.<PollAndroidAbis>m__1B () (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1252)
GooglePlayServices.PlayServicesResolver+PropertyPoller`1[T].Poll (System.Func`1[TResult] getCurrentValue, GooglePlayServices.PlayServicesResolver+PropertyPoller`1+Changed[T] changed) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:278)
GooglePlayServices.PlayServicesResolver.PollAndroidAbis () (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1252)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:303)
```

**Comment by stewartmiles** [comment]
This is a dupe of #224 are you sure you're using 1.2.115?  Did you restart Unity to be sure?

**Comment by elblogbruno** [comment]
Yes I downloaded the package from: https://github.com/googlesamples/unity-jar-resolver/raw/v1.2.115/play-services-resolver-1.2.115.0.unitypackage
and imported it.
Then, I reimported the unity project.
![image](https://user-images.githubusercontent.com/10481058/59053952-e29c2f00-8892-11e9-8078-2f26cba9378d.png)

![image](https://user-images.githubusercontent.com/10481058/59053984-f9db1c80-8892-11e9-85a5-0ab969d3269e.png)

**Comment by stewartmiles** [comment]
What version of Unity are you using?

What version is displayed when you goto "Assets > Play Services Resolver > Android Resolver > Settings"?

**Comment by elblogbruno** [comment]
![image](https://user-images.githubusercontent.com/10481058/59055855-209b5200-8897-11e9-8bcf-0255ad4177ea.png)

I'm using Unity 2019.3.0a3

**Comment by stewartmiles** [comment]
<img width="430" alt="Screen Shot 2019-06-06 at 11 21 56 AM" src="https://user-images.githubusercontent.com/6042948/59056547-50256c80-884d-11e9-9b54-bb4e1277dde2.png">
The settings menu should have a version number at the top, `1.2.115`.  I recommend deleting the Play Services Resolver entirely from your project and re-importing.

**Comment by elblogbruno** [comment]
Doing this fixed my problem! Thanks @stewartmiles!
