### ISSUE TITLE
PlayResolver drains battery even on background.

### ISSUE THREAD

**Issue by dps999** [googlesamples/unity-jar-resolver#231]
PlayResolver drains battery even on background.
Please how can I stop it?
![image](https://user-images.githubusercontent.com/1697478/59083684-f9796a80-8900-11e9-90a0-da445353184c.png)

**Comment by stewartmiles** [comment]
@dps999 you should disable auto-resolution if this is an issue for you.

**Comment by dps999** [comment]
Why you use it in loop? I. E. You can use OnPostImporting event or something else.

**Comment by stewartmiles** [comment]
@dps999 the numbers you're seeing here look like a result of using an old build of the plugin.  See https://github.com/googlesamples/unity-jar-resolver/issues/181

I just took a look with the current build and without resolution enabled it's sitting about ~1% with most of the time in DateTime checking to see whether a task should be executed each frame.

**Comment by stewartmiles** [comment]
@dps999 haven't heard from you so I'll assume the latest build solves your issue.
