### ISSUE TITLE
Unable to find command line tool generate_xml_from_google_services_json.exe

### ISSUE THREAD

**Issue by Thaina** [googlesamples/unity-jar-resolver#232]
Windows 10 Pro 64 bit 1809
Unity 2018.4.1f1
Firebase 6.1.0
unity-jar-resolver 1.2.115

> Unable to find command line tool Assets/Firebase/Editor/generate_xml_from_google_services_json.exe required for Firebase Android resource generation.
> Assets/Firebase/Editor/generate_xml_from_google_services_json.exe is required to generate the Firebase Android resource file google-services.xml from Assets/GoogleService-Info.plist. Without Firebase Android resources, your app will fail to initialize.
> Assets/Firebase/Editor/generate_xml_from_google_services_json.exe was distributed with each Firebase Unity SDK plugin, was it deleted?
> 

> System.ComponentModel.Win32Exception (0x80004005): ApplicationName='Assets/Firebase/Editor/generate_xml_from_google_services_json.exe', CommandLine='-i "Assets/GoogleService-Info.plist" -l --plist', CurrentDirectory='D:\Users\Admin\Documents\MyProject', Native error= The system cannot find the file specified.

>Native error= The system cannot find the file specified.

The file is exist and the path is correct

![image](https://user-images.githubusercontent.com/1042507/59095014-aa9ff500-8941-11e9-9ad7-2c9ad03ecd75.png)

I try to run the same command in cmd. It seem like it require backslash?

![image](https://user-images.githubusercontent.com/1042507/59095250-33b72c00-8942-11e9-9e7f-ff5c5fcb3cf6.png)

**Comment by stewartmiles** [comment]
@Thaina since this is a Firebase editor plugin issue, feel free to open this up on github.com/firebase/quickstart-unity .
