### ISSUE TITLE
Getting wrong version dependency without patching gradle file

### ISSUE THREAD

**Issue by ilterbilguven** [googlesamples/unity-jar-resolver#234]
I wrote a dependency xml for my project but these lines below causes problems:

```
<androidPackage spec="com.android.support:multidex:1+">
       <repositories>
        <repository>https://maven.google.com</repository>
      </repositories>
</androidPackage>
```

if i use patching gradle, it has no errors but if i don't it gives this error:

```
Resolution failed
Failed to fetch the following dependencies:
com.android.support:multidex:27.1.1
```

27.1.1? latest version of multidex library is 1.0.3. And no other xml or script is mentioning multidex library. I think jar resolver assumes all support libraries' version are similar to api level versions.

**Comment by stewartmiles** [comment]
Historically all Android support libraries were released in lock step so it was clear which API level they supported, see https://developer.android.com/topic/libraries/support-library#release-versions .  The Android Resolver's [artifact downloader](https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/scripts/download_artifacts.gradle) enforces this requirement by locking all references to libraries under `com.android.support` to the same version, it appears that `com.android.support:multidex` breaks the versioning rules that were in place for all other libraries in the suite.

We'll have to exclude `com.android.support:multidex` from the version locking mechanism that was put in place for Google Play Services and the legacy Android Support libraries.
