### ISSUE TITLE
Resolve deletes all libraries

### ISSUE THREAD

**Issue by Nyankoo** [googlesamples/unity-jar-resolver#235]
When I'm resolving my Android dependencies, all libraries in my project are deleted and nothing new is downloaded.
I don't really know why this is happening all of a sudden.

I'm using Unity 2018.3.8f1 and the latest release of the resolver (v1.2.117).

**Comment by stewartmiles** [comment]
See https://github.com/googlesamples/unity-jar-resolver/issues/233#issuecomment-501460820

**Comment by Nyankoo** [comment]
@stewartmiles Disabling"Patch AndroidManifest.xml" is still removing all libraries. When doing a normal "Resolve", nothing happens and the Force Resolve" deletes all libraries.

**Comment by stewartmiles** [comment]
![Uploading Screen Shot 2019-06-15 at 5.10.49 PM.png…]()

**Comment by stewartmiles** [comment]
<img width="423" alt="Screen Shot 2019-06-15 at 5 10 49 PM" src="https://user-images.githubusercontent.com/6042948/59557524-bc604880-8f90-11e9-9b1f-7e87fef7a56c.png">

**Comment by Nyankoo** [comment]
Ah, my bad! That did the trick!
