### ISSUE TITLE
Dependencies.xml files in packages are not found

### ISSUE THREAD

**Issue by sp-jordi-vilalta** [googlesamples/unity-jar-resolver#236]
I'm creating a [custom Unity package](https://docs.unity3d.com/Manual/CustomPackages.html) that has native dependencies, and I would like to use this project to resolve them. I've added a *Dependencies.xml file in the package, but it seems to be ignored.
I've noticed the [AssetDatabase.FindAssets](https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/src/XmlDependencies.cs#L49) call just returns the assets from /Assets by default.
Adding the "Packages" path to the paths to search, properly finds all the assets from the included packages too:
`AssetDatabase.FindAssets("t:TextAsset", new []{"Assets", "Packages"})`
In addition, FindAssets can be given parts of the name to search, which greatly reduces the number of assets to iterate in big projects:
`AssetDatabase.FindAssets("Dependencies t:TextAsset", new []{"Assets", "Packages"})`

**Comment by stewartmiles** [comment]
@sp-jordi-vilalta sounds like a great patch, wanna send us a pull request?  Any chance this also works as expected in older versions of Unity e.g 4.7.x+, 5.x+ etc. ?

**Comment by sp-jordi-vilalta** [comment]
Hi @stewartmiles, I thought about doing the PR, but I've noticed I should sign the CLA, etc. I think the change is trivial enough that it will be faster for you to do the change yourself 😉

About backwards compatibility:
- The oldest documentation I could find is from Unity 5.0, and it already supports [this method](https://docs.unity3d.com/500/Documentation/ScriptReference/AssetDatabase.FindAssets.html), so I think it should work there. I couldn't find documentation for 4.7.x, but I see 4.7.0 was released in December 2015 and there was [people already using this method in March 2015](https://forum.unity.com/threads/trouble-with-assetdatabase-findassets.312240/), but I don't know if this specific overload existed... It should be tested 😅
- In older Unity versions, the "Packages" folder may not exist but I've tried passing non-existing folders in 2018.2 and it just shows a warning in the console, so I think it should be safe.

**Comment by sp-jordi-vilalta** [comment]
I just found a [reference to that specific overload from June 2015](https://answers.unity.com/questions/996188/modify-prefabs-in-editor-script.html), so I think everything's fine :)

**Comment by sp-jordi-vilalta** [comment]
I've downloaded Unity 4.7.0 and tested this call:
`AssetDatabase.FindAssets("Dependencies t:TextAsset", new []{"Assets", "Packages"})`

It works fine and, as expected, the only issue (non-critical in my opinion) is this warning in the console:
```
AssetDatabase.FindAssets: Folder not found: 'Packages'
UnityEditor.AssetDatabase:FindAssets(String, String[])
```

**Comment by stewartmiles** [comment]
@sp-jordi-vilalta yep I have the patched staged on an internal git repo, will push an update hopefully later today.

BTW: If you're planning on redistributing this plugin via the package manager how is this going to work when multiple plugins include this package?

**Comment by sp-jordi-vilalta** [comment]
Hi @stewartmiles, thanks for pushing it to the last update! 😃
At this moment we're planning to use these packages only for optional features for our projects. All of our projects already include the Google Play Services Resolver in the common code, so the current status is fine for our purposes. In the future it would be cool to be able to reference the resolver itself as a package dependency, but we can live as it is for now.
Thanks for your work on this project!

**Comment by stewartmiles** [comment]
@sp-jordi-vilalta if you're playing around with packaging using the Unity Package Manager, a patch to the top level `build.gradle` script to support this would be appreciated ;)
