### ISSUE TITLE
Gradle Out error when using Jar Resolver

### ISSUE THREAD

**Issue by waqasbhattii** [googlesamples/unity-jar-resolver#237]
Hi @stewartmiles ,

I am importing these plugins and trying to make apk in Unity 2017.4.17f1 but i am getting error that "task transformdexarchivewithexternallibsdexmergerfordebug failed unity error". What i am doing is this:

1) Import [Google Mobile Ads Plugin](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0) without Play Services Resolver.

2) Import [Chartboost SDK](http://www.chartboo.st/sdk/unity) without Play Services Resolver.

3) Import [unity-jar-resolver](https://github.com/googlesamples/unity-jar-resolver) latest version.

4) I try to make apk but the gradle build fails.

Please help me how to fix this issue. I have also attached the screenshot of the error.

<img width="424" alt="Screen Shot 2019-06-19 at 12 49 28 AM" src="https://user-images.githubusercontent.com/43206618/59714919-28aaa880-922c-11e9-93d4-7f8753a0a0f3.png">

Thanks,

Waqas

**Comment by stewartmiles** [comment]
@waqasbhattii this isn't a general support channel.  I recommend you contact the authors of Google Mobile Ads and Chartboost definitely with more details (i.e logs) of what you're doing and how exactly the build is failing.  Posting a screenshot with a load of numbered .jar files isn't very useful.
