### ISSUE TITLE
Google Play Services AndroidX breaks builds

### ISSUE THREAD

**Issue by takaaptech** [googlesamples/unity-jar-resolver#241]
Hi!
I am using unity 2018.2.19f. Resolver version 1.2.104
The resolve and build works before but today when the resolve run it add some androidx file so build error because of duplicate.
If I delete all androidx file and build again, it works but maybe some function not work as usual?
Could you please explain why we have androidx after resolve and how to find what plugin need that files? And how to avoid that?
![androidx](https://user-images.githubusercontent.com/6276251/59894697-c5776c80-940b-11e9-99ef-b071ffa6eae0.PNG)

Thank so much!

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/app/INotificationSideChannel$Stub.class
```

**Comment by glodos** [comment]
I have the same problem using the latest version. There is no AndroidX dependency in .xml files, but the resolver started to pull these libraries after the update without any reason causing the build to fail.

**Comment by huran438** [comment]
We have the same problem... Why? How to avoid this?

**Comment by bilck** [comment]
We are also having the same issue...

**Comment by drallcom3** [comment]
I also have this issue. AndroidX files get downloaded by any version of the Resolver and break my game. There are no dependencies and no Gradle file.

Currently I can't use the resolver and have to copy the plugins from last week.

**Comment by stewartmiles** [comment]
Google Play Services libraries changed their dependencies in the most recent release from the legacy Android support libraries to AndroidX (see release notes [here](https://developers.google.com/android/guides/releases#june_17_2019)).  If the resolver is pulling the latest revision of Google Play Services libraries (`com.google.android.gms.*`packages) this will grab AndroidX libraries which are likely conflicting with other components in your project.

Right now there are two options:
- Pin all references to `com.google.android.gms.*` packages to the release before the migration to AndroidX.  See https://developers.google.com/android/guides/releases#may_31_2019 .  If version numbers are specified with `[]` e.g `com.google.firebase:firebase-database:[18.0.0]` will pin the Firebase Realtime Database library to `18.0.0`.
- Upgrade the resolver to `1.2.119`, enable the AndroidX build option.  The current integration will not process libraries with the Jetifier unless you modify your project to have the Android Resolver manage them.  See the release notes [here](https://github.com/googlesamples/unity-jar-resolver/blob/master/CHANGELOG.md#new-features).

**Comment by drallcom3** [comment]
There's no "AndroidX build option" in 119. Do you mean "Use Jetifier"?
It would surely be nice to have a checkbox to prevent pulling AndroidX files.

**Comment by stewartmiles** [comment]
@drallcom3 yes I mean "Use Jetifier".  The Android Resolver pulls libraries and their dependencies, there is no special case for things like AndroidX, if libraries require them it pulls them.

**Comment by huran438** [comment]
I have this error on startup of the app with "Use Jetifier" enabled:

Plugins used: Firebase 6.1.1 - Analytics, Crashlytics, Messaging, Appodeal SDK, Devtodev, AppsFlyer

`06-24 23:32:36.680 8108-30302/? E/HeadsetStateMachine: returning mCurrentState as Connected
06-24 23:32:37.153 577-640/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
06-24 23:32:37.155 3130-7830/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
06-24 23:32:37.175 3130-7830/? E/ActivityTrigger: activityStartTrigger: not whiteListedstudio.secretplace.ttf/com.google.firebase.MessagingUnityPlayerActivity/354
06-24 23:32:37.175 3130-7830/? E/ActivityTrigger: activityResumeTrigger: not whiteListedstudio.secretplace.ttf/com.google.firebase.MessagingUnityPlayerActivity/354
06-24 23:32:37.186 3130-7830/? E/ActivityTrigger: activityResumeTrigger: not whiteListedstudio.secretplace.ttf/com.google.firebase.MessagingUnityPlayerActivity/354
06-24 23:32:37.228 11340-11340/? E/secretplace.tt: Not starting debugger since process cannot load the jdwp agent.
06-24 23:32:37.845 8108-30302/? E/HeadsetStateMachine: returning mCurrentState as Connected
06-24 23:32:38.586 11340-11340/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: studio.secretplace.ttf, PID: 11340
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
        at com.facebook.internal.BoltsMeasurementEventListener.open(BoltsMeasurementEventListener.java:54)
        at com.facebook.internal.BoltsMeasurementEventListener.getInstance(BoltsMeasurementEventListener.java:70)
        at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:313)
        at com.facebook.marketing.internal.MarketingInitProvider.onCreate(MarketingInitProvider.java:42)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6484)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5982)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5888)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/studio.secretplace.ttf-xgEhrP3eT7rsjHoGA1FaLg==/base.apk", zip file "/data/app/studio.secretplace.ttf-xgEhrP3eT7rsjHoGA1FaLg==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/studio.secretplace.ttf-xgEhrP3eT7rsjHoGA1FaLg==/lib/arm64, /data/app/studio.secretplace.ttf-xgEhrP3eT7rsjHoGA1FaLg==/base.apk!/lib/arm64-v8a, /data/app/studio.secretplace.ttf-xgEhrP3eT7rsjHoGA1FaLg==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.internal.BoltsMeasurementEventListener.open(BoltsMeasurementEventListener.java:54) 
        at com.facebook.internal.BoltsMeasurementEventListener.getInstance(BoltsMeasurementEventListener.java:70) 
        at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:313) 
        at com.facebook.marketing.internal.MarketingInitProvider.onCreate(MarketingInitProvider.java:42) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6484) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5982) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5888) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6762) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/studio.secretplace.ttf-xgEhrP3eT7rsjHoGA1FaLg==/split_config.arm64_v8a.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:718)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:801)
        at android.app.LoadedApk.getResources(LoadedApk.java:1023)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5780)
        		... 8 more
06-24 23:32:41.807 8108-30302/? E/HeadsetStateMachine: returning mCurrentState as Connected
06-24 23:32:42.588 11340-11340/? E/CrashlyticsCore: Failed to execute task.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
        at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:321)
        at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:301)
        at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:42)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
06-24 23:32:42.708 11413-11413/? E/ttxapps.wifiad: Not starting debugger since process cannot load the jdwp agent.
06-24 23:32:42.755 23952-24283/? E/droid.launcher: No package ID ff found for ID 0xffffffff.
06-24 23:32:42.755 577-640/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
06-24 23:32:42.757 23952-24283/? E/IconLoader: Could not find icon drawable from resource
    android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
        at android.content.res.Resources.getDrawable(Resources.java:827)
        at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(IconLoader.java:118)
        at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(IconLoader.java:94)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(RecentsTaskLoader.java:325)
        at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(RecentsTaskLoadPlan.java:188)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(RecentsTaskLoader.java:173)
        at com.android.quickstep.RecentsModel.onTaskStackChangedBackground(RecentsModel.java:214)
        at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(TaskStackChangeListeners.java:80)
        at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
        at android.os.Binder.execTransact(Binder.java:731)
06-24 23:32:43.127 3130-3307/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.android.vending/com.google.android.finsky.activities.MainActivity/81531400
06-24 23:32:43.131 577-640/? E/ANDR-PERF-OPTSHANDLER: Perflock resource /sys/class/devfreq/soc:qcom,llccbw/min_freq not supported
06-24 23:32:43.132 577-640/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [12, 0]
06-24 23:32:43.132 577-640/? E/ANDR-PERF-OPTSHANDLER: Failed to read /sys/class/kgsl/kgsl-3d0/force_no_nap
06-24 23:32:43.132 577-640/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [10, 7]
06-24 23:32:43.901 577-640/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
06-24 23:33:08.389 11340-11373/? E/FirebaseInstanceId: Token retrieval failed without exception message. Will retry token retrieval
06-24 23:33:32.925 2485-2626/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
`

![image](https://user-images.githubusercontent.com/1672637/60050218-c690ee00-96d8-11e9-81cc-864e5352ebfa.png)

**Comment by stewartmiles** [comment]
@huran438 as I mentioned, this doesn't process other plugin's Android libraries with the Jetifier.  So plugins that just include some `.jar` and `.aar` files are not going to be mapped from the Android Support Library to Jetpack (AndroidX).  If you want to make this work you'll need to follow the steps I outlined in https://developers.google.com/android/guides/releases#may_31_2019 otherwise, as I mentioned pin to the older version of Google Play Services.

**Comment by takaaptech** [comment]
Just want to learn and confirm, @stewartmiles 
If you want to use the option:
```
Pin all references to com.google.android.gms.* packages to the release before the migration to AndroidX
```
All you need is search for com.google.android.gms in your project and find what dependencies XML file pull the new file. In my case, I found OneSignal plugin  cause problem:
```
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-base:[10.2.1, 12.1.0[" />
    <androidPackage spec="com.google.firebase:firebase-messaging:[10.2.1, 12.1.0["/>
    <androidPackage spec="com.google.android.gms:play-services-location:[10.2.1, 12.1.0[" />
    <androidPackage spec="com.android.support:support-v4:[26.0.0, 27.2.0[" />
    <androidPackage spec="com.android.support:customtabs:[26.0.0, 27.2.0[" />
  </androidPackages>
</dependencies>
```
So we just change some thing like [10.2.1, 12.1.0[ to fixed version that works before.

**Comment by birdkingz** [comment]
> @huran438 as I mentioned, this doesn't process other plugin's Android libraries with the Jetifier. So plugins that just include some `.jar` and `.aar` files are not going to be mapped from the Android Support Library to Jetpack (AndroidX). If you want to make this work you'll need to follow the steps I outlined in https://developers.google.com/android/guides/releases#may_31_2019 otherwise, as I mentioned pin to the older version of Google Play Services.

How can i pin to the older version of Google Play Services?

**Comment by stewartmiles** [comment]
@birdkingz @takaaptech provided an example in https://github.com/googlesamples/unity-jar-resolver/issues/241#issuecomment-506151368

**Comment by Kendja** [comment]
@drallcom3 @huran438 did you manage fix this crash on startup?

**Comment by jkasten2** [comment]
> @huran438 as I mentioned, this doesn't process other plugin's Android libraries with the Jetifier. So plugins that just include some `.jar` and `.aar` files are not going to be mapped from the Android Support Library to Jetpack (AndroidX). If you want to make this work you'll need to follow the steps I outlined in https://developers.google.com/android/guides/releases#may_31_2019 otherwise, as I mentioned pin to the older version of Google Play Services.

@stewartmiles Could you provide details on why Jetifier would skip processing `.jar` and `.aar` files added directly to the Unity project even when it is enabled in this plugins settings? Is it something specific to how this plugin or Unity's build system?
I notice if I go to  "Player Settings" > "Publishing Settings" > and enable "Custom Gradle Template" then Jetifier **does** the package transition from `android.support` to `androidx`. I verified this by checking the dex file in the APK before and after changing just this one setting.

**Comment by stewartmiles** [comment]
@jkasten2 you're right that if `mainTemplate.gradle` patching is enabled and the developer provides a `mainTemplate.gradle` file, the Jetifier will process all library files in the project.  However, if the custom gradle build options aren't enabled or the Internal build is used, the Jetifier processing will only be applied to dependencies managed by the Android Resolver plugin.

As I mentioned, I'm working on a solution that will import loose files in the project into a form that can be managed by the Android Resolver but it's not ready yet.

**Comment by bilck** [comment]
My 2 cents on the issue:
Maybe I did something wrong, but setting "Use Jetifier" didn't work out for me. 
To fix it just update all plugin dependencies [using their corresponding AndroidX build artifact](https://developer.android.com/jetpack/androidx/migrate)`.

It **is** a tedious proccess, but ended up being far more effective for me.

**Comment by JimmyDeemo** [comment]
I use some 3rd party plugins that have not yet updated to AndroidX. I am trying to pin my dependencies in order for AndroidX dependencies are not needed. I have tried to pin everything that mentions `com.google.android.gms.*` in the dependencies .xml files but still the AndroidX libraries come in to the project.

Please can someone tell me how I might find which libaries are resolving to AndroidX? Perhaps one of the logs from the resolver itself? I would like to try pinning these dependencies also.

**Comment by stewartmiles** [comment]
@JimmyDeemo the Android X migration happened in https://firebase.google.com/support/release-notes/android#update_-_june_17_2019

The prior release should not reference any AndroidX dependencies.
https://firebase.google.com/support/release-notes/android#update_-_may_31_2019
If you unfold the `BOM` section it contains the set of library versions you'll need.

**Comment by JimmyDeemo** [comment]
I've pinned everything I can think of an then noticed that the Facebook SDK does this; https://github.com/facebook/facebook-sdk-for-unity/blob/9389c5cfcaf1daa2a49fac39570e51b4563f37be/Facebook.Unity.Editor/android/AndroidSupportLibraryResolver.cs#L95. Even in the latest version that utilises the Jar Resolver.

So I end up with the following in the resolution output;

> Some conflicting dependencies were found.
> The following dependency versions were modified:
> com.android.support:appcompat-v7:25.3.1 --> androidx.appcompat:appcompat:1.0.0
> com.android.support:cardview-v7:25.3.1 --> androidx.cardview:cardview:1.0.0
> com.android.support:customtabs:25.3.1 --> androidx.browser:browser:1.0.0
> com.android.support:support-v4:25.3.1 --> androidx.legacy:legacy-support-v4:1.0.0
> com.facebook.android:audience-network-sdk:5.2.0 --> com.facebook.android:audience-network-sdk:5+
> com.google.games:gpgs-plugin-support:0.9.62 --> com.google.games:gpgs-plugin-support:0+

Am I right in thinking that these will always expand into androidx territory? Funnily enough the Facebook SDK is the one i'm having trouble with as it can't find `LocalBroadcastManager`

> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: FATAL EXCEPTION: main
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: Process: com.lockwoodpublishing.avakinlife, PID: 19389
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at com.facebook.internal.BoltsMeasurementEventListener.open(BoltsMeasurementEventListener.java:54)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at com.facebook.internal.BoltsMeasurementEventListener.getInstance(BoltsMeasurementEventListener.java:70)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:313)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:246)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at com.facebook.internal.FacebookInitProvider.onCreate(FacebookInitProvider.java:20)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5852)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5444)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5383)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.lockwoodpublishing.avakinlife-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lockwoodpublishing.avakinlife-1/lib/arm, /data/app/com.lockwoodpublishing.avakinlife-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 07-23 08:40:31.229 19389 19389 E AndroidRuntime: 	... 18 more

Is it expected that the Jetifier is able to resolve this? Forgive my lack of understanding but what/how should this probess map one package to the androidx equivolent? Or do Facebook just need to update their SDK? I was thinking of submitting a request that removes these code lines and adds the dependecies to the `Dependencies.xml` in their project.

Thoughts/ideas much appreciated.

**Comment by JimmyDeemo** [comment]
I don't think my project is being compiled with the Jetifier enabled. Please can someone outline what the plugin should do when the Jetifier option is turned on? Can I look in any files for the appropriate settings?

**Comment by stewartmiles** [comment]
https://github.com/facebook/facebook-sdk-for-unity/blob/9389c5cfcaf1daa2a49fac39570e51b4563f37be/Facebook.Unity.Editor/android/AndroidSupportLibraryResolver.cs#L95 should be ok, if the Jetifier is enabled it will map those dependencies to the AndroidX libraries instead, basically doing https://developer.android.com/jetpack/androidx/migrate

At the moment, the Android Resolver will not rewrite libraries to point at AndroidX if it doesn't know about them.  So if there are any loose .jar or .aar files in your project they will not get processed if you're using Unity's Internal build system or Gradle without a mainTemplate.gradle.

If you're using mainTemplate.gradle, enable the Jetifier in the Android Resolver and you're using a version of Unity that ships with Gradle `3.2.0` (you can check under `AndroidPlayer/Tools/gradle/lib`) then the Jetifier will process all Java libraries in your Gradle project.

**Comment by JimmyDeemo** [comment]
Thanks for the information @stewartmiles but I really think this is my problem. We are using Gradle with a mainTemplate.gradle file, however I don't see any edits from the play service resolver. When I export our project to an Android Studio project then I don't see `android.useAndroidX` nor
`android.enableJetifier` in the properties. Is that expected? We have a custom template so perhaps this is being skipped some how. Please can you tell me if there is any way to confirm that the jetifier is in use when exporting to an android studio project?

**Comment by JimmyDeemo** [comment]
This thread appears to illustrate my issue; https://forum.unity.com/threads/androidx-vs-android-libraries.710831/.

Is it expected that, in order to use the Jetifier, you also have 'Enabled Resolution On Build' enabled? We don't use this as we want our libaries to remain static until we have a reason to update and resolve them (e.g. plugin update).

**Comment by JimmyDeemo** [comment]
It's because I have a custom setup for my mainTemplate.gradle files, meaning that the jar resolver wasn't editing the file to include the jetifier setting. I'm looking to go with a more traditional setup.

**Comment by stewartmiles** [comment]
@JimmyDeemo the resolver can patch any mainTemplate.gradle file if it contains the sections described in https://github.com/googlesamples/unity-jar-resolver/blob/4bed53b74049c25fe2884be2a7d8290b5636128a/source/PlayServicesResolver/src/GradleTemplateResolver.cs#L39 

i.e

`// Android Resolver Repos Start`
`// Android Resolver Repos End`
`// Android Resolver Dependencies Start`
`// Android Resolver Dependencies End`
`// Android Resolver Exclusions Start`
`// Android Resolver Exclusions End`

The default code injection points are lines that match the following regular expressions:

  * Repos --> ".*apply plugin: 'com\.android\.(application|library)'.*"
  * Dependencies --> ".*\*\*DEPS\*\*.*"
  * Exclusions --> "android +{"

If you take a look at the default mainTemplate.gradle that ships with Unity you'll see where the Repos, Dependencies and Exclusions comments can be injected in your mainTemplate.gradle file for the resolver to inject the dependencies.

**Comment by JimmyDeemo** [comment]
So i've managed to get this working but I had to work around a problem that confuses me.

If I enable 'Patch mainTemplate.gradle' then the resolver replaces all of my .aar dependencies with entries in the mainTemplate.gradle file. This is fine but none of these resolve into AndroidX dependencies, therefore my project doesn't build with any of them. In fact if I were to export my project to Android Studio then it suggests I update these dependencies.

If I disable 'Patch mainTemplate.gradle' then the resolver adds AndroidX dependencies to my project (in the form of .aar files) but doesn't add the lines in the mainTemplate.gradle file to enable AndroidX and Jetifier. Therefore when I build the project and run it I get an error where the app doesn't know that the dependencies have been remapped.

I think herein lies the problem. I want to say this is a bug but i'm not confident this isn't working as expected. If you are not using your own 'mainTemplate.gradle' file then there isn't a way for this to work unless you do something like I mentioned in my [post above](https://github.com/googlesamples/unity-jar-resolver/issues/241#issuecomment-514534629). This is only available to users on Unity 2018 and up. I am using Unity 2017.4 LTS.

**My work around for the OP's (@takaaptech) issue** is to keep 'Patch mainTemplate.gradle' **off** and 'Use Jetifier' **on**. Then create and manually patch the 'mainTemplate.gradle' file in your project to add the following just above `apply plugin: 'com.android.application'`;

```
([rootProject] + (rootProject.subprojects as List)).each {
	ext {
		it.setProperty("android.useAndroidX", true)
		it.setProperty("android.enableJetifier", true)
	}
}
```

Also note: you might have to add the following line to your build script dependencies if you are using anything less than 2019.1.7f1 ([here is the reason](https://stackoverflow.com/a/57184411/807965));

```
buildscript {
	repositories {
		google()
		jcenter()
	}

	dependencies {
		classpath 'com.android.tools.build:gradle:3.2.1'
		classpath 'com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02' //Jetifier workaround
	}
}
```

I have included my mainTemplate.gradle file below for breivity.

[mainTemplate.txt](https://github.com/googlesamples/unity-jar-resolver/files/3431104/mainTemplate.txt)

**Comment by LordBelasco** [comment]
Hi, 
I get the same problem after installing the AudienceNetwork component

To solve my problem, I have removed the 4 Android files included with this AudienceNetwork Untiy package (support-compat, support-core-ui...) corresponding to Google classes, to delete a part of duplicated classes, and avoid the use and download of AndroidX files !

After that, I always get a duplicated class in another component. I rename the .aar of this component to zip, open it, rename  it's inner file classes.jar to .zip, open it, remove the directory corresponding to google classes, save all and restore the file extension (jar and aar)

The build is now ok, and I don't get the crash at startup with the Java.lang class not found

With this solution, I don't need to use AndroidX or Jetifier
I use a lot of components, so it was too difficult to use AndroidX or Jetifier

Hope it helps...

**Comment by yth1130** [comment]
I had a similar problem.

If I didn't use Jetifier, build was failed.
And if I used Jetifier, build was success but the game was crashed as soon as it turned on.

I solved the problem by using Jetifier and changing the manifest.
I changed "android.support.multidex.MultiDexApplication"
to "androidx.multidex.MultiDexApplication"

I hope this will help.

**Comment by iRDS** [comment]
> 
> 
> So i've managed to get this working but I had to work around a problem that confuses me.
> 
> If I enable 'Patch mainTemplate.gradle' then the resolver replaces all of my .aar dependencies with entries in the mainTemplate.gradle file. This is fine but none of these resolve into AndroidX dependencies, therefore my project doesn't build with any of them. In fact if I were to export my project to Android Studio then it suggests I update these dependencies.
> 
> If I disable 'Patch mainTemplate.gradle' then the resolver adds AndroidX dependencies to my project (in the form of .aar files) but doesn't add the lines in the mainTemplate.gradle file to enable AndroidX and Jetifier. Therefore when I build the project and run it I get an error where the app doesn't know that the dependencies have been remapped.
> 
> I think herein lies the problem. I want to say this is a bug but i'm not confident this isn't working as expected. If you are not using your own 'mainTemplate.gradle' file then there isn't a way for this to work unless you do something like I mentioned in my [post above](https://github.com/googlesamples/unity-jar-resolver/issues/241#issuecomment-514534629). This is only available to users on Unity 2018 and up. I am using Unity 2017.4 LTS.
> 
> **My work around for the OP's (@takaaptech) issue** is to keep 'Patch mainTemplate.gradle' **off** and 'Use Jetifier' **on**. Then create and manually patch the 'mainTemplate.gradle' file in your project to add the following just above `apply plugin: 'com.android.application'`;
> 
> ```
> ([rootProject] + (rootProject.subprojects as List)).each {
> 	ext {
> 		it.setProperty("android.useAndroidX", true)
> 		it.setProperty("android.enableJetifier", true)
> 	}
> }
> ```
> 
> Also note: you might have to add the following line to your build script dependencies if you are using anything less than 2019.1.7f1 ([here is the reason](https://stackoverflow.com/a/57184411/807965));
> 
> ```
> buildscript {
> 	repositories {
> 		google()
> 		jcenter()
> 	}
> 
> 	dependencies {
> 		classpath 'com.android.tools.build:gradle:3.2.1'
> 		classpath 'com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02' //Jetifier workaround
> 	}
> }
> ```
> 
> I have included my mainTemplate.gradle file below for breivity.
> 
> [mainTemplate.txt](https://github.com/googlesamples/unity-jar-resolver/files/3431104/mainTemplate.txt)

This worked for me thanks! had a lot of time put into solving it in vain until i saw your message, thanks again!

**Comment by drallcom3** [comment]
> > **My work around for the OP's (@takaaptech) issue** is to keep 'Patch mainTemplate.gradle' **off** and 'Use Jetifier' **on**. Then create and manually patch the 'mainTemplate.gradle' file in your project to add the following just above `apply plugin: 'com.android.application'`;

'Patch mainTemplate.gradle' off and 'Use Jetifier' **on** was already enough for me to make it work (I don't use any manual gradle files and luckily I don't have to). Thanks!

**Comment by takaaptech** [comment]
@google-oss-bot I will close it now. Thanks BOT!
