### ISSUE TITLE
Which version of resolver won't pull AndroidX?

### ISSUE THREAD

**Issue by birdkingz** [googlesamples/unity-jar-resolver#248]
As title. May I know which version of resolver doesn't not pull AndroidX libraries?

I've spent a few days trying to make things work and until today I still couldn't get it done.
Currently using Unity 2018.4 and I have Facebook, Google Play Game Services plugin integrated and I keep seeing errors like

Initially, the error is 
**_transformDexArchiveWithExternalLibsDexMergerForRelease_**. 
After updating to the latest resolver (which can enable Jetifier) then the error becomes 
**_Cannot fit requested classes in a single dex file (# methods: 68538 > 65536)_**

I'm trying to avoid enable multi dex since my other plugins may not support it yet. Also, I'm trying to keep the build size low.

**Comment by stewartmiles** [comment]
@birdkingz the resolver just downloads whatever transitive dependencies are required by a library.  Google Play Services started to depend upon AndroidX in the last major release https://developers.google.com/android/guides/releases#june_17_2019 so if you pull any of these packages it's going to download AndroidX as well.
