### ISSUE TITLE
Dex hit limit after importing Facebook SDK and running Android resolver

### ISSUE THREAD

**Issue by CarryRocky** [googlesamples/unity-jar-resolver#252]
I upgraded Facebook Unity SDK from 7.8.0 to 7.17.1 in my project, ran Android resolver then building and showing "Too many field references to fit in one dex file: 124313; max is 65536".
Before the importing and Android resolving our dex file defines 8329 classes with 47228 methods, and references 55547 methods.
My PlayServicesResolver version is 1.2.115.0, and we had GooglePlayGames 0.9.64 imported in the project. 
My Unity version is 2017.4.27f1

Is there any way to solve this problem?

**Comment by a-maurice** [comment]
Hi @CarryRocky 

To fix that you will need to enable Proguard minification, which strips out unused code.  Some more information on how to do so can be found at https://docs.unity3d.com/Manual/android-gradle-overview.html

**Comment by chkuang-g** [comment]
@CarryRocky 

It has been 2 weeks with no response.  I will close this issue.
Please let us know if you still have problem.
