### ISSUE TITLE
Understanding conflicts.

### ISSUE THREAD

**Issue by JimmyDeemo** [googlesamples/unity-jar-resolver#253]
When I run the resolver and I see output like this:

```
com.google.android.gms:play-services-basement conflicting due to package(s):
- com.facebook.android:audience-network-sdk:5.2.0/com.google.android.gms:play-services-basement:11.0.4
```

I understand that this means there is some sort of conflict between the first dependency and the second. This is resolved futher down by increase the scope of the first dependency and trying to find something that is compatible.

I wondered if anyone might be able to explain why conflicts such as this come about and whether there is anything I can do to keep the revision of the first dependency from changing too much.

e.g. In the above example, despite not updating the `audience-network-sdk` (which is tied to 5.2.0 in one dependency XML), this .aar is pushed to all the way to 5.4.1 due to the conflict with `play-services-basement`.

**Comment by stewartmiles** [comment]
I know the format isn't great, but the way this reports the conflict is:

```
CONFLICTING_PACKAGE_NAME conflicting due to package(s):
- PATH_TO_CONFLICTING_PACKAGE_NAME_AND_VERSION_0
...
- PATH_TO_CONFLICTING_PACKAGE_NAME_AND_VERSION_N
```

In this case `com.google.android.gms:play-services-basement` is included transitively by `com.facebook.android:audience-network-sdk:5.2.0`.  It's likely being required by other packages at a different version which would be printed out in the list of conflict paths.

**Comment by JimmyDeemo** [comment]
Ok, thanks for the explaination I will try and review my next resolution output.
