### ISSUE TITLE
Plugin appears to modify mainTemplate.gradle despite setting turned off.

### ISSUE THREAD

**Issue by JimmyDeemo** [googlesamples/unity-jar-resolver#254]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/4234718/61461513-bb904d00-a968-11e9-99ee-ac51121a9bc3.png">

Steps:
1. Open settings and check that the patch option is turned off. Hit OK.
2. Select Assets --> Play Service Resolver --> Android Resolver --> Delete Resolved Libraries.
3. Observe logs indicating tha the .gradle file is being searched for and written to.

**Comment by stewartmiles** [comment]
@JimmyDeemo that's the expected behavior.  With the patching turned off but the resolver turned on it will remove any modifications the resolver has added to the file.  I guess it could be a bit smarter and not rewrite the file if no resolver modifications are found and removed.

**Comment by JimmyDeemo** [comment]
Understood. Yes it does repeat those logs for each action.
