### ISSUE TITLE
Can't pass 'sources' to InvokeMethod (Cocoapods)

### ISSUE THREAD

**Issue by kjakm** [googlesamples/unity-jar-resolver#259]
In the latest version of the resolver I am no longer able to successfully invoke the `AddPod` method when I include 'sources' in the `namedArgs` parameter (if I remove 'sources' the below code works). This is my code:

```
    IEnumerable<String> sources = new String[]{"http://testurl.com"};
 
    Google.VersionHandler.InvokeStaticMethod(
    	iOSResolver, "AddPod",
    	new object[] {"MyPod"},
    	namedArgs: new Dictionary<String, object>(){
        {"version", "123"},
        {"bitcodeEnabled",true},
        {"minTargetSdk", "123"},
        {"sources", sources}
      });

```

The point at which it fails is when `InvokeMethod` in the VersionHandler checks the `parameterType` matches the `namedArg` type for 'sources':

`if (namedArg != null && parameterType != namedArg.GetType()) break;`

As you can see above I insert an `IEnumerable` of sources into the Dictionary (I have also tested with a `List` type). When we reach the `parameterType` check it expects an `IEnumerable`. Despite have passed this `namedArg.GetType()` returns a `System.String[]` and the test fails triggering the `break`. This then causes an error in Unity that the `AddPod` method does not exist. 

It seems that the `Dictionary<string, object>` is casting the `IEnumerable` to a different type (just a guess)?

My code worked prior to updating the resolver. I'm not sure if there is a way around this on my side or the `parameterType` check has been made too strict in the latest update.

**Comment by stewartmiles** [comment]
@kjakm thanks for the report, we've fixed the issue .. just waiting for internal code review before it can be published.

**Comment by kjakm** [comment]
Thanks for such a quick response @stewartmiles!

**Comment by stewartmiles** [comment]
Fixed in https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.123
