### ISSUE TITLE
The name `Google' does not exist in the current context

### ISSUE THREAD

**Issue by grosalex** [googlesamples/unity-jar-resolver#26]
Hi,
I've succesfully added the play-services-resolver-1.2.6.0.unitypackage in my unity project and copy paste the sample files in my script folder, but it won't build cause of : 

> Assets/Scripts/SampleDependencies.cs(95,5): error CS0103: The name `Google' does not exist in the current context

What I've missed? 

Regards,

**Comment by fraserleecampbell** [comment]
the dependencies file needs to be in an editor folder, from what i can gather.

**Comment by grosalex** [comment]
Yes I've figured it out thanks for your answear :)

**Comment by malisasmaz** [comment]
Hi I have same problem but Your solution not work on me
Assets/googleads-mobile-unity-master/source/plugin/Assets/GoogleMobileAds/Editor/AdMobDependencies.cs(30,36): error CS0103: The name `Google' does not exist in the current context

**Comment by pgilmorepf** [comment]
Same Issue:
Assets/PlayServicesResolver/Editor/SampleDependencies.cs(69,36): error CS0103: The name `Google' does not exist in the current context
