### ISSUE TITLE
Could not find the UnityEditor.Android.AndroidSDKTools class via reflection. etc.

### ISSUE THREAD

**Issue by u3556571** [googlesamples/unity-jar-resolver#260]
I didn't do anything but opening a new Unity project. Then these errors showed up:
- Could not find the UnityEditor.Android.AndroidSDKTools class via reflection.
- Could not find the UnityEditor.Android.PostProcessAndroidPlayer class via reflection.
- Failed to determine the most recently installed Android SDK version.

Although they didn't bother me anyway, but I think it would be better to report these bugs for improvements. And I don't know if the following messages would help, so I'll just give as much info as I can. Also I'm using latest Unity version 2019.1.11f1.

## Could not find the UnityEditor.Android.AndroidSDKTools class via reflection.
> Could not find the UnityEditor.Android.AndroidSDKTools class via reflection. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues
UnityEngine.Debug:LogError(Object)
GooglePlayServices.UnityCompat:get_AndroidSDKToolsClass() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:172)
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:234)
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:120)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2221)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1593)
GooglePlayServices.<ScheduleResolve>c__AnonStorey6:<>m__0() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1562)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1421)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1575)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1096)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__8() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1075)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

## Could not find the UnityEditor.Android.PostProcessAndroidPlayer class via reflection.

> Could not find the UnityEditor.Android.PostProcessAndroidPlayer class via reflection. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues
UnityEngine.Debug:LogError(Object)
GooglePlayServices.UnityCompat:get_PostProcessAndroidPlayerClass() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:204)
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:287)
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:120)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2221)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1593)
GooglePlayServices.<ScheduleResolve>c__AnonStorey6:<>m__0() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1562)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1421)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1575)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1096)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__8() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1075)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

## Failed to determine the most recently installed Android SDK version.
> Failed to determine the most recently installed Android SDK version. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25
UnityEngine.Debug:LogError(Object)
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:298)
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:120)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2221)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1593)
GooglePlayServices.<ScheduleResolve>c__AnonStorey6:<>m__0() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1562)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1421)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1575)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action) (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1096)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__8() (at Z:/tmp/tmp.i6ePfwE8Aq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1075)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.AbYCIb2V4h/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by stewartmiles** [comment]
@u3556571 thanks for reporting this.  It sounds like Unity continue to generate work.

**Comment by oakwarrior** [comment]
Hi! Is there any workaround for this? The Android Setup for the Google Play Games plugin will not work if this error is present.

**Comment by oakwarrior** [comment]
There is a workaround for this, for my case at least.

1. Open Unity Editor (2019)
2. Open the "Edit" dropdown in the top bar
3. Select "Preferences"
4. Select "External Tools"
5. Uncheck "Android SDK Tools Installed With Unity (recommended)", this will lag a bit so don't spam-click
6. Delete any and all data inside the input field that appears. Make sure it's empty, no whitespace either. This will lag, too.
7. Click on "Browse", the field should now populate with the Editor's own SDK path. Verify that this is the case. If not, manually find the SDK of the version of the Editor you're running but it should fill it automatically after a bit of lag.
8. Check "Android SDK Tools Installed With Unity (recommended)", this will also lag.
9. It should work now, try and see if the project opens. If not, try to Reimport All (this was required for my case).

Good luck. I hope this helps someone.

**Comment by BlueSpiritbox** [comment]
I had a similar problem with the 1.2.124 resolver. I downgraded it to an older version (1.2.109) and now it's building again without any errors.

**Comment by dominicdev** [comment]
is there any fix?
