### ISSUE TITLE
Run Resolver before building

### ISSUE THREAD

**Issue by MartinGonzalez** [googlesamples/unity-jar-resolver#261]
Hi!
I would like to know if there is a way to run the resolver and get a callback when it finished resolving dependencies so I can run it in CI.
Right now we are pushing all the .aar but it would be better just to commit the AndroidResolverDependencies.xml (that I guess works like package-lock.json in npm or Gemfile.lock in ruby)

Thanks!

**Comment by stewartmiles** [comment]
If you add a `mainTemplate.gradle` and enable `mainTemplate.gradle` patching in the resolver you can use the Gradle to pull the dependencies at build time instead.

If you're using the old build process in Unity (i.e no `mainTemplate.gradle`) there is already an option to resolve on build.  `AndroidResolverDependencies.xml` is not the same a Gemfile.lock, it's simply a cache.

**Comment by MartinGonzalez** [comment]
Ok, I will close the issue then.

Thanks!
