### ISSUE TITLE
Can final dlls path be in Assets/Plugins Directory?

### ISSUE THREAD

**Issue by hiradyazdan** [googlesamples/unity-jar-resolver#264]
Since this is used for plugins, can the path be within Plugins directory?

**Comment by stewartmiles** [comment]
I don't understand what you're asking.  Exploded AARs are placed in `Assets/Plugins/Android` they can't really be placed elsewhere as various versions of Unity won't include them in the build.

See https://docs.unity3d.com/Manual/AndroidAARPlugins.html

**Comment by hiradyazdan** [comment]
I am using a plugin that has this resolver built-in and if I move the built-in PlayServicesResolver from Assets directory to Plugins directory, then it cannot recognize Google namespace. So, I don't know if I am missing something because of my unfamiliarity with your library or not.

**Comment by hiradyazdan** [comment]
Oh, I noticed that I can actually rebuild their unitypackage and import unity-jar-resolver with the correct path myself. Sorry to bother.

**Comment by hiradyazdan** [comment]
I am not sure if this can be done through the other plugins import export unitypackage as the export directory path is Assets:

> 2. Export your plugin by running Unity from the command line, ensuring that you:
Include the contents of the Assets/PlayServicesResolver directory.
Add the -gvh_disable option.
You must specify the -gvh_disable option in order for the Version Handler to work correctly!

> For example, the following command will import the play-services-resolver-1.2.46.0.unitypackage into the project MyPluginProject and export the entire Assets folder to MyPlugin.unitypackage:
...

I very much appreciate your advice on this. Thanks :)

**Comment by hiradyazdan** [comment]
@stewartmiles No I can't sorry. But, I thought I have clarified my problem by mentioning specific issues above.

**Comment by hiradyazdan** [comment]
@stewartmiles `Google.VersionHandler` is the actual problem, the Google namespace is not available if I move the `PlayServicesResolver` into the `Plugins` directory. The weird thing is that all the dlls are already inside `Editor` directory which Unity be default allocate it as `Assembly-CSharp-Editor` project.

**Comment by stewartmiles** [comment]
Could you share a minimal project that reproduces this or perhaps exactly where you're moving the plugin's DLLs in your project.  It sounds like you're moving them into a folder where they will not be loaded in the context of the editor.

**Comment by hiradyazdan** [comment]
@stewartmiles I have provided an exact reproduction of the issue as above three weeks ago, and mentioned:

> For example in below project, if PlayServicesResolver is located inside the plugins directory, the Google namespace is no longer available:

> jizc/CloudOnce:source/PluginDev/Assets/Extensions/CloudOnce/Internal/Editor/Utils/GooglePlayGamesSetup/GPGAndroidSetup.cs@master#L33 

It's not like I am moving them into outside the project directory!

**Comment by hiradyazdan** [comment]
It's very easy bypassing and ignoring real issues by labelling them as `help wanted`!

**Comment by stewartmiles** [comment]
To quote what you wrote

"I am using a plugin that has this resolver built-in and if I move the built-in PlayServicesResolver from Assets directory to Plugins directory, then it cannot recognize Google namespace"

what `Plugins` directory?  If this is the top level Plugins directory i.e not `Assets/Plugins/Editor` but instead `Assets/Plugins`, yes this isn't going to work.

**Comment by hiradyazdan** [comment]
Yes top-level Plugins directory in Unity! 

Most libraries have `Editor` directory as their inner directory (i.e. `Assets/Plugins/TheLibrary/Editor/...`) and Top-level `Editor` directory (i.e. `Assets/Plugins/Editor`) is usually for the custom scripts that the developer uses in their own game. 

I actually can't remember now if this is going to work or not since the last replication was nearly three weeks ago.

**Comment by stewartmiles** [comment]
@hiradyazdan this plugin is redistributed under `Assets/PlayServicesResolver/Editor`.  I just tried moving the files to various locations, `Assets/Plugins/Editor` and `Assets/Plugins` in each case the plugin works as expected.  Everything is visible to editor components and they execute in the editor.

Though the convention is to always have editor components under a `Editor` directory.

If this isn't working with your(assuming it's yours) plugin https://github.com/jizc/CloudOnce/blob/master/source/PluginDev/Assets/Extensions/CloudOnce/Internal/Editor/Utils/GooglePlayGamesSetup/GPGAndroidSetup.cs#L33 then you're on your own to debug it.

If you want help, you'll need a share a minimal project that can reproduce the issue.  To set expectations though, maintainers of this project have other stuff we're working on this is not a consulting service.

**Comment by stewartmiles** [comment]
@hiradyazdan as I mentioned if you're able to describe the change you would like to see, or even better since this project is open source, send a pull request with a patch to make your workflow work myself and other maintainers of this project would be happy to discuss this further.  Closing the issue with a thumbs down and wide eyed emoji really doesn't seem to make any progress.
