### ISSUE TITLE
Prompt to enabled Jetifier not appearing when updating to FireBase 6.2.1 or higher

### ISSUE THREAD

**Issue by CriticalForce** [googlesamples/unity-jar-resolver#266]
Reproed using JarResolved 1.2.122.0 and 1.2.124.0

Upgrading a project with FireBase 6.2.1 or higher causes the Jetifier to be always toggled on in "Resolve" and "Force Resolve"

The prompt never comes and it shows a log that it detected AndroidX related libs.
**Version 1.2.121 - Jun 27, 2019:**
> Android Resolver: If AndroidX is detected in the set of resolved libraries, the user will be prompted to enable the Jetifier.

This can be reproed by importing Crashlytics 6.2.1 SDK from the FireBase Unity SDK and running resolve. (6.1.1 Crashlytics works normally)
This causes the Gvhsettings flag for jetifier to be toggled on.

**Comment by stewartmiles** [comment]
@CriticalForce the Jetifier is automatically turned when AndroidX libraries are detected here:

https://github.com/googlesamples/unity-jar-resolver/blob/a4ccc351c74182315c3da862d7fc14e9db458f08/source/PlayServicesResolver/src/GradleResolver.cs#L408

without turning on the Jetifier it's very likely a build will fail as there are still a lot of Unity plugins that depend upon the legacy Android Support Libraries.  This was introduced in 9d7fac674d0fa777c90fcc77a00760a98eb2efbf

Are you suggesting that this should display an error if Jetpack isn't supported by the selected API level / Gradle version or the Android Support Libraries are detected instead?
