### ISSUE TITLE
Firebase Unity SDK

### ISSUE THREAD

**Issue by zhushaojun65** [googlesamples/unity-jar-resolver#267]
Hi guys, thanks for help me!
I use firebase unity sdk(version: 6.4.0), my unity version is: 2018.2.21f
When i build project with android for apk, i got a switch api to 28 message box, but in unity version 2018.2.21f , there are no api 28, if i check no, reslover can not dependencies download jar and aar

**Comment by stewartmiles** [comment]
I recommend you contact https://firebase.google.com/support
