### ISSUE TITLE
Please add option to disable logging entirely

### ISSUE THREAD

**Issue by kevinfoley** [googlesamples/unity-jar-resolver#269]
Even when Verbose logging is disabled, the Resolver outputs nearly 100 log entries every time we press "Play" in the Editor:

    Assets\PlayServicesResolver\Editor\Google.IOSResolver.dll metadata will be checked
    Assets\PlayServicesResolver\Editor\Google.JarResolver.dll metadata will be checked
    Assets\PlayServicesResolver\Editor\Google.VersionHandler.dll metadata will be checked

etc. These messages tend to bury the messages from our own code that we actually want to see. There should be an option to disable these log messages altogether.

**Comment by stewartmiles** [comment]
@kevinfoley there is an option to disable logging entirely, it's per component in the plugin are you sure you have it disabled across all components i.e Version Handler, Android Resolver, iOS Resolver?

**Comment by kevinfoley** [comment]
Whoops, missed that there was a separate logging setting in Version Handler. Thanks!
