### ISSUE TITLE
Google.JarResolver.ResolutionException: Cannot resolve com.android.support:support-v7:23.4.0()   at Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest) [0x00000] in <filename unknown>:0 

### ISSUE THREAD

**Issue by grosalex** [googlesamples/unity-jar-resolver#27]
Hi,
I'm just trying to add android support to a unity pluggin but when the dependency script starts I'm having this output in the console : 
`Google.JarResolver.ResolutionException: Cannot resolve com.android.support:support-v7:23.4.0()
  at Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest) [0x00000] in <filename unknown>:0 
  at GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation) [0x00000] in <filename unknown>:0 
UnityEngine.Debug:LogError(Object)
GooglePlayServices.ResolverVer1_1:DoResolutionNoAndroidPackageChecks(PlayServicesSupport, String, OverwriteConfirmation)
GooglePlayServices.<DoResolution>c__AnonStorey5:<>m__8()
GooglePlayServices.<DoResolution>c__AnonStorey6:<>m__D(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
GooglePlayServices.CommandLineDialog:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
`

I'm not even asking for 23.4.0 I'm asking for 25.0.1, any idea?

Regards,

**Comment by grosalex** [comment]
Resolved this by deleting all call for 23.4.0 and after that delete GoogleDependencyGooglePlayGmaes.xml

**Comment by stewartmiles** [comment]
We've removed the cache in the latest release so this should not happen anymore.
