### ISSUE TITLE
Unity failed to determine the most recently installed Android SDK version

### ISSUE THREAD

**Issue by talos1279** [googlesamples/unity-jar-resolver#273]
Hello, I'm reporting this Unity bug according to the console screen.

This bug happens when I try to export the project on Android platform. My Unity version is 2019.2.0f1 Personal.

Failed to determine the most recently installed Android SDK version. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25
UnityEngine.Debug:LogError(Object)
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:298)
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:120)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2221)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1593)
GooglePlayServices.<ScheduleResolve>c__AnonStorey6:<>m__0() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1562)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1421)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1575)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1096)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__8() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1075)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by dominicdev** [comment]
I had this issue and it was causing crash when ads load, and so annoying!!

**Comment by SirPirelli** [comment]
I have this issue too, appears every time I open the project in Unity. I didnt find any issues related to it besides the error itself.

**Comment by stewartmiles** [comment]
I have a patch lined up though I would like to test with exactly the same configuration where you're seeing this.  Which Unity version are you using and how is your Android SDK configured?

**Comment by SirPirelli** [comment]
First of all when I open the project, asks me if I want to enable Jetpack, to which I say no, I mantain the Automatic(Highest Installed). When I open the dropdown, I see there the API Level 29 doesnt have the same nomenclature as the others "Android x.x 'Name' (API Level X)", just says API Level 29.
I'm using Unity version 2019.2.5f1 and I installed the Android SDK through Android Studio (like half a year ago) and Android SDK Tools With Unity (if this makes sense, I only have 1 year experience with Android).

**Comment by stewartmiles** [comment]
@SirPirelli what dropdown are you referring to?  If you're talking about the `Minimum API  level` and `Target API level` in Unity's Player Settings, they're not generated by this plugin.

If you disable Jetpack / Jetifier and any Android libraries in the project depend upon Jetpack you're going to be using an unsupported configuration.

**Comment by jdelange** [comment]
Same issue see #298

**Comment by stewartmiles** [comment]
I've been playing around with this using various Unity 2019.x versions and as far as I can tell all of the reported issues must be prior to the [1.2.125](https://github.com/googlesamples/unity-jar-resolver/blob/master/CHANGELOG.md#version-12125---sep-23-2019) which was fixed in https://github.com/googlesamples/unity-jar-resolver/commit/c48c995ec0c8592cbd96b8e21c72aef6bdb82d2d#diff-c41a8aec79d6c352db4d7baa2a3979aa .  If you're able to reproduce with newer Android Resolver releases.
