### ISSUE TITLE
Freezing on batch builds

### ISSUE THREAD

**Issue by FodderMK** [googlesamples/unity-jar-resolver#274]
This is inconsistent, but our Jenkins builds often freezes when making Android builds.  The last few messages in the log file are related to the resolver which is why I'm posting here.  Once the build process hits this point the CPU gets pegged and Unity does not continue building, forcing me to kill the process and try again.  I can't seem to figure out any rhyme-or-reason for it and the builds usually succeed when we restart the process.

Unity 2018.4.6f1
Google.VersionHandlerImpl_v1.2.119.0.dll

```
[...]
Extracting Assets/Firebase/m2repository/com/google/firebase/firebase-app-unity/6.1.1/firebase-app-unity-6.1.1.aar ("AndroidManifest.xml" "jni" "classes.jar") to /workspace/PROJECT/Temp/gy2f2ewq.97g
[...]
Caching AAR Assets/GooglePlayGames/Editor/m2repository/com/google/games/gpgs-plugin-support/0.9.60/gpgs-plugin-support-0.9.60.aar state
[...]
Extracting Assets/GooglePlayGames/Editor/m2repository/com/google/games/gpgs-plugin-support/0.9.60/gpgs-plugin-support-0.9.60.aar ("AndroidManifest.xml" "jni" "classes.jar") to /workspace/PROJECT/Temp/vs7y2t7e.s0s
[...]

Compiling...
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Google.Logger:Log(String, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:95)
Google.VersionHandlerImpl:Log(String, Boolean, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/VersionHandlerImpl.cs:1715)
Google.<NotifyWhenCompliationComplete>c__AnonStoreyB:<>m__19() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/VersionHandlerImpl.cs:1554)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__17() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
Google.RunOnMainThread:Run(Action, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.RunOnMainThread:RemoveOnUpdateCallback(CallbackFunction) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:223)
Google.RunOnMainThread:remove_OnUpdate(CallbackFunction) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:195)
GooglePlayServices.PlayServicesResolver:.cctor() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:847)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:.cctor()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
UnityEditor.EditorAssemblies:ProcessEditorInitializeOnLoad(Type) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:128)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:168)
```

**Comment by stewartmiles** [comment]
@FodderMK that message is displayed if the Version Handler component detects the editor is still compiling while starting up.  Is that the only message present in your logs?  Have you tried upgrading the resolver since quite a bit has changed?

**Comment by FodderMK** [comment]
The messages up to that point are related to the resolver.  My post above has the 4 most recent.  I haven't tried upgrading to the latest, I'll look at doing that for the next release.

**Comment by stewartmiles** [comment]
@FodderMK oh that's interesting.  I missed the "Extracting" messages.  It looks like the Android Resolver starts running then Unity decides to kick off compilation which causing the Android Resolver DLL to be unloaded which stops the process.  If you're waiting on Android Resolution completing this could be part of the problem.  I guess you could workaround this by running the Android Resolver on another machine and checking in the resultant artifacts (i.e `aar` and `jar` files / folders) which will result in no Android Resolution on your build machine - assuming there are no differences between the state in `ProjectSettings/AndroidResolverDependencies.xml` see [this code](https://github.com/googlesamples/unity-jar-resolver/blob/780aef4e58c1a75a8977ccf8208f3d69afefedc9/source/PlayServicesResolver/src/PlayServicesResolver.cs#L53) and the set of dependencies requested by the project.

**Comment by FodderMK** [comment]
This workaround appears to have fixed the problem.  We haven't encountered a lockup on build since then.
