### ISSUE TITLE
CommandInvokationFailure: Gradle build failed

### ISSUE THREAD

**Issue by DreamerYinYu** [googlesamples/unity-jar-resolver#277]
CommandInvokationFailure: Gradle build failed. 
D:\Unity\2018.4.8f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\OpenJDK\Windows\bin\java.exe -classpath "D:\Unity\2018.4.8f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-5.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class android.support.customtabs.ICustomTabsCallback found in modules classes.jar (:androidx.browser.browser-1.0.0:) and classes.jar (androidx.browser:browser:1.0.0)
  Duplicate class android.support.customtabs.ICustomTabsCallback$Stub found in modules classes.jar (:androidx.browser.browser-1.0.0:) and classes.jar (androidx.browser:browser:1.0.0)
  Duplicate class android.support.customtabs.ICustomTabsCallback$Stub$Proxy found in modules classes.jar (:androidx.browser.browser-1.0.0:) and classes.jar (androidx.browser:browser:1.0.0)
  Duplicate class android.support.customtabs.ICustomTabsService found in modules classes.jar (:androidx.browser.browser-1.0.0:) and classes.jar (androidx.browser:browser:1.0.0)
  Duplicate class android.support.customtabs.ICustomTabsService$Stub found in modules classes.jar (:androidx.browser.browser-1.0.0:) and classes.jar (androidx.browser:browser:1.0.0)
  Duplicate class android.support.customtabs.ICustomTabsService$Stub$Proxy found in modules classes.jar (:androidx.browser.browser-1.0.0:) and classes.jar (androidx.browser:browser:1.0.0)
  Duplicate class android.support.customtabs.IPostMessageService found in modules classes.jar (:androidx.browser.browser-1.0.0:) and classes.jar (androidx.browser:browser:1.0.0)
  Duplicate class android.support.customtabs.IPostMessageService$Stub found in modules classes.jar (:androidx.browser.browser-1.0.0:) and classes.jar (androidx.browser:browser:1.0.0)
  Duplicate class android.support.customtabs.IPostMessageService$Stub$Proxy found in modules classes.jar (:androidx.browser.browser-1.0.0:) and classes.jar (androidx.browser:browser:1.0.0)
  Duplicate class android.support.v4.graphics.drawable.IconCompatParcelizer found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (androidx.core:core:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$CallbackHandler found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$ConnectionCallback found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$ConnectionCallback$StubApi21 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$CustomActionCallback found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$CustomActionResultReceiver found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$ItemCallback found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$ItemCallback$StubApi23 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$ItemReceiver found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImpl found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi21 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi21$1 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi21$2 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi21$3 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi21$4 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi21$5 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi21$6 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi21$7 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi23 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi26 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplBase found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplBase$1 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplBase$2 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplBase$3 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplBase$4 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplBase$5 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplBase$6 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplBase$MediaServiceConnection found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplBase$MediaServiceConnection$1 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserImplBase$MediaServiceConnection$2 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaBrowserServiceCallbackImpl found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaItem found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaItem$1 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$MediaItem$Flags found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$SearchCallback found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$SearchResultReceiver found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$ServiceBinderWrapper found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$Subscription found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$SubscriptionCallback found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$SubscriptionCallback$StubApi21 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompat$SubscriptionCallback$StubApi26 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi21 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi21$ConnectionCallback found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi21$ConnectionCallbackProxy found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi21$MediaItem found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi21$SubscriptionCallback found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi21$SubscriptionCallbackProxy found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi23 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi23$ItemCallback found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi23$ItemCallbackProxy found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi26 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi26$SubscriptionCallback found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaBrowserCompatApi26$SubscriptionCallbackProxy found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaDescriptionCompat found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaDescriptionCompat$1 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaDescriptionCompat$Builder found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaDescriptionCompatApi21 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaDescriptionCompatApi21$Builder found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaDescriptionCompatApi23 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaDescriptionCompatApi23$Builder found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaMetadataCompat found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaMetadataCompat$1 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaMetadataCompat$BitmapKey found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaMetadataCompat$Builder found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaMetadataCompat$LongKey found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaMetadataCompat$RatingKey found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaMetadataCompat$TextKey found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaMetadataCompatApi21 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.MediaMetadataCompatApi21$Builder found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.ParceledListSliceAdapterApi21 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.RatingCompat found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.RatingCompat$1 found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.RatingCompat$StarStyle found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.RatingCompat$Style found in modules classes.jar (:androidx.media.media-1.0.0:) and classes.jar (androidx.media:media:1.0.0)
  Duplicate class android.support.v4.media.se<message truncated>

**Comment by DreamerYinYu** [comment]
// GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN

buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
**BUILD_SCRIPT_DEPS**}
}

allprojects {
    repositories {
        mavenCentral()
        google()
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
}

// Android Resolver Repos Start
([rootProject] + (rootProject.subprojects as List)).each {
    ext {
        it.setProperty("android.useAndroidX", true)
        it.setProperty("android.enableJetifier", true)
    }
}
([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
        def unityProjectPath = "file:///" + file(rootProject.projectDir.path + "/../../").absolutePath
        maven {
            url "https://maven.google.com"
        }
        maven {
            url (unityProjectPath + "/Assets/Firebase/m2repository") // Assets/Firebase/Editor/AnalyticsDependencies.xml:20, Assets/Firebase/Editor/AppDependencies.xml:20
        }
        maven {
            url "https://maven.google.com/" // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
        }
        maven {
            url "https://jcenter.bintray.com/" // Assets/GoogleMobileAds/Editor/MoPubMediationDependencies.xml:8
        }
        maven {
            url "https://s3.amazonaws.com/moat-sdk-builds" // Assets/GoogleMobileAds/Editor/MoPubMediationDependencies.xml:8
        }
        mavenLocal()
        jcenter()
        mavenCentral()
    }
}
// Android Resolver Repos End
apply plugin: 'com.android.application'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:multidex:1.0.3'
// Android Resolver Dependencies Start
    implementation 'com.applovin:applovin-sdk:9.4.2' // Assets/GoogleMobileAds/Editor/AppLovinMediationDependencies.xml:6
    implementation 'com.google.ads.mediation:applovin:9.4.2.0' // Assets/GoogleMobileAds/Editor/AppLovinMediationDependencies.xml:4
    implementation 'com.google.ads.mediation:mopub:5.7.1.0' // Assets/GoogleMobileAds/Editor/MoPubMediationDependencies.xml:8
    implementation 'com.google.android.gms:play-services-ads:18.1.1' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
    implementation 'com.google.firebase:firebase-analytics:17.0.0' // Assets/Firebase/Editor/AppDependencies.xml:15
    implementation 'com.google.firebase:firebase-analytics-unity:6.2.2' // Assets/Firebase/Editor/AnalyticsDependencies.xml:20
    implementation 'com.google.firebase:firebase-app-unity:6.2.2' // Assets/Firebase/Editor/AppDependencies.xml:20
    implementation 'com.google.firebase:firebase-common:18.0.0' // Assets/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-iid:[19.0.1]' // Assets/Firebase/Editor/AnalyticsDependencies.xml:15
// Android Resolver Dependencies End
**DEPS**}

// Android Resolver Exclusions Start
android {
  packagingOptions {
      exclude ('/lib/arm64-v8a/*' + '*')
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
// Android Resolver Exclusions End
android {
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        applicationId '**APPLICATIONID**'
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        multiDexEnabled true
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb'**STREAMING_ASSETS**]
    }**SIGN**

    buildTypes {
        debug {
            minifyEnabled **MINIFY_DEBUG**
            useProguard **PROGUARD_DEBUG**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD**
            jniDebuggable true
        }
        release {
            minifyEnabled **MINIFY_RELEASE**
            useProguard **PROGUARD_RELEASE**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD****SIGNCONFIG**
        }
    }**PACKAGING_OPTIONS****SPLITS**
**BUILT_APK_LOCATION**
    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }
}**SPLITS_VERSION_CODE****REPOSITORIES****SOURCE_BUILD_SETUP**

**Comment by stewartmiles** [comment]
@DreamerYinYu I'm not sure what we're supposed to do with this report.  It looks like you the build failed because you have duplicate instances of Android packages included in your build.  If these libraries are being pulled in by plugins using Android Resolver you're running into https://github.com/googlesamples/unity-jar-resolver/issues/243 which is a known issue when using the mainTemplate patching mode.
