### ISSUE TITLE
Xcode 11/Unity2019.3 issue with project resolve?

### ISSUE THREAD

**Issue by Extrawurst** [googlesamples/unity-jar-resolver#280]
is it possible that there is an issue with Xcode 11 xcproject alternation? I cannot narrow it further but since upgrading to Xcode 11 the pods integration into the Xcode project instead of workspace integration does not work anymore. 

I start to see linker errors that the dependencies like FBSDKCoreKit cannot be found

**Comment by Extrawurst** [comment]
Ok never mind it was the cocoapods version not working correctly as it seems. updating `1.7.4` to `1.8.1` fixed the issue, took me just a day of my life :D

**Comment by stewartmiles** [comment]
@Extrawurst glad you figured it out, thanks for letting us know.

**Comment by Extrawurst** [comment]
@stewartmiles I am afraid I have to reopen this. Turns out on Unity 2019.3.x this happens no matter of the CocoaPods version. The project integration instead of workspace mode does not seem to work anymore. Is it possible that the iOS resolver gets confused because there is suddenly two  targets `Unity-iPhone` and `UnityFramework`?

**Comment by Extrawurst** [comment]
So after looking into both `project.pbxproj` after building with unity 2019.2 vs. 2019.3 it is obvious that all the pods files are missing in the 2019.3 result. I am wondering now how iosresolver works. How is it putting the pods into the project in the case of pre-unity-2019.3 case where it works? Because CocoaPods states that you *need* to use the workspace `pods` generates?
Is it a problem with some `PostBuildProcessor` scripts that are not running properly?

Also I see this error in the console on unity 2019.3:
```
Exception: Calling TargetGuidByName with name='Unity-iPhone' is deprecated. There are two targets now, call GetUnityMainTargetGuid() - for app or GetUnityFrameworkTargetGuid() - for source/plugins to get Guid instead.
UnityEditor.iOS.Xcode.PBXProject.TargetGuidByName (System.String name) (at /Users/builduser/buildslave/unity/build/External/XcodeAPI/Xcode/PBXProject.cs:170)
Google.IOSResolver.UpdateProjectDeps (UnityEditor.BuildTarget buildTarget, System.String pathToBuiltProject) (at /Users/smiles/dev/src/unity-jar-resolver/source/IOSResolver/src/IOSResolver.cs:2325)
Google.IOSResolver.OnPostProcessUpdateProjectDeps (UnityEditor.BuildTarget buildTarget, System.String pathToBuiltProject) (at /Users/smiles/dev/src/unity-jar-resolver/source/IOSResolver/src/IOSResolver.cs:2288)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
UnityEditor.Build.BuildPipelineInterfaces+AttributeCallbackWrapper.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:177)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass17_0.<OnBuildPostProcess>b__1 (UnityEditor.Build.IPostprocessBuildWithReport bpp) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:433)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:391)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:187)
```

which is weird because I saw that being addressed before here. But I still see it happening in the recent release of `1.2.125` of the resolver

**Comment by Extrawurst** [comment]
Ok looking further it seems obvious for some reason the Unity Version detection inside the IOSResolver believes it is a version where you can still call `TargetGuidByName` with the main target name. This throws and the whole project alternation of adding the dependencies is not finished: https://github.com/googlesamples/unity-jar-resolver/blob/4bfc71ae6726dc41562ee9ca04ee98ed3999cdc3/source/IOSResolver/src/IOSResolver.cs#L2325

That seems to be a regression in `1.2.125` - what do you think @stewartmiles ?

**Comment by Extrawurst** [comment]
Ok it appears this part was not touched in the previous commit that was supposed to fix the resolver for iOS and Unity 2019.3: https://github.com/googlesamples/unity-jar-resolver/commit/bc43146b6c2003ae0a053c889a78744b9f92fb99

I went further down the rabbit hole trying to fix this but stumbled over even more hurdles: I cannot get it to find my unity installation on OSX:
`/Applications/Unity/Hub/Editor/2019.3.0b4/Unity.app/Contents/MacOS/Unity`

so I hardcoded that one in the Gradle script, **boom** next issue it cannot seem to build `:compileVersionHandler` 

```
Execution failed for task ':compileVersionHandler'.
> A problem occurred starting process 'command '/Applications/Unity/Hub/Editor/2019.3.0b4/Unity.app/Contents/MonoBleedingEdge/bin/xbuild''
```

Without help I am lost on this. But it seems definitely hard to get this lib to build on OSX right now

**Comment by stewartmiles** [comment]
Hi @Extrawurst thanks for looking into this.  If it's having trouble finding your Unity installation you can set it via `gradle.properties` e.g

```
$ cat gradle.properties 
#Fri Jul 13 16:57:34 PDT 2018
UNITY_DIR=/Applications/Unity5.6.5f1
XBUILD_EXE=/Applications/Unity5.6.5f1/Unity.app/Contents/Mono/bin/xbuild
UNITY_NUNIT_PATH=/Applications/Unity5.6.5f1/Unity.app/Contents/Managed
UNITY_EXE=/Applications/Unity5.6.5f1/Unity.app/Contents/MacOS/Unity
NUNIT_CONSOLE_EXE=/Applications/Unity5.6.5f1/Unity.app/Contents/Mono/bin/nunit-console2
UNITY_IOS_PLAYBACK_PATH=/Applications/Unity5.6.5f1/PlaybackEngines/iOSSupport
UNITY_DLL_PATH=/Applications/Unity5.6.5f1/Unity.app/Contents/Managed
```

You _should_ be able to just set `UNITY_DIR` and the other variables will be set when the gradle script runs.  I'm not sure why it's not possible to run xbuild from Unity's distribution, was it removed?

**Comment by Extrawurst** [comment]
@stewartmiles thanks for the tip with the `gradle.properties`. regarding `xbuild` I get the following output when running it:
```
/Applications/Unity/Hub/Editor/2019.3.0b5/Unity.app/Contents/MonoBleedingEdge/bin/xbuild

>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

MSBUILD: error MSBUILD0003: Please specify the project or solution file to build, as none was found in the current directory.
```

my guess is the non-zero exit code breaks the gradle build?

**Comment by Extrawurst** [comment]
@stewartmiles what do you think about the issue with https://github.com/googlesamples/unity-jar-resolver/blob/4bfc71ae6726dc41562ee9ca04ee98ed3999cdc3/source/IOSResolver/src/IOSResolver.cs#L2325 throwing in unity 2019.3?

**Comment by stewartmiles** [comment]
@Extrawurst yeah it looks like you're right that should be using `GetXcodeTargetGuids()` instead added in https://github.com/googlesamples/unity-jar-resolver/commit/a00f7d0e6b8c0cb64bb6b605ac6f1fe1c62985cb

**Comment by Extrawurst** [comment]
@stewartmiles thanks so much for the fix! looking forward to the next release 👍

**Comment by stewartmiles** [comment]
@Extrawurst thanks for letting us know and narrowing this down.  It's released in https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.128
