### ISSUE TITLE
Any build after 1.2.124.0 causes error (Exception) on Unity (2019.1.14f1)

### ISSUE THREAD

**Issue by PixelEnvision** [googlesamples/unity-jar-resolver#283]
Hi,

I end up with the following error on Unity console when using any build after 1.2.124.0

`Exception: Method VersionHandlerImpl.UpdateVersionedAssets not found
Google.VersionHandler.InvokeMethod (System.Type type, System.Object objectInstance, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary2[TKey,TValue] namedArgs) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandler/src/VersionHandler.cs:554)`

Tested with 125,126,127,128,129

**Comment by stewartmiles** [comment]
@PixelEnvision is this reproducible in an empty project?  Which Unity version and which platform are you using?  Kinda need more to go on than what you've posted.

**Comment by PixelEnvision** [comment]
Thanks for the prompt reply.

I'm using following package https://github.com/jizc/CloudOnce/releases

It comes with Play Services Resolver v1.2.111

In its control panel it has a function called "Run setup" for Android which sets Google Application ID for game services and then runs resolve function.

Updating Play Services Resolver to any version up to 1.2.124 works fine, any version above it casues the error in the console when the function called.

I think importing the CloudOnce to an empty project should be enough to reproduce...

**Comment by PixelEnvision** [comment]
Sorry forgot to post, I'm on Unity (2019.1.14f1) as in the title, on macOS Mojave.

**Comment by stewartmiles** [comment]
Could you share the full stack trace of the error?  I'm guessing this "Run Setup" thing is coming from https://github.com/jizc/CloudOnce/blob/d78b2554de713febfec0ec0e4feb51e1b2ae5f70/source/PluginDev/Assets/Extensions/CloudOnce/Internal/Editor/CloudOnceEditor.cs#L815

**Comment by stewartmiles** [comment]
Nevermind, I've see where it's calling it https://github.com/jizc/CloudOnce/blob/fef1ca6ab776a77d5e31d651ed15a8e678369b22/source/PluginDev/Assets/Extensions/CloudOnce/Internal/Editor/Utils/GooglePlayGamesSetup/GPGAndroidSetup.cs#L71

**Comment by stewartmiles** [comment]
@PixelEnvision I'm not entirely sure why this would happen with this plugin so I recommend you reach out to that plugin author to see what's up.  All I can imagine is that the Google.VersionHandler.dll is failing to bootstrap Google.VersionHandlerImpl-VERSION.dll when the plugin is imported for some reason.  You could try turning on version logging in the Version Handler settings to see whether that yields more information.

**Comment by PixelEnvision** [comment]
Resolved with Version 1.2.130
