### ISSUE TITLE
Do not explode aar for Unity >= 5.5

### ISSUE THREAD

**Issue by comtaler** [googlesamples/unity-jar-resolver#29]
Unity 5.5 is released, according to (https://forum.unity3d.com/threads/dealing-with-new-style-aars-that-have-applicationid-in-their-androidmanifest-xml.380596/), there is no need to explode aar anymore. Can we add a check for unity version and if it's >= 5.5, do not explode the aar files.

**Comment by rgngl** [comment]
The check should be for Unity version >= 5.5 and the build system is set as gradle I suppose.

**Comment by comtaler** [comment]
Yes, build system has to be set to gradle. I tried it myself and actually found there is problem building with gradle. I found 2 problems so far:
1. the gradle config file it generates contains windows directory path separator '\', and gradle build complains about it.
2. it can't find google_play_services_version and I have included proper jar file that contains the definition.

So, I guess it's better to add this as an option and allow users to choose whether to explode it or not.

**Comment by stewartmiles** [comment]
We now have an option to disable AAR explosion.  However, if the AAR requires variable expansion for the applicationId you'll end up with a non-functional build until you define the applicationId in your exported build.gradle file.  At the moment we only allow AAR explosion on Android Studio project export as that is the only way you can massage a working build out of Unity without hacking your Unity install.
