### ISSUE TITLE
Unable to commit modifications on Android Resolver Settings

### ISSUE THREAD

**Issue by nanddo** [googlesamples/unity-jar-resolver#292]
### Please fill in the following fields:
Unity editor version: 2019.2.9f1
Play Services Resolver version: 1.2.125.0
Features in Play Services Resolver in use: Android Resolver, iOS Resolver
Plugins SDK in use: Firebase 6.6.0, Facebook 
Platform you are using the Unity editor on: Mac and Windows
Platform you are targeting: Android and iOS
Scripting Runtime: IL2CPP

### Please describe the issue here:
When I change the settings on Android Resolver Settings window, the modifications don't appear on my VCS (bitbucket) to commit. I would be great if the Resolver Settings was an .asset instead of a GUI.

The specific problem I'm facing with this is that I can only make local builds. When I try to build on TeamCity, the settings are reset to default and the Use Jetfier property is by default false. I need to enable Jetfier to make the build work with Firebase.

### Please answer the following, if applicable:
What's the issue repro rate? 100%

**Comment by markchandler-google** [comment]
Hi @nanddo,

The resolver will save all its settings out to `ProjectSettings/GvhProjectSettings.xml` (note: ProjectSettings is in the same directory as the Assests folder). Please make sure you have included this file in source control and thus your team city builds should pick it up and use the same resolver settings.

Let me know if you have any more questions.

**Comment by nanddo** [comment]
Hey @markchandler-google,

Thanks for the prompt answer! We usually keep the ProjectSettings folder contents on our gitignore, this is why the TeamCity wasn't keeping the settings. After explicitly commit the `ProjectSettings/GvhProjectSettings.xml` file, it should work as expected 😊.


PS: We ended up using another solution for this:

`#if UNITY_ANDROID
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEditor.Android;
using UnityEngine;

public class AndroidPostBuildProcessor : IPostGenerateGradleAndroidProject
{
    public int callbackOrder => 999;


    void IPostGenerateGradleAndroidProject.OnPostGenerateGradleAndroidProject(string path)
    {
        string gradlePropertiesFile = path + "/gradle.properties";
        if (File.Exists(gradlePropertiesFile))  { File.Delete(gradlePropertiesFile); }
        StreamWriter writer = File.CreateText(gradlePropertiesFile);
        writer.WriteLine("org.gradle.jvmargs=-Xmx4096M");
        writer.WriteLine("android.useAndroidX=true");
        writer.WriteLine("android.enableJetifier=true");
        writer.Flush();
        writer.Close();
    }
}
#endif`
