### ISSUE TITLE
Podfile.lock and source control

### ISSUE THREAD

**Issue by polmum** [googlesamples/unity-jar-resolver#293]
I was wondering if it was ever considered to be able to check in to source control the Podfile.lock generated after the iOS Resolver runs its operations.
The problem we have today is that transitive dependecies (which don't have a fixed version in the dependencies.xml file) are always updated to the latest version after a pod install, with no way to control this, as the Podfile.lock is also regenerated after each run.

**Comment by markchandler-google** [comment]
Talking with @stewartmiles we dont know if it is safe to check the lock file in. You should refer to Cocoapods documentation for more information on this.

The iOS resolver just runs "pod install" on the generated XCode project so if Cocoapods says it safe to checkin the generated project then perhaps that's ok. It might be worth reading the docs and giving it a try and see how it works. Let us know what you find out.
