### ISSUE TITLE
DIR_UNITYPROJECT results in a Gradle error

### ISSUE THREAD

**Issue by qbit86** [googlesamples/unity-jar-resolver#294]
### Please fill in the following fields:

Unity editor version: 2018.4.10f1
Play Services Resolver version: 1.2.131
Features in Play Services Resolver in use: Android Resolver
Plugins SDK in use: Google Mobile Ads
Platform you are using the Unity editor on:  Windows
Platform you are targeting: Android
Scripting Backend: IL2CPP (Runtime: .NET 4.x Equivalent, Compat: .NET Standard 2.0)

### Please describe the issue here:

From [Changelog](https://github.com/googlesamples/unity-jar-resolver/blob/master/CHANGELOG.md):

> Android Resolver: Improved local maven repo path reference in mainTemplate.gradle using DIR_UNITYPROJECT. DIR_UNITYPROJECT by Unity to point to the local filesystem path of the Unity project when Unity generates the Gradle project.

This fragment:
```
def unityProjectPath = "file:///**DIR_UNITYPROJECT**"
```
results in a Gradle error on Windows:
```
stderr[

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Viktor\GitLab\…\Temp\gradleOut\build.gradle' line: 35

* What went wrong:
Could not compile build file 'D:\Viktor\GitLab\…\Temp\gradleOut\build.gradle'.
> startup failed:
  build file 'D:\Viktor\GitLab\…\Temp\gradleOut\build.gradle': 35: unexpected char: '\' @ line 35, column 43.
     unityProjectPath = "file:///D:\Viktor\Gi
                                   ^
  
  1 error
```

**Comment by stewartmiles** [comment]
@ipilipski-gsn it looks like https://github.com/googlesamples/unity-jar-resolver/pull/285 caused a regression.  Any chance you've seen similar behavior or know of a workaround?

It makes me wonder whether this should be yet another option (uggh) to add to the settings menu.

**Comment by qbit86** [comment]
> whether this should be yet another option

Is there a way to wrap `**DIR_UNITYPROJECT**` into some call that replaces backslashes with forward slashes for directory separators?

@stewartmiles @ianpilipski

**Comment by stewartmiles** [comment]
@qbit86 that is an excellent idea, should be fairly easy to cook up some groovy to do that.
