### ISSUE TITLE
Firebase can not find jar

### ISSUE THREAD

**Issue by phuctri9898** [googlesamples/unity-jar-resolver#295]
### Please fill in the following fields:
Unity editor version: 2017.4.27
Play Services Resolver version: 1.2.125
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.):Android Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.):Firebase, Facebook, Appsflyer
Platform you are using the Unity editor on (Mac, Windows, or Linux): Window
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
Hi!
I am using plugin version v1.2.125.0, when building android, we have the error below (similar #240 )

When going to the directory, we only have two files:
firebase-analytics-unity-6.6.0.pom
firebase-analytics-unity-6.6.0.srcaar
Please help! Thank so much!

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not find firebase-app-unity.jar (com.google.firebase:firebase-app-unity:6.6.0).
  Searched in the following locations:
      file:/D:/Project/Library/testapp/Assets/Firebase/m2repository/com/google/firebase/firebase-app-unity/6.6.0/firebase-app-unity-6.6.0.jar
> Could not find firebase-messaging-unity.jar (com.google.firebase:firebase-messaging-unity:6.6.0).
  Searched in the following locations:
      file:/D:/Project/Library/testapp/Assets/Firebase/m2repository/com/google/firebase/firebase-messaging-unity/6.6.0/firebase-messaging-unity-6.6.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
]

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by stewartmiles** [comment]
The error describes what's going on, it looks like the gradle build can't find `Assets/Firebase/m2repository/com/google/firebase/firebase-app-unity/6.6.0/firebase-app-unity-6.6.0.aar` as the Android Resolver hasn't been executed to change the `srcaar` to a `aar` file when patching `mainTemplate.gradle` see https://github.com/googlesamples/unity-jar-resolver#integrate-into-maintemplategradle

I recommend trying this out with a sample project in http://github.com/firebase/quickstart-unity to validate you can build at all then compare with your project while turning on verbose logging in the Android Resolver to see whether anything is going wrong by checking the Unity console.
