### ISSUE TITLE
Implementing Play Services Location into an Unity game

### ISSUE THREAD

**Issue by LenneRoijmans** [googlesamples/unity-jar-resolver#3]
Hey, not quite an issue bit it seems to be the best way to contact you. Do you maybe have some examples on how to use the Play Services Location(or any other *.aar package) in a custom class inside Unity?

Thanks

**Comment by claywilkinson** [comment]
Thanks for the suggestion - I don't know of any simple sample that shows how to use play services from Unity.  Maybe take a look at Admob which uses this plugin.  https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Platforms/Android/Utils.cs

I'll add it to the list to come up with a simple sample.

**Comment by LenneRoijmans** [comment]
Thanks, I'll look into it. Looking forward to an example!

**Comment by LenneRoijmans** [comment]
I've managed to add it to my Unity project, yet I'm unable to create an APK since I'm getting the following error;

`Error building Player: CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:\Program Files\Java\jdk1.7.0_80\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="D:/Programs/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[

]
stdout[
Warning: [Temp\StagingArea\AndroidManifest-main.xml:1, C:\Unity Projects\CaptoGPS\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\AndroidManifest.xml:5] Main manifest has <uses-feature android:glEsVersion='0x00010000'> but library uses glEsVersion='0x00020000'
Note: main manifest lacks a <uses-feature android:glEsVersion> declaration, and thus defaults to glEsVersion=0x00010000.
Warning: [Temp\StagingArea\AndroidManifest-main.xml:1, C:\Unity Projects\CaptoGPS\Temp\StagingArea\android-libraries\play-services-maps-8.4.0\AndroidManifest.xml:6] Main manifest has <uses-feature android:glEsVersion='0x00010000'> but library uses glEsVersion='0x00020000'
Note: main manifest lacks a <uses-feature android:glEsVersion> declaration, and thus defaults to glEsVersion=0x00010000.
]
`
I've looked around for solutions but am unable to find one that is working for me. I've added `
    <uses-feature android:glEsVersion="0x00020000"/>` to my own manifest but to no avail. Any help is mostly appreciated!

**Comment by claywilkinson** [comment]
Which  version of Unity are you using?  You may need to set the graphics API in the player settings.  so that the main AndroidManifest.xml has the correct value. In version 5.3, this is under Other Settings and check "Auto Graphics API"

**Comment by LenneRoijmans** [comment]
Thanks for the suggestion. I'm using 5.3, the option was already checked. Unchecking the option didn't affect the error.

**Comment by claywilkinson** [comment]
Hmm. Which file has the version set to 1?

**Comment by LenneRoijmans** [comment]
To be honest I've failed to find which file is causing this. The error says the main manifest lacks it, and so it defaults to glEsVersion=0x00010000. Yet I've added glEsVersion=0x00020000 to the manifest that is used to build the jar file with, but I suppose this does not count as the main manifest.

**Comment by LenneRoijmans** [comment]
Hey Clay, I created a [repository](https://github.com/LenneRoijmans/LocationTest) with my Unity project for you to check out. What confuses me is that I'm only trying to access the location via the play-services-location, yet the resolver adds a few other .aar one of which (maps) is causing the error. It might be a problem I'm overseeing or maybe these .aar files depend on each other. If there's any other info you need to help solve the problem let me know.

**Comment by claywilkinson** [comment]
The repository where the .aars are located ${ANDROID_HOME}/extras/google/m2repository.  In there there is a corresponding .pom file which has the metadata for the aar file.  In the case of play-services-location it has 3 dependencies - play-services-base, play-services-basement, and play-services-maps.

As a result those aars are copied into the project as well, (and their dependencies).

One thing you could try is to "explode" the maps aar into a directory in Assets/Plugins/Android named the same as the file without the .aar extension, then edit the AndroidManifest.xml and remove the attribute.

Another option is to export the project and compile it using Android Studio and add the overrides attributes to your AndroidManifest.xml so the conflict can be resolved. This approach is more work, but provides maximum control.
