### ISSUE TITLE
DIR_UNITYPROJECT path issue on Windows

### ISSUE THREAD

**Issue by sakiraykurt** [googlesamples/unity-jar-resolver#306]
[THIS](https://github.com/googlesamples/unity-jar-resolver/issues/294) issue still exists.

I get this error after Unity build in Android Studio.
**ERROR: startup failed:
General error during parsing: Did not find four digit hex character code.**

I can solve the error if  I change the path in gradle 
from
def unityProjectPath = $/file:///E:\FolderName\FolderName\FolderName/$.replace("\\\\", "/")
to
def unityProjectPath = $/file:///E:\\\FolderName\\\FolderName\\\FolderName/$.replace("\\\\", "/")

Unity: v2018.4.8
Play resolver: v1.2.135

**Comment by stewartmiles** [comment]
@sakiraykurt this sounds like an issue with the version of Gradle you're using in whatever Android Studio version you're using as the backslashes are encapsulated in raw Groovy strings.
https://groovy-lang.org/syntax.html#_dollar_slashy_string

**Comment by stewartmiles** [comment]
Could you share the Gradle & Android Studio version you're using that reproduces this issue?

**Comment by sakiraykurt** [comment]
Sure,
Android Studio v3.5.3
Gradle v3.5.3

**Comment by sakiraykurt** [comment]
Fixed that with Unity v2019.x.
Thanks.
