### ISSUE TITLE
Transitive Dependencies of Androidx Room are not present when building in the CI

### ISSUE THREAD

**Issue by PeterBocan** [googlesamples/unity-jar-resolver#307]
Unity editor version: 2018.3.11f1
Play Services Resolver version: ?
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Firebase, AndroidX Room.
Platform you are using the Unity editor on (Mac, Windows, or Linux): Linux and Mac 
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Mono (?)
Gradle Version: 4.6

Internally, in the company I work for, we have a Unity package that consumes Java Implementation of our Data Persistence Layer. We are using AndroidX Room, in our Unity package alongside Jar we have a Dependencies XML file which does specify the AndroidX room dependency, however, there's no mention of `androidx.paging` package being installed and/or even detected.

This is the crucial message I get from the build log from Unity:

`/root/.gradle/caches/transforms-1/files-1.1/androidx.room.room-runtime-2.2.2.aar/b59d0885714803325773e991ff3e7a6a/jars/classes.jar: D8: Type androidx.paging.PositionalDataSource was not found, it is required for default or static interface methods desugaring of boolean androidx.room.paging.LimitOffsetDataSource.isInvalid()`

This only happens in building the project in Unity in the CI (not even locally, weirdly enough), which is a Docker image.  

Issue repro rate is 100% in CI.

~Peter.

**Comment by stewartmiles** [comment]
@PeterBocan looking at the dependencies of androidx.room https://mvnrepository.com/artifact/androidx.room/room-runtime/2.2.2 (also see the POM here https://dl.google.com/dl/android/maven2/androidx/room/room-runtime/2.2.2/room-runtime-2.2.2.pom ) you're right that the package doesn't depend upon androidx.paging and yet appears to have a reference to that package baked into the library.  The Android Resolver simply downloads and integrates Android libraries with their stated dependencies (via POM files) from Maven using Gradle, this looks like a bug in the androidx.room libraries dependencies so I recommend either working around this by adding the appropriate dependencies yourself and/or reporting an issue with the AndroidX team https://source.android.com/setup/contribute/report-bugs#developer-tools
