### ISSUE TITLE
Unity Package Manager support

### ISSUE THREAD

**Issue by vzlomvl** [googlesamples/unity-jar-resolver#309]
### Please fill in the following fields:
Unity editor version: >= 2018.3
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.): All
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Firebase, Facebook, Mixpanel, Appsflyer, OneSignal
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows, Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS, Android
Scripting Runtime IL2CPP

### Please describe the issue here:
This is a feature request / suggestion for improvement / request for comments.

Summary: Starting from version 2018.3 Unity added support of git packages into the Package Manager system(https://docs.unity3d.com/Manual/upm-git.html https://unity3d.com/unity/whats-new/unity-2018.3.0). It will be great if developers will be able to integrate Play Services Resolver with Unity Package Manager.
Advantages:
1) Very fast integration and upgrade time. Just change the version in the packages.json.
2) Ability to add Play Services Resolver as a dependency in other packages.
Thanks.

**Comment by paulinon** [comment]
Thanks for your feedback @vzlomvl! I've created an internal feature request for this. With that being said, I'll keep this open.

**Comment by sp-jordi-vilalta** [comment]
Someone already created a package for it: https://openupm.com/packages/io.elhan.play-services-resolver/
Anyway it would be great to have an official package maintained by the upstream team and with proper simultaneous releases.

**Comment by stopiccot** [comment]
+1 vote for official UPM package for PlayServicesResolver

**Comment by vzlomvl** [comment]
Support of UPM was added. Thank you very much. You are the best. 👍
