### ISSUE TITLE
Unity Jar Resolver can't resolve packages on build & high resource usage

### ISSUE THREAD

**Issue by PeterBocan** [googlesamples/unity-jar-resolver#313]
Unity editor version: 2018.3.11f1
Play Services Resolver version: 1.2.132 - 1.2.135
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.):
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Firebase
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac 
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Mono

Unity Jar Resolver hangs the whole Unity on build with high CPU and/or high RAM usage (reported Unity has been oscillating between 10-30 GB of allocated memory). We do have a few libraries when merged together lists the below mentioned packages. 

When we built from CLI we have noticed that Jar Resolver tried over 20 resolutions, none of them worked. It spent the whole time (> 1 hour) in Google's gms packages, trying to resolve the issues between them.   

When we tried the listed packages in Gradle (Android Studio test project) everything was working.

```
com.google.firebase:firebase-common:19.3.0
com.google.firebase:firebase-analytics:17.2.1
com.google.firebase:firebase-app-unity:6.9.0
com.crashlytics.sdk.android:crashlytics:2.9.9
com.google.firebase:firebase-crashlytics-unity:6.9.0
androidx.appcompat:appcompat:1.1.0
androidx.constraintlayout:constraintlayout:1.1.3
androidx.room:room-runtime:2.0.0
androidx.paging:paging-runtime:2.0.0
com.polidea.rxandroidble2:rxandroidble:1.10.3
com.polidea.rxandroidble2:mockclient:1.10.4
com.google.protobuf:protobuf-lite:3.0.0
```

Rate:  100%

**Comment by paulinon** [comment]
Hi @PeterBocan sorry to hear about this issue. Could you try using the latest version of Unity and see if the issue persists? If so, please send a [runnable example](https://stackoverflow.com/help/minimal-reproducible-example) (if applicable) as well as steps in reproducing this. Thanks.

**Comment by PeterBocan** [comment]
If I recall correctly we tried to use 2019.2 version as well, but that didn't help (we thought that the issue could've been caused by the resolution in the UPM import). As far as "runnable example", I can only give you a description at the moment (not sure when I get back with the example). 

We have a UPM package, that does have the following dependencies:

```
androidx.appcompat:appcompat:1.1.0
androidx.constraintlayout:constraintlayout:1.1.3
androidx.room:room-runtime:2.0.0
androidx.paging:paging-runtime:2.0.0
com.polidea.rxandroidble2:rxandroidble:1.10.3
com.polidea.rxandroidble2:mockclient:1.10.4
com.google.protobuf:protobuf-lite:3.0.0
```

and alongside the project, we import the Firebase SDK, which we use for Crashlytics.

**Comment by paulinon** [comment]
Hi @PeterBocan It appears that you've specified a set of incompatible packages and the resolver is attempting to find the closest set of compatible packages that will work instead. Here's the [script](https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/scripts/download_artifacts.gradle ) used by the resolver to figure out what will work and what won't.

I recommend you try the following:
- Turn on verbose logging in the Android Resolver settings menu which will log all of the actions the download_artifacts script is taking and the conflicting packages, this could allow you to figure out what is causing the slow down.
- After resolution is complete, the resolver will tell you what changes were applied to make things kinda work, you can try and apply these version changes back to the configuration so that it doesn't have to search again.
- Try running download_artifacts and debug.

**Comment by PeterBocan** [comment]
Hi @paulinon thanks for that script, how am I suppose to use it? 

 - the nature of the problem is just the non-deterministic nature of the beast somewhere in the algorithm. It causes it to go for too long, and I have no patience to wait a day to resolve the issue (if ever, as I have "only" 16 GB RAM). Without the Firebase SDK, it takes around 5-10 minutes of resolution to resolve other libraries, and I think that grows exponentially with Firebase, as, by the logs I am judging that Firebase SDK is a dependency nightmare. 
 - funny byproduct of killing Unity, if you time it correctly, the libraries are present in the Plugins/Android folder.  
- if I may suggest a feature - set max time for resolution and kill it if it goes over some hard limit. 
- I am able to resolve the given list of packages WITHOUT Firebase SDK:
```
androidx.appcompat:appcompat:1.1.0
androidx.constraintlayout:constraintlayout:1.1.3
androidx.room:room-runtime:2.0.0
androidx.paging:paging-runtime:2.0.0
com.polidea.rxandroidble2:rxandroidble:1.10.3
com.polidea.rxandroidble2:mockclient:1.10.4
com.google.protobuf:protobuf-lite:3.0.0
```
 - I don't know if the following resolution log is okay for you. Yes, the verbose and full build log version of it is 130MB, after around 10 minutes of resolution. 
[resolution-whole.log](https://github.com/googlesamples/unity-jar-resolver/files/4128635/resolution-whole.log)
 - Maybe I should file a bug at Firebase team?

**Comment by paulinon** [comment]
Hi @PeterBocan, I noticed that you have a protobuf-lite in your list of dependencies. Could you try sharing a runnable example that contains at least the protobuf-lite dependency and the Firebase SDK? This could be related to an [ongoing issue](https://github.com/firebase/firebase-android-sdk/issues/1152).

**Comment by PeterBocan** [comment]
I might get back with the Unity example on Sunday, I will try to mimic the issue on my own computer.

**Comment by PeterBocan** [comment]
I will get to it in my spare time. 

We have decided to sidestep this issue in the company, so this is basically me, doing it on my spare time.
