### ISSUE TITLE
Failed to determine the most recently installed Android SDK version

### ISSUE THREAD

**Issue by umerasghar** [googlesamples/unity-jar-resolver#314]
i am having this issue on Unity 2019.2.4f1, i already have android 28 installed and my target api level is set to highest installed

**Comment by paulinon** [comment]
Hi @umerasghar Could you try to provide screenshots of logs that show this issue as well as steps to reproduce this?

**Comment by sskenth** [comment]
Just installed Firebase SDK. The version I have on Android is the version Unity installs itself. Unity version 2019.3.0.5f

<img width="1637" alt="Screenshot 2020-01-25 at 02 20 16" src="https://user-images.githubusercontent.com/1942693/73115065-3c806080-3f19-11ea-95b3-41f0217d1f50.png">

**Comment by umerasghar** [comment]
@paulinon thanks for the reply but i already solved it. i just change the android sdk path...it turn out  that my android sdk path was set to android unity path, so i uncheck the box and define my own sdk path

**Comment by umerasghar** [comment]
Solved!
