### ISSUE TITLE
Freeze after enter in play mode

### ISSUE THREAD

**Issue by mouurusai** [googlesamples/unity-jar-resolver#316]
### Please fill in the following fields:
Unity editor version: 2019.2.17f1
Play Services Resolver version: 1.2.135.0
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.):Android Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.):Firebase, Facebook,Twitter, GoogleSignIn 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Mono

### Please describe the issue here:
Open included project, than open the "test" scene,  activate play mode. Editor froze for from 5 to 20 seconds before you can see a cube on scene start to spin.

Screenshots from profiler:
![1](https://user-images.githubusercontent.com/13837158/73092921-8f90ee00-3eee-11ea-8c58-ce705955bfe3.png)
![2](https://user-images.githubusercontent.com/13837158/73092924-8f90ee00-3eee-11ea-8be1-b9c5ab24c97d.png)

Test project:
https://drive.google.com/file/d/1DhuyNRKfCcMlwfF1WI8-IYj3J6XEuMQy/view?usp=sharing

### Please answer the following, if applicable:
100%

**Comment by paulinon** [comment]
Thanks for reporting this, @mouurusai. I've used your test project, and it only takes around three seconds on my end for the cube to start spinning. Could you share your logs by turning on verbose logging in the Android Resolver settings? This could allow them to figure out what is causing the slow down. Thanks

**Comment by mouurusai** [comment]
paulina, thanks sure I send log. But profiler says it's about "XcodeProjectPatcher" not android, so I enable verbose logging for IOS.
[IOSLog.txt](https://github.com/googlesamples/unity-jar-resolver/files/4123950/IOSLog.txt)
Is exist any method to disable IOSResolver, because I don't need IOS platform?

**Comment by paulinon** [comment]
Hi @mouurusai, you can disable the iOS Resolver in the settings menu. Know that this will break iOS builds unless a developer integrates Cocoapods manually if you choose to build for iOS

**Comment by mouurusai** [comment]
> disable the iOS Resolver in the settings menu
I can’t find the settings to disable IOS resolving. Can you give me more exact directions?
Is there any additional information I have to provide?

**Comment by paulinon** [comment]
Hi @mouurusai, if you turn off Podfile generation and Podfile integration, it should do nothing.

**Comment by mouurusai** [comment]
Same result.
![Settings](https://user-images.githubusercontent.com/13837158/74040375-ab0ef500-49d4-11ea-969b-12cd60a6013b.png)

**Comment by paulinon** [comment]
Hi @mouurusai. Unity version 2019.3 introduced a feature that lets you configure your play mode as seen on this [blog post](https://blogs.unity3d.com/2019/11/05/enter-play-mode-faster-in-unity-2019-3/). Could you try updating your Unity editor and see if it still freezes for too long?
