### ISSUE TITLE
Play Services Resolver replaces third-party dependencies with incorrect (max) version

### ISSUE THREAD

**Issue by ybereza** [googlesamples/unity-jar-resolver#317]
### Please fill in the following fields:
Unity editor version: 2019.2.19f1
Play Services Resolver version: 1.2.133.0
Features in Play Services Resolver in use: Android Resolver
Plugins SDK in use: Firebase
Platform you are using the Unity editor on: Mac
Platform you are targeting: Android
Scripting Runtime: IL2CPP

### Please describe the issue here:
We have our own dependencies xml file (MRGSDependencies.xml) for third-party library MyTracker.

Content of file is:
```
<dependencies>
	<androidPackages>
		<androidPackage spec="com.my.tracker:mytracker-sdk:1.5.12"/>
	</androidPackages>
</dependencies>
```
After importing latest Firebase Unity package with GPSR 1.2.133.0 we have found such messages in logs:

```
Modified artifacts:
com.google.firebase:firebase-analytics:17.2.1 --> com.google.firebase:firebase-analytics:+
com.google.firebase:firebase-common:19.3.0 --> com.google.firebase:firebase-common:+
com.google.firebase:firebase-messaging:20.1.0 --> com.google.firebase:firebase-messaging:+
com.my.tracker:mytracker-sdk:1.5.12 --> com.my.tracker:mytracker-sdk:+
```

After resolving dependencies we've got com.my.tracker:mytracker-sdk:2.0.0 in our project and this breaks our build, because we have not adapted our application for 2.0.0 API changes.

It looks like a critical bug for us. Replacing concrete library version with a "+" sign (any new version) is not a good idea at all. 

### Please answer the following, if applicable:
100%

**Comment by paulinon** [comment]
Thanks for reporting the issue @ybereza Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project as well as steps to reproduce this issue so I could isolate the cause of this? Thanks.

**Comment by ybereza** [comment]
Hi! https://github.com/ybereza/GoogleResolverTest Here is an empty project with imported Firebase and removed  Assets/Firebase/Plugins/x86_64/FirebaseCppApp-6_9_0.so just because it 's too big and exeeds GitHub file size limit (FirebaseMessaging.unitypackage version Version 6.9.0 - December 27, 2019 to be clear).
Also this project contains our GPSR dependencies xml file, located in Assets/Plugins/Editor/MRGS/MRGServiceDependencies.xml

Just open project in Unity (we have used 2019.2.19f1), choose File -> Build Setting -> Switch platform to Android. After resolving dependencies there will be Assets/Plugins/Android/com.my.tracker.mytracker-sdk-2.0.0.aar file, but MRGServiceDependencies.xml contains
```
<dependencies>
	<androidPackages>
		<androidPackage spec="com.my.tracker:mytracker-sdk:1.5.12"/>
	</androidPackages>
</dependencies>
```
I've also added another sample project https://github.com/ybereza/ResolverWithoutFirebase. It contains the same Assets/Plugins/Editor/MRGS/MRGServiceDependencies.xml file but without Firebase plugin and with GooglePlayServicesResolver 1.2.129
You can try to open this project, select File -> Build Settings -> Switch platform to Android and than you can find Assets/Plugins/Android/com.my.tracker.mytracker-sdk-1.5.12.aar file

**Comment by paulinon** [comment]
Thanks for providing more information, @ybereza. This issue also occurs on my end. I've filed an internal bug for this. I can't provide any timelines for the fix, so I'll leave this open for now.

**Comment by paulinon** [comment]
Hi @ybereza, it turns out that this behavior involving the resolver is intended. The resolver loosens the versions of specified dependencies if it find conflicts. In this case it looks like com.my.tracker:mytracker-sdk:1.5.12 has dependencies that conflict with other specified dependencies. 

I suggest you turn on verbose logging in the resolver which will print out the libraries in the dependency tree that conflict. You can then change the libraries in a way that is said to work together.

**Comment by ybereza** [comment]
Hi!
We have checked build with old version of GPRS but with new version of Google Firebase. The same issue occurs. You're right - com.my.tracker:mytracker-sdk:1.5.12 depends on 'com.google.android.gms:play-services-ads-identifier:15.0.1' which depends on play-services-basement [15.0.1,16.0.0). But Google Firebase depends on play-services-basement 17.x version which is not compatible with 15.x-16.x versions. So GPSR tries to resolve a newer version of com.my.tracker:mytracker which is 2.0.0 (at this time already 2.0.1). But com.my.tracker:mytracker-sdk:2.0.0 also depends on 'com.google.android.gms:play-services-ads-identifier:15.0.1'. Are you sure that this resolving is correct? To my option GPSR must hangs with error something like - 'Incompatible dependencies error' or something like this.

You may find maven pom files for mytracker 2.0.0 in bintray to check dependencies:
https://bintray.com/mytracker/maven/mytracker-sdk/view#files/com%2Fmy%2Ftracker%2Fmytracker-sdk%2F2.0.0

and mytracker 1.5.12 is:
https://bintray.com/mytracker/maven/mytracker-sdk/view#files/com%2Fmy%2Ftracker%2Fmytracker-sdk%2F1.5.12

**Comment by paulinon** [comment]
Sorry for the late reply. Yes, the behavior is correct. If you want to force the selection of dependencies, you should use a hard version.
