### ISSUE TITLE
PlayServiceResolver makes Unity editor freeze 30s for entering Play mode or user script recompilation

### ISSUE THREAD

**Issue by KichangKim** [googlesamples/unity-jar-resolver#318]
### Please fill in the following fields:
Unity editor version: 2019.3.0f6
Play Services Resolver version: 1.2.130.0
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.): all
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Firebase
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows and Mac
Platform you are targeting (iOS, Android, and/or desktop): Android and iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
When I entering Play mode or changing script, PlayServicesResolver makes editor freezing 30s.

Here is Deep profiling log of editor:
<img width="1332" alt="Screen Shot 2020-01-30 at 12 36 29" src="https://user-images.githubusercontent.com/2926674/73417972-4660f400-435d-11ea-9040-3ec4bcf020cc.png">

It doesn't occurred in 2019.2.x. And disabling all resolvers in its setting windows doesn't help.

### Please answer the following, if applicable:
What's the issue repro rate? 100%

**Comment by paulinon** [comment]
Thanks for reporting this issue, @KichangKim. Could you try using an updated version of the resolver and see if the issue persists? If it does, please send a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so I can identify what's causing the issue.

**Comment by KichangKim** [comment]
@paulinon After further investigation, I figured out that AssetDatabase.FindAssets() with label filter makes this issue (it is used in VersionHandlerImpl). It seems that Unity's bug, so I reported it to Unity.

https://issuetracker.unity3d.com/issues/asset-pipeline-v2-assetdatabase-dot-findassets-with-label-filtering-is-significantly-slower-when-using-asset-pipeline-v2
