### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by derwaldgeist** [googlesamples/unity-jar-resolver#319]
### Please fill in the following fields:
Unity editor version: 2018.4.15f1
Play Services Resolver version: 1.2.129.0
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Unsure
Plugins SDK in use (Firebase, Admob, Facebook, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): macOS Catalina
Platform you are targeting (iOS, Android, and/or desktop): Android (and iOS)
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:

We are trying to setup the UT Notifications package to receive push notifications. This asset uses the Play Services Resolver to resolve Android dependencies. When we first started Unity after installing the package, we got a message if we wanted to enable the resolver. After accepting this, a window popped up, but showed an error message quickly before it closed again.

In the Unity logs, I found an error log refering to an illegal reflective access operation. I attached the logs to this issue. Since I am new to this whole resolver thing, I have no clue what to do now. Thanks for your support.

[error.log](https://github.com/googlesamples/unity-jar-resolver/files/4139511/error.log)

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc): 100%

**Comment by derwaldgeist** [comment]
I was able to workaround this by downgrading JRE from 13 to 11. I think it should be mentioned somehow that Java 13 is not compatible; at least on macOS.

**Comment by derwaldgeist** [comment]
Just some update: The core reason seems to be that this package is using Gradle 5.x, which is not compatible to Java 13. Could this be updated to Gradle 6.x?

**Comment by paulinon** [comment]
Hi @derwaldgeist, I noticed that you used an old version of the resolver. Could you try updating your Play Services Resolver as well as your Unity Editor and see if the issue persists? Thanks

**Comment by derwaldgeist** [comment]
Thanks for the fast response. I've imported this as part of the UT Notifications plugin, which includes the resolver. So I'm unsure if I can just update this myself?

**Comment by paulinon** [comment]
Hi @derwaldgeist. You can simply download a zip of this repo then import the .unitypackage file found inside. Afterwards, simply delete the obsolete files. If the issue still persists, could you share a [runnable, example](https://stackoverflow.com/help/minimal-reproducible-example) of your project? Thanks
