### ISSUE TITLE
Released DLLs file names should only change with major versions

### ISSUE THREAD

**Issue by jkasten2** [googlesamples/unity-jar-resolver#32]
File names of released DLLs change with each version which creates `defined multiple times` errors when app developers add more than one Unity plugin that includes different versions of this library.

I suggest the release `.unitypackage` contain `v1` instead of `v1.2.9.0` as part of their containing file names. Example, change `Google.JarResolver_v1.2.9.0.dll` to `Google.JarResolver_v1.dll`.

**Comment by voxelbusters** [comment]
I second that. Its good if the new version overrides existing files rather than giving duplicate class errors.

**Comment by stewartmiles** [comment]
When the Google.*.dlls are imported they should disabled by default.  The Google.VersionHandler plugin enables / disables versions when DLLs are imported.  We do this as common components that are shared across multiple Unity plugins allow us to select the latest version.

It's possible we have a regression in this behavior, what errors are you seeing?

**Comment by jkasten2** [comment]
@stewartmiles The issue is reproducible with the following steps.
(This is going from version 1.2.6.0 to 1.2.9.0)
1. Create a new Unity 5.5 project.
2. Import [googleads-mobile-unity v3.1.3](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.1.3)
3. Import [play-services-resolver-1.2.9.0.unitypackage](https://github.com/googlesamples/unity-jar-resolver/blob/b7a90e43d6c893622102ca53681f53a58dab1a24/play-services-resolver-1.2.9.0.unitypackage) from this repo.
4. Error will show up in the Console and can no longer build the project.
5. However it does resolve the issue after reopening Unity.
   - The old 1.2.6.0 files seem to be removed

I mistakenly thought the [play-services-resolver-1.2.9.0.unitypackage](https://github.com/googlesamples/unity-jar-resolver/blob/b7a90e43d6c893622102ca53681f53a58dab1a24/play-services-resolver-1.2.9.0.unitypackage) contained version numbered DLL names but I extracted it again to double check and they don't. I believe I was originally looking at [this folder exploded folder](https://github.com/googlesamples/unity-jar-resolver/tree/b7a90e43d6c893622102ca53681f53a58dab1a24/exploded/Assets/PlayServicesResolver/Editor).

I am guessing since Unity loaded the old 1.2.6.0 DLLs you can't clean them up due to a lock which is why a restart is needed.

Anyway I am guessing you moving forward with no version number on the DLLs in the containing .unitypackage? As this is what is in the latest 1.2.9.0.

**Comment by stewartmiles** [comment]
This definitely sounds like a regression, we should have version numbered
DLLs in the Play Services Resolver package.  We'll take a look.

**Comment by stewartmiles** [comment]
I took a look at this and we do ship packages with version numbered DLLs.  You'll get an error importing the Play Services Resolver when importing multiple revisions, you then need to delete the oldest VersionHandler.dll (see the asset label for the version).

**Comment by jkasten2** [comment]
@stewartmiles Thanks for confirming, the dll renaming when Unity is importing them was throwing me off.
