### ISSUE TITLE
Target API Level 29 Incompatibility

### ISSUE THREAD

**Issue by The3Designer** [googlesamples/unity-jar-resolver#322]
### Please fill in the following fields:
Unity editor version: 2019.3.0f6
Play Services Resolver version: 1.2.135
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.):
Android Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 10
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
When I set my Target API Level to 29 (for Android 10 support), I get the following error message:
![](https://user-images.githubusercontent.com/59917065/74333216-6c3fbd00-4d8f-11ea-9063-326b797544fd.png)

After setting the Target API to 29, pushing the "Resolve" or "Force Resolve" under the Android Resolver menu does nothing at all, whereas I'll get a "success" message on API Level 28. When changing the Target API to 28, there's no problem.

I'm using the NDK and SDK that come installed with Unity.

### Please answer the following, if applicable:
Repro rate 100%, happens every time I switch the Target API to 29 (which is what I want for Android 10 support).

**Comment by paulinon** [comment]
Thanks for reporting the issue, @The3Designer. Here are something I'd like you to try (ensure that you have a backup copy of your project):

1. In your Unity project, delete your Library folder (leaving behind Assets, Packages, and ProjectSettings)
2. Delete the PlayServicesResolver in your Assets folder
3. Switch your platform to anything, and else then to android
4. Import the resolver

**Comment by The3Designer** [comment]
@paulinon Thanks for the suggestion! Sadly enough, it didn't work. Here's what I did:

1. Closed Unity and Unity Hub
2. Made a backup of my project file in Windows Explorer
3. In Windows Explorer, removed the entire Library folder of the project
4. In Windows Explorer, removed the PlayServicesResolver folder (in the Assets folder) of the project
5. Started Unity Hub and opened my project file. This step takes a while, I assume because the Library folder had to be recreated. Also, when the project did load, the platform was no longer Android.
6. When the project was launched, it was already set to a different platform (PC, Mac & Linux Standalone). Thus no need for me to switch it.
7. Imported the resolver package
8. Switched my platform to Android. This step took some time too, but that's normal for as far as I know. Once the platform was switched, the Target API Level was automatically set to 28.
9. Set the Target API Level to 29 in the project settings
10. Clicked on Android Resolver --> Resolve. This resulted in this error:
`NullReferenceException: Object reference not set to an instance of an object`
11. Clicked on Android Resolver --> Force Resolve. This had no result.
12. Tried to run the game, which gave me the error I showed in my opening post.
13. Tried to build the game with Target API Level still set to 29, which resulted in Unity freezing at the "Building scene 0: mainLevel" phase (after checking NDK and SDK).

Hope this helps with finding and fixing the issue.

**Comment by paulinon** [comment]
Could you please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so I can try to identify the issue on my end?

**Comment by The3Designer** [comment]
Sure, I have a project with the base Universal Render Pipeline template and the Google Ads plugin, which has the same issue I'm facing in my actual project. I've zipped the project (and the Ads package I've imported in it) and uploaded it to my Google Drive: https://drive.google.com/file/d/19v5799oUxtS3yQ-cbJ0gmezA3_W6RTXv/view?usp=sharing

Can you let me know if it downloads correctly?

**Comment by paulinon** [comment]
Hi @The3Designer, I was able to reproduce the issue you're facing with the repro you sent. I've filed an internal bug report for this (b/149680566). I can't give you any timelines for the fix, so I'll leave this open.

**Comment by dersnek** [comment]
I'm also facing this bug. I've been able to build before, but at some point started to get this same error. Tried deleting/reinstalling plugin, didn't help. Trying to build with target API set to 29 results in Unity freezing on `Building scene 0`

**Comment by dersnek** [comment]
@The3Designer @paulinon Seems like I've found a way to create a build for Android and target API 29. Here's what I did:

1. Switched my Target API in Unity to 28
2. Restarted Unity
3. Went to Assets -> Play Services Resolver -> Android Resolver -> Resolve (got a message that it resolved successfully)
4. Switched my Target API in Unity back to 29
5. Build

It threw the same error right after it finished building, but it still went successfully and GP Console detects target SDK as 29, everything seem to work properly.

Now if I restart Unity again, I get the same error and to build again, I have to go through same steps.

**Comment by The3Designer** [comment]
@paulinon Thank you for filing the bug!
@dersnek Thanks for the guide, I'll try it on the next build 👍

**Comment by paulinon** [comment]
Hi @The3Designer. There's a new version of the resolver. With it, I've used your project and did @dersnek's steps on my end, and Unity no longer freezes on `Building scene 0`. Could you try the guide above and see if you're still facing the issue? Thanks.

**Comment by The3Designer** [comment]
It works! I manually imported the new package (by downloading it from GitHub) into my project. It automatically offered to remove the deprecated old plugin version files. After doing this, I simply set the target API to level 29 and let Unity build the game. There was no freezing, no error, and I didn't even have to follow @dersnek his steps.

Thanks again for the bug report @paulinon !

**Comment by The3Designer** [comment]
Okay, partially disregard my previous comment. I was able to build my project with target api level set to 29 with the new resolver version. However, upon reopening the project, I got the same error as in my first comment. Next time I'm building the game, I'll try to do @dersnek his suggested steps...

**Comment by SimasZ** [comment]
I also had this issue recently with v1.2.136 and the above solution did not work although I was able to build for android before reopening the project.

**Comment by The3Designer** [comment]
I have just build my project with the updated resolver using @dersnek his steps:
>     1. Switched my Target API in Unity to 28
>     2. Restarted Unity
>     3. Went to Assets -> Play Services Resolver -> Android Resolver -> Resolve (got a message that it resolved successfully)
>     4. Switched my Target API in Unity back to 29
>     5. Build

So even though I am able to build my app with the API level set to 29, this method is still a workaround to a problem in the resolver. Therefore, is it wise to keep this issue open?

**Comment by paulinon** [comment]
Glad that you found a workaround. I'll be closing this for now. In the event that you encounter an issue with your workaround, feel free to reopen the issue so that this could be investigated further.
