### ISSUE TITLE
As of Unity 2018, resolver can't find XML dependencies in Plugins folder

### ISSUE THREAD

**Issue by toxikman** [googlesamples/unity-jar-resolver#324]
Unity editor version: 2018.4.16f1
Play Services Resolver version: 1.2.135.0
Features in Play Services Resolver in use: Android Resolver
Plugins SDK in use: Facebook, AdMob, AppsFlyer
Platform you are using the Unity editor on: Mac
Platform you are targeting: Android
Scripting Runtime: IL2CPP
What's the issue repro rate? 100%

Problem Description:
In Unity 2017 and earlier, when you place a Dependencies.xml file in a folder such as Plugins/MyPlugin/, the resolver would find those dependencies and add them to gradle build. However, in Unity 2018.1, Unity changed it so that Plugins are no longer read as assets, so the code in GooglePlayServices.XmlDependencies.FindFiles() no longer works because it's looking for TextAssets with "Dependencies" in the name. This code needs to be changed to recursively search for files named *Dependencies*.xml in these paths.

More information [here](https://docs.unity3d.com/Manual/UpgradeGuide20181.html). Scroll down to _"Assets located in plugin folders will no longer be imported via specialized importers."_

**Comment by paulinon** [comment]
Thanks for reporting this, @toxikman. I've created an internal feature request for this (b/149833504). I can't give any timelines for this request to be processed, so I'll leave this open for now.

**Comment by chkuang-g** [comment]
@toxikman 

According to the code, it not only looking for a TextAsset with "Dependencies" in it, but also expect the file to be under `Editor` folder.  See the regex here
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/AndroidResolver/src/XmlDependencies.cs#L36

Could this be the issue?

The [readme](https://github.com/googlesamples/unity-jar-resolver#android-resolver-usage) did pointed out that it need to be under `Editor` folder.

**Comment by toxikman** [comment]
> According to the code, it not only looking for a TextAsset with "Dependencies" in it, but also expect the file to be under `Editor` folder. See the regex here
> https://github.com/googlesamples/unity-jar-resolver/blob/master/source/AndroidResolver/src/XmlDependencies.cs#L36
> Could this be the issue?
This is not the problem and the dependencies file **_is_** in an Editor folder. The issue is with the way that the resolver enumerates assets. It does not find them in the Plugins folder after Unity 2018.1  Unity no longer registers TextAssets in the AssetDatabase when they are inside the Plugins folder. This is a documented change that Unity made in the 2018.1 release. Please read my original post where I link to information about this change.

**Comment by toxikman** [comment]
It looks like the link I provided has moved. Here's the new one:
https://docs.unity3d.com/2018.1/Documentation/Manual/UpgradeGuide20181.html
See "Assets located in plugin folders will no longer be imported via specialized importers"

**Comment by chkuang-g** [comment]
I see.

Based on the description, this seems to only affect files under "`directories with the extension .bundle, .plugin, or .folder`".  Does this affect folders like `Assets/Plugins/MyPlugin/Editor/MyDependencies.xml`?

I actually tried this with Unity 2018.4.22f1 with `Assets/Plugins/MyPlugin/Editor/MyDependencies.xml` and seems like EDM4U can find this xml with no problem.

Could you give us an example project, or problematic plugins, when this happened?

Thank you,
Shawn
