### ISSUE TITLE
There's just absolutely too much spam from the resolver.

### ISSUE THREAD

**Issue by JonathanDotCel** [googlesamples/unity-jar-resolver#327]
### Please fill in the following fields:
Versions: 
Any

Services/Features:
Android Resolver, VersionHandler, Firebase, IAB, AdMob, some mediation

Platforms:
Win10, for Android, runtime irrelevant

### Please describe the issue here:
-Build a script.
-20-30 console log messages from the resolver.

- Incredibly counter productive
- adds no value unless you're already looking for issues
( in which case a separate log window or switch would do the job )
- i don't even need it to check *every time* I update a script, let alone tell me about it 20-30 times depending on the project.

### Please answer the following, if applicable:
100%

Not asking for a lot, just something like this in impl

internal static void Log(string message, bool verbose = false, LogLevel level = LogLevel.Info)
{
	if ( level == LogLevel.Info && userWantsSomePeaceFromTheEndlessSpam )
	{
		return;
	}
	VersionHandlerImpl.logger.Log(message, (!verbose) ? level : LogLevel.Verbose);
}

### Suggestion:
- switch to shut it up
- switch to delay checking until you force another resolve, or build
(99% of my time is not spent worrying if the plugins have changed after each variable name tweak)

Cheers =)

P.s. not trying to be a negative nancy; the resolver has come leaps and bounds in the last year or so - it's getting better to work with all the time!

**Comment by MartinGonzalez** [comment]
Yes! Totally agree. I created a similar issue here: https://github.com/googlesamples/unity-jar-resolver/issues/326

Plugins in general should avoid InitializeOnLoad that make our recompilation time grow

**Comment by JonathanDotCel** [comment]
Ah, no, I searched and that didn't come up - didn't mean to dupe!

Yeah, just in terms of pure cost/value
cost: obscures legitimate, useful information, adds extra time.
value: none
(unless you're looking for it).

**Comment by MartinGonzalez** [comment]
No prob at all! I will close the other one and just merge it with this! Its really important that the plugin should turn off this stuff

**Comment by paulinon** [comment]
Thank you all for your inputs. I've filed a request to add a feature that optimizes the resolver's performance (b/150194381). I'm not able to provide any timelines for the fix, so I'll leave this open.

**Comment by paulinon** [comment]
Hello again. I received word that you can try turning off [auto resolution](https://github.com/googlesamples/unity-jar-resolver#auto-resolution) to optimize resolver's recompile time.

**Comment by MartinGonzalez** [comment]
@paulinon Thanks for that but is not what we mean.
The auto resolution is the try resolve every time we add a new XXXDependencies.xml but what we mean with the recompile time is with this stuff.

![image](https://user-images.githubusercontent.com/4130008/75340760-d36e6e80-5871-11ea-8432-bec54f9ac2fd.png)

Every recompile is doing that process, is it necessary? Can be done just once or on build time only? Or some MenuItem we need to select to run that?

If every plugin adds processes when recompile the project takes seconds-minutes to recompile and it's really REALLY annoying for development flow.

I don't know if @JonathanDotCel agrees with me.

**Comment by JonathanDotCel** [comment]
> @paulinon Thanks for that but is not what we mean.
> The auto resolution try to resolve every time we add a new XXXDependencies.xml but what we mean with the recompile time is with this stuff.
> 
> ![image](https://user-images.githubusercontent.com/4130008/75340760-d36e6e80-5871-11ea-8432-bec54f9ac2fd.png)
> 
> Every recompile is doing that process, is it necessary? Can be done just once or on build time only? Or some MenuItem we need to select to run that?
> 
> If every plugin adds processes when recompile the project takes seconds-minutes to recompile and it's really REALLY annoying for development flow.
> 
> I don't know if @JonathanDotCel agrees with me.

Yeah, similar issue.
I change *one* line in a script, re-focus the Unity window aaaand:

![Unity_2020-02-26_11-39-49](https://user-images.githubusercontent.com/61208676/75341670-d2970600-588c-11ea-8191-8ffcafd354bd.png)

I get 15 of these from Firebase and the same again from admob, etc.
(Can't screenie the other messages atm, I silenced the Log() function with dnSpy)

Then when I hit play... bam another 10-15 "Dummy!" messages from the admob scripts with no option to turn them off. Just trampling all over important messages.

When I build, same thing as above... constant spam.
You can turn off resolve-on-build, sure, but certain build configuration changes (mono to il2cpp and back) seem to reset the settings, and it does randomly re-enable itsself.

In the past I've found myself resolving then completely removing the plugin for a bit of sanity, but I don't want to risk it with production code.

**Comment by stewartmiles** [comment]
Hey everyone, have you tried to disable verbose logging in each component of the plugin?

All logs typically go through:
https://github.com/googlesamples/unity-jar-resolver/blob/ef792db218af69c6fbda967bee0ead37cd79df7e/source/VersionHandlerImpl/src/Logger.cs#L109

Each component has a logger with log level that is configured via the settings menus.  i.e via

```
Assets > Play Services Resolver > Android Resolver > Settings > Verbose Logging
Assets > Play Services Resolver > iOS Resolver > Settings > Verbose Logging
Assets > Play Services Resolver > Version Handler > Settings > Verbose Logging
```

To store to system-wide settings uncheck "Use project settings", to store changes in just the project check "Use project settings".

**Comment by MartinGonzalez** [comment]
Unchecking Verbose logging log this

![image](https://user-images.githubusercontent.com/4130008/75376324-a0969b80-58ae-11ea-9f6f-76513d69f85a.png)

My question is does the plugin need to run that every time we recompile?

**Comment by stewartmiles** [comment]
@MartinGonzalez that log isn't coming from this plugin, that's coming from the Firebase Unity SDK and those logs - which were left lover from debugging - were removed in [6.11.0](https://firebase.google.com/support/release-notes/unity#version_6110_-_february_20_2020) AFAIK.

Regarding whether it needs to run every time, it needs to at least make sure that the configuration files in the project are in sync with the generated Android resources.  The team is actively working on better configuration in the Firebase Unity SDK that would allow you to disable various build and configuration steps so perhaps this could be something that could be disabled and run manually or only at build time if you're not changing configuration.  @chkuang-g FYI

**Comment by MartinGonzalez** [comment]
@stewartmiles that sounds promising! Any ETA?

**Comment by stewartmiles** [comment]
It's a couple of months away, @chkuang-g is working on it.  For the moment I recommend upgrading to 6.11.0 which should; at least make the log spam go away.

**Comment by JonathanDotCel** [comment]
Sounds good!
Was just hoping for something like this (minimum log level).

![image](https://user-images.githubusercontent.com/61208676/75393752-af00a980-58e6-11ea-9bb8-34c21f59474e.png)

Cheers!

**Comment by stewartmiles** [comment]
@JonathanDotCel could you describe what logs you're seeing that you think are too spammy?

Feel free to send a pull request to change the log level of some of these.

**Comment by JonathanDotCel** [comment]
> @JonathanDotCel could you describe what logs you're seeing that you think are too spammy?
> 
> Feel free to send a pull request to change the log level of some of these.

Sure thing,
here's one project in Unity2018.4 using resolver 1.2.136

After changing a single byte in a single source file:

3+ seconds extra lag / build time
26 items in the console..

![image](https://user-images.githubusercontent.com/61208676/76095678-97977f80-5fbc-11ea-9999-8477a2b90010.png)

If I was to hit play (Clear On Play), then edit a line of code, as this causes things to stack, it looks like this:

![image](https://user-images.githubusercontent.com/61208676/76095823-daf1ee00-5fbc-11ea-9cd3-7f8141930ffc.png)

On top of extending build time.

About 52 in all, + another 6 from Admob's own spammy "Dummy .ctor", "Dummy Initialize" functions, etc.

Another project,
Unity 2019.2, Resolver  1.2.135

![image](https://user-images.githubusercontent.com/61208676/76096238-a92d5700-5fbd-11ea-9c55-157c3f89d364.png)

21 items per build and per play.

It really is a bit much!

I considered changing it, but Firebase extends the logger rather than calling it. I'm also not sure how many other plugins extend the logger and how much stuff would break. Any ideas?

**Comment by stewartmiles** [comment]
@JonathanDotCel each component of the plugin has a separate verbose logging option, the logs in your screenshots come from the Version Handler but the settings you're showing are in the Android Resolver component, if you turn off the Version Handler verbose logging what does it look like?

w.r.t logging in general, verbose logs are extremely useful to us when debugging issues with developer's builds that usually come with very vague bug descriptions.  e.g in this bug report I was able to glance at the logs and tell you what is likely going wrong in your project.

**Comment by JonathanDotCel** [comment]
> @JonathanDotCel each component of the plugin has a separate verbose

Facepalm.
I didn't spot that the plugins have separate options. That certainly helps, thanks. 

While it would still be nice to have a centralised Log function ( E.g. >= warn on recompile, >= verbose on build ), I can deal with the odd trickle from GPGS and Firebase; much more manageable!

Just for the record;
Do so many callbacks/events need to be called every time the editor recompiles, or is it a semi-precautionary cover-all measure? (I'm not familliar with the process/code and could probably get a more succinct answer asking directly than combing through it all.)

**Comment by stewartmiles** [comment]
Yep, we need to run through checks each time the project changes which is unfortunately due to the limitations in Unity's compilation and build system.  Pretty much every game engine or environment I've worked on we've had distinct edit / compile / asset build / package steps with hooks throughout the process, Unity has really spotty support across their build pipeline as soon as you try to do anything non-trivial which is what we need to deal with in various plugins like this.
