### ISSUE TITLE
Cocoapods resource bundle support

### ISSUE THREAD

**Issue by rlepinski** [googlesamples/unity-jar-resolver#33]
Resource bundles defined by the podspec key `resource_bundle` are missing from the generated xcodeproject.  Here is an example - https://github.com/urbanairship/ios-library-dev/blob/master/UrbanAirship-iOS-SDK.podspec#L17

**Comment by stewartmiles** [comment]
I'm fairly sure we added support for pods like this in 0ae23d3303890611261ddd826ed994dae37a9dea .  Give it a try and provide feedback if it's broken.
