### ISSUE TITLE
"Enable Resolution On Build" re-enables itsself several times per day.

### ISSUE THREAD

**Issue by JonathanDotCel** [googlesamples/unity-jar-resolver#331]
### Please fill in the following fields:
Unity editor version:  2019.2
Play Services Resolver version: 1.2.134 (but also older versions)
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Resolver, versionhandler, etc
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Admob, firebase, mediation, mediation test suite, etc
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Win10 x64
Platform you are targeting (iOS, Android, and/or desktop):  Android
Scripting Runtime (Mono, and/or IL2CPP): Both

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Any time I change unrelated build settings, this thing re-enables itsself (e.g. checking and unchecking mono/il2cpp builds)
Any time I switch projects... there it is again, enabled...
Not sure if it's ever saved properly.

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

Doesn't seem like a big deal but,

A- 1.2.135 is about the first time we've been able to literally just use the resolver and not hand-pick different resover/plugin combos to get *everything* working. 
Before that, it would take days to find a stable mixture of plugs.
As such there's 1 known working setup and several thousand combinations of broken ones, so not a lot of trust that the next iteration of any one plugin won't break everything.
(esp as we're stuck on 2019.2 due to multidex problems)

Even then we're overlooking an issue where AdMob does not call the OnBannerAdShown callback ever on any device, just for the convenience of everything else actually working.

One day you're not paying attention and miss this... bam, project's dead.. backup time.
So now part of the build process is going through the menu and manually disabling this *every time*. At some point the time spent doing this is going to surpass manually downloading the latest plugs into a known stable build.

B- Several .aar files have to be manually edited to remove the READ_PHONE_STATE permission on our end, or users won't get auto updates due to the added perms. 
We'd rather be well aware of every update for this reason before it's sent off for testing.

Cheers,
J

![image](https://user-images.githubusercontent.com/61208676/75816389-042c3780-5d8d-11ea-9a41-d698a6b63315.png)

**Comment by JonathanDotCel** [comment]
Edit: I had originally mistakenly claimed that switching between aab/apk builds would cause this issue, but it does not. IL2CPP/Mono switches seems to cause it (as does loading the project afresh).

**Comment by stewartmiles** [comment]
@JonathanDotCel the settings are saved under `YOUR_PROJECT/ProjectSettings/GvhProjectSettings.xml`, is it possible this file is being reverted?

**Comment by JonathanDotCel** [comment]
@stewartmiles I removed the file and haven't been able to replicate the issue for a week now, so happy to call this one closed. Thanks again!
