### ISSUE TITLE
Is EDM4U registry missing GooglePlayGamesService ?

### ISSUE THREAD

**Issue by Thaina** [googlesamples/unity-jar-resolver#339]
### Please fill in the following fields:
Unity editor version: 2018.4.19f1
External Dependency Manager version: 
Features in External Dependency Manager in use : VersionHandler
Plugins SDK in use : Firebase, GooglePlayGames
Platform you are using the Unity editor on : Windows 
Platform you are targeting : iOS + Android 
Scripting Runtime: IL2CPP

### Please describe the issue here:

While EDM4U current version can uninstall managed dependency, GooglePlayGamesService was also one of the managed library that could be uninstalled. So I want to remove it from my project and install as package. But I can't find GooglePlayGamesService from package manager

![image](https://user-images.githubusercontent.com/1042507/77393103-fcc9de00-6dce-11ea-83c7-0381f8e70106.png)

I am a little confuse from expectation that the package that could be uninstalled should already have replacement in the registry already, is that was the cases or I am misunderstood something, or it just some problem that we don't have GPGS in registry yet?

**Comment by stewartmiles** [comment]
@Thaina you'll need to file an issue with the Google Play Games Unity library instead.  AFAIK they haven't created a UPM package yet.
