### ISSUE TITLE
Allow to set a custom folder for resolved JARs

### ISSUE THREAD

**Issue by amjaliks** [googlesamples/unity-jar-resolver#34]
Allow to set a custom folder for resolved JARs.

**Comment by stewartmiles** [comment]
This is "fixed" in 1.2.11, however Unity does not recursively search directories under Plugins/Android so if you change the directory - you'll need to set GooglePlayServices.SettingsDialog.ConfigurablePackageDir to true then you can change the directory and produce non-working builds as you desire.
