### ISSUE TITLE
When making command line builds, verbose logging is used regardless of settings

### ISSUE THREAD

**Issue by snlehton** [googlesamples/unity-jar-resolver#340]
### Please fill in the following fields:
Unity editor version: 2019.2.3f1
External Dependency Manager version: 1.2.143
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver, Version Handler
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Facebook, Firebase
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
When I do a build in Unity Editor, I get minimal logging. When I do it from the command line, I get about 1200 lines of log, as if verbose logging was enabled (it is not).

![image](https://user-images.githubusercontent.com/5459058/77410105-1402ce80-6dc3-11ea-9c75-490ecf26ecf3.png)

Example entry in log

```
Find web request type
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Google.Logger:Log(String, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:115)
Google.PortableWebRequest:FindAndCacheRequestType() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/PortableWebRequest.cs:403)
Google.PortableWebRequest:StartRequest(HttpMethod, String, IDictionary`2, WWWForm) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/PortableWebRequest.cs:460)
Google.<StartRequestOnMainThread>c__AnonStorey2:<>m__5() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/PortableWebRequest.cs:443)
Google.RunOnMainThread:ExecuteNext() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:377)
Google.RunOnMainThread:<ExecuteAll>m__B() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:408)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
Google.RunOnMainThread:Run(Action, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.PortableWebRequest:StartRequestOnMainThread(HttpMethod, String, IDictionary`2, WWWForm) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/PortableWebRequest.cs:442)
Google.PortableWebRequest:Post(String, IDictionary`2, IEnumerable`1) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/PortableWebRequest.cs:516)
Google.EditorMeasurement:Report(String, String) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/EditorMeasurement.cs:492)
GooglePlayServices.PlayServicesResolver:PatchAndroidManifest(String, String) (at /Users/smiles/dev/src/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1323)
GooglePlayServices.PlayServicesResolver:OnSettingsChanged() (at /Users/smiles/dev/src/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2203)
GooglePlayServices.PlayServicesResolver:.cctor() (at /Users/smiles/dev/src/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:919)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:.cctor() (at Z:\tmp\tmp.RfRwjbXYBX\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:104)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[]) (at C:\buildslave\unity\build\Editor\Mono\EditorAssemblies.cs:108)
 
(Filename: /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs Line: 115)
```

### Please answer the following, if applicable:
100% repro rate on our Windows machines.

**Comment by stewartmiles** [comment]
@snlehton at the moment verbose logging is enabled by default in command line builds.

https://github.com/googlesamples/unity-jar-resolver/blob/c00bc4d620464d8d6de6e2d0fa49b5d7c90ead85/source/VersionHandlerImpl/src/VersionHandlerImpl.cs#L2234

I guess we could have an option to enable verbose logging from the command line instead.

**Comment by stewartmiles** [comment]
Here as well 
https://github.com/googlesamples/unity-jar-resolver/blob/2907855107a4b415d326601f5c6797ae93f95e6a/source/VersionHandlerImpl/src/Logger.cs#L110

**Comment by snlehton** [comment]
Yeah, I would really appreciate it. We currently do resolving at build time, and the logs are incredibly tedious to wade through as resolver makes up 95% of the logging with all the stacktracing included.   

I was doing the resolving manually, but then a lot of libraries needed to be upgraded and commited to git all the time. Even if the libs don't chance per se (ie. same version), because of repackaging they still do. So build time resolving was the only way to do it.

Having said that, I'm still contemplating of switching to completely manual resolving and do it only when things change/need updating.
