### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by G33ks** [googlesamples/unity-jar-resolver#343]
### Please fill in the following fields:
Unity editor version: 2019.3.4f1
External Dependency Manager version: 1.2.144
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): I dont know
Plugins SDK in use : FaceBook SDK
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 10
Platform you are targeting (iOS, Android, and/or desktop): all
Scripting Runtime (Mono, and/or IL2CPP): hum .. none ?

### Please describe the issue here:
Hi, I'm surely missing something big here as I am struggling for hours for something I thought would be easy. I just want to build the latest version of playServicesResolver to get rid of those annoying infinite 

> "ArgumentException: Requested value 'X86' was not found."

 I got after importing the FaceBook SDK (last version still use EDM 1.2.95).
I downloaded the last version, extracted it, and try to run the command ".\gradlew.bat build". Unfortunately, I always get errors like :

```
> A problem occurred evaluating root project 'playServicesResolver'.
> > Unity editor executable (UNITY_EXE) not found
```
I tried modifying the file "build.gradle" to target the right directory, but then it's 
`Unity root directory (UNITY_DIR) not found.`
and then
`xbuild not found (XBUILD_EXE)`
so as I don't want to rewrite a lot of code, do you have any idea of what I'm doing wrong ?
Many thanks

### Please answer the following, if applicable:
What's the issue repro rate? 100%

**Comment by stewartmiles** [comment]
To upgrade to the latest EDM just install the `.unitypackage` file in your project, you don't need to build from source.

**Comment by G33ks** [comment]
wow, just noticed the unitypackage files, right under my nose.
