### ISSUE TITLE
Gradle build exported from empty project with Firebase Analytics, Facebook SDK and Unity 2019.3.6 fails to build

### ISSUE THREAD

**Issue by snlehton** [googlesamples/unity-jar-resolver#348]
### Please fill in the following fields:
Unity editor version: 2019.3.6f1
External Dependency Manager version: 1.2.144
Source you installed EDM (from .unitypackage or Unity Package Manager): indirectly from Firebase analytics package from Unity Package Manager
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver, Version Handler
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Firebase Analytics, Facebook (7.19.1)
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 10
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:

I installed Firebase Analytics (6.13.0) using Unity Package Manager. I exported Gradle project and built it in command line, worked fine.
Then I installed Facebook SDK (7.19.1) and ran the Android Resolver. The Gradle project exported fine, but now when I try to build, I get this error:

```
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  C:\projects\xxx\Builds\unityLibrary\build\intermediates\aapt_friendly_merged_manifests\release\aapt\AndroidManifest.xml:36: error: resource mipmap/app_icon (aka com.unity3d.player:mipmap/app_icon) not found.
  C:\projects\xxx\Builds\unityLibrary\build\intermediates\aapt_friendly_merged_manifests\release\aapt\AndroidManifest.xml:36: error: resource string/app_name (aka com.unity3d.player:string/app_name) not found.
  C:\projects\xxx\Builds\unityLibrary\build\intermediates\aapt_friendly_merged_manifests\release\aapt\AndroidManifest.xml:41: error: resource string/app_name (aka com.unity3d.player:string/app_name) not found.
  error: failed processing manifest.
```
I'm not sure if this is EDM problem, but I have no other sources to turn to, so I'm checking here as well. Same config used to work on Unity 2019.2.3f1. In 2019.3.x they have changed the way Gradle builds are generated, so either EDM, Firebase or Facebook SDK is not compatible with the new way of things.

I did find a solution, though. If I copy missing resources from Builds/launcher/src/main/res to Builds/unityLibrary/src/main/res, it works. The files are mipmap-anydpi-v26, mipmap-mdpi, and values/strings.xml

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by snlehton** [comment]
Apparently the problem is that AndroidManifest.xml is no longer used for the launcher manifest but for the unityLibrary project. There is a separate LauncherManifest.xml which makes things complicated as all plugins so far expect AndroidManifest.xml to be the launcher manifest, and treat it like that.

If I make a build where AndroidManifest.xml is deleted, everything works. If AndroidManifest.xml in the old form is present (with launcher related stuff), it references assets that are not in the unityLibrary, and the build fails.

As an insult to injury: you can disable AndroidManifest.xml by unticking the override checkbox in the settings, and Unity renames the AndroidManifest.xml to AndroidManifest.xml.DISABLED. However, soon as you reload the project, Facebook SDK goes and recreates AndroidManifest.xml, and then you have both override and disabled override in your project:
![image](https://user-images.githubusercontent.com/5459058/78248029-8c207100-74f4-11ea-8bbe-6dc4f0ac2db4.png)

After that you can't uncheck the override anymore in the build settings 😂

I'm going to implement a support for deleting the AndroidManifest.xml in our builds, so that Facebook SDK cannot interfere with the build process. What they should do is fix their SDK (and test it with latest Unity version which they don't seem to do).

**Comment by stewartmiles** [comment]
Sounds like you figured out the root cause of the problem, I recommend opening up an issue with Facebook.
