### ISSUE TITLE
Jetifier not working when building on Mac

### ISSUE THREAD

**Issue by chbecher** [googlesamples/unity-jar-resolver#349]
### Please fill in the following fields:
Unity editor version: 2019.1.14
External Dependency Manager version: 1.2.144
Source you installed EDM (from .unitypackage or Unity Package Manager): .unitypackage
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Firebase, AppsFlyer, other jars 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
We are currently trying to update to a newer Firebase Version and to avoid conflicts with other plugins we enabled the Jetifer option. The build works perfectly when we are building with a Windows Maschine but when we build with Mac we get the following error on the start-up of the App: 
`
java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.company.appname-1/base.apk"],nativeLibraryDirectories=[/data/app/com.company.appname-1/lib/arm64, /data/app/com.company.appname-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at android.app.ActivityThread.installProvider(ActivityThread.java:5855)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5444)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5383)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
`

We tried using a Gradle file and without (all libraries in Plugins/Android). The same error appears when we disable Jetifier on Windows. 

### Please answer the following, if applicable:
What's the issue repro rate? 100%

**Comment by chkuang-g** [comment]
It does look like something is trying to use legacy android.support library.

What are the `other jars` you are using in the project?
Could it be possible that those libraries are trying to use legacy support library?

**Comment by chbecher** [comment]
The other jar/aar files are from plugins from the Unity Asset Store. One of them is already using AndroidX the other one is not. As far as I can see AppsFlyer is also still using the old support libraries. 
In my understanding, Jetifier should convert these plugins to the new libraries. The strange part is that the compiled version (using the normal Unity Build) with a Windows PC works.

**Comment by chkuang-g** [comment]
I see.  

Any `AARs` or `JARs` will need to be in either local or remote maven repos so they're processed by the Android Resolver.  If those plugins does not come with their own Dependencies.xml, those will be ignored by AndroidResolver.

I think it is those plugins from Unity Asset Store that are causing trouble.
I actually do not know why it works on Windows.

A couple of approaches you can do

1. Add your own Dependencies.xml and define local repos for those plugins. Ex.
    https://github.com/googlesamples/unity-jar-resolver/blob/master/source/AndroidResolver/test/resolve_async/Assets/ExternalDependencyManager/Editor/TestDependencies.xml#L8
1. Use custom gradle template.  Android Resolver will help to patch it and inject repo and dependency from Dependencies.xml.  You can also specify your local dependencies here as well.  Here is an interesting post for your reference.  And the Jetfifier integration in the Android Gradle build will process them
   https://forum.unity.com/threads/androidx-vs-android-libraries.710831/

Let us know if this helps

**Comment by chbecher** [comment]
Hey, I will give it a try with the local repositories. In the other approach, they mentioned updating the internal Gradle. This will not be a big overhead if we have to do this for our build machines.
In our Unity version, we have Gradle 3.4. Is there any limitation working with this version?

**Comment by chkuang-g** [comment]
@chbecher 

There is one open issue that the Gradle version with Unity 2018.4.0 isn't interpreting dollar slashy strings correctly.  https://github.com/googlesamples/unity-jar-resolver/issues/334#issuecomment-596819412
This _might_ be fixed with the version you have.  But please do report to us if you are experiencing with any issue.

Shawn
