### ISSUE TITLE
Any way to Add pod from GitHub?

### ISSUE THREAD

**Issue by rchallenger** [googlesamples/unity-jar-resolver#35]
MobFox SDK has a way to autoimport its files through such a line in a podfile
pod 'MobFoxSDK', :git => 'https://github.com/mobfox/MobFox-iOS-SDK.git'

Is there any way to do the same in generic way in Unity?
Maybe like this
Google.VersionHandler.InvokeStaticMethod (
          iosResolver, "AddPod",
          new object [] { "MobFoxSDK" },
          namedArgs: new Dictionary<string, object> ( ) {
      { "git", "https://github.com/mobfox/MobFox-iOS-SDK.git" },
      { "bitcodeEnabled", false },
          } );

**Comment by stewartmiles** [comment]
There is no way to do it at the moment but if you want to send us a patch we'll happily merge support for this, sounds really useful.

**Comment by stewartmiles** [comment]
Support for top level pod sources were added in b627bc6f370baea92963a60cac8c48869afc79af .  i.e you can add a "sources" argument with a list of sources to add to the top of the generated Podfile see https://github.com/googlesamples/unity-jar-resolver/blob/master/source/IOSResolver/src/IOSResolver.cs#L729
