### ISSUE TITLE
Nothing to import!

### ISSUE THREAD

**Issue by qbit86** [googlesamples/unity-jar-resolver#351]
### Please fill in the following fields:

Unity editor version: 2018.4.10f1 (a0470569e97b) revision 10503941
External Dependency Manager version: 1.2.145
Source you installed EDM: [external-dependency-manager-1.2.145.unitypackage](https://github.com/googlesamples/unity-jar-resolver/raw/v1.2.145/external-dependency-manager-1.2.145.unitypackage)
Plugins SDK in use: GooglePlayGamesPlugin-0.10.06, GoogleMobileAds-v4.2.1, facebook-unity-sdk-7.18.0
Platform you are using the Unity editor on: Windows 10  (10.0.0) 64bit
Platform you are targeting: Android, minSdkVersion: 16, targetSdkVersion: 29
Scripting Runtime/Backend/Compatibility: .NET 4.x Equivalent/IL2CPP/.NET Standard 2.0

#### Steps to reproduce
Import external-dependency-manager-1.2.145.unitypackage.

#### Observed behavior
Import failed with the following message: “Nothing to import! All assets from this package are already in your project.”  
![edm-1 2 145](https://user-images.githubusercontent.com/880168/78759720-b953a000-7988-11ea-9612-c2ec360d48b4.png)

[Editor.log](https://github.com/googlesamples/unity-jar-resolver/files/4449087/edm-1.2.145-Editor.log)

### Please answer the following, if applicable:

What's the issue repro rate? 100%

**Comment by Zifkan** [comment]
Same for me this Unity 2019.3.8

**Comment by Ospanaattori** [comment]
Same thing here.

Got it to work by manually extracting the unitypackage (it's basically a zip file) using [7-zip](https://www.7-zip.org)

The zip contains another unitypackage that imported nicely into Unity.

**Comment by qbit86** [comment]
The same for 1.2.149.
![resolver-package-issue](https://user-images.githubusercontent.com/880168/78875579-c8088880-7a56-11ea-9289-bbe1cf4a929f.png)

@stewartmiles It's probably better to stop releasing new knowingly broken versions and to fix packaging issue.

**Comment by stewartmiles** [comment]
@qbit86 which versions are causing problems and on which versions of Unity and which operating systems?  The main thing that changed is the tool used to package the .unitypackage on each release.

**Comment by stewartmiles** [comment]
Ah ok

Unity: 2018.4.10f1 (a0470569e97b) revision 10503941
External Dependency Manager version: 1.2.145
Source you installed EDM: external-dependency-manager-1.2.145.unitypackage
Platform you are using the Unity editor on: Windows 10 (10.0.0) 64bit

**Comment by qbit86** [comment]
✔️ external-dependency-manager-**1.2.144**.unitypackage is okay.
❌ external-dependency-manager-**1.2.145**.unitypackage is the first one broken.

**Comment by stewartmiles** [comment]
Ok reproduced, yeah it's a Windows thing.  Seems to work fine on macOS and Linux, Unity on Windows can't unpack these tar.gz files (.unitypackage files are .tar.gz files) for some reason.

**Comment by Cyberex** [comment]
Workaround for Windows. Open the archive "external-dependency-manager-1.2.149.unitypackage" using 7zip and run the "external-dependency-manager.unitypackage" file installation.

**Comment by qbit86** [comment]
@stewartmiles Off topic: please, rename it back to %Something% Resolver. Just Resolver is fine too. New branding breaks continuity, makes it harder to communicate.

**Comment by stewartmiles** [comment]
@qbit86 we've gone all in on External Dependency Manager for Unity / EDM4U, I'm afraid.

On the issue, I'm waiting for code review then I'll publish a new package that should work on Windows.
