### ISSUE TITLE
 Unity editor executable (UNITY_EXE) not found in mac

### ISSUE THREAD

**Issue by AbhayaAgrawal1** [googlesamples/unity-jar-resolver#354]
I am getting the following error on creating Gradle build in macOS
A problem occurred evaluating root project 'playServicesResolver'.
> Unity editor executable (UNITY_EXE) not found

I am using mac os Mojave
I have several versions of unity installed.

**Comment by stewartmiles** [comment]
You can set this manually by setting the [system property](https://docs.gradle.org/current/userguide/build_environment.html#sec:project_properties) from the command line...

```
./gradlew -PUNITY_EXE=path_to_your_unity_executable
```

e.g

```
./gradlew -PUNITY_EXE=/Applications/Unity5.6.5f1/Unity.app/Contents/MacOS/Unity
```
