### ISSUE TITLE
Reduce log spam

### ISSUE THREAD

**Issue by lambdor** [googlesamples/unity-jar-resolver#36]
I'm getting the following log messages everytime I start Unity:
```
Resolver version is now: 10101
Resolver version is now: 10102
Registering resolver version 1.2.0
Resolver version is now: 10102
```
Please add an option to disable these log messages.

**Comment by stewartmiles** [comment]
We fixed this back in 385fa3bb43e803d6944adf2ac9364bfb4141440e we have an option to enable / disable logging, though it gets real noisy.
