### ISSUE TITLE
NotSupportedException with External Dependency Manager 1.2.151

### ISSUE THREAD

**Issue by vzlomvl** [googlesamples/unity-jar-resolver#362]
Unity editor version: 2018.4.21
External Dependency Manager version: 1.2.151
Source you installed EDM (from .unitypackage or Unity Package Manager): Unity Package Manager
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver, iOS Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.):
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop):  IOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
1) Install External Dependency Manager 1.2.151 with UPM. 
2) See error in console
`Stopped polling job due to exception: System.NotSupportedException: The invoked member is not supported in a dynamic module.
  at System.Reflection.Emit.AssemblyBuilder.get_Location () [0x00006] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at Google.VersionHandlerImpl.get_EnabledEditorDllsLoaded () [0x0001c] in Z:\tmp\tmp.Y00V1yK86i\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\VersionHandlerImpl.cs:2352 
  at Google.VersionHandlerImpl+<NotifyWhenCompliationComplete>c__AnonStorey0.<>m__0 () [0x00000] in Z:\tmp\tmp.Y00V1yK86i\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\VersionHandlerImpl.cs:2387 
  at Google.RunOnMainThread.ExecutePollingJobs () [0x0004a] in Z:\tmp\tmp.Y00V1yK86i\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:409 
UnityEngine.Debug:LogError(Object)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.Y00V1yK86i/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:412)
Google.RunOnMainThread:<ExecuteAllUnnested>m__1() (at Z:/tmp/tmp.Y00V1yK86i/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.Y00V1yK86i/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at Z:/tmp/tmp.Y00V1yK86i/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.Y00V1yK86i/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:512)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:200)`
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by novavision** [comment]
Got the same issue on same Unity version on Mac as well

**Comment by stewartmiles** [comment]
Oh bummer, looks like it `Assembly.Location` is throwing an exception in some cases rather than just returning null :/

**Comment by bassarisse** [comment]
Having the same issue.

On this line:
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/VersionHandlerImpl/src/VersionHandlerImpl.cs#L2352

Maybe if we check for assembly.IsDynamic before anything, the error would be avoided without resorting to the try/catch?
