### ISSUE TITLE
[QUESTION] Support EDM in UPM?

### ISSUE THREAD

**Issue by MartinGonzalez** [googlesamples/unity-jar-resolver#363]
I saw that we have to download the external dependency manager package just like the old .unitypackages.

Is there any plan to support it in UPM? I guess this would be REALLY useful for other plugins providers, they can point to EDM package as dependency.

**Comment by stewartmiles** [comment]
It's already published on UPM see https://github.com/googlesamples/unity-jar-resolver/blob/master/README.md#unity-package-manager-resolver-usage and https://developer.android.com/games/develop/build-in-unity#download-registry

**Comment by MartinGonzalez** [comment]
@stewartmiles 
Something I don't understand.  The doc says what i put above

```
1- Download the latest Game Package Registry for Unity release.

2- Import the .unitypackage file by selecting the Unity IDE menu option Assets > Import package > Custom Package and importing all items.
```

What I mean is to be .unitypackage free. And set in the `manifest.json` just the registry and see every package that registry has. 
So if I have a plugin to develop and want to use the resolver I can just add it from the unity package manager and avoid .unitypackage.

**Comment by stewartmiles** [comment]
Correct you can use EDM4U from the Game Package Registry (GPR) but you'll need a way for your developers to add GPR to `manifest.json` which could either be instructions telling them to modify the file or by importing the EDM4U `.unitypackage` first.
