### ISSUE TITLE
Windows command prompt build hangs and never finishes

### ISSUE THREAD

**Issue by tenkiX** [googlesamples/unity-jar-resolver#364]
### Please fill in the following fields:
Unity editor version: 2019.3.12f1
External Dependency Manager version: 1.2.153
Source you installed EDM (from .unitypackage or Unity Package Manager): tried both ways
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android resolver, version handler.
Plugins SDK in use (Firebase, Admob, Facebook, etc.): firebase cloud messaging only
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Windows
Platform you are targeting (iOS, Android, and/or desktop): Android only
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP (but it fails with Mono too)

### Please describe the issue here:
After integrating firebase cloud messaging sdk 6.14 building my project from Windows command prompt does not work. It starts, but never finishes and just hangs forever. **However, it was working with version 6.11 !**
Did anything changed since then, maybe some dependencies I need to have on my computer installed? (My project build easily and fine from the opened editor, but I would need to use it from command line.)

Steps to reproduction:
1. Install Firebase Cloud Messaging newest version (6.14) with or without EDM
2. Try to build from Windows command prompt like this:
"C:\Program Files\Unity\Hub\Editor\2019.3.12f1\Editor\Unity.exe" -projectPath C:\Users\TenkiX\Desktop\FirebaseIntegrationExample -batchMode -quit -buildTarget Android -executeMethod Build.BuildDebug -buildOutput C:\Users\TenkiX\Desktop\FirebaseIntegrationExample\test.apk -logFile -

(BuildDebug() is a static method in the editor which simply adds the scenes, it is tested and working on 6.11 sdk)

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by gergelytenk** [comment]
(forgot to mention, that my project is a simple empty project containing cloud messaging only + the editor script with the BuildDebug() function which adds the samplescene to build list. Calling this from inside the editor with a [MenuItem("Tools/Build/Debug")]) make a perfectly fine build. It just does not work from the command propmt with the new version.

**Comment by tenkiX** [comment]
forgot to mention, that my project is a simple empty project containing cloud messaging only + the editor script with the BuildDebug() function which adds the samplescene to build list. Calling this from inside the editor with a [MenuItem("Tools/Build/Debug")) make a perfectly fine build. It just does not work from the command propmt with the new version.

**Comment by seansaleh** [comment]
FYI I have a duplicate issue over at https://github.com/firebase/quickstart-unity/issues/669 (I'm not sure which project it is more applicable to)
In my repro steps I have a [fork of the quickstart-unity project which shows the exact commit which broke it for me.](https://github.com/seansaleh/quickstart-unity/commit/0d4a9b6898523aef4ea03f92683e648c7d72c047)
I also have the following stack trace:
```
Cancelling DisplayDialog: Enable Analytics Would you like to report Firebase usage to the developers?

This data can be used to improve this product.

For more information, see https://policies.google.com/privacy by clicking show policy
This should not be called in batch mode.
UnityEditor.EditorUtility:DisplayDialogComplex(String, String, String, String, String)
Google.Dialog:DisplayDefault(String, String, Option, String, String, String) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\Dialog.cs:96)
Google.Dialog:Display(String, String, Option, String, String, String) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\Dialog.cs:117)
Google.EditorMeasurement:PromptToEnable() (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\EditorMeasurement.cs:348)
Google.EditorMeasurement:Report(String, String) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\EditorMeasurement.cs:446)
Google.EditorMeasurement:Report(String, ICollection`1, String) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\EditorMeasurement.cs:434)
Firebase.Editor.Measurement:ReportWithBuildTarget(String, ICollection`1, String) (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\Measurement.cs:92)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:RunResourceGenerator(IEnumerable`1, String, Boolean) (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:544)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:ReadBundleIds(String) (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:415)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:UpdateConfigFileDirectory() (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:303)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:CheckConfiguration() (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:254)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:<GenerateXmlFromGoogleServicesJson>m__0() (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:115)
Google.RunOnMainThread:ExecuteNext() (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:486)
Google.RunOnMainThread:<ExecuteAllUnnested>m__1() (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:536)
Google.RunOnMainThread:RunAction(Action) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:530)
Google.RunOnMainThread:Run(Action, Boolean) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:472)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:.cctor() (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:115)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[]) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:114)

[/Users/builduser/buildslave/unity/build/Editor/Platform/OSX/EditorUtility.mm line 344] 
(Filename: Z Line: 0)
```

**Comment by seansaleh** [comment]
From the other thread, using `-batchmode` instead of `-batchMode` is a workaround.
> There is piece of code on Google.VersionHandlerImpl that checks against the lowercase version to decide if certain things should run or not.

For Google folks can we track this as a bug since this is a regression considering builds for 6.13 worked just fine with `-batchMode`?

**Comment by gergelytenk** [comment]
> 
> 
> From the other thread, using `-batchmode` instead of `-batchMode` is a workaround.
> 
> > There is piece of code on Google.VersionHandlerImpl that checks against the lowercase version to decide if certain things should run or not.
> 
> For Google folks can we track this as a bug since this is a regression considering builds for 6.13 worked just fine with `-batchMode`?

Holy hell, oh my god, it really works with small M. Thank you.

**Comment by chkuang-g** [comment]
Hi folks,

Seems like this is the case issue.
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/VersionHandlerImpl/src/ExecutionEnvironment.cs#L32

This indeed is a regression.  Thanks for reporting this.  Will fix this in the next release.
