### ISSUE TITLE
Generated gradle template not using Local Maven Repo Directory

### ISSUE THREAD

**Issue by tarrowood** [googlesamples/unity-jar-resolver#366]
### Please fill in the following fields:
Unity editor version: 2019.2.21f1
External Dependency Manager version: 1.2.153
Source you installed EDM (from .unitypackage or Unity Package Manager): Package Manager
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver, iOS Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): FIrebase, AppLovin
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS, Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
When running Android Resolver, if using a a local repository, the local repository directory override defined in the settings is not used by the grade template generation/patching, leading to incorrect paths to local repos in the build.gradle, and resolution failures at build.

Easiest repo is simply to integrate the Firebase packages, since they use local repos. Use the following settings:

Explode AARs: True
Patch mainTemplate.gradle: True
Local Maven Repo DIrectory: `Assets/GeneratedLocalRepo`

Note that the Dependencies.xmls for all Firebase packages locates the local repo for the Firebase unity libraries at: `<repository>Assets/Firebase/m2repository</repository>`

During resolve, the Local Maven Repo DIrectory Override will move those to `Assets/GeneratedLocalRepo/Firebase/m2repository`

But the gradle template generation/patching will not use that override, and failing to find them, will search out the repos in the packages themselves, which don't contain the aars. In the mainTemplate.gradle output will be:
`maven {
            url "file:////<PATH_TO_PROJECT>/Library/PackageCache/com.google.firebase.app@6.14.0/Firebase/m2repository" // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:20
        }`

one for each of the Firebase libraries in use.

A workaround is to change the Local Maven Repo Directory to `Assets`. This will place the repos in the place that the gradle template generation/patching expects them to be. Obviously not ideal, since repos will be scattered and the unified local repo directory is a good idea.

Doing so changes the output in the mainTemplate.gradle to a single repo line:
`maven {
            url "file:////<PATH_TO_PROJECT>/Assets/Firebase/m2repository" // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:20
        }`

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc) 100%

**Comment by chkuang-g** [comment]
@tarrowood 

Thanks for reporting this.  I did notice that this occurs from Unity 2019 (verified working in 2018), which broke this fix https://github.com/googlesamples/unity-jar-resolver/commit/ed6e2dbdb5c4ee29a4f1d2213c50a670c4a6a048.

Seems like `GetRepos()` returned the wrong path to repo here.
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/AndroidResolver/src/PlayServicesResolver.cs#L2009

Will take a look and compose a fix for this.
