### ISSUE TITLE
Meta files have platform-specific path characters in gvhp_exportpath field, causing source control mess

### ISSUE THREAD

**Issue by MigrantP** [googlesamples/unity-jar-resolver#369]
### Please fill in the following fields:
Unity editor version: 2019.3.10f1
External Dependency Manager version: 1.2.144
Source you installed EDM (from .unitypackage or Unity Package Manager): Google Play Game Services plugin version 0.10.08
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Google Play Game Services
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac & Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS, Android, and desktop
Scripting Runtime (Mono, and/or IL2CPP): Mono and IL2CPP

### Please describe the issue here:
The meta files under ExternalDependencyManager have a gvhp_exportpath field. By default this has forward slash characters in it, and it stays that way on Mac. But for our developers on Windows, the characters change to backslashes, so those files are shown as changed by git. All of the files in the folder have this problem. Examples attached.

![image](https://user-images.githubusercontent.com/345012/81313572-6b50bb80-905e-11ea-881a-1de7d2b5aeb5.png)

![image (1)](https://user-images.githubusercontent.com/345012/81313580-6f7cd900-905e-11ea-928b-61f66fc499a7.png)

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc) 100%

**Comment by chkuang-g** [comment]
Hi @MigrantP 

I think this has been fixed in 1.2.145. 
https://github.com/googlesamples/unity-jar-resolver/commit/46851fd3560fa1ebcaced2cda54f33c8e6d3d6d5

Could you update to the latest EDM4U and see of this still happens?

Shawn

**Comment by MigrantP** [comment]
Hi @chkuang-g 

We updated to 1.2.154 and that solved the issue, thanks!
