### ISSUE TITLE
Failed to determine the most recently installed Android SDK version.

### ISSUE THREAD

**Issue by ChrisKalahiki** [googlesamples/unity-jar-resolver#370]
### Please fill in the following fields:
Unity editor version: 2019.3.10f1
External Dependency Manager version: 
Source you installed EDM (from .unitypackage or Unity Package Manager): .unitypackage
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
Failed to determine the most recently installed Android SDK version. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25
UnityEngine.Debug:LogWarning(Object)
GooglePlayServices.UnityCompat:WarnOnAndroidSdkFallbackVersion()
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion()
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion()
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean)
GooglePlayServices.<ScheduleResolve>c__AnonStorey1E:<>m__3F()
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob()
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__47()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAll>m__A()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc) 100%

**Comment by chkuang-g** [comment]
@ChrisKalahiki 

Could you provide a bit more information. Ex.

* What is the version of the External Dependency Manager (Formally Play Services Resolver)?
  The easiest way to find it is in the first line of settings windows at `Assets > External Dependency Manager > Android Resolver > Settings`.  
  * If you are using older version of EDM, you may find the settings at `Assets > Play Services Resolver > Android Resolver > Settings`.  
* When did you see this error message?  
* Did you setup Android path properly in Unity Preference?  Did you use the one with Unity or the one from Android Studio?
* Is this a regression for you or just after you installed Admob?
