### ISSUE TITLE
i cant find the unitypackage 

### ISSUE THREAD

**Issue by AnandMulay** [googlesamples/unity-jar-resolver#372]
where can i find the unity package file to download ?

**Comment by bhallionOhbibi** [comment]
go to https://github.com/googlesamples/unity-jar-resolver
Then click the "Releases" button which is near above "Clone or download" button
Then on the page you will find the link to download the package (which is zipped)

**Comment by chkuang-g** [comment]
You should be able to always find the latest .unitypackage here
https://github.com/googlesamples/unity-jar-resolver/blob/master/external-dependency-manager-latest.unitypackage

Or as @bhallionOhbibi suggested, here for each release.
https://github.com/googlesamples/unity-jar-resolver/releases
