### ISSUE TITLE
Editor freezes more than usual when hitting play

### ISSUE THREAD

**Issue by Hauki** [googlesamples/unity-jar-resolver#374]
### Please fill in the following fields:
Unity editor version: 2018.4.15 & 2019.3.10
External Dependency Manager version: 1.2.153
Source you installed EDM (from .unitypackage or Unity Package Manager):Unity Package Manager
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.):Android Resolver, iOS Resolver, VersionHandler
Plugins SDK in use (Firebase, Admob, Facebook, etc.):Firebase
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS & Android
Scripting Runtime (Mono, and/or IL2CPP): both

### Please describe the issue here:
This is also a issue at the firebase plugin git site, but not sure if the team is the same or if it has been brought to your attention. Link to issue: https://github.com/firebase/quickstart-unity/issues/639 & https://github.com/firebase/quickstart-unity/issues/667

Copy of issue: 
Everytime i hit play (even on a empty project), Unity takes too long to build, compared to the usual time, this is not practical for me.
Also, when the game starts (the play button becomes blue), the editor completely freezes for a few seconds as if it was compiling the game once again.
Am i doing something wrong ?

To easily reproduce this issue:

Create a empty 3D project
Switch to Android Platform in the build settings
Import FirebaseMessaging.unitypackage from Assets -> Import Package
After import, a popup shows up to enable Android Auto-Resolution, click "Enable"
The Unity Packager Manager Resolver window opens, click "Add selected registries"
Wait until all dependencies update.
Don't add anything else, and hit "Play"
You will notice the editor freezing and taking way too long to build.
This problem happens even if you don't have any base code running.
Also, tried adding the google-services.json, but it doesn't do anything in this case.

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by bhallionOhbibi** [comment]
This issue is also related I think: https://github.com/googlesamples/unity-jar-resolver/issues/352

**Comment by Whyser** [comment]
This issue is also related I think: https://github.com/firebase/quickstart-unity/issues/639

**Comment by chkuang-g** [comment]
Hi folks,
There are multiple factors that is causing the freeze.  Firebase 6.15.0 did improve the performance a bit but more changes need to be done to reduce the freeze.

Will keep you updated.

**Comment by chkuang-g** [comment]
Hi folks, I'll close this bug for duplication to #639.  It is easier to respond in a centralized place.

Please monitor that one instead.

Thank you and sorry for the inconvenience

Shawn
