### ISSUE TITLE
I can't set settings-dialog programmatically

### ISSUE THREAD

**Issue by kjt0429** [googlesamples/unity-jar-resolver#375]
### Please fill in the following fields:
Unity editor version: all
External Dependency Manager version: 1.2.144
Source you installed EDM (from .unitypackage or Unity Package Manager):
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.):
Plugins SDK in use (Firebase, Admob, Facebook, etc.):
Platform you are using the Unity editor on (Mac, Windows, or Linux): 
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP):

### Please describe the issue here:
I can't set settings-dialog programmatically (just manual). could you give me api ? or how to set programmatically

**Comment by chkuang-g** [comment]
@kjt0429 

Which setting do you need to set programmatically? And in what scenario do you need to do so?

AFAIK, some settings window will execute some jobs when the setting is changed manually. So making the API might not be simple.

Shawn
