### ISSUE TITLE
Error running CocoaPods. Please ensure you have at least version 1.0.0. You can install CocoaPods with the Ruby gem package manager:

### ISSUE THREAD

**Issue by GITHUB243884919** [googlesamples/unity-jar-resolver#376]
### Please fill in the following fields:
Unity editor version: Unity2018.4.2
External Dependency Manager version: V.1.2.153
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac 10.15.4
Platform you are targeting (iOS, Android, and/or desktop): ios
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
**1.When I build my project in Unity Editor to IOS, console shows :Error running CocoaPods. Please ensure you have at least version 1.0.0. You can install CocoaPods with the Ruby gem package manager.....
3.But if I type gem -v then shows : 3.0.3 and
if I type ruby -v then shows: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
and if I type gem list shows : cocoapods (1.8.4)
The full error log:**
Error running CocoaPods. Please ensure you have at least version 1.0.0. You can install CocoaPods with the Ruby gem package manager:
sudo gem install -n /usr/local/bin cocoapods
pod setup

'pod --version' returned status: 1
output:
33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
Consider adding the following to ~/.profile:

export LANG=en_US.UTF-8
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:118:in git_version': Failed to extract git version from git --version("xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n") (RuntimeError) from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:130:inverify_minimum_git_version!'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:49:in run' from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in <top (required)>'
from /usr/local/bin/pod:23:in load' from /usr/local/bin/pod:23:in

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by NazarKozak** [comment]
Same issue on Unity 2019.3.12f1. Mac Os Catalina.
Using Firebase Analytics + Crashlytics.

Issue happened with Cocoapods v 1.9.1. Calling `pod --version` returned 
1.9.1, `which pod` gives `/usr/local/bin/pod`. So installation seems to be ok.

- Tried full uninstallation of cocoapods and re-install, doesn't helped.
- Tried installing older version of cocoapods (1.8.4), doesn't helped.
- Tried another versions of Unity (2019.2.21f1), doesn't helped.
- Tried updating EDM from V.1.2.153 to V.1.2.155, doesn't helped.
- Tried manually running `pod install` in project, it installs dependencies, but project seems to be messed up.

Error log, i'm getting all the time.
`Error running CocoaPods. Please ensure you have at least version 1.0.0.  You can install CocoaPods with the Ruby gem package manager:
 > sudo gem install -n /usr/local/bin cocoapods
 > pod setup

'pod --version' returned status: 1
output: 


 #0 GetStacktrace(int)
 #1 DebugStringToFile(DebugStringToFileData const&)
 #2 DebugLogHandler::Internal_Log(LogType, LogOption, core::basic_string<char, core::StringStorageDefault<char> >, Object*)
 #3 DebugLogHandler_CUSTOM_Internal_Log(LogType, LogOption, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
 #4  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
`

**Comment by NazarKozak** [comment]
Finally managed to fix this issue via iOS Resolver Settings.

Assets -> External Dependencies Manager -> iOS Resolver -> Settings -> Use Shell to Execute Cocoapod Tool -> Uncheck.

**Comment by GITHUB243884919** [comment]
> Finally managed to fix this issue via iOS Resolver Settings.
> 
> Assets -> External Dependencies Manager -> iOS Resolver -> Settings -> Use Shell to Execute Cocoapod Tool -> Uncheck.
I disabled the Use Shell to Execute Cocoapod Tool, but still meet the same error. I don't known
why I have installed Ruby, gem, and CocoaPods still meet this error.

![image](https://user-images.githubusercontent.com/17681628/82881557-6bafe880-9f72-11ea-835e-fbb65f940f49.png)

**Comment by NazarKozak** [comment]
> > Finally managed to fix this issue via iOS Resolver Settings.
> > Assets -> External Dependencies Manager -> iOS Resolver -> Settings -> Use Shell to Execute Cocoapod Tool -> Uncheck.
> 
> ![image](https://user-images.githubusercontent.com/17681628/82881557-6bafe880-9f72-11ea-835e-fbb65f940f49.png)
> 
> > Finally managed to fix this issue via iOS Resolver Settings.
> > Assets -> External Dependencies Manager -> iOS Resolver -> Settings -> Use Shell to Execute Cocoapod Tool -> Uncheck.
> 
> **I disabled the Use Shell to Execute Cocoapod Tool, but still meet the same error. I don't known why I have installed Ruby, gem, and CocoaPods still meet this error.**
> 
> ![image](https://user-images.githubusercontent.com/17681628/82882131-41125f80-9f73-11ea-9a5d-404237effedf.png)

Seems like you don't have **Command Line Tools** installed (It happens all the time after xCode update).
Try running `xcode-select --install` in console.
More info [here](https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a)

**Comment by GITHUB243884919** [comment]
> > > Finally managed to fix this issue via iOS Resolver Settings.
> > > Assets -> External Dependencies Manager -> iOS Resolver -> Settings -> Use Shell to Execute Cocoapod Tool -> Uncheck.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/17681628/82881557-6bafe880-9f72-11ea-835e-fbb65f940f49.png)
> > > Finally managed to fix this issue via iOS Resolver Settings.
> > > Assets -> External Dependencies Manager -> iOS Resolver -> Settings -> Use Shell to Execute Cocoapod Tool -> Uncheck.
> > 
> > 
> > **I disabled the Use Shell to Execute Cocoapod Tool, but still meet the same error. I don't known why I have installed Ruby, gem, and CocoaPods still meet this error.**
> > ![image](https://user-images.githubusercontent.com/17681628/82882131-41125f80-9f73-11ea-9a5d-404237effedf.png)
> 
> Seems like you don't have **Command Line Tools** installed (It happens all the time after xCode update).
> Try running `xcode-select --install` in console.
> More info [here](https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a)

thank you. It's ok now~

**Comment by chkuang-g** [comment]
Hi folks,

I think this is a common issue with Unity after you upgrade to Catalina.
Try to use the following comment to reinstall cocoapods. 
```
sudo gem uninstall -aIx && rm -rf ~/.gem && gem install cocoapods
```

Hope this helps!

**Comment by GITHUB243884919** [comment]
> CocoaPods/CocoaPods#8955

Thank you . I install xcode again, It's ok now~
