### ISSUE TITLE
macOS External Dependency Manager prompts Developer Tools Access Request

### ISSUE THREAD

**Issue by oguzhalil** [googlesamples/unity-jar-resolver#381]
### Please fill in the following fields:
Unity editor version: 2019.3.15f1
External Dependency Manager version: Google.VersionHandlerImpl_v1.2.155
Source you installed EDM (from .unitypackage or Unity Package Manager): https://firebase.google.com/download/unity
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): iOS Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Firebase, Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Mac Catalina 10.15.3
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
The issue is if I install firebase sdk (with external dependency manager) , macOS prompts following dialog
![image](https://user-images.githubusercontent.com/32879685/84606260-231e8780-aead-11ea-9acf-e206e91e47b7.png)

If I press continue unity3d freezes forever. If I press cancel (multiple times) unity crashes. Here is the thing firebase installation with playservicesresolver version working as expected, because it is not prompting the dialog above. I can see this is not directly related to external dependency manager. Is there anyway to prevent external dependency manager prompting the dialog? with my best.

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
%100

**Comment by alexames** [comment]
Hi @oguzhalil 

This is a strange bug, can you cause the crash for us, and then attach the unity editor log?

It's not entirely clear whether this is being caused by our plug in, can you also try opening xcode and attaching to unity? Then, when Unity crashes, let us know what the call stack looks like so we can see where the crash is coming from?
