### ISSUE TITLE
class org.gradle.api.DefaultTask_Decorated cannot be cast to class java.lang.String

### ISSUE THREAD

**Issue by AbhayaAgrawal1** [googlesamples/unity-jar-resolver#382]
I am getting the following error on creating Gradle build in macOS.
I am using the following command to build the

**./gradlew -PUNITY_EXE=/Applications/Unity/Hub/Editor/5.6.7f1/Unity.app/Contents/MacOS/Unity** 

class org.gradle.api.DefaultTask_Decorated cannot be cast to class java.lang.String (org.gradle.api.DefaultTask_Decorated is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @4629104a; java.lang.String is in module java.base of loader 'bootstrap')

you can find scan result [here](https://gradle.com/s/gjutuluoovxxw)

**Comment by alexames** [comment]
Can you `--info` or `--debug` to your build to get some more logs and post them here? `--debug` will be very verbose though, so try `--info` first to see if you get any useful information out of that.
