### ISSUE TITLE
Support for dependencies variants

### ISSUE THREAD

**Issue by sp-miguel-ibero** [googlesamples/unity-jar-resolver#385]
Hi,

At my company we have games that we want to release in different android app stores and that need different dependencies for each one. Is there any way of doing this currently? If not, would you be interested in having support for these kind of dependencies variants? One way of doing it would be to allow modifying the `XmlDependencies.fileRegularExpressions` field.

If there is interest I can work on it and prepare a PR.

thanks!

**Comment by alexames** [comment]
Hi @sp-miguel-ibero, 

Can you give us some more details on your use case? What do you need different plugin dependencies for? Is it for your own plug ins, or third party plug ins? Can you describe what changes you would like to make to `XmlDependencies.fileRegularExpressions`? 

Feel free to submit a PR if you have an idea on how to fix this, if you'd like.
