### ISSUE TITLE
Unable to copy firebase to GeneratedLocalRepo when Forced Resolve

### ISSUE THREAD

**Issue by pogsdbest** [googlesamples/unity-jar-resolver#392]
### Please fill in the following fields:
Unity editor version: 2019.3.13f1
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): Unity Package Manager
Firebase plugins in use (Auth, Database, etc.): Firebase App, Firebase Cloud Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, AdMob, GoogleSignin
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Windows10
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
1.installed EDM4U 1.2.156.
2.installed Facebook, Admob, GoogleSignin via .unitypackage
3.forced resolve working properly. and GeneratedLocalRepo has a folder inside, but only for GoogleSignin
4.installed Firebase App and Firebase Messaging via package manager. both or Firebase App alone. same error.
5.forced resolve failed. with the error. below. 

`Unable to copy Packages\com.google.firebase.app\Firebase/m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.srcaar to Assets/GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.aar.  Assets/GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.aar will not be included in Gradle builds. Reason: Source file Packages\com.google.firebase.app\Firebase/m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.srcaar not found.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel) (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\Logger.cs:136)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:990)
GooglePlayServices.GradleTemplateResolver:CopySrcAars(ICollection`1) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\GradleTemplateResolver.cs:134)
GooglePlayServices.GradleTemplateResolver:InjectDependencies(ICollection`1) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\GradleTemplateResolver.cs:312)
GooglePlayServices.<ResolveUnsafe>c__AnonStorey9:<>m__1() (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1850)
Google.RunOnMainThread:ExecuteNext() (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:486)
Google.RunOnMainThread:<ExecuteAllUnnested>m__1() (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:536)
Google.RunOnMainThread:RunAction(Action) (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:530)
Google.RunOnMainThread:Run(Action, Boolean) (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:472)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1849)
GooglePlayServices.PlayServicesResolver:ResolveUnsafeAfterPromptCheck(Action`1, Boolean, Boolean, Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1763)
GooglePlayServices.<ResolveUnsafeAfterJetifierCheck>c__AnonStorey7:<>m__0(Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1674)
GooglePlayServices.<CanEnableJetifierOrPromptUser>c__AnonStoreyF:<>m__1(ApiLevelJetifierResult) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2594)
GooglePlayServices.PlayServicesResolver:CheckApiLevelForJetifier(Boolean, String, Action`1) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2558)
GooglePlayServices.<CanEnableJetifierOrPromptUser>c__AnonStoreyF:<>m__0(Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2579)
GooglePlayServices.PlayServicesResolver:CheckGradleVersionForJetifier(Boolean, String, Action`1) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2486)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String, Action`1) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2577)
GooglePlayServices.PlayServicesResolver:ResolveUnsafeAfterJetifierCheck(Action`1, Boolean, Boolean, Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1671)
GooglePlayServices.<ScheduleResolve>c__AnonStorey5:<>m__0() (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1638)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1495)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1651)
GooglePlayServices.PlayServicesResolver:ExecuteMenuResolve(Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1904)
GooglePlayServices.PlayServicesResolver:MenuForceResolve() (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1928)`

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

tried, to reproduce on a clean project. but it didn't happen. this only happen on my working project.

What's the issue repro rate? (eg 100%, 1/5 etc): 100%

**Comment by chkuang-g** [comment]
@pogsdbest 

Thank you for reporting this.  Judged by the log, this seems to be some forward/backward slash issue on Windows

```
Packages\com.google.firebase.app\Firebase/m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.srcaar
```
```
Assets/GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.aar
```

These two paths are generated here
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/AndroidResolver/src/GradleTemplateResolver.cs#L107
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/AndroidResolver/src/GradleTemplateResolver.cs#L110

I think I know what is wrong with the second url but not sure how the first one got screwed.

A quick fix for this is to wrap `FileUtils.NormalizePathSeparators()` around `FileUtils.ReplaceBaseAssetsOrPackagesFolder()`.

If you need this right away, I would recommend you to download this repo, make the change and use `./gradlew buildUpmPlugin`.  You should find the `.tgz` file under `build` folder.  Then you can install it through Unity Package Manager using this tarball for now.
Make sure you setup UNITY_EXE in your environment variable.

I'll file a ticket for this.

**Comment by vimanyu** [comment]
Hi @pogsdbest ,
I was trying to reproduce this issue on my end but could not get the exact error that you are seeing. Here are the steps that I tried,

Fresh project in Unity 2019, Build Settings set to "Android" and PlayerSettings->Player->Publishing Settings -> enable Custom Main Gradle Template

Attempt 1:
- Install EDM4u via UPM (after manually updating Packages/manifest.xml file as mentioned in https://firebase.google.com/docs/unity/setup#add-sdks-upm)
- Install Facebook unitypackage
- Force Resolve (WORKS!)
- Install Firebase app via UPM
- Force Resolve (WORKS!)

NOTES:
`Assets/GeneratedLocalRepo/Firebase` was created after successfully resolving the second time.

Attempt2:
- Install EDM4u via UPM (after manually updating Packages/manifest.xml file as mentioned in https://firebase.google.com/docs/unity/setup#add-sdks-upm)
- Install Facebook, Google Admob, Google SignIn unitypackages
- Force Resolve (WORKS!)
- Install Firebase Cloud messaging (and Firebase app as its dependency) via UPM
- Force Resolve (ERROR but not the same as the one you listed)

NOTES:
- Depending on the order of installation of unitypackages, the active EDM4u package gets overwritten. The menu option changed form Assets -> External Dependency Manager to Assets -> Play Store resolver
- No `Assets/GeneratedLocalRepo` directory and the resolve complains as its can't find one of the dependencies

WORKAROUND:
I could get it to resolve by the following steps,
   - Delete all the additional EDM4u packages in Assets folder installed by the unitpackages (fb, google sign in etc). Delete "Assets/External Dependency Manager*" and "Assets/PlayStoreResolver*"
   - Restart Unity and Force resolve worked and created `Assets/GeneratedLocalRepo`

Now, I know you mentioned you got a partial GeneratedLocalRepo and that you couldn't reproduce this issue in a fresh scene. Could you pass me a lightweight version of your project (removing all the heavyweight assets)? I can compare our projects and this will help in debugging. 

Thanks!

**Comment by chkuang-g** [comment]
@pogsdbest 

I cannot reproduce this issue with Unity 2019.3.13f1 on Windows using Quickstart either.

Based on the error message, it was not able to find the source file.
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/AndroidResolver/src/PlayServicesResolver.cs#L2271

The source file is `Packages\com.google.firebase.app\Firebase/m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.srcaar`.  This is a logical path from Unity AssetDatabase.  The actual path should be 
```
Library\PackageCache\com.google.firebase.app@6.15.2\Firebase/m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.srcaar
```

Could you confirm that file exists?

Also, as @vimanyu mentioned, Unity can act funky when there are duplicated copy of EDM4U or Play Services Resolver.  Please make sure those are removed from `Assets` folder.

Finally, to help us debug for your situation better, could you send us a minimum viable product for reproduction?

Thank you,
Shawn

**Comment by vimanyu** [comment]
Not sure if this was the original cause of the problem but since we noticed a mix of forward and backward slashes while copy AARs, we have normalized these file paths and are also using physical paths rather than logical Unity paths. Should go out in the next release.
