### ISSUE TITLE
Unity 2020.1.2f1: Android development and non-development builds rely on different versions of AndroidX annotations, which causes conflicts when resolved with EDM4U

### ISSUE THREAD

**Issue by yuriy-universal-ivanov** [googlesamples/unity-jar-resolver#396]
### Please fill in the following fields:
Unity editor version: 2020.1.2f1
External Dependency Manager version: 1.2.157
Source you installed EDM (from .unitypackage or Unity Package Manager): Unity Package Manager
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
When EDM4U-resolved packages depend (including transitively) on androidx.annotation:annotation, Android build fails depending on the version of annotation being resolved and development/non-development option enabled when building:
Development builds implies annotation 1.0.0, non-development builds imply 1.1.0. If EDM4U-version doesn't match it, then the build fails with duplicated symbols, f.e.: having `<file>Assets/Plugins/Android/androidx.annotation.annotation-1.1.0.jar</file>` in ProjectSettings\AndroidResolverDependencies.xml and Development Build produces this error:

```
C:\Users\u-n-i\Documents\projects\utnotifications\unity\Temp\gradleOut\launcher\build\intermediates\external_file_lib_dex_archives\debug\out\0_androidx.annotation.annotation-1.0.0.jar: D8: Type androidx.annotation.AnimRes is defined multiple times: C:\Users\u-n-i\Documents\projects\utnotifications\unity\Temp\gradleOut\launcher\build\intermediates\external_file_lib_dex_archives\debug\out\0_androidx.annotation.annotation-1.0.0.jar:classes.dex, C:\Users\u-n-i\Documents\projects\utnotifications\unity\Temp\gradleOut\launcher\build\intermediates\external_file_lib_dex_archives\debug\out\0_androidx.annotation.annotation-1.1.0.jar:classes.dex

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

```
(same error with `<file>Assets/Plugins/Android/androidx.annotation.annotation-1.0.0.jar</file>` and non-Development Build). No error with 1.1.0 and non-dev build and 1.0.0 and dev build.

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by cynthiajoan** [comment]
Hi @yuriy-universal-ivanov ,

There are some more information that we'd like to collect:
1. Is there anyway you can share your project structure? We'd like to see how the dependencies are constructed in the project.
2. Are you using mainTemplate.gradle?
3. If you have time, can you try the change [here](https://github.com/googlesamples/unity-jar-resolver/issues/296#issuecomment-597010133) to see if that fixed your issue?
