### ISSUE TITLE
Misdetecting library update

### ISSUE THREAD

**Issue by yuriy-universal-ivanov** [googlesamples/unity-jar-resolver#4]
Hi,

It permanently misdetects "support-annotations-24.0.0-alpha2" library as updated:
```
Android Jar Dependencies
Remove or replace support-annotations-24.0.0 version alpha2 with version 24.0.0-alpha2?
```

I suppose, the reason is "-" in a version (not just 24.0.0, but 24.0.0-alpha2).

Here is my dependencies initialization:
```
PlayServicesSupport playServicesSupport = PlayServicesSupport.CreateInstance(m_pluginName, EditorPrefs.GetString("AndroidSdkRoot"), "ProjectSettings");
playServicesSupport.DependOn("com.android.support", "support-v4", "+");
playServicesSupport.DependOn("com.google.android.gms", "play-services-gcm", "+");
```

Thank you!

**Comment by claywilkinson** [comment]
Thanks for the report.  So to confirm you are saying the release version 24.0.0 is newer than 24.0.0-alpha?

**Comment by yuriy-universal-ivanov** [comment]
@claywilkinson 
No, it misdetects the same version to be newer than itself (and as the version has not changed after replacing the library, it keeps detecting the same again).

So, as you can see, it offers replacing "support-annotations-24.0.0 version alpha2" "with version 24.0.0-alpha2" which is actually the same version.

Regards
