### ISSUE TITLE
 Unable to determine mono version from C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe

### ISSUE THREAD

**Issue by soethihanaing** [googlesamples/unity-jar-resolver#400]
> root project
* Where:
Build file 'C:\Users\Soe Thiha Naing\Downloads\unity-jar-resolver-master\build.gradle' line: 153

* What went wrong:
A problem occurred evaluating root project 'playServicesResolver'.
> Unable to determine mono version from C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by vimanyu** [comment]
Thanks for creating this issue. Can you please list some steps to reproduce this?
Can you also verify if this is also happening with the Unity quickstart examples?
https://github.com/firebase/quickstart-unity

From the error, it looks like `mono` cant be found. Do you see `mono.exe` in `C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Data\MonoBleedingEdge\bin"?

**Comment by chkuang-g** [comment]
@soethihanaing 

Judge by your post, I assume you are trying to build EDM4U on WIndows.  Please confirm if this is correct.

In that case, I did noticed that later version of Unity no longer ships `mono.bat` as the build.gradle expected.

Try to modify [this line](https://github.com/googlesamples/unity-jar-resolver/blob/master/build.gradle#L129) to
```
          "**/bin/mono.exe" : "**/bin/mono")
```

Let us know if this resolved your issue.

We may need to did some investigation to see if this change is safe from Unity 5 to 2020.

**Comment by soethihanaing** [comment]
@chkuang-g 
I upgraded my unity to 2019.4.9f. I got an error on playstoreResolver that "ArgumentException: Requested value 'X86' was not found." .
So other dev recommend me to upgrade playstoreResolver. I am doing as "Build From Source" section. I got an error like that. Also, unity not support MONO build longer. Maybe Mono.exe or Mono.bat will not include anymore.

> @soethihanaing
> 
> Judge by your post, I assume you were trying to build EDM4U on WIndows. Please confirm if this is correct.
> 
> In that case, I did notice that later version of Unity no longer ships `mono.bat` as the `build.gradle` expected.
> 
> Try to modify [this line](https://github.com/googlesamples/unity-jar-resolver/blob/master/build.gradle#L129) to
> 
> ```
>           "**/bin/mono.exe" : "**/bin/mono")
> ```
> 
> We may need some investigation to see if this change is safe from Unity 5 to 2020.
> 
> Another issue is that it may fail at `:Bootstrap_PYTHON_'python'`.
> This...is a more annoying issue since that package for Windows has be removed. If you really need to build EDM4U, I would recommend you to do this on Mac for now.

**Comment by soethihanaing** [comment]
@vimanyu I following this https://github.com/googlesamples/unity-jar-resolver#building-from-source. Yes, mono.exe found under C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Data\MonoBleedingEdge\bin .
![image](https://user-images.githubusercontent.com/45550908/93004602-72d52380-f56e-11ea-95a9-995727ac9c10.png)

**Comment by soethihanaing** [comment]
Full Error
===========
 ./gradlew.bat build --info
Initialized native services in: C:\Users\Soe Thiha Naing\.gradle\native
The client will now receive all logging from the daemon (pid: 644256). The daemon log file: C:\Users\Soe Thiha Naing\.gradle\daemon\5.1.1\daemon-644256.out.log
Starting 7th build in daemon [uptime: 38 mins 2.442 secs, performance: 100%]
Using 12 worker leases.
Starting Build
Settings evaluated using settings file 'C:\Users\Soe Thiha Naing\Documents\Projects\PwalKyamGit\Assets\unity-jar-resolver-master\settings.gradle'.
Projects loaded. Root project using build file 'C:\Users\Soe Thiha Naing\Documents\Projects\PwalKyamGit\Assets\unity-jar-resolver-master\build.gradle'.
Included projects: [root project 'playServicesResolver']

> Configure project :
Evaluating root project 'playServicesResolver' using build file 'C:\Users\Soe Thiha Naing\Documents\Projects\PwalKyamGit\Assets\unity-jar-resolver-master\build.gradle'.
UNITY_EXE: C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe
UNITY_DIR: C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe
UNITY_DLL_PATH: C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe
UNITY_IOS_PLAYBACK_PATH: C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe
XBUILD_EXE: C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe
MONO_EXE: C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe
Starting process 'command 'C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe''. Working directory: C:\Users\Soe Thiha Naing\Documents\Projects\PwalKyamGit\Assets\unity-jar-resolver-master Command: C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe -V
Successfully started process 'command 'C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe''

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Soe Thiha Naing\Documents\Projects\PwalKyamGit\Assets\unity-jar-resolver-master\build.gradle' line: 153

* What went wrong:
A problem occurred evaluating root project 'playServicesResolver'.
> Unable to determine mono version from C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Unity.exe

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
<-------------> 0% WAITING

**Comment by DellaBitta** [comment]
Hi @soethihanaing,

A few follow up questions if you don't mind:

1. Are you building the sources from this repository from scratch?  The manager is also available in a [precompiled form in the base directory of the main branch](https://github.com/googlesamples/unity-jar-resolver/blob/master/external-dependency-manager-latest.unitypackage). You may have better luck with the pre-compiled version, unless you need to edit the sources before compilation.

2. Which platform are you targeting ( iOS/Android ) when you encounter the errors?

3. Does the error occur when you attempt to resolve dependencies or when you build the application?

4. Could you enable verbose logging ( Assets - > External Dependency Manager -> Android (or iOS Resolver) -> Settings. Then enable "Verbose Logging".

**Comment by soethihanaing** [comment]
@DellaBitta  I use precompiled, it works now, thanks.
