### ISSUE TITLE
[BUG] Long path length causes android resolver to fail to copy or find certain files.

### ISSUE THREAD

**Issue by humblesagegames** [googlesamples/unity-jar-resolver#409]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.8f1
  * External Dependency Manager version: 1.2.161
  * Source you installed EDM4U: Unity Package Manager
  * Features in External Dependency Manager in use: Android Resolver (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: Firebase, Facebook, Photon, (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)

### [REQUIRED] Please describe the issue here:
Pretty much everything from Issue #392 
This issue has been closed but the "solution" I believe wasn't correct (atleast didn't fix it in my case)

This error I get now when trying to resolve android dependenices: 
`Job failed with exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\CompanyName\git repositories\Git Project\a very long path to try to break firebase copy lmao\Game_git\Game_Name_Big_project_unity\Library\PackageCache\com.google.firebase.database@6.15.2\Firebase\m2repository\com\google\firebase\firebase-database-unity\6.15.2'.`
(I believe this error is different to what I was getting on an older version, and different to what issue #392 shows, but the same workaround works for it etc)
The directory DOES exist (I can copy it into 'Run' and it opens). The path length is just too long. (260 characters or whatever)

Not really looking for help on this, as the workaround we've been using has been fine, though it would be nice to not have to put our project on the root of the C drive for EDM resolve correctly. I think I've read that we can increase the windows path length relative easily as well so no issue. Just wanted to bring some attention to it.

#### Please answer the following, if applicable:
What's the issue repro rate? 100% (when the path length is long)

What happened? How can we make the problem occur?
Read Issue #392 

Delete GeneratedLocalRepo, then EDM->Android Resolver -> Resolve

**Comment by DellaBitta** [comment]
Hi @humblesagegames,

Are you certain that this is a problem with the resolver, and not just [a limitation of the Windows platform](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#:~:text=In%20editions%20of%20Windows%20before,required%20to%20remove%20the%20limit.)?

Thanks!

**Comment by humblesagegames** [comment]
The files which it fails to find do exist in Unity's packagecache, so Unity must be doing something to be able to handle/ generate them. Looking at the properties though shows a shortened path with some strange tilde notation like "C:\PROGRA~1\"

I can manually generate the "GeneratedLocalRepo" by copying the files from the PackageCache, and programs like notepad have no problem opening and saving files over that "max" length... though windows explorer does freak out a bit.

Definitely don't know for sure though, just seems like something that there would be a workaround for.

**Comment by chkuang-g** [comment]
@humblesagegames 

This is very likely MAX_PATH limitation, as David pointed out.  You can find many StackOverflow mentioning the same issues.

If you are using Windows 10 version 1607 or above, please try to increase MAX_PATH.

EDM4U tends to use the absolute path when using C# `File` or `Directory` class, since that is the safest way across EVERY Unity versions. I did notice some Unity version accept relative path for `File` or `Directory` methods but this really require a thorough evaluation across all Unity versions and desktop platform before we can make any change.
