### ISSUE TITLE
 com.google.android.gms.drive

### ISSUE THREAD

**Issue by SamiSdd** [googlesamples/unity-jar-resolver#41]
I see it adds few aars by default

Method count
com.google.android.gms.drive: 1731
com.google.android.gms.nearby: 1614

and other few. Are those libraries used by default i removed drive and build succeed. Any explanation or a way to get rid of these library and keeping the auto sync feature on

**Comment by stewartmiles** [comment]
@SamiSdd did you figure out what was going on?

**Comment by SamiSdd** [comment]
Hey not sure what was going on for me. I've added Ironsource SDK and few other. It seems one of them or as a dependency for one of them the google drive was being added. Did the fix by manually removing drive aar and turn off the auto download option. Thanks
