### ISSUE TITLE
[Question] Enable MultiDex in Unity Without using Gradle

### ISSUE THREAD

**Issue by behrooz-fard** [googlesamples/unity-jar-resolver#417]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.11f1
  * External Dependency Manager version: 1.2.162
  * Source you installed EDM4U: external-dependency-manager-1.2.162.unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Admob
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the question here: 
I Use External Dependency Manager for Unity in my project. And I added my project dependencies in a .xml file instead of using Gradle. But now I got some error about MultiDex. Can I enable MultiDex in my project without using Gradle files?

**Comment by Str4tos** [comment]
Hey. I use a custom script to modifies the gradle file.
However, I think enable MultiDex option is useful enough to be part of EDM4U.

**Comment by DellaBitta** [comment]
Hi @behrooz-fard,

Configuring for Multidex is an Android build configuration decision and is a bit outside the domain of this repo.  However, we do have some ideas of where you might start looking:

1.  Configure Unity to export the project into Android studio which has tools to build with Multidex support.  I'm not sure if this is viable for your project, however.

1. We've found a [App Mediation Unity Guide](https://appmediation.com/unity-enable-multidex/) which has some information on how to work with AndroidManifest file to enable multidex support. 

1. The [Android Multidex Documentation](https://developer.android.com/studio/build/multidex) has some information on how to enable Multidex support depending on which minimum Android version you're targeting.

I hope this helps!
