### ISSUE TITLE
[Question] How to let *Dependencies.xml auto add annotationProcessor to mainTemplate ?

### ISSUE THREAD

**Issue by Scorpius-gg** [googlesamples/unity-jar-resolver#419]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2017.4
  * External Dependency Manager version: 1.2.156
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Firebase, Facebook ,gms and so on
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the question here:

I need add a third party SDK into my project. This SDK need add dependencies as follows
`implementation 'com.github.bumptech.glide:glide:4.11.0'`
`annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'`
I didn't find something about annotationProcessor in SampleDependencies.xml
I hope Android Resolver can do this instead of manually add to mainTemplate.
Because i don't need it every time. If i need this sdk, my onekey packing code will copy the files to Plugin/Android folder before building.

And sorry, my English is not very well, I hope you can understand what I want to express

**Comment by vimanyu** [comment]
Hi @Scorpius-gg,
Thanks for creating this ticket. As you noted, "annotationProcessor" is not supported in Android Resolver. We could add this to our list of feature requests or if you have some time, feel free to create a PR for this request and we can merge that in. I didn't understand the last bit about onekey packing code. Are you exporting an Android project from Unity and manually patching the mainTemplate? Copying plugin files to Plugin/Android folder happens only when we dont use the mainTemplate.

**Comment by Scorpius-gg** [comment]
> Hi @Scorpius-gg,
> Thanks for creating this ticket. As you noted, "annotationProcessor" is not supported in Android Resolver. We could add this to our list of feature requests or if you have some time, feel free to create a PR for this request and we can merge that in. I didn't understand the last bit about onekey packing code. Are you exporting an Android project from Unity and manually patching the mainTemplate? Copying plugin files to Plugin/Android folder happens only when we dont use the mainTemplate.

Thanks for your response. if "annotationProcessor" is not supported in Android Resolver, it is convenient for my project. Now, i have to solve this problem with an other plan. 
About  onekey packing code, this is not important now.
