### ISSUE TITLE
JarResolver 1.2.14 throws exceptions with Unity 5.5

### ISSUE THREAD

**Issue by claywilkinson** [googlesamples/unity-jar-resolver#42]
It looks like it is looking for PlayerSettings.applicationIdentifier - but this was added in 5.6 as far as I know.  5.5 should be using PlayerSettings.bundleIdentifier. 

I get this error when using Unity 
MissingMethodException: Method not found: 'UnityEditor.PlayerSettings.get_applicationIdentifier'.
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for GooglePlayServices.PlayServicesResolver
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
UnityEditor.EditorAssemblies.ProcessEditorInitializeOnLoad (System.Type type) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:130)

**Comment by stewartmiles** [comment]
@claywilkinson could you try 1.2.16?  This was fixed in 26d126a1b5ab85d3e6c779f2768062b5be063fab

**Comment by stewartmiles** [comment]
I've tested this out with 1.2.16 and everything is working fine.
