### ISSUE TITLE
[BUG] Auto Resolution for Android with Addressables causes hangs of editor while building packages

### ISSUE THREAD

**Issue by batonPiotr** [googlesamples/unity-jar-resolver#420]
* Unity editor version: 2019.4.17f1
  * External Dependency Manager version: 1.2.163
  * Source you installed EDM4U: .unitypackage (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: Android Resolver, iOS Resolver, VersionHandler (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: Firebase Analytics (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Target: Android

### Issue
I am using dependency resolver and addressables in one project. Addressables have some features like analyser tools for checking for duplicated asset dependencies to optimise the addressables packages. The thing is, everytime this tool is running, the editor runs scriptable build pipeline. And it hangs every time it wants to check asset dependencies of scenes in those packages.

When debugging I could see an error thrown when running this method: `ContentBuildInterface.CalculatePlayerDependenciesForScene(scenePath, settings, usageTags, m_DependencyData.DependencyUsageCache);` in `CalculateSceneDependencyData`. This class is part of the addressables
 package.

### Workaround

The only workaround is to disable **Enable Auto Resolution On Build** and **Enable Auto-Resolution**.

It's 100% replicable

Edit: Further investigation led me to the conclusion, that the underlying problem was that the dependencies couldn't be solved with the built-in JDK Version (1.8.0). After updating the JDK to 1.15.0 it went well. However, I cannot use this version continuously as Unity needs its own, built in version for building APK files. So this problem is twofold:

- In case of problems with resolving dependencies, when auto resolving is enabled, addressables cannot build its packages because of problems with dependencies
- The Resolution fails if used with built in JDK Version

**Comment by patm1987** [comment]
Hi @batonPiotr ,

Would it be possible for you to build a small example to help the team reproduce this?

Another thing you could try is enabling `mainTemplate.gradle` (and `gradleTemplate.properties` on newer versions of Unity):
![image](https://user-images.githubusercontent.com/1111611/107093268-2fe84680-67c2-11eb-965c-5d335b91a89e.png)
