### ISSUE TITLE
[BUG] unity-jar-resolver fails if the classifier doesn't have artifactType attached

### ISSUE THREAD

**Issue by bhbac-nhnent** [googlesamples/unity-jar-resolver#422]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: `2020.1.11f1`
  * External Dependency Manager version: `v1.2.164`
  * Source you installed EDM4U: `external-dependency-manager-1.2.164.unitypackage`
  * Features in External Dependency Manager in use: `Android Resolver`
  * Plugins SDK in use: `Not use`
  * Platform you are using the Unity editor on: `Windows 10 64bit`

#### Please answer the following, if applicable:
What's the issue repro rate?
- `100%`

Hi.

In #416 , you guys modified the unity-jar-resolver to be able to identify the classifier as well.
But unfortunately, after some testing, I found out that the functionality was not fully implemented yet.

In gradle, '@ + artifactType' means 'dependency is ignored'.
See an example below how it works in gradle.

WITH DEPENDENCIES
![image](https://user-images.githubusercontent.com/17632448/107463522-a3fb6380-6ba1-11eb-8d16-4f19fe3c7b13.png)
WITHOUT DEPENDENCIES
![image](https://user-images.githubusercontent.com/17632448/107463605-cf7e4e00-6ba1-11eb-9c53-50ed85691b81.png)

However, unity-jar-resolver fails if the classifier doesn't have artifactType attached.
This is not the correct behavior.

SUCCESS
```xml
<dependencies>
  <androidPackages>
    <androidPackage spec="com.sina.weibo.sdk:core:10.10.0:openDefaultRelease@aar">
      <repositories>
        <repository>https://dl.bintray.com/thelasterstar/maven</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
</dependencies>
```
FAIL
```xml
<dependencies>
  <androidPackages>
    <androidPackage spec="com.sina.weibo.sdk:core:10.10.0:openDefaultRelease">
      <repositories>
        <repository>https://dl.bintray.com/thelasterstar/maven</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
</dependencies>
```
![image](https://user-images.githubusercontent.com/17632448/107463757-24ba5f80-6ba2-11eb-9754-9e5382df3e6b.png)

**Comment by vimanyu** [comment]
Hi @bhbac-nhnent, 
Thanks for creating this issue. I did not see many examples of package specification with classifiers and added the feature with the example which had an artifact type. Will look into implementing support for this.

**Comment by bhbac-nhnent** [comment]
@vimanyu I'm sorry. It seems I haven't properly verified it.
I checked the screenshot and found that the weibo-sdk module does not exist when there is no `@aar` definition, so I tested again.
As a result, it was confirmed that an error occurred even in gradle.
![image](https://user-images.githubusercontent.com/17632448/107777496-3d836a80-6d86-11eb-8c52-58caf6f526fd.png)

So, I don't think there is any problem with the current behavior of unity-jar-resolver, and I think you can close this issue here.
I am sorry again for reporting unnecessary issues.

Thanks!

**Comment by vimanyu** [comment]
Oh, no worries. Thanks for creating these detailed issues with all the information. I am going to close this ticket. I still think the support is limited to classifiers with artifact types specified but if you are unable to use an android package with such specification, feel free to create a ticket.
