### ISSUE TITLE
[Bug] ProjectSettings/GvhProjectSettings.xml is saved as UTF-8 with BOM

### ISSUE THREAD

**Issue by robinfischerinnogames** [googlesamples/unity-jar-resolver#425]
* Unity editor version: 2019.4.3f1
  * External Dependency Manager version: 1.2.164
  * Source you installed EDM4U: Unity Package Manager
  * Features in External Dependency Manager in use: Android Resolver, iOS Resolver, VersionHandler
  * Plugins SDK in use: Firebase
  * Platform you are using the Unity editor on: Mac

### [REQUIRED] Please describe the issue here:
After upgrading the External Dependency Manager from 1.2.159 to 1.2.164 I have the problem that every time I open Unity the "ProjectSettings/GvhProjectSettings.xml" file is saved with the UTF-8 with BOM encoding. 

Git Diff:
```
git diff frontend/ProjectSettings/GvhProjectSettings.xml
diff --git a/frontend/ProjectSettings/GvhProjectSettings.xml b/frontend/ProjectSettings/GvhProjectSettings.xml
index 4e83d24c20..31bed15b0d 100644
--- a/frontend/ProjectSettings/GvhProjectSettings.xml
+++ b/frontend/ProjectSettings/GvhProjectSettings.xml
@@ -1,4 +1,4 @@
-<?xml version="1.0" encoding="utf-8"?>
+<U+FEFF><?xml version="1.0" encoding="utf-8"?>
 <projectSettings>
   <projectSetting name="com.google.external-dependency-managerAnalyticsEnabled" value="False" />
```

This messes with my setup because Git refuses to commit this BOM character. Every time I open Unity I have this file modified and i can't commit the change. It is very frustrating. I also haven't found a way to commit the BOM character into the git repo.
I tried deleting the file, downgrading to the older EDM4U version. Nothing seems to work.

In another project we have the "GvhProjectSettings.xml" that is missing the complete xml header and that works well.

Am I missing something here? It seems like a bug and EDM4U should not use an outdated/unsupported encoding.

My settings file:

```<?xml version="1.0" encoding="utf-8"?>
<projectSettings>
  <projectSetting name="com.google.external-dependency-managerAnalyticsEnabled" value="False" />
  <projectSetting name="com.google.firebaseAnalyticsEnabled" value="False" />
  <projectSetting name="Google.IOSResolver.AutoPodToolInstallInEditor" value="False" />
  <projectSetting name="Google.IOSResolver.CocoapodsIntegrationMethod" value="2" />
  <projectSetting name="Google.IOSResolver.Enabled" value="True" />
  <projectSetting name="Google.IOSResolver.PodfileEnabled" value="True" />
  <projectSetting name="Google.IOSResolver.PodToolExecutionViaShellEnabled" value="True" />
  <projectSetting name="Google.IOSResolver.VerboseLoggingEnabled" value="False" />
  <projectSetting name="Google.PackageManagerResolver.VerboseLoggingEnabled" value="False" />
  <projectSetting name="Google.VersionHandler.VerboseLoggingEnabled" value="False" />
  <projectSetting name="GooglePlayServices.AndroidPackageInstallationEnabled" value="True" />
  <projectSetting name="GooglePlayServices.AutoResolutionDisabledWarning" value="False" />
  <projectSetting name="GooglePlayServices.AutoResolveOnBuild" value="False" />
  <projectSetting name="GooglePlayServices.AutoResolverEnabled" value="False" />
  <projectSetting name="GooglePlayServices.ExplodeAars" value="True" />
  <projectSetting name="GooglePlayServices.LocalMavenRepoDir" value="Assets/GeneratedLocalRepo" />
  <projectSetting name="GooglePlayServices.PatchAndroidManifest" value="False" />
  <projectSetting name="GooglePlayServices.PatchMainTemplateGradle" value="True" />
  <projectSetting name="GooglePlayServices.PatchPropertiesTemplateGradle" value="True" />
  <projectSetting name="GooglePlayServices.PromptBeforeAutoResolution" value="True" />
  <projectSetting name="GooglePlayServices.UseGradleDaemon" value="False" />
  <projectSetting name="GooglePlayServices.UseJetifier" value="True" />
  <projectSetting name="GooglePlayServices.VerboseLogging" value="False" />
</projectSettings>
```

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

Thank you,
Cheers

**Comment by chkuang-g** [comment]
Thanks for reporting.

This seems to be related to this change.
https://github.com/googlesamples/unity-jar-resolver/commit/468518d8bbe9fab38d56f74e8225222cd4a8f063

Seems like `UTF8Encoding` would emit BoM by default.
https://docs.microsoft.com/en-us/dotnet/api/system.text.utf8encoding.-ctor?view=net-5.0#System_Text_UTF8Encoding__ctor_System_Boolean_

I think the right things to do here is to use `new UTF8Encoding(false)` for `XmlWriterSettings.Encoding`

Seem to be a simple change.  However, I wonder why git refuse to accept file with BoM. Did a quick search, this seem to bring agony to the git community.

**Comment by robinfischerinnogames** [comment]
Hi @chkuang-g,
Thank you for the response. Did you have any luck crafting a change to fix this? So far we are using the old version of the resolver. Now we really have to update and this is kind of blocking us. 
We can still upgrade but in our team everybody will constantly have this file marked as changed... I could not find a way to force GIT to accept the BOM encoding :/
