### ISSUE TITLE
Git Url [Question]

### ISSUE THREAD

**Issue by iantierney** [googlesamples/unity-jar-resolver#429]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.13f1
  * External Dependency Manager version: 1.2.164
  * Source you installed EDM4U:NA (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: NA(Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: NA(Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on:Mac (Mac, Windows, or Linux)

### [REQUIRED] Please describe the question here:

What is the URL for installing from Unity package manager->Install from Git Url

I have tried all the urls below. I have also tried downloading the unitypackage and installing it from disk but in Mac OS file browser files ending in _".unitypackage"_ are greyed out.

- https://github.com/googlesamples/unity-jar-resolver.git
- https://github.com/googlesamples/unity-jar-resolver/external-dependency-manager-latest.unitypackage
- https://github.com/googlesamples/unity-jar-resolver/blob/master/external-dependency-manager-1.2.164.unitypackage
- https://github.com/googlesamples/unity-jar-resolver/blob/3dfc84aba31425c1def8a2da7027757d4b3d59fd/external-dependency-manager-latest.unitypackage

**Comment by paulinon** [comment]
Hi @iantierney,

The Play Services Resolver can't be installed via git, so you would want to use the Package Manager. 

I noticed you've tried a different method in installing the Play Services Resolver. Could you try double clicking the .unitypackage file with one Unity editor open and see if this works? If it doesn't, please provide detailed steps, you've taken so far in importing the resolver.

Thanks!

**Comment by iantierney** [comment]
Hey @paulinon,
I am using the package manager.

In the _Unity package manager_ you can _Install from Git Url_

**Comment by iantierney** [comment]
When I double click the downloaded ".unitypackage" file. It seems to import, however it does not seem to appear in the package manager.
- how do I know if its imported correctly?
- is there any other step I'm missing apart from double clicking?

**Comment by paulinon** [comment]
Hi @iantierney,

Upon importing the Play Services Resolver, you will see the added files in your Assets folder because Unity manages this by unzipping into the assets directory. This is why you can't find it in the Package Manager. I apologize for the confusion this may have caused. If you can find an ExternalDependencyManager folder in your assets, then you've done it right.

I'll be closing this for now. Feel free to reopen if you have any other questions.
