### ISSUE TITLE
[Question] Game Package Registry (GPR) by Google will shut down on May 19, 2021 - Does this apply to EDM4U too?

### ISSUE THREAD

**Issue by manwithsteelnerves** [googlesamples/unity-jar-resolver#434]
We recently got a mail from firebase team mentioning GPR will shutdown and no more easy support for UPM on unity.

We are currently using EDM4U through package manager by adding the dependency and GPR in the scoped registries.

Does this shutdown applies to EDM4U too or only for firebase packages?

**Comment by manwithsteelnerves** [comment]
@stewartmiles can you please have a look?

**Comment by chkuang-g** [comment]
@manwithsteelnerves Yes, this will affect EDM4U as well.

We will continue to publish both `unitypackage` and  `tgz` format on [Google APIs for Unity](https://developers.google.com/unity/package).
You can find both the [latest](https://developers.google.com/unity/packages#tools) and the [older versions](https://developers.google.com/unity/archive#external_dependency_manager_for_unity).

For more context, see https://github.com/firebase/quickstart-unity/issues/1030#issuecomment-825095383

**Comment by manwithsteelnerves** [comment]
@chkuang-g  Can we re-bundle EDM4U and have it in our own packages as a dependency? We have our own scoped registry which will be added automatically once the user downloads from Asset Store.

**Comment by chkuang-g** [comment]
@manwithsteelnerves 

EDM4U is under [Apache License](https://github.com/googlesamples/unity-jar-resolver/blob/master/LICENSE#L103).
That is, you should be able to redistribute EDM4U through your own scoped registry.

You can either download the pre-built tgz from [Google APIs for Unity archive page](https://developers.google.com/unity/archive#external_dependency_manager_for_unity).

If you are using Mac or Linux, you can build `tgz` from source by running the following command from the root of this project.
```
./gradlew buildupmplugin
```
Make sure you set `UNITY_EXE` environment variable properly.

Shawn
