### ISSUE TITLE
[Question] Android build failed on mac os

### ISSUE THREAD

**Issue by nima-vonvon** [googlesamples/unity-jar-resolver#435]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.20f1
  * External Dependency Manager version: 1.2.164
  * Source you installed EDM4U: unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Platform you are using the Unity editor on: Mac

### [REQUIRED] Please describe the question here:

On Windows, the build was successful.
But on Mac, it failed with the following error.
How do I fix this error?

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':unityLibrary:compileReleaseAidl'.
> Could not resolve all task dependencies for configuration ':unityLibrary:releaseCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-base:[10.2.1, 12.1.0[.
     Required by:
         project :unityLibrary
      > Failed to list versions for com.google.android.gms:play-services-base.
         > Unable to load Maven meta-data from https://adcolony.bintray.com/AdColony/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://adcolony.bintray.com/AdColony/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://adcolony.bintray.com/AdColony/com/google/android/gms/play-services-base/maven-metadata.xml'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[.
     Required by:
         project :unityLibrary
      > Failed to list versions for com.google.firebase:firebase-messaging.
         > Unable to load Maven meta-data from https://adcolony.bintray.com/AdColony/com/google/firebase/firebase-messaging/maven-metadata.xml.
            > Could not get resource 'https://adcolony.bintray.com/AdColony/com/google/firebase/firebase-messaging/maven-metadata.xml'.
               > Could not GET 'https://adcolony.bintray.com/AdColony/com/google/firebase/firebase-messaging/maven-metadata.xml'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)

**Comment by paulinon** [comment]
Hi @nima-vonvon,

A new version of the resolver is available. Could you try version 1.2.165 and see if this resolves your issue? If not, I'd like you to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the detailed steps you've taken before facing this issue.

**Comment by nima-vonvon** [comment]
EDM4U does not seem to be the cause of this error.
When I tested it with an empty Unity project (newly created project + empty scene), I got the same error.
I will ask the Unity technical team for help.
Thanks for your comment.
