### ISSUE TITLE
IOSResolver pod path installation detection

### ISSUE THREAD

**Issue by EmpTim** [googlesamples/unity-jar-resolver#436]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.25
  * External Dependency Manager version: 1.2.163
  * Source you installed EDM4U: Unity Package Manager
  * Features in External Dependency Manager in use: Android Resolver, iOS Resolver
  * Plugins SDK in use: Facebook 8.1.0, Firebase 6.15.2
  * Platform you are using the Unity editor on: Mac

### [REQUIRED] Please describe the question here:
Our project uses a CircleCI pipeline to create our Android and iOS builds. We had been using Xcode 11.3.0 as the image to use which included a pod script in the `/usr/local/bin` directory, but this has recently changed with the Xcode 12.x image since that is now required going forward.

Now when running `which pod` it points to `/Users/distiller/.rubies/ruby-2.7.2/bin/` instead which I suppose is part of the image change from CircleCI, but this now causes the IOSResolver to fail to locate the existing pod installation as the script is looking for a pod file specifically in either `/usr/local/bin` or `/usr/bin`.

The IOSResolver scripts installs cocoapods when it can't find it but then after installation an error is logged that it could not find `pod` anyway, I'm wondering if anyone else has had similar issues? We've solved this currently by adding an extra step to our pipeline by running `pod --install` after the Unity build but would prefer if it was all self contained within the IOSResolver script since it's doing most of the heavy lifting of this part regarding iOS dependencies. Is it possible to instead have IOSResolver check for whether the `pod` command is available rather than to check for `pod` in hardcoded paths?

**Comment by paulinon** [comment]
Hi @EmpTim,

A new version of the resolver has been released (version 1.2.165). Could you try this and see if the issue persists? If it does, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the detailed steps you've taken before facing this behavior.
