### ISSUE TITLE
[Bug]  Cannot unzip the file - path could not be found, directories cannot be created

### ISSUE THREAD

**Issue by juppaGames** [googlesamples/unity-jar-resolver#437]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * External Dependency Manager version: _____
  * Source you installed EDM4U: _____ (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: _____ (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: _____ (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)

### [REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by juppaGames** [comment]
It cannot even be unzipped - errors come up immediately. Errors like ..Path could not be found, directories could not be created... ecc ecc Plenty of red messages appear immediately. If I choose ignore and unzip the next file, other errors come up.. I am on Windows 10. all updates installed. I did not even try to import this broken plugin into Unity. Thank you

**Comment by paulinon** [comment]
Hi @juppaGames,

My understanding here is that you couldn't unzip the repository for the External Dependency Manager. Could you try if downloading the [.unitypackage file](https://github.com/googlesamples/unity-jar-resolver/blob/master/external-dependency-manager-1.2.165.unitypackage) and importing it to your project works for you? 

If your scenario is different from what I've described, please let me know so that we can identify what's causing it.
