### ISSUE TITLE
[Bug] Confusing version comparison: `version2 = version1.EndsWith("+")`

### ISSUE THREAD

**Issue by qbit86** [googlesamples/unity-jar-resolver#442]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.10f1
  * External Dependency Manager version: 1.2.165
  * Source you installed EDM4U: `.unitypackage`
  * Features in External Dependency Manager in use: Android Resolver, VersionHandler
  * Plugins SDK in use: Firebase, Facebook, etc.
  * Platform you are using the Unity editor on: Mac, Windows

### [REQUIRED] Please describe the issue here:

I was reading sources of `Dependency` class investigating another issue. And was confused by this argument coercion in `IsGreater()` method [1]:
```cs
version2 = version1.EndsWith("+") ?
    version2.Substring(0, version2.Length - 1) : version2;
```

Shouldn't it be `version2`?
```cs
version2 = version2.EndsWith("+") ? ...
```

Or with `TrimEnd()` [2]:
```cs
version2 = version2?.TrimEnd(...);
```

#### Please answer the following, if applicable:

> What's the issue repro rate?

100%

> How can we make the problem occur?

Take a look at `Dependency.IsGreater(string version1, string version2)`

[1] [source/JarResolverLib/src/Google.JarResolver/Dependency.cs#L196](https://github.com/googlesamples/unity-jar-resolver/blob/d370ab8ef6c9199ae8d033c9d75e8f727e8b0c3d/source/JarResolverLib/src/Google.JarResolver/Dependency.cs#L196)
[2] https://docs.microsoft.com/en-us/dotnet/api/system.string.trimend?view=net-5.0

**Comment by chkuang-g** [comment]
Thanks for catching this!

This should be fixed in https://github.com/googlesamples/unity-jar-resolver/pull/443 and will be included in the next release.

If you need the patch immediately, you can build EDM4U from source using:
```
# Build .unitypackage to build/ folders
./gradlew buildPlugin

# Build .tgz to build/ folder
./gradlew buildUpmPlugin
```

**Comment by DellaBitta** [comment]
I'm going to close this issue for now.  If the upcoming change does not fix your issue in the next release, then please re-open this ticket to let us know!  Thanks!
