### ISSUE TITLE
This issue does not seem to follow the issue template. Make sure you provide all the required information.

### ISSUE THREAD

**Issue by viviskas** [googlesamples/unity-jar-resolver#446]
This issue does not seem to follow the issue template. Make sure you provide all the required information.

_Originally posted by @google-oss-bot in https://github.com/googlesamples/unity-jar-resolver/issues/445#issuecomment-867356391_

**Comment by paulinon** [comment]
Hi @viviskas,

I see that you've filed #445 regarding a security issue. I'll be closing this for now so that we can funnel our discussions on that ticket.

**Comment by paulinon** [comment]
Duplicate of #445
