### ISSUE TITLE
Failed to determine the most recently installed Android SDK version.

### ISSUE THREAD

**Issue by charles-mersereau** [googlesamples/unity-jar-resolver#451]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.9f1
  * External Dependency Manager version: 1.2.135.0
  * Source you installed EDM4U: .unitypackage 
  * Features in External Dependency Manager in use: not sure, just being made aware of its existence
  * Plugins SDK in use: Facebook
  * Platform you are using the Unity editor on: windows

### [REQUIRED] Please describe the issue here:
I imported the Facebook SDK package. After doing some setup, I restarted my machine and reopened my project. I got a prompt  saying Jetpack libraries are only available on API 28 but my project is targeting 25. It asks if I want to set target to 28, I click no.

After doing that, I see the following log in the console:

> Failed to determine the most recently installed Android SDK version. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25

#### Please answer the following, if applicable:
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
Not sure if there is any major issue here, just reporting as the log asked me to.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by paulinon** [comment]
Hi @charles-mersereau,

Could you try if setting the target to 28 resolves the issue? Take note that [targeting newer SDKs](https://developer.android.com/distribute/best-practices/develop/target-sdk#why-target) still allows your app to run on older Android versions with added security and performance improvements.

**Comment by charles-mersereau** [comment]
I'm actually no longer getting the prompt to update my target version or the console log about not being able to find the Android SDK. I'm not sure what fell into place as I was working yesterday to make that go away, but I can't reproduce it anymore.

I did notice that our target level was actually not set to 25. I'm not sure how it detected that number, but it was not correct.

I do however get an error when I try to use the Android SDK tools that come with Unity. When I have that preference set and I try to run, I get an error prompt.

> Failed To update Android SDK package list. See the Console for details.

The only relevant console log I could find says this:

> CommandInvokationFailure: Failed to update Android SDK package list.
> C:\Program Files\Unity\Hub\Editor\2020.3.9f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\cmdline-tools\latest\bin\sdkmanager.bat --list
> 
> stderr[
> Error: Could not find or load main class Files\Unity\Hub\Editor\2020.3.9f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\cmdline-tools\latest\bin\\..
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
> ]
> stdout[
> 
> ]
> exit code: 1

I don't know if this is related to the original issue or not. When I set the path to use the Android SDK that I have in Android Stuido, I no longer experience this issue. I tried finding solutions to this elsewhere online but nothing appeared relevant.

**Comment by paulinon** [comment]
HI @charles-mersereau,

I found a [community post](https://forum.unity.com/threads/failed-to-update-android-sdk-package-list-error-when-using-sdk-installed-with-unity.722777/) that talks about your recent issue, and it primarily talks about removing some environment variables. Could you try the steps there and see if they make a difference?

**Comment by charles-mersereau** [comment]
Just got around to trying the things on that post. Nothing there made a difference. 

As I said before, I  was able to work around the issue by setting my own Android SDK Tools path to the Android Studios path instead of the tools that come with Unity. It would be unfortunate to make everyone on my team download Android Studio and set a new path for their Android SDK Tools.

**Comment by paulinon** [comment]
Glad to hear that you've discovered a workaround for your issue, @charles-mersereau. With that, I'll be closing this for now. Let me know if you have any questions or if an issue arises.

**Comment by charles-mersereau** [comment]
Just in case someone comes along searching for answers, this is the actual solution the problem I was experiencing.

https://forum.unity.com/threads/failed-to-update-android-sdk-package-list.1086305/
