### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Kunruedee1993** [googlesamples/unity-jar-resolver#459]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * External Dependency Manager version: _____
  * Source you installed EDM4U: _____ (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: _____ (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: _____ (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)

### [REQUIRED] Please describe the question here:

**Comment by Kunruedee1993** [comment]
> This issue does not have all the information required by the template.  Looks like you forgot to fill out some sections.  Please update the issue with more information.

**Comment by KillitsGaming** [comment]
Unity editor version: unity 2020.3.15f1
External Dependency Manager version: _____
Source you installed EDM4U Unity Package Manager
Features in External Dependency Manager in use: Android Resolver
Plugins SDK in use: Facebook
Platform you are using the Unity editor on: Windows

Failed to determine the most recently installed Android SDK version

**Comment by paulinon** [comment]
Hi @Kunruedee1993,

I see that you've filed a ticket with just the issue template. With that, I'll be closing this ticket.

If you're facing an issue with the resolver on your Unity platform or if you have a feature that you want implemented, kindly include the necessary information in a new ticket.
