### ISSUE TITLE
[Question] Which files/folders will be generated fron EDM4U and should be put in gitignore

### ISSUE THREAD

**Issue by Thaina** [googlesamples/unity-jar-resolver#464]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.1
  * External Dependency Manager version: v1.2.166
  * Source you installed EDM4U: tgz
  * Features in External Dependency Manager in use: all
  * Plugins SDK in use: Firebase Facebook Onesignal
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the question here:

Since there would be a file that always generated and/or regenerated from EDM4U we wish we could exclude those from our repo to not pollute the codebase and could always make a fresh start cloning. I wish we would have template for gitignore or some guideline for those files and folders

`AndroidResolverDependencies.xml` seem very much one of it, but I cannot be sure about it

**Comment by paulinon** [comment]
Hi @Thaina,

Since EDM4U can easily be imported anytime. It's advisable to exclude all files generated from it. This way, it would be easier in handling updates to your dependencies.

I'll be closing this for now. Let me know if you have any other questions.

**Comment by Thaina** [comment]
@paulinon Thank you very much. But if it like so I wish there would be documented about all the files and/or pattern of files that would be generated with this package, at least `gitignore` on the `readme` page
