### ISSUE TITLE
[BUG] ARM64 excluded when building in BatchMode

### ISSUE THREAD

**Issue by huran438** [googlesamples/unity-jar-resolver#474]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: **2020.3.21f1 (LTS)**
  * External Dependency Manager version: **1.2.167**
  * Source you installed EDM4U: **.unitypackage**
  * Features in External Dependency Manager in use: **Android Resolver**
  * Plugins SDK in use: **NO PLUGINS**
  * Platform you are using the Unity editor on: **Windows**

### [REQUIRED] Please describe the issue here:
We have build machine based on TeamCity, this machine is building various types of builds. The types are:

- Debug (Mono, ARMv7, apk)
- Release (IL2CPP, ARMv7, ARM64, apk)
- Master (IL2CPP, ARMv7, ARM64, aab)

In our script we dynamically switching target architecture in script:

```
public static void BuildMaster()
    {
        Log("Started");

        if (!Validate()) return;

        UpdateVersion();

        AddressableAssetSettings.CleanPlayerContent();
        BuildCache.PurgeCache(false);
        AddressableAssetSettings.BuildPlayerContent();

        // Player Settings Setup

        PlayerSettings.SetScriptingBackend(EditorUserBuildSettings.selectedBuildTargetGroup,
            ScriptingImplementation.IL2CPP);

        PlayerSettings.Android.androidIsGame = true;

        PlayerSettings.Android.targetArchitectures = AndroidArchitecture.ARMv7 | AndroidArchitecture.ARM64;

        PlayerSettings.Android.useCustomKeystore = true;

        PlayerSettings.Android.minifyRelease = true;
        PlayerSettings.Android.minifyDebug = true;

        EditorUserBuildSettings.androidCreateSymbolsZip = true;

        PlayerSettings.Android.forceInternetPermission = false;

        EditorUserBuildSettings.buildAppBundle = true;

        PlayerSettings.SetArchitecture(BuildTargetGroup.Android,
            (int)(AndroidArchitecture.ARMv7 | AndroidArchitecture.ARM64));

        IncrementBuildVersion();

        PlayerSettings.SplashScreen.showUnityLogo = false;

        DefineSymbols.Add("FINAL_BUILD");

        // Build Player Options

        BuildPlayerOptions buildPlayerOptions = new BuildPlayerOptions
        {
            scenes = GetEnabledScenes(),
            locationPathName = GetFilePath(BuildType.Master),
            target = EditorUserBuildSettings.activeBuildTarget,
            options = BuildOptions.CompressWithLz4HC
        };

        //Start Build

        BuildFMODFiles();

        BuildPipeline.BuildPlayer(buildPlayerOptions);
        GenerateBuildReport(ref buildPlayerOptions);

        DefineSymbols.Remove("FINAL_BUILD");

        Log("Finished");
    }
```
After **MASTER** or **RELEASE** build finished i can see that symbols.zip contains both _arm64_ and _arm7_ debug symbols, but libraries in build are stripped. It looks like mainTemplate.gradle excludes arm64. But why? Also it's not cleared when GPSR regenerates mainTemplate.gradle (on which step? before building or after). I tried to call **Force Resolve** from code before build and after setting target platform architecture, but didn't find this method.

One interesting thing: everything works normally when we call our BuildMaster method manually from editor.

#### Please answer the following, if applicable:
**100%**

What happened? How can we make the problem occur?
![image](https://user-images.githubusercontent.com/1672637/139065534-106a3dac-7fff-4ba3-b443-a2b543fe9486.png)

**Comment by huran438** [comment]
@paulinon  Hello! Tried to reproduce issue on empty project, but cant reproduce it. Will write back in the next few days. Thanks for fast response!

**Comment by paulinon** [comment]
Hi @huran438,

Currently, I don't have enough information to replicate this behavior. It would be helpful if you can provide a sample project that demonstrates this issue so that we can analyze what's causing this.

**Comment by huran438** [comment]
Finally i found method `PlayServicesResolver.ResolveSync(true);` It resolved issue.
