### ISSUE TITLE
[Bug] Cocoapods 1.11.2 seems to be incompatible with how its run from unity

### ISSUE THREAD

**Issue by ShmulikArmon** [googlesamples/unity-jar-resolver#479]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.30 (happens on other versions as well)
  * External Dependency Manager version: 1.2.167
  * Source you installed EDM4U: unitypackage (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: iOS resolver (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: firbase, admob, facebook and more (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: Mac (osx 11.6) (Mac, Windows, or Linux)

### [REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

0. Make sure you have cocoapods 1.11.2 (latest at this time) installed (and that it is the one unity is using)
1. Open new project in unity
2. Create Dependencies xml under Editor with only ios pods and add this line - <iosPod name="Google-Mobile-Ads-SDK" version="8.10.0" minTargetSdk="10.0" />
3. Build for iOS

Expected : Cocoapods should run without an issue
Actual: Build fails, cocoapods gives message - 

> normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)

If I take the result xcode project and run pod install from my terminal, it passes. Also, if I downgrade to cocoapods 1.10.x it stops occuring, but this is not a great option. Another way I've just solved it was to add export LANG=en_US.UTF-8 to ~/.profile as suggested, but this is also not optimal - if I could suggest a solution, you could export this environment variable in the process of running "pod install" - just an idea

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)

Reproduces all the time.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Console log error -

> iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.
> 
> After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.
> 
> pod install output:
> 
> 
> 
>     [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
>     Consider adding the following to ~/.profile:
> 
>     export LANG=en_US.UTF-8
>     [0m
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `unicode_normalize'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `installation_root'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in `podfile_path'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:105:in `markdown_podfile'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:30:in `report'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in `report_error'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `load'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `unicode_normalize'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `installation_root'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in `podfile_path'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:205:in `podfile'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:46:in `run'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `load'
> 	from /usr/local/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'
> 
> 
> 
> pod repo update output:
> 
> Updating spec repo `amazonaws-cocoapods`
>   $ /usr/bin/git -C /Users/shmulika/.cocoapods/repos/amazonaws-cocoapods fetch origin --progress
>   $ /usr/bin/git -C /Users/shmulika/.cocoapods/repos/amazonaws-cocoapods rev-parse --abbrev-ref HEAD
>   master
>   $ /usr/bin/git -C /Users/shmulika/.cocoapods/repos/amazonaws-cocoapods reset --hard origin/master
>   HEAD is now at 39fa1fd8 [Update] TT_Plugins_Billing_Pod (3.5.0.95.18)
> Updating spec repo `amazonaws-v1-repos-cocoapods`
>   $ /usr/bin/git -C /Users/shmulika/.cocoapods/repos/amazonaws-v1-repos-cocoapods fetch origin --progress
>   $ /usr/bin/git -C /Users/shmulika/.cocoapods/repos/amazonaws-v1-repos-cocoapods rev-parse --abbrev-ref HEAD
>   master
>   $ /usr/bin/git -C /Users/shmulika/.cocoapods/repos/amazonaws-v1-repos-cocoapods reset --hard origin/master
>   HEAD is now at 39fa1fd8 [Update] TT_Plugins_Billing_Pod (3.5.0.95.18)
> Updating spec repo `cl-pod-repo`
> Updating spec repo `cocoapods`
> Updating spec repo `ironsource-mobile`
> Updating spec repo `ironsource-mobile-1`
> Updating spec repo `shmulmul`
> Updating spec repo `trunk`
> Updating spec repo `vungle`
> 
> 
>     [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
>     Consider adding the following to ~/.profile:
> 
>     export LANG=en_US.UTF-8
>     [0m
> 
> UnityEngine.Debug:LogError (object)
> Google.Logger:Log (string,Google.LogLevel) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:136)
> Google.IOSResolver:Log (string,bool,Google.LogLevel) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/IOSResolver/src/IOSResolver.cs:1159)
> Google.IOSResolver:OnPostProcessInstallPods (UnityEditor.BuildTarget,string) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/IOSResolver/src/IOSResolver.cs:2567)
> UnityEngine.GUIUtility:ProcessEvent (int,intptr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)
> 

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

Since it is very easy to reproduce i think uploading a unity project wont really help, if necessary sure I can upload it.

**Comment by ShmulikArmon** [comment]
I've copied the template as requested... im not sure why the bot fires the message above

**Comment by ShmulikArmon** [comment]
Just an update, I'm not sure this resolves this issue, but it is a good workaround for us - I found that setting the following fixes the problem for me -

`IOSResolver.PodToolExecutionViaShellEnabled = false;`

The issue I have with this solution is that it does not happen with cocoapods 1.10.x, only 1.11... and also when running through terminal which uses the same shell the issue does not reproduce.. so while this fixes my issue, i still think that setting this new required environment variable should be somewhere in the unity code of the plugin.

**Comment by paulinon** [comment]
Hi @ShmulikArmon,

Could you elaborate the second step in the procedure you listed? My initial understanding is that you need to manually create a Dependencies.xml with a specific line in a folder named "Editor".

**Comment by ShmulikArmon** [comment]
@paulinon exactly what you said - create the xml under the editor, here is my file -

`<dependencies>
  <iosPods>
    <sources>
      <source>https://s3.amazonaws.com/cl-cocoapods-repo</source>
    </sources>
    <iosPod name="Google-Mobile-Ads-SDK" version="8.10.0" minTargetSdk="10.0" />
  </iosPods>
</dependencies>`

**Comment by paulinon** [comment]
Thanks for the clarification, @ShmulikArmon. I haven't been able to replicate this issue so far, but it seems that the Google Mobile Ads SDK is needed. Are there any other SDKs that have to be imported or additional steps to perform in order to replicate the issue?

**Comment by rdominic** [comment]
Hey gang, I've stumbled across this issue today too. 

## Steps to replicate
1. Check you have Cocoapods `1.11.2` installed. Run `pod --version` in the Terminal
2. If you don't have `1.11.2` installed, run `sudo gem install cocoapods -v 1.11.2` in the Terminal
3. Create new Unity project
4. Import latest External Dependency Manager package (Currently 1.2.167)
5. Create xml file `Assets/Editor/PluginDependencies.xml` with contents pulling ANY cocoapod. E.g.
```
<dependencies>
<iosPods>
    <iosPod name="Alamofire" />
</iosPods>
</dependencies>
```
6. Build iOS
7. Observe console logs with error messages
<details>
  <summary>Error logs - Click to expand!</summary>

```
iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:



    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `unicode_normalize'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `installation_root'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in `podfile_path'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:105:in `markdown_podfile'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:30:in `report'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in `report_error'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `unicode_normalize'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `installation_root'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in `podfile_path'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:205:in `podfile'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:46:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'



pod repo update output:

Updating spec repo `cocoapods`
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/cocoapods fetch origin --progress
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/cocoapods rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/cocoapods reset --hard origin/master
  HEAD is now at 1dbea891ac11 [Add] ETCustomView 0.1.4
Updating spec repo `tapdaq`
Updating spec repo `tapdaq-1`
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/tapdaq-1 fetch origin --progress
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/tapdaq-1 rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/tapdaq-1 reset --hard origin/master
  HEAD is now at 870ecd1 [Update] Tapdaq (7.10.0)
Updating spec repo `tapjoy`
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/tapjoy fetch origin --progress
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/tapjoy rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/tapjoy reset --hard origin/master
  HEAD is now at 870ecd1 [Update] Tapdaq (7.10.0)
Updating spec repo `tapjoy-1`
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/tapjoy-1 fetch origin --progress
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/tapjoy-1 rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/[USERNAME]/.cocoapods/repos/tapjoy-1 reset --hard origin/master
  HEAD is now at b6e735f [Update] TapjoySDK (12.9.0-rc1)
Updating spec repo `trunk`


    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m
  remote: Enumerating objects: 18, done.        
  remote: Counting objects:   5% (1/18)        
  remote: Counting objects:  11% (2/18)        
  remote: Counting objects:  16% (3/18)        
  remote: Counting objects:  22% (4/18)        
  remote: Counting objects:  27% (5/18)        
  remote: Counting objects:  33% (6/18)        
  remote: Counting objects:  38% (7/18)        
  remote: Counting objects:  44% (8/18)        
  remote: Counting objects:  50% (9/18)        
  remote: Counting objects:  55% (10/18)        
  remote: Counting objects:  61% (11/18)        
  remote: Counting objects:  66% (12/18)        
  remote: Counting objects:  72% (13/18)        
  remote: Counting objects:  77% (14/18)        
  remote: Counting objects:  83% (15/18)        
  remote: Counting objects:  88% (16/18)        
  remote: Counting objects:  94% (17/18)        
  remote: Counting objects: 100% (18/18)        
  remote: Counting objects: 100% (18/18), done.        
  remote: Compressing objects:   5% (1/17)        
  remote: Compressing objects:  11% (2/17)        
  remote: Compressing objects:  17% (3/17)        
  remote: Compressing objects:  23% (4/17)        
  remote: Compressing objects:  29% (5/17)        
  remote: Compressing objects:  35% (6/17)        
  remote: Compressing objects:  41% (7/17)        
  remote: Compressing objects:  47% (8/17)        
  remote: Compressing objects:  52% (9/17)        
  remote: Compressing objects:  58% (10/17)        
  remote: Compressing objects:  64% (11/17)        
  remote: Compressing objects:  70% (12/17)        
  remote: Compressing objects:  76% (13/17)        
  remote: Compressing objects:  82% (14/17)        
  remote: Compressing objects:  88% (15/17)        
  remote: Compressing objects:  94% (16/17)        
  remote: Compressing objects: 100% (17/17)        
  remote: Compressing objects: 100% (17/17), done.        
  remote: Total 18 (delta 2), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     fb489cc204a8..1dbea891ac11  master     -> origin/master

UnityEngine.Debug:LogError (object)
Google.Logger:Log (string,Google.LogLevel) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:136)
Google.IOSResolver:Log (string,bool,Google.LogLevel) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/IOSResolver/src/IOSResolver.cs:1159)
Google.IOSResolver:OnPostProcessInstallPods (UnityEditor.BuildTarget,string) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/IOSResolver/src/IOSResolver.cs:2567)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```
</details>

Replicated with 2020.1.5, 2020.3.8 & 2021.2.1

## Workaround
### Downgrade cocoapods to `1.10.2`
In Terminal run `sudo gem install cocoapods -v 1.10.2` then build iOS in Unity again.

### Run pod update manually
In Terminal goto your xcode project, run `pod update`

**Comment by revolt3r** [comment]
I think the bot is confused. There is enough information in this thread to reproduce the issue.

**Comment by revolt3r** [comment]
Not sure which Cocoapod version UCB uses, but here are the versions I could find

UCB 
Xcode : 13.0
macOS : 11.6
Ruby : ruby-2.4.2

Local
Xcode : 13.1
macOS : macOS 12.1
CocoaPods : 1.11.2
Ruby : ruby 2.7.2p137
RubyGems : 3.1.4
