### ISSUE TITLE
[Bug] Verbose logging - spam, not work disable option

### ISSUE THREAD

**Issue by Temka193** [googlesamples/unity-jar-resolver#480]
* Unity editor version: 2020.3.14f1
  * External Dependency Manager version: 1.2.162, 1.2.167
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: GPGS, AppMetrica
  * Platform you are using the Unity editor on: Windows

The "Verbose logging" option in the "Google Version Handler Settings" window does not turn off (in menu Assets->External Dependency Manager->Version Handler->Settings)
Accordingly, I cannot turn off the spam logs that are thrown around every time the asset is imported.

Repro rate: 100%

What happened? How can we make the problem occur?
Unfortunately I don’t know, I just installed GPGS and Dependency Manager came with it.
I've already seen someone open a similar problem, but it could not be reproduced, so it was closed and advised to contact GPGS.
On the GPGS page, I found a similar issue, where they also told to contact the Dependency Manager, this is very funny, of course, but the problem needs to be solved.

If you cannot reproduce the problem, I will try to build a small project.

**Comment by paulinon** [comment]
HI @Temka193,

In order to identify what's causing this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project that's causing the issue?

**Comment by Temka193** [comment]
In this example, I try to check the "Verbose logging" checkbox, but after closing the window, it is cleared.
(In my project, the opposite happens, I uncheck this checkbox, but after closing it is checked again.)
https://user-images.githubusercontent.com/11135702/144470976-aec842b2-cf21-47b6-aef7-c5aca98c2af9.mp4

[New Unity Project.zip](https://github.com/googlesamples/unity-jar-resolver/files/7643874/New.Unity.Project.zip)

**Comment by paulinon** [comment]
HI @Temka193,

I've downloaded the project you provided, but I haven't encountered the issue even after importing the GPGS package. Is it possible for you to try and replicate this issue using a separate, blank project? If so, please provide the steps you've taken so I can analyze this behavior.

**Comment by Temka193** [comment]
Instructions for reproducing the bug:
1. Install Unity 2020.3.14f1
2. Create a new project from the "3D" template
3. Download Dependency Manager - https://github.com/googlesamples/unity-jar-resolver/raw/v1.2.167/external-dependency-manager-1.2.167.unitypackage
4. Import external-dependency-manager-1.2.167.unitypackage
5. Go to the menu item Assets-> External Dependency Manager-> Version Handler-> Settings
6. Try to change any checkboxes in the window that opens
7. Close the window and repeat step 5
8. If the checkboxes you changed are not saved, then the bug has been reproduced

**Comment by paulinon** [comment]
Hi @Temka193,

I wasn't able to replicate your issue using the steps you provided. I should point out that I'm using version 2021.2.3f1 of the Unity editor. Could you try updating your editor and see if the issue persists?

**Comment by Temka193** [comment]
I will of course check, but I cannot update the project to another version of Unity (

**Comment by paulinon** [comment]
Hi @Temka193, I recently tested using versions 2020.3.21f1 and 2020.3.23f1 of the editor on a Windows machine, and Verbose logging was still ticked for both instances. It's possible that updating your Unity editor would resolve the issue.

I look forward to your results.

**Comment by Temka193** [comment]
On Unity 2021.2.2f1 the bug is still reproducible.
How are these options saved? There may be some software installed on the computer.

**Comment by Temka193** [comment]
Ahah, I didn't know there was an ok button, I always clicked on the cross. Is it possible to turn off verbose logging from code?

**Comment by paulinon** [comment]
Hi @Temka193, 

Given that the resolver manages library dependencies, going to the settings is the way to do this. Is your feature something that you would like to see in a future release?

**Comment by Temka193** [comment]
Ah, I didn't know that it was saved to the project file, I thought in EditorPrefs.
In this case, there are no more questions, the issue can be closed. But make the window wider :)
