### ISSUE TITLE
[Bug] Non-secure network connections disabled in Player Settings

### ISSUE THREAD

**Issue by Thaina** [googlesamples/unity-jar-resolver#484]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.1.0b1
  * External Dependency Manager version: 1.2.168
  * Source you installed EDM4U: UPM tgz
  * Features in External Dependency Manager in use: Android Resolver + VersionHandler
  * Plugins SDK in use: -
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:

Weird error and warning while using EDM4U

![image](https://user-images.githubusercontent.com/1042507/145861629-d1c37ea8-65e2-4280-8fde-b456d8e68cf2.png)

It seem the config for using secure connection was needed to disabled to shut these error

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
- 100%

What happened? How can we make the problem occur?
- Just install and open unity editor and also every action that trigger

I suspect that this below might be the cause?

https://github.com/googlesamples/unity-jar-resolver/blob/d370ab8ef6c9199ae8d033c9d75e8f727e8b0c3d/source/VersionHandlerImpl/src/EditorMeasurement.cs#L516-L517

Any reason using `http` here though?

**Comment by paulinon** [comment]
Hi @Thaina,

In order to identify what's causing this, could you provide the complete steps needed to replicate the issue?

**Comment by Thaina** [comment]
@paulinon Just install 1.2.168 by tgz in 2022.1.0b1 android project then close and reopen project it will throw this error every time

I am not sure for your machine but I think default setting for `Allow HTTP` should be `Not Allowed` to cause this error

**Comment by chkuang-g** [comment]
@Thaina 

Thank you for reporting this issue.  Seems like Unity 2022 added some security feature which blocks the non-https web request.  I wonder why it used `http` in the first place.

At the meantime, as a workaround, I would recommend you to disable Analytics reporting from our editor tools for now. Here are all the settings:
- EDM4U: `Assets` > `External Dependency Manager` > `Version Handler` > `Settings` > `Enable Analytics Reporting`
- Firebase: `Windows` > `Firebase` > `Documentation` > `Enable Analytics Reporting` (At the very bottom)

**Comment by FranArjona** [comment]
I have followed the recommendation by @chkuang-g and it works well with Unity 2022.1.3f1.

However, in principle Unity is doing the right by blocking non-secure connections, so, please, someone should review the reason why this is using http instead of https, and upgrade it if possible.

**Comment by kd9696** [comment]
I am facing similar issues, apart from the workaround provided above, is there any progress on this issue?
