### ISSUE TITLE
[Bug] Unity Editor crashing on Android Build

### ISSUE THREAD

**Issue by revolt3r** [googlesamples/unity-jar-resolver#485]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.25f1
  * External Dependency Manager version: 1.2.168
  * Source you installed EDM4U: Package Manager .tgz tar
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Firebase, Facebook
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
Start an Android Build -> crashes
[Editor.log](https://github.com/googlesamples/unity-jar-resolver/files/7730465/Editor.log)

#### Please answer the following, if applicable:
100%

What happened? How can we make the problem occur?
Not sure, but I suppose it's something to do with Android SDK version

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

![image](https://user-images.githubusercontent.com/11783754/146450542-f5e288b3-73e7-4157-9ece-500f175b421a.png)

**Comment by revolt3r** [comment]
The project is quite large, I don't think I can provide a sample project, but let me know if I can send you any more info.

**Comment by paulinon** [comment]
Hi @revolt3r,

Thanks for reporting this issue. While you can't provide a minimal, reproducible example right now, could you verify if this issue persists using a blank project? If so, please provide the seps to replicate this behavior.

**Comment by revolt3r** [comment]
I've looked more into the issue and it seems like this Exception is not the cause of the crash. This exception might be already handled silently.
