### ISSUE TITLE
[Question] Should packages created in "Assets/Plugins" be tracked in source control or ignored?

### ISSUE THREAD

**Issue by guneyozsan** [googlesamples/unity-jar-resolver#490]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.34f1
  * External Dependency Manager version: 1.2.168
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Firebase Auth, Firebase Analytics
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the question here:

The resolver downloads packages to `Assets/Plugins/Android`. Should we include them in source control or exclude them (e.g. gitignore)?

(Also, note that GUIDs in `.meta` files are occasionally updated during the latter runs of the resolver caused by unrelated actions like config changes or switching platforms in Unity. This clutters the commit history of related feature.)

**Comment by paulinon** [comment]
Hi @guneyozsan,

It's recommended that you exclude the files generated by the resolver since it can easily be imported anytime. With this, it would be easier in handling updates to your dependencies.

I'll be closing this for now. Let me know if you have any other questions.

**Comment by guneyozsan** [comment]
Thank you @paulinon

**Comment by guneyozsan** [comment]
@paulinon Is there a similar situation with files in `Plugins/iOS`?
