### ISSUE TITLE
Unable to copy assets etc at: GooglePlayServices.PlayServicesResolver.CopyAssetAndLabel

### ISSUE THREAD

**Issue by oddgames-david** [googlesamples/unity-jar-resolver#492]
* Unity editor version: 2020.3.25f1
  * External Dependency Manager version: 1.2.168
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Firebase, Unity Mediation, OneSignal
  * Platform you are using the Unity editor on: Window

### [REQUIRED] Please describe the issue here:

Receiving the following error randomly on multiple build serveres:

[Error] Unable to copy Assets\Firebase\m2repository\com\google\firebase\firebase-analytics-unity\8.7.0\firebase-analytics-unity-8.7.0.srcaar to Assets\GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-analytics-unity\8.7.0\firebase-analytics-unity-8.7.0.aar.  Assets\GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-analytics-unity\8.7.0\firebase-analytics-unity-8.7.0.aar will not be included in Gradle builds. Reason: Cannot label Assets\GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-analytics-unity\8.7.0\firebase-analytics-unity-8.7.0.aar properly.
[Error] Unable to copy Assets\Firebase\m2repository\com\google\firebase\firebase-app-unity\8.7.0\firebase-app-unity-8.7.0.srcaar to Assets\GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-app-unity\8.7.0\firebase-app-unity-8.7.0.aar.  Assets\GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-app-unity\8.7.0\firebase-app-unity-8.7.0.aar will not be included in Gradle builds. Reason: Cannot label Assets\GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-app-unity\8.7.0\firebase-app-unity-8.7.0.aar properly.
[Error] Unable to copy Assets\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13\gpgs-plugin-support-0.10.13.srcaar to Assets\GeneratedLocalRepo\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13\gpgs-plugin-support-0.10.13.aar.  Assets\GeneratedLocalRepo\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13\gpgs-plugin-support-0.10.13.aar will not be included in Gradle builds. Reason: Failed to copy Assets\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13\gpgs-plugin-support-0.10.13.srcaar to Assets\GeneratedLocalRepo\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13\gpgs-plugin-support-0.10.13.aar due to System.IO.DirectoryNotFoundException: Destination directory not found: Assets\GeneratedLocalRepo\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00162] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName) [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at GooglePlayServices.PlayServicesResolver.CopyAssetAndLabel (System.String sourceLocation, System.String targetLocation, System.Boolean force) [0x0009e] in Z:\tmp\tmp.cvthQg1D2s\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2467 
[Error] Resolution Failed.

Unable to copy Assets\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13\gpgs-plugin-support-0.10.13.srcaar to Assets\GeneratedLocalRepo\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13\gpgs-plugin-support-0.10.13.aar.  Assets\GeneratedLocalRepo\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13\gpgs-plugin-support-0.10.13.aar will not be included in Gradle builds. Reason: Failed to copy Assets\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13\gpgs-plugin-support-0.10.13.srcaar to Assets\GeneratedLocalRepo\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13\gpgs-plugin-support-0.10.13.aar due to System.IO.DirectoryNotFoundException: Destination directory not found: Assets\GeneratedLocalRepo\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.10.13
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00162] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName) [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at GooglePlayServices.PlayServicesResolver.CopyAssetAndLabel (System.String sourceLocation, System.String targetLocation, System.Boolean force) [0x0009e] in Z:\tmp\tmp.cvthQg1D2s\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2467 
[Assert] Assertion failed on expression: 'newChildren.size() == numChildren - 1'
[Error] Error building Player: 4 errors

#### Please answer the following, if applicable:
What's the issue repro rate?
 30%

What happened? How can we make the problem occur?

I don't have any clue how to make it happen, I re-run the build a few times and eventually it works

**Comment by paulinon** [comment]
Hi @oddgames-david,

In order to identify what's causing this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the complete steps performed before facing the issue?
