### ISSUE TITLE
[Bug] Failed to determine the most recently installed Android SDK version.

### ISSUE THREAD

**Issue by alphacrutch** [googlesamples/unity-jar-resolver#493]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.25f1
  * External Dependency Manager version: _____
  * Source you installed EDM4U:  .unitypackage.
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use:Firebase, unity ads)
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
* Did a windows update that was geared toward .net 
* Had a Internet provider issue that caused unity to have one stale start up (editor did not start after selecting project in unity hub)
* Switched to a slower internet router to sign in to my account and access dashboard
* After being able to sign in, i made project modifications and proceeded to build project
* This is the first time i have encountered the issue

* Failed to determine the most recently installed Android SDK version. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25
0x00007ff617268bdc (Unity) StackWalker::GetCurrentCallstack
0x00007ff61726ffd9 (Unity) StackWalker::ShowCallstack
0x00007ff617fccd9c (Unity) GetStacktrace
0x00007ff618a15e83 (Unity) DebugStringToFile
0x00007ff6173202f6 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x00000184495127bb (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x000001844951270b (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x0000018449512490 (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x0000018548c0b048 (Mono JIT Code) UnityEngine.Debug:LogWarning (object)
0x0000018548c0afeb (Mono JIT Code) [UnityCompat.cs:312] GooglePlayServices.UnityCompat:WarnOnAndroidSdkFallbackVersion () 
0x00000184df15c65b (Mono JIT Code) [UnityCompat.cs:403] GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion () 
0x00000184df15ba7b (Mono JIT Code) [UnityCompat.cs:136] GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion () 
0x00000184df15b71b (Mono JIT Code) [PlayServicesResolver.cs:2681] GooglePlayServices.PlayServicesResolver:CheckApiLevelForJetifier (bool,string,System.Action`1<GooglePlayServices.PlayServicesResolver/ApiLevelJetifierResult>) 
0x00000184df15b5eb (Mono JIT Code) [PlayServicesResolver.cs:2749] GooglePlayServices.PlayServicesResolver/<CanEnableJetifierOrPromptUser>c__AnonStoreyF:<>m__0 (bool) 
0x00000184df15b412 (Mono JIT Code) [PlayServicesResolver.cs:2656] GooglePlayServices.PlayServicesResolver:CheckGradleVersionForJetifier (bool,string,System.Action`1<bool>) 
0x00000184df15b043 (Mono JIT Code) [PlayServicesResolver.cs:2747] GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser (string,System.Action`1<bool>) 
0x00000184df156a1b (Mono JIT Code) [PlayServicesResolver.cs:1752] GooglePlayServices.PlayServicesResolver:ResolveUnsafeAfterJetifierCheck (System.Action`1<bool>,bool,bool,bool) 
0x00000184df15682b (Mono JIT Code) [PlayServicesResolver.cs:1719] GooglePlayServices.PlayServicesResolver/<ScheduleResolve>c__AnonStorey5:<>m__0 () 
0x00000184df1566e3 (Mono JIT Code) [PlayServicesResolver.cs:1576] GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob () 
0x00000184df1563eb (Mono JIT Code) [PlayServicesResolver.cs:1732] GooglePlayServices.PlayServicesResolver:ScheduleResolve (bool,bool,System.Action`1<bool>,bool) 
0x000001844950136b (Mono JIT Code) [PlayServicesResolver.cs:1513] GooglePlayServices.PlayServicesResolver:ResolveOnAndroidSdkRootChange (object,GooglePlayServices.PlayServicesResolver/AndroidSdkRootChangedArgs) 
0x000001844950130e (Mono JIT Code) [PlayServicesResolver.cs:1502] GooglePlayServices.PlayServicesResolver:<PollAndroidSdkRoot>m__5 (string,string) 
0x00000184df150c3c (Mono JIT Code) [PlayServicesResolver.cs:359] GooglePlayServices.PlayServicesResolver/PropertyPoller`1<T_REF>:Poll (System.Func`1<T_REF>,GooglePlayServices.PlayServicesResolver/PropertyPoller`1/Changed<T_REF>) 
0x00000184df153beb (Mono JIT Code) [PlayServicesResolver.cs:1498] GooglePlayServices.PlayServicesResolver:PollAndroidSdkRoot () 
0x00000184df0b5e72 (Mono JIT Code) (wrapper delegate-invoke) <Module>:invoke_void ()
0x00000184df0b80e4 (Mono JIT Code) UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
0x0000018498d1ac4d (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007ffa6a8ff1e0 (mono-2.0-bdwgc) [mini-runtime.c:2849] mono_jit_runtime_invoke 
0x00007ffa6a882ac2 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007ffa6a88bb1f (mono-2.0-bdwgc) [object.c:2968] mono_runtime_invoke 
0x00007ff6171acd34 (Unity) scripting_method_invoke
0x00007ff6171a8011 (Unity) ScriptingInvocation::Invoke
0x00007ff6171a1e05 (Unity) ScriptingInvocation::Invoke<void>
0x00007ff6164673ab (Unity) Scripting::UnityEditor::EditorApplicationProxy::Internal_CallUpdateFunctions
0x00007ff6179efdef (Unity) SceneTracker::Update
0x00007ff617b8daea (Unity) Application::TickTimer
0x00007ff617fd34d1 (Unity) MainMessageLoop
0x00007ff617fd7521 (Unity) WinMain
0x00007ff619665752 (Unity) __scrt_common_main_seh
0x00007ffaba7d7034 (KERNEL32) BaseThreadInitThunk
0x00007ffabc1e2651 (ntdll) RtlUserThreadStart
#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%
What happened? How can we make the problem occur?
Two significant things i rememder i did a windows update January 11, 2022-KB5008876 Cumulative Update for .NET Framework 3.5 and 4.8 for Windows 10, version 20H2, Windows Server, version 20H2, Windows 10 Version 21H1, and Windows 10 Version 21H2.

Just imported Firebase version .net4 Analytics, Authentication, Firestore and Installations packages.
Implemented Signin and login firebase features and a test for Firestore. All Functions were tested and working. Decided to do a build to test on phone. Encountered the Issue during build

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by paulinon** [comment]
Hi @alphacrutch,

This is likely related to your Unity configuration. Later versions of the editor usually require a minimum API version of 19. It's recommended that you use OpenJDK and Android SDK installed through Unity Hub. Otherwise, if you like to use your own, please make sure the required version is installed and set correctly in your Preferences > External Tools.

Could you try this solution and see if the issue persists or if it suits your use case?
