### ISSUE TITLE
Warning that stops Force Resolving on 100 % in Unity

### ISSUE THREAD

**Issue by DNK-Creator** [googlesamples/unity-jar-resolver#497]
* Unity editor version: 2021.2.8f1
  * External Dependency Manager version: 1.2.168
  * Source you installed EDM4U:
  * Features in External Dependency Manager in use: Android Resolve
  * Plugins SDK in use: 
  * Platform you are using the Unity editor on: Windows

Hey everyone, I have a warning when I try to force resolve my game, it stops on 100% and then nothing is happening. 

Some conflicting dependencies were found.
The following dependency versions were modified:
com.google.games:gpgs-plugin-support:0.10.13 --> com.google.games:gpgs-plugin-support:+

UnityEngine.Debug:LogWarning (object)
Google.Logger:Log (string,Google.LogLevel) (at Z:/tmp/tmp.wzz20lkBKd/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/Logger.cs:129)
GooglePlayServices.PlayServicesResolver:Log (string,Google.LogLevel) (at Z:/tmp/tmp.cvthQg1D2s/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1055)
GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey1:<>m__2 (GooglePlayServices.CommandLine/Result) (at Z:/tmp/tmp.cvthQg1D2s/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:473)
GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey1/<GradleResolution>c__AnonStorey3:<>m__0 () (at Z:/tmp/tmp.cvthQg1D2s/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:572)
Google.RunOnMainThread:ExecuteNext () (at Z:/tmp/tmp.wzz20lkBKd/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:486)
Google.RunOnMainThread:<ExecuteAllUnnested>m__1 () (at Z:/tmp/tmp.wzz20lkBKd/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:536)
Google.RunOnMainThread:RunAction (System.Action) (at Z:/tmp/tmp.wzz20lkBKd/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested (bool) (at Z:/tmp/tmp.wzz20lkBKd/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:ExecuteAll () (at Z:/tmp/tmp.wzz20lkBKd/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:512)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by paulinon** [comment]
Hi @DNK-Creator,

Thanks for reporting this issue. In order to identify what's causing this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the complete steps to replicate this behavior?

**Comment by DNK-Creator** [comment]
> Hi @DNK-Creator,
> 
> Thanks for reporting this issue. In order to identify what's causing this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the complete steps to replicate this behavior?

Hi! Thank you for your reply. I will attach screenshots of what I think can be the problem, I imagine there is something wrong with my gradle file or android resolver settings. I also tried it without default gradle that Unity sets, but it just doesnt build. Also maybe android manifest file could tell something?
![Unity_ZjJHN0sgtl](https://user-images.githubusercontent.com/97904851/150513044-595c0b06-d039-4425-850a-b86b754791f7.png)
![Unity_EPwYyHdkQP](https://user-images.githubusercontent.com/97904851/150513060-d6c04661-0c3c-4fb2-82a2-d7a7c98652ad.png)
![Unity_pVH6qgGUT0](https://user-images.githubusercontent.com/97904851/150513075-edf975c6-200b-41c2-9d12-54e1abe956b2.png)

**Comment by DNK-Creator** [comment]
Its also combines with my google play services not working error. This thing is just a warning and I can build a project, but in the other thread nothing showing up: check this - https://github.com/playgameservices/play-games-plugin-for-unity/issues/3111

**Comment by DNK-Creator** [comment]
> Hi @DNK-Creator,
> 
> Thanks for reporting this issue. In order to identify what's causing this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the complete steps to replicate this behavior?

Actually every code line is passing me to my android manifest, maybe something wrong in there? I will attach screenshot of it and the log as an image.
![image](https://user-images.githubusercontent.com/97904851/150523676-e3fbdb88-410b-46c3-8655-f3a64e729d4d.png)

![image](https://user-images.githubusercontent.com/97904851/150523535-0a4dc7d8-0921-462f-9c7d-542a4bde5888.png)

**Comment by DNK-Creator** [comment]
I fixed it by deleting all files connected to google play services
Then importing plugin from github once again and then force resolve works fine.
