### ISSUE TITLE
Resolver improperly handles play-services-basement

### ISSUE THREAD

**Issue by rhyok** [googlesamples/unity-jar-resolver#5]
Hey all,

I'm working on a project that with a plugin utilizes your resolver for grabbing the appropriate libs from Google Play. Problem is this: Google distributes a library which seems like it's undocumented called "play-services-basement". From what I could gather with some Google-Fu, this is either an extension of play-services-base or a minimal version of base that is required for using certain services libs. Either way, it's required for the ad networks we're working with, as it seems to contain a class called "GooglePlayServicesUtil" which the advertising libraries use to get advertising IDs.

Your resolver removes copies of this file as part of resolving the needed JARs, which has been breaking our app. Some sites call basement a dependency of base, so I'm confused why it wouldn't be included whenever base is included.

Additionally, the resolver does not even seem to be aware of the existence of basement. If I try to force an import by requesting it by name using code like: 

```
var svcSupport = PlayServicesSupport.CreateInstance( PluginName, EditorPrefs.GetString( "AndroidSdkRoot" ), "ProjectSettings" );
svcSupport.DependOn( "com.google.android.gms", "play-services-basement", "8.4+" );
```

the resolver does not indicate an error has occurred, but does not add the library and will remove it from my project if it is there.

If I'm totally misinformed about what basement is, then I apologize, but it certainly seems like it doesn't collide with any other of the services libs and is an integral part of Play Services that people depend on. Please do let me know what should be done here if I'm mistaken about how to use these libraries.

**Comment by rhyok** [comment]
Just as a follow-up: the POM for the version of Play Services we're running with lists basement as a dependency:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.google.android.gms</groupId>
  <artifactId>play-services-base</artifactId>
  <version>8.4.0</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-basement</artifactId>
      <version>8.4.0</version>
      <scope>compile</scope>
      <type>aar</type>
    </dependency>
  </dependencies>
</project>
```
so again, I'm confused why it's not being added.

**Comment by maksimonishchenko** [comment]
just tried to use the plugin there very important to keep an eye on the GoogleDependencies_pluginname_.xml in PorjectSettings folder i think the plugin doesnt clean it up properly sometimes and fill it up after renaming of the plugin in settings file or updating the dependencies. so try to explore it and makesure it contains the dependencies you need

**Comment by rhyok** [comment]
@maksimonishchenko:

So, the .xml file in question looks correct to me: 

```
<dependencies>
	<dependency>
		<groupId>com.google.android.gms</groupId>
		<artifactId>play-services-ads</artifactId>
		<version>8.4+</version>
	</dependency>
	<dependency>
		<groupId>com.google.android.gms</groupId>
		<artifactId>play-services-basement</artifactId>
		<version>8.4+</version>
	</dependency>
</dependencies>
```

I am specifically requesting the basement library and the resolver does nothing with it and deletes it like I said in my original post.

Even if this wasn't happening, I'd still consider what you said to be a bug. If the program isn't generating the proper dependencies in the XML, or it's creating a mess in its own generated files that it cannot resolve, those are both problems that should be fixed!

**Comment by prime31** [comment]
I have confirmed this as a bug as well. Very easy to repro this:

- `DependOn( "com.google.android.gms", "play-services-ads", "8.4+" )`
- `DependOn( "com.google.android.gms", "play-services-games", "8.4+" )`
- `DependOn( "com.google.android.gms", "play-services-plus", "8.4+" )`

This combo requires the basement but it does not get added. Even worse, if you manually stick play-services-basement-8.4.0.aar in the project it will get deleted by Jar Resolver. The temporary workaround is to add `play-services-basement-8.4.0.aar` but name it something different so Jar Resolver leaves it alone.
