### ISSUE TITLE
Support for Ivy version ranges [Feature Request]

### ISSUE THREAD

**Issue by jkasten2** [googlesamples/unity-jar-resolver#50]
For example depending on Google Play services from versions 9.0.0 inclusive and 10.2.0 exclusive.
```
[9.0.0,10.2.0)
```

Gradle supports Ivy version ranges, the spec for this noted below.
http://ant.apache.org/ivy/history/2.1.0/settings/version-matchers.html

Support for this means that multiple plugins would run into less conflict issues as this resolver could use a version of that fits within multiple plugin's defined decency ranges.

**Comment by stewartmiles** [comment]
This is almost there now we've changed the resolution to use Gradle to download dependencies.  The remaining issue is that we have a load of code that parses artifacts group / name / versions to see whether dependencies are present before deciding to run Gradle (as it's slow).  If you're game, it would be great to see if you could patch the code that determines the current set of dependencies vs. what's required to finish this up ;)
