### ISSUE TITLE
[Bug] Failed to extract Android SDK Platform version from string 'Tiramisu'

### ISSUE THREAD

**Issue by Galiastr** [googlesamples/unity-jar-resolver#503]
### Environment setup
  * Unity editor version: 2019.2.21f1
  * External Dependency Manager version: 1.2.169
  * Source you installed EDM4U: .unitypackage (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: Android Resolver (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: OneSignal (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)

### Steps to reproduce
- Create new empty project
- Import latest OneSignal sdk for Push Notifications from official website
- Import .unitypackage of External Dependency Manager downloaded from official Google developers website.
- Force Resolve
- You will see an error log and nothing happens.
_Failed to extract Android SDK Platform version from string 'Tiramisu', 
Input string was not in a correct format.
System.Threading.ThreadHelper:ThreadStart()_
![image](https://user-images.githubusercontent.com/2443503/154450212-027dc95a-37dd-4971-9d53-5680dc86bf4b.png)

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
Log from console in Warnings section.

**Comment by paulinon** [comment]
Hi @Galiastr,

Thanks for reporting this. I recommend that you make use of an updated version of the Unity editor (the latest LTS release  is version 2020.3.28f1) as this behavior tends to appear in older versions of the Unity editor. 

That being said, I'll be closing this for now. Let me know if an issue arises.
