### ISSUE TITLE
I found a few problems with this issue:

### ISSUE THREAD

**Issue by Mercadojale** [googlesamples/unity-jar-resolver#517]
I found a few problems with this issue:
  * I couldn't figure out how to label this issue, so I've labeled it for a human to triage. Hang tight.
  * This issue does not seem to follow the issue template. Make sure you provide all the required information.

_Originally posted by @google-oss-bot in https://github.com/firebase/quickstart-unity/issues/1271#issuecomment-1124495423_

**Comment by paulinon** [comment]
Hi @Mercadojale, 

It seems that you've posted a comment from the issue you mentioned. I'll be closing this for now. Please file a new ticket containing the needed information whether for a new feature or an issue you've spotted in the resolver.
