### ISSUE TITLE
AndroidResolverDependencies.xml files section is empty

### ISSUE THREAD

**Issue by alienniki** [googlesamples/unity-jar-resolver#522]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.29
  * External Dependency Manager version: [1.2.171
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: firebase, gpgs, google-signin
  * Platform you are using the Unity editor on: Mac

### [REQUIRED] Please describe the issue here:
Project build from Jenkins.
Settings:
![GvhProjectSettings](https://user-images.githubusercontent.com/17922791/170940361-03685cfc-ae9d-4049-a506-5614d57c6ec7.png)
mainTemplate.gradle
![MainTemplate gradle](https://user-images.githubusercontent.com/17922791/170944013-c6014256-059d-4874-8921-31726f35167c.png)
Dependencies in repo:
![AndroidResolverDependencies-repo](https://user-images.githubusercontent.com/17922791/170940780-a3047cf9-7f6a-43d8-9d02-5f45b9e710aa.png)
Files aar in repo:
![Aar-repo](https://user-images.githubusercontent.com/17922791/170941065-972d05a1-439c-4ddd-9a9a-e0e1c62d5d8c.png)
After build:
![AndroidResolverDependencies](https://user-images.githubusercontent.com/17922791/170941314-7650b126-8e2e-4283-8131-fc92ba99f5a4.png)
files section is empty

In build dir many Cached repo folders
![Build-dir-ater](https://user-images.githubusercontent.com/17922791/170942072-a0e7ae5f-041c-4da7-9b32-8346c8fa9f36.png)
![Build-dir-ater2](https://user-images.githubusercontent.com/17922791/170942082-5806da5e-11ee-44ab-a88b-ea9354c6113f.png)
![Build-dir-ater3](https://user-images.githubusercontent.com/17922791/170942085-78135d52-b500-4d94-964d-4b00d230e6e9.png)
![Build-dir-ater4](https://user-images.githubusercontent.com/17922791/170942087-bd9de1d1-3b50-485a-b8f6-501460dde3d0.png)

all folders with no files

If a delete resolved dependencies and Force resolve from Unity and run build, i got success build.
If i clone sources from repo and run build, i got failed. Automatic resolve from build not worked correctly.

Logs when invalid build:
![Gradle Faild](https://user-images.githubusercontent.com/17922791/170943771-80505599-0211-4ed2-a61b-cb5a3bd34a9c.png)

#### Please answer the following, if applicable:
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
Log is big, I can provide the necessary parts

**Comment by paulinon** [comment]
Hi @alienniki,

Thanks for reporting this. In order to identify what's causing this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the complete steps to replicate the issue?
