### ISSUE TITLE
[Bug] Podfile is not regenerated correctly after I've removed the relevant Dependencies.xml file in the project

### ISSUE THREAD

**Issue by jacattrongnlh** [googlesamples/unity-jar-resolver#529]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.18
  * External Dependency Manager version: 1.2.171
  * Source you installed EDM4U: .unitypackage (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: iOS Resolver (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: Admob, Admob Mediation for Facebook Audience Network, AppLovin's MAX, MAX Mediation for Facebook Audience Network
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)

### [REQUIRED] Please describe the issue here:
- Make Unity Project
- Add Admob SDK, Admob Mediation for FAN.
- Add AppLovin MAX SDK, integrate MAX Mediation for FAN.
- File > Build Setting > Build (tried both Append and Replace).
- Unity report error:
```
iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "FBAudienceNetwork":
  In Podfile:
    AppLovinMediationFacebookAdapter (= 6.11.1.0) was resolved to 6.11.1.0, which depends on
      FBAudienceNetwork (= 6.11.1)

    GoogleMobileAdsMediationFacebook (= 6.10.0.0) was resolved to 6.10.0.0, which depends on
      FBAudienceNetwork (= 6.10.0)
```

The content of the generated Podfile in XCode folder:
```
source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'AppLovinMediationAdColonyAdapter', '4.9.0.0.0'
  pod 'AppLovinMediationFacebookAdapter', '6.11.1.0'
  pod 'AppLovinMediationGoogleAdapter', '9.6.0.1'
  pod 'AppLovinSDK', '11.4.2'
  pod 'Firebase/Analytics', '9.1.0'
  pod 'Firebase/Core', '9.1.0'
  pod 'Firebase/Crashlytics', '9.1.0'
  pod 'Firebase/Messaging', '9.1.0'
  pod 'Firebase/RemoteConfig', '9.1.0'
  pod 'FirebaseInstallations'
  pod 'GoogleMobileAdsMediationFacebook', '6.10.0.0'
  pod 'GoogleMobileAdsMediationIronSource', '7.2.1.2.0'
  pod 'GoogleMobileAdsMediationUnity', '4.2.1.0'
  pod 'Google-Mobile-Ads-SDK', '~> 9.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
```

The .xcworkspace file is not generated in the XCode folder.
- Delete the file: `Assets/GoogleMobileAds/Editor/FacebookMediationDependencies.xml` to remove Admob Mediation for FAN to fix the conflict.
- File > Build Setting > Build (tried both Append and Replace).
- Still get the above error. The content of the Podfile remains the same, it still contain the line `pod 'GoogleMobileAdsMediationFacebook', '6.10.0.0'`

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
Expected result: When I deleted the file `Assets/GoogleMobileAds/Editor/FacebookMediationDependencies.xml` in Unity project, the generated Podfile should no longer contain the line `pod 'GoogleMobileAdsMediationFacebook', '6.10.0.0'`.

**Comment by jacattrongnlh** [comment]
I tried to fix it by deleting cocoapod's downloaded files, restart my computer, then build to replace XCode. The issue is gone, the Podfile was generated with correct dependencies and xcworkspace was generated. I can no longer replicate the error.

**Comment by paulinon** [comment]
Thanks for the update, @jacattrongnlh. Glad to hear that the issue has been resolved. 

I'll be closing this for now. Let me know if an issue arises.
