### ISSUE TITLE
[Bug] Prompt Before Auto-Resolution cannot be activated

### ISSUE THREAD

**Issue by Francesco-FL** [googlesamples/unity-jar-resolver#531]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.36f1
  * External Dependency Manager version: 1.2.171
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Admob
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
When I activate "Prompt Before Auto-Resolution" and then confirm, it is not saved.
When I go back into the Android settings of the EDM, I always find Prompt Before Auto-Resolution turned off.

![Immagine 2022-06-30 164814](https://user-images.githubusercontent.com/83022092/176709197-d4f6c91d-d6ac-4cb3-8a2b-89018f2a6c11.png)

#### Please answer the following, if applicable:
What's the issue repro rate? 100%

**Comment by paulinon** [comment]
Hi @Francesco-FL,

I'm able to save `Prompt Before Auto-Resolution` on my end. Were you able to click 'Ok'? Are there other steps performed before going back to your Android Settings?
