### ISSUE TITLE
[Bug] mainTemplate.gradle and ProjectSettings/AndroidResolverDependencies.xml change when switching between building Android build and exporting Android project

### ISSUE THREAD

**Issue by marekzd** [googlesamples/unity-jar-resolver#537]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.17f1
  * External Dependency Manager version: 1.2.171
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Firebase, Facebook
  * Platform you are using the Unity editor on: Mac

### [REQUIRED] Please describe the issue here:

1. Open Unity project
2. Switch to Android target
3. Build for Android

    _mainTemplate.gradle_ will look like this:
    ```groovy
    def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
    maven {
        url (unityProjectPath + "/Assets/GeneratedLocalRepo/Firebase/m2repository") // Assets/Firebase/Editor/AnalyticsDependencies.xml:18, Assets/Firebase/Editor/AppDependencies.xml:22, Assets/Firebase/Editor/CrashlyticsDependencies.xml:20, Assets/Firebase/Editor/DynamicLinksDependencies.xml:20
    }
    ```
    
    and generated _unityLibrary/build.gradle_ will look like this:
    ```groovy
    def unityProjectPath = $/file:////Users/marekzd/Documents/projects/unity-project/$.replace("\\", "/")
    maven {
        url (unityProjectPath + "/Assets/GeneratedLocalRepo/Firebase/m2repository") // Assets/Firebase/Editor/AnalyticsDependencies.xml:18, Assets/Firebase/Editor/AppDependencies.xml:22, Assets/Firebase/Editor/CrashlyticsDependencies.xml:20, Assets/Firebase/Editor/DynamicLinksDependencies.xml:20
    }
    ```

    additionally _ProjectSettings/AndroidResolverDependencies.xml_ will change to:
    ```xml
    <setting name="projectExportEnabled" value="False" />
    ```

4. Export Android project to Android Studio

    _mainTemplate.gradle_ will change to:
    ```groovy
    def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
    maven {
        url "file:////Users/marekzd/Documents/projects/unity-project/Assets/GeneratedLocalRepo/Firebase/m2repository" // Assets/Firebase/Editor/AnalyticsDependencies.xml:18, Assets/Firebase/Editor/AppDependencies.xml:22, Assets/Firebase/Editor/CrashlyticsDependencies.xml:20, Assets/Firebase/Editor/DynamicLinksDependencies.xml:20
    }
    ```

    and _unityLibrary/build.gradle_ in exported project will look like this:
    ```groovy
    def unityProjectPath = $/file:////Users/marekzd/Documents/projects/unity-project/$.replace("\\", "/")
    maven {
        url "file:////Users/marekzd/Documents/projects/unity-project/Assets/GeneratedLocalRepo/Firebase/m2repository" // Assets/Firebase/Editor/AnalyticsDependencies.xml:18, Assets/Firebase/Editor/AppDependencies.xml:22, Assets/Firebase/Editor/CrashlyticsDependencies.xml:20, Assets/Firebase/Editor/DynamicLinksDependencies.xml:20
    }
    ```

    additionally _ProjectSettings/AndroidResolverDependencies.xml_ will change to:
    ```xml
    <setting name="projectExportEnabled" value="True" />
    ```

5. When you will build for Android once again _mainTemplate.gradle_ and _ProjectSettings/AndroidResolverDependencies.xml_  will change once again.

Would it be possible to avoid changing these files during building ?
These changes frequently ends up in random commits and obscure them.

Would it be possible to always use `unityProjectPath` in _mainTemplate.gradle_ generated code ?

Here seems to be a [code](https://github.com/googlesamples/unity-jar-resolver/blob/master/source/AndroidResolver/src/PlayServicesResolver.cs#L2145) responsible for these changes in _mainTemplate.gradle_.

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by chkuang-g** [comment]
Hi @marekzd 

Hmm, after reading the change https://github.com/googlesamples/unity-jar-resolver/commit/7d84e3bfd77f2d7efca73ff46d4d9d729d8af362 again, I _THINK_ we might be able to always use `unityProjectPath`, no matter it is exported project or not.  I cannot recall why I used absolute path by that time.  It could be oversight or to handle for certain configuration. 

We will need to verify the following scenario just in case the change still works for all scenario

- In Unity 2018 and 2019
- Build without exporting
- Build with exporting under the same Unity project
- Build with exporting under a different location to the Unity project.

We may need to schedule some time in the future to verify this.  

Or feel free to send us a Pull Request about this change and also help the community to verify if the change works in the scenario describe above.

**Comment by chkuang-g** [comment]
Oh, also, `ProjectSettings/AndroidResolverDependencies.xml ` and `unityLibrary/build.gradle` are not changed by EDM4U but by Unity.

It is probably not a good idea to version control these two files.

**Comment by chkuang-g** [comment]
Also, `unityLibrary/build.gradle` is not created by EDM4U but by Unity based on `mainTemplate.gradle`.  It might not be a good idea to version control this file if this project may be downloaded to a different workstation because `def unityProjectPath = $/file:////Users/marekzd/Documents/projects/unity-project/$.replace("\\", "/")` may not be valid on a different workstation.

As for `AndroidResolverDependencies.xml`, while it is generated by EDM4U, it is probably not a good idea to version control it since this is a cached dependency resolution file specifically for the workstation.
