### ISSUE TITLE
How do I remove this unity-jar-resolver?

### ISSUE THREAD

**Issue by tleylan** [googlesamples/unity-jar-resolver#546]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.10fl_____
  * External Dependency Manager version: 1.2.272_____
  * Source you installed EDM4U: _.unitypackage____ (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: _Android Resolver____ (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: _none____ (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: Windows_____ (Mac, Windows, or Linux)

### [REQUIRED] Please describe the question here:
I installed it because I was getting gradle errors for no apparent reason and now I'm getting sharing violations on GvhProjectSettings.xml. I just need to know the steps to remove it completely.
Thanks.

**Comment by tleylan** [comment]
I deleted the ExternalDependencyManager folder from the project. If that is all then I'm good.

**Comment by paulinon** [comment]
Hi @tleylan,

Deleting the folder is the way to go since it contains the relevant files. You can see its contents before importing the .unitypackage file.

That said, I'll be closing this for now. Let me know if an issue arises.
