### ISSUE TITLE
Android delete libraries or force resolve doesn't work properly

### ISSUE THREAD

**Issue by MH2B** [googlesamples/unity-jar-resolver#563]
When I try to us this tools there is not any error messages even when I use force resolve it says it was successful but nothing has changed in the project. I am using the latest version of the SDK but still have the same issue.

**Comment by paulinon** [comment]
Hi @MH2B,

I understand that your issue that can't be remedied by force resolving persists in your implementation. It would be great if you provide the needed information as indicated in the issue template. Once you've gathered them, kindly include these in a new ticket. Thanks!
