### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by ant5033** [googlesamples/unity-jar-resolver#566]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.1f1
  * External Dependency Manager version: 9.6.0
  * Source you installed EDM4U: unitypackage 
  * Features in External Dependency Manager in use:Android Resolver
  * Plugins SDK in use: google SDK(GPGS + AdMob + Firebase + assetdelivery + review)
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the question here:

![111](https://user-images.githubusercontent.com/80405495/196608061-7f91ee3f-2fe6-4aa5-86c4-c45142a90be8.png)

After importing Google SDKs,
These logs will occur
Is the log editable in SDK settings?
Or is it a log that can be edited in Unity editor?

**Comment by paulinon** [comment]
Hi @ant5033,

Thanks for providing additional information. While I try to reproduce this, could you confirm if you've ticked anything in your `Player Settings > Publishing Settings`? I'm guessing that a custom file related to your build is causing these logs to appear.

**Comment by ant5033** [comment]
> Hi @ant5033,안녕하세요 @ant5033님
> 
> Thanks for providing additional information.추가 정보를 제공해 주셔서 감사합니다. While I try to reproduce this, could you confirm if you've ticked anything in your 제가 이걸 재현하려고 하는 동안, 혹시 제 머리에 체크 마크가 붙어 있지 않은지 확인해 주시겠어요?`Player Settings > Publishing Settings`? I'm guessing that a custom file related to your build is causing these logs to appear.빌드 관련 커스텀파일이 원인으로, 이러한 로그가 표시되는 것이 원인이라고 생각됩니다.

Thank you! I think I solved it thanks to you!
