### ISSUE TITLE
[Question] Dependency issues with this com.google.ads.mediation:facebook package

### ISSUE THREAD

**Issue by iamfrankjie** [googlesamples/unity-jar-resolver#569]
* Unity editor version: ___2020.3.25f1__
  * External Dependency Manager version: __1.2.171___
  * Source you installed EDM4U: _Unity Package Manager_Unity Package Manager
  * Features in External Dependency Manager in use: _Android Resolver Android Resolver (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: __Admob__ (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: _Windows_ (Mac, Windows, or Linux)

Hi,
I downloaded com.google.ads.mediation:facebook:6.10.0.0 through EDM4U, but the download prompted a conflict and I ended up downloading com.google.ads.mediation:facebook:6.11.0.1. 
When I download the 6.10.0.0 dependency via gradle in Android studio, it works fine.
Attached is the relevant log of my test.
1. Why is it upgraded to 6.11.0.1 and why is there a conflict with just one dependency package?
2. When this package is combined with other packages that depend on it, it becomes even worse, I have downloaded various alpha versions of the package, is there a good way to solve it?

**cmd:**
`
E:\xxx\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "E:\xxx\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=E:\Env\Android\Sdk" "-PTARGET_DIR=E:\xxx\Assets\Plugins\Android" "-PMAVEN_REPOS=https://maven.google.com/;https://repo.maven.apache.org/maven2/;https://dl.google.com/dl/android/maven2/" "-PPACKAGES_TO_COPY=com.google.ads.mediation:facebook:6.10.0.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=4.0.1" 
`

**export log:**
`
> Configure project :
ANDROID_HOME: E:\Env\Android\Sdk
MAVEN_REPOS: name=Google url=https://dl.google.com/dl/android/maven2/
MAVEN_REPOS: name=maven url=https://dl.google.com/dl/android/maven2/
MAVEN_REPOS: name=maven2 url=https://dl.google.com/dl/android/maven2/
MAVEN_REPOS: name=MavenRepo url=https://repo.maven.apache.org/maven2/
PACKAGES_TO_COPY: com.google.ads.mediation:facebook:6.10.0.0
TARGET_DIR: E:\xxx\Plugins\Android
Resolution attempt 1: packages [com.google.ads.mediation:facebook:6.10.0.0]
com.google.android.gms:play-services-ads-base conflicting due to package(s):
- com.google.ads.mediation:facebook:6.10.0.0/com.google.android.gms:play-services-ads:20.6.0/com.google.android.gms:play-services-ads-base:[20.6.0]
- com.google.ads.mediation:facebook:6.10.0.0/com.google.android.gms:play-services-ads:20.6.0/com.google.android.gms:play-services-ads-lite:[20.6.0]/com.google.android.gms:play-services-ads-base:[20.6.0]
com.google.android.gms:play-services-ads-identifier conflicting due to package(s):
- com.google.ads.mediation:facebook:6.10.0.0/com.google.android.gms:play-services-ads:20.6.0/com.google.android.gms:play-services-ads-identifier:17.0.0
- com.google.ads.mediation:facebook:6.10.0.0/com.google.android.gms:play-services-ads:20.6.0/com.google.android.gms:play-services-ads-lite:[20.6.0]/com.google.android.ump:user-messaging-platform:1.0.0/com.google.android.gms:play-services-ads-identifier:17.0.0
-
....
....
....
....
> Task :copyPackages
Copied artifacts:
androidx.annotation.annotation-1.3.0.jar
androidx.annotation.annotation-experimental-1.1.0.aar
androidx.arch.core.core-common-2.1.0.jar
androidx.arch.core.core-runtime-2.1.0.aar
androidx.asynclayoutinflater.asynclayoutinflater-1.0.0.aar
androidx.browser.browser-1.4.0.aar
androidx.collection.collection-1.1.0.jar
androidx.concurrent.concurrent-futures-1.0.0.jar
androidx.coordinatorlayout.coordinatorlayout-1.0.0.aar
androidx.core.core-1.6.0.aar
androidx.cursoradapter.cursoradapter-1.0.0.aar
androidx.customview.customview-1.0.0.aar
androidx.documentfile.documentfile-1.0.0.aar
androidx.drawerlayout.drawerlayout-1.0.0.aar
androidx.fragment.fragment-1.0.0.aar
androidx.interpolator.interpolator-1.0.0.aar
androidx.legacy.legacy-support-core-ui-1.0.0.aar
androidx.legacy.legacy-support-core-utils-1.0.0.aar
androidx.lifecycle.lifecycle-common-2.1.0.jar
androidx.lifecycle.lifecycle-livedata-2.1.0.aar
androidx.lifecycle.lifecycle-livedata-core-2.1.0.aar
androidx.lifecycle.lifecycle-runtime-2.1.0.aar
androidx.lifecycle.lifecycle-service-2.1.0.aar
androidx.lifecycle.lifecycle-viewmodel-2.0.0.aar
androidx.loader.loader-1.0.0.aar
androidx.localbroadcastmanager.localbroadcastmanager-1.0.0.aar
androidx.print.print-1.0.0.aar
androidx.room.room-common-2.2.5.jar
androidx.room.room-runtime-2.2.5.aar
androidx.slidingpanelayout.slidingpanelayout-1.0.0.aar
androidx.sqlite.sqlite-2.1.0.aar
androidx.sqlite.sqlite-framework-2.1.0.aar
androidx.startup.startup-runtime-1.0.0.aar
androidx.swiperefreshlayout.swiperefreshlayout-1.0.0.aar
androidx.tracing.tracing-1.0.0.aar
androidx.versionedparcelable.versionedparcelable-1.1.1.aar
androidx.viewpager.viewpager-1.0.0.aar
androidx.work.work-runtime-2.7.0.aar
com.facebook.android.audience-network-sdk-6.12.0.aar
com.google.ads.mediation.facebook-6.11.0.1.aar
com.google.android.gms.play-services-ads-21.2.0.aar
com.google.android.gms.play-services-ads-base-21.2.0.aar
com.google.android.gms.play-services-ads-identifier-18.0.1.aar
com.google.android.gms.play-services-ads-lite-21.2.0.aar
com.google.android.gms.play-services-appset-16.0.2.aar
com.google.android.gms.play-services-base-18.0.1.aar
com.google.android.gms.play-services-basement-18.1.0.aar
com.google.android.gms.play-services-measurement-base-20.1.2.aar
com.google.android.gms.play-services-measurement-sdk-api-20.1.2.aar
com.google.android.gms.play-services-tasks-18.0.2.aar
com.google.android.ump.user-messaging-platform-2.0.0.aar
com.google.guava.listenablefuture-1.0.jar

Modified artifacts:
com.google.ads.mediation:facebook:6.10.0.0 --> com.google.ads.mediation:facebook:+

BUILD SUCCESSFUL in 43s
1 actionable task: 1 executed

`

**Comment by paulinon** [comment]
Hi @iamfrankjie, 

It's possible that this behavior is the result of EDM4U's auto-resolution. Could you try if [disabling auto-resolution](https://github.com/googlesamples/unity-jar-resolver#auto-resolution) makes any difference?

**Comment by DellaBitta** [comment]
Also, in addition to @paulinon's suggestion, It [seems](https://mvnrepository.com/artifact/com.google.ads.mediation/facebook/6.10.0.0) that Facebook relies on `play-services-ads-base` version `20.6.0` and another dependency also requires `play-services-ads-base` but at a dfiferent version. Eventually `21.2.0` is used. Can you check the rest of your log for entries of `play-services-ads-base` to see if there's anything that stands out there? Perhaps the AdMob Unity SDK requires a different version.

Thanks!
