### ISSUE TITLE
[Bug] Installed pod, but EDM4U can not touch it!

### ISSUE THREAD

**Issue by CodeMasterYi** [googlesamples/unity-jar-resolver#577]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.14f1
  * External Dependency Manager version: 1.2.174
  * Source you installed EDM4U: .unitypackage (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: iOS Resolver (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: Firebase,AppLovin Max,Facebook,Adjust (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)

### [REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

I installed pod via ruby 2.7.2 which is installed by rvm(Ruby Version Manager), but EDM4U always check pod installation while I have already done it.
So I check your source code to find out what happened.
`iOSResolver` only check pod path in two folder `/usr/local/bin` and `/usr/bin`.
But mine is...
```
% which pod
/Users/xxxxxx/.rvm/rubies/ruby-2.7.2/bin/pod
```

```
% gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.4
  - RUBY VERSION: 2.7.2 (2020-10-01 patchlevel 137) [x86_64-darwin21]
  - INSTALLATION DIRECTORY: /Users/xxxxxx/.rvm/gems/ruby-2.7.2
  - USER INSTALLATION DIRECTORY: /Users/xxxxxx/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /Users/xxxxxx/.rvm/rubies/ruby-2.7.2/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /Users/xxxxxx/.rvm/gems/ruby-2.7.2/bin
  - SPEC CACHE DIRECTORY: /Users/xxxxxx/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/xxxxxx/.rvm/rubies/ruby-2.7.2/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-21
  - GEM PATHS:
     - /Users/xxxxxx/.rvm/gems/ruby-2.7.2
     - /Users/xxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0
  ...
  ... 
```

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by CodeMasterYi** [comment]
I have already worked around this issue by using `brew install cocoapods` instead.

**Comment by paulinon** [comment]
Hi @CodeMasterYi,

Glad to hear that you worked around the issue. That said, I'll be closing this. Feel free to ask this to be reopened if you think this is a mistake. Let me know if any issue arises.

**Comment by CodeMasterYi** [comment]
Hi @paulinon,
Yes, you can close it. But I think the method, which finds `pod` executable, is not very strong.
