### ISSUE TITLE
Dependencies are ignored

### ISSUE THREAD

**Issue by Tamplier** [googlesamples/unity-jar-resolver#58]
I think I found a problem.
In case if I add only my plugin to a project all works fine. But if I add two plugins with jar resolver (one of them is mine), I can't find my dependencies. I've tried to add log output to RegisterDependencies method and I know that it has been called and finished. 
I didn't see any other log output. 
Clearing temp files, library folder, and project settings don't help.

Here is my dependencies file:
https://gist.github.com/Tamplier/d56300c846ee62879c85125bdf711de3

To reproduce the bug you can add GooglePlayGamesPlugin (version 0.9.38a):
https://github.com/playgameservices/play-games-plugin-for-unity

I work in Unity 5.6.1f1 at the moment.

**Comment by Tamplier** [comment]
I found one interesting detail. If I remove call RegisterDependencies() from GPGSDependencies constructor, then my dependencies file process fine.
It looks like users really can't add dependencies in two different files. It may be related to wrong usage of static variables or something like that.

**Comment by stewartmiles** [comment]
I'm not sure how this is failing TBH, in Firebase we have a separate module register dependencies for each component then when including GPGS and AdMob they'll again register additional dependencies.  Everything ends up in a global list so I'm not sure how your code is failing.

Any chance you could enable verbose logging in the settings menu to see what's going on?

**Comment by stewartmiles** [comment]
This should be resolved by the 1.2.47 release c532ffe88dd6ffa628ef5da43acbdadafcb8e1a8
