### ISSUE TITLE
Admob Demo and Real Ads are not showing on Android Build but show on Ios Build?[Question] 

### ISSUE THREAD

**Issue by FunRiseRoyal** [googlesamples/unity-jar-resolver#580]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.6f1 _____
  * External Dependency Manager version: 1.2.172_____
  * Source you installed EDM4U: ____ (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: All_____ (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: Admob, Firebase, Unity Ads _____ (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: M1 Mac_____ (Mac, Windows, or Linux)

### [REQUIRED] Please describe the question here:

I installed google mobile ads Sdk version 7.2.0 and test ads show on my Unity Editor but when I build and test it for Android, the test ads does not show.  The app is published on google Playstore for months now and it has users playing, but there is no request being shown on my Admob account when I check android.  My Admob script is working fine, since my Ios app shows reals ads and everything works fine for Ios, but android does not work.  I tried so many things but not even requests are being shown on my Admob account.   I looked at Github and it said that Admob Sdk 7.2.0 is compatible with External Dependency 1.2.171 and I have 1.2.172.  Is the cause of my demo and real ads not showing? I even tried Force Resolve in External Dependency for Android, but it did not work.   Also, I added Unity Ads to my Admob Mediation to see if it work.  It worked for ios but it still did not work for android.   In my Admob account everything is zero when I go to my Android. Please help me.

**Comment by paulinon** [comment]
Hi @FunRiseRoyal,

From the looks of this issue, it seems that the cause of this may lie either in the Ads SDK or your implementation. The difference between the versions of the resolver you mentioned is a fix regarding the iOS resolver. That said, you may relay this to the [Google Mobile Ads repository](https://github.com/googleads/googleads-mobile-unity/issues). Let me know if an issue with the resolver arises.
