### ISSUE TITLE
[Bug] disabling Explore AAR still downloads and modifies AARs 

### ISSUE THREAD

**Issue by shefich** [googlesamples/unity-jar-resolver#584]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3
  * External Dependency Manager version: 1.2.175
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Admob
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
Disable "Explode AARs" in Android Resolver Settings and then make Force Resolve. 
AARs are still downloaded and exploaded to the Plugins/Android folder.

**Comment by paulinon** [comment]
Hi @shefich,

Thank you for filing this issue. I was able to see this behavior on the editor using the information you provided. The resolver settings mention that AAR explosion will be disabled in exported Gradle builds. Could you try exporting the project and see if there's a difference between enabling and disabling `Explode AARs`? You may provide other relevant information that would help the investigation.

**Comment by shefich** [comment]
Hi @paulinon ,

"The resolver settings mention that AAR explosion will be disabled in exported Gradle builds" - it says that this option will be disabled for exporting the project. I am not exporting the project. How to disable it completely?
The main difference in my projects is in the "Force build". The settings are the same, but one project just make changes in gradle and dependencies files. Other project adds or explodes AARs. Disabling or enabling "Explode AARs" does nothing in project.
