### ISSUE TITLE
[Bug] disabling Explore AAR still downloads and modifies AARs 

### ISSUE THREAD

**Issue by shefich** [googlesamples/unity-jar-resolver#585]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.45
  * External Dependency Manager version: _____
  * Source you installed EDM4U: unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use:  Admob
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
Disable "Explode AARs" in Android Resolver Settings and then make Force Resolve.
AARs are still downloaded and exploaded to the Plugins/Android folder.

#### Please answer the following, if applicable:
100%

**Comment by paulinon** [comment]
Hi @shefich,

I noticed that the content of this issue is similar to the one in #584. Let's have all discussion there so that we just have one thread for it. That being said, I'll be closing this for now.
