### ISSUE TITLE
[Bug] Linux: Resolution of dependencies does not work at all

### ISSUE THREAD

**Issue by Watcher3056** [googlesamples/unity-jar-resolver#592]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.13f1
  * External Dependency Manager version: 1.2.172
  * Source you installed EDM4U:.unitypackage
  * Features in External Dependency Manager in use: Android Resolver, VersionHandler
  * Plugins SDK in use: None
  * Platform you are using the Unity editor on: Linux

### [REQUIRED] Please describe the issue here:
Pressing buttons Android Resolver >> "Resolve" and "Force Resolve" does not work. Nothing happens, no window popups, no logs in console.
Also this error appears when automatic resolution launches:

> `Gradle failed to fetch dependencies.
> 
> Failed to run '/home/admin/Projects/Unity3d/Merge_Game/Temp/PlayServicesResolverGradle/gradlew --no-daemon -b "/home/admin/Projects/Unity3d/Merge_Game/Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=/home/admin/Unity3d/2021.3.13f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK" "-PTARGET_DIR=/home/admin/Projects/Unity3d/Merge_Game/Assets/Plugins/Android" "-PMAVEN_REPOS=" "-PPACKAGES_TO_COPY=com.android.support:support-v4:25.3.1;com.android.support:appcompat-v7:25.3.1;com.android.support:cardview-v7:25.3.1;com.android.support:customtabs:25.3.1;com.yandex.android:mobmetricalib:5.2.0;com.appsflyer:af-android-sdk:6.8.2;com.appsflyer:unity-wrapper:6.8.2;com.android.installreferrer:installreferrer:2.1;com.parse.bolts:bolts-android:1.4.0;com.facebook.android:facebook-core:[14.1, 15);com.facebook.android:facebook-applinks:[14.1, 15);com.facebook.android:facebook-login:[14.1, 15);com.facebook.android:facebook-share:[14.1, 15);com.facebook.android:facebook-gamingservices:[14.1, 15)" "-PUSE_JETIFIER=0" "-PDATA_BINDING_VERSION=4.0.1"'
> stdout:
> 
> stderr:
> java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
> 	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
> 	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
> 	at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109)
> 	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
> 	at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
> 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:209)
> 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:107)
> 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:85)
> 	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
> 	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
> 	at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
> 	at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
> 	at org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.<init>(DefaultExtraPropertiesExtension.java:29)
> 	at org.gradle.api.internal.plugins.DefaultConvention.<init>(DefaultConvention.java:47)
> 	at org.gradle.api.internal.ExtensibleDynamicObject.<init>(ExtensibleDynamicObject.java:58)
> 	at org.gradle.initialization.DefaultSettings.<init>(DefaultSettings.java:93)
> 	at org.gradle.initialization.DefaultSettings_Decorated.<init>(Unknown Source)
> 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
> 	at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
> 	at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
> 	at org.gradle.initialization.SettingsFactory.createSettings(SettingsFactory.java:52)
> 	at org.gradle.initialization.ScriptEvaluatingSettingsProcessor.process(ScriptEvaluatingSettingsProcessor.java:56)
> 	at org.gradle.initialization.PropertiesLoadingSettingsProcessor.process(PropertiesLoadingSettingsProcessor.java:37)
> 	at org.gradle.initialization.SettingsEvaluatedCallbackFiringSettingsProcessor.process(SettingsEvaluatedCallbackFiringSettingsProcessor.java:34)
> 	at org.gradle.initialization.RootBuildCacheControllerSettingsProcessor.process(RootBuildCacheControllerSettingsProcessor.java:36)
> 	at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:48)
> 	at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:45)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
> 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
> 	at org.gradle.initialization.BuildOperationSettingsProcessor.process(BuildOperationSettingsProcessor.java:45)
> 	at org.gradle.initialization.DefaultSettingsLoader.findSettingsAndLoadIfAppropriate(DefaultSettingsLoader.java:104)
> 	at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:45)
> 	at org.gradle.initialization.SettingsAttachingSettingsLoader.findAndLoadSettings(SettingsAttachingSettingsLoader.java:35)
> 	at org.gradle.internal.composite.CommandLineIncludedBuildSettingsLoader.findAndLoadSettings(CommandLineIncludedBuildSettingsLoader.java:34)
> 	at org.gradle.internal.composite.ChildBuildRegisteringSettingsLoader.findAndLoadSettings(ChildBuildRegisteringSettingsLoader.java:47)
> 	at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:35)
> 	at org.gradle.initialization.DefaultGradleLauncher$LoadBuild.run(DefaultGradleLauncher.java:277)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
> 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
> 	at org.gradle.initialization.DefaultGradleLauncher.loadSettings(DefaultGradleLauncher.java:202)
> 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:147)
> 	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:134)
> 	at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:58)
> 	at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:55)
> 	at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:82)
> 	at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:75)
> 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:183)
> 	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
> 	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:75)
> 	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:55)
> 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
> 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
> 	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:58)
> 	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
> 	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
> 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
> 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
> 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
> 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:49)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:46)
> 	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:78)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
> 	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
> 	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
> 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
> 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
> 	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
> 	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
> 	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
> 	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
> 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
> 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
> 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
> 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
> 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
> 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
> 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
> 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
> 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
> 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
> 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:55)
> 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:207)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:403)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:376)
> 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:37)
> 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:23)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:369)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:299)
> 	at org.gradle.launcher.Main.doAction(Main.java:36)
> 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
> 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
> 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
> 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
> 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Caused by: java.lang.ExceptionInInitializerError: Exception org.codehaus.groovy.GroovyBugError [in thread "main"]
> 	at org.codehaus.groovy.vmplugin.v7.Java7.<clinit>(Java7.java:45)
> 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
> 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
> 	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
> 	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
> 	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:201)
> 	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:547)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:497)
> 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
> 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:306)
> 	at java.base/java.lang.Class.newInstance(Class.java:684)
> 	at org.codehaus.groovy.vmplugin.VMPluginFactory.createPlugin(VMPluginFactory.java:57)
> 	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:39)
> 	... 113 more
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not create an instance of type org.gradle.initialization.DefaultSettings_Decorated.
> > Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> 
> exit code: 1
> 
> UnityEngine.Debug:LogError (object)
> Google.Logger:Log (string,Google.LogLevel) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:136)
> GooglePlayServices.PlayServicesResolver:Log (string,Google.LogLevel) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1055)
> GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey11:<>m__19 (GooglePlayServices.CommandLine/Result) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:459)
> GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey11/<GradleResolution>c__AnonStorey13:<>m__2C () (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:572)
> Google.RunOnMainThread:ExecuteNext () (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:486)
> Google.RunOnMainThread:<ExecuteAllUnnested>m__12 () (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:536)
> Google.RunOnMainThread:RunAction (System.Action) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/`

#### Please answer the following, if applicable:
100%

What happened? How can we make the problem occur?
- ArchLinux Install Unity Hub on archlinux
- Install Unity Editor via UnityHub with Android modules(including JDK, NDK)
- Import External Dependency Manager
- Try resolve

**Comment by paulinon** [comment]
Hi @Watcher3056,

Thanks for reporting this issue. I'd like you to try the following:
1. Go to `Edit > Preferences > External Tools`.
2. Untick then tick the JDK, Android SDK, Android NDK, and Gradle checkboxes.
3. Resolve or Force Resolve.

If that doesn't work, could you try if updating the resolver to the latest version makes any difference?

**Comment by Watcher3056** [comment]
> Hi @Watcher3056,
> 
> Thanks for reporting this issue. I'd like you to try the following:
> 
>     1. Go to `Edit > Preferences > External Tools`.
> 
>     2. Untick then tick the JDK, Android SDK, Android NDK, and Gradle checkboxes.
> 
>     3. Resolve or Force Resolve.
> 
> 
> If that doesn't work, could you try if updating the resolver to the latest version makes any difference?

Hi. Already did several times. Even copy and pasted path manually. No result. Nothing changed from described behaviour.

**Comment by paulinon** [comment]
Hi @Watcher3056,

Could you confirm the version of your JDK by running `java -version` in your terminal? Also, could you try if enabling Gradle Daemon in Resolver Settings (Assets -> External Dependency Manager -> Android Resolver -> Settings) makes a difference? Have you also tried the latest resolver version (1.2.175 as of writing)?

**Comment by Watcher3056** [comment]
Hi. Enabling Gradle daemon change nothing.
Also should I launch java -version for my entire system or just for this one installed with unity?

**Comment by chkuang-g** [comment]
Should be for your system, not the one setup in Unity editor. You can open a terminal and type `java --version`

Also, I am curious if you get the same result if you run the same command in the terminal.
```
/home/admin/Projects/Unity3d/Merge_Game/Temp/PlayServicesResolverGradle/gradlew --no-daemon -b "/home/admin/Projects/Unity3d/Merge_Game/Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=/home/admin/Unity3d/2021.3.13f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK" "-PTARGET_DIR=/home/admin/Projects/Unity3d/Merge_Game/Assets/Plugins/Android" "-PMAVEN_REPOS=" "-PPACKAGES_TO_COPY=com.android.support:support-v4:25.3.1;com.android.support:appcompat-v7:25.3.1;com.android.support:cardview-v7:25.3.1;com.android.support:customtabs:25.3.1;com.yandex.android:mobmetricalib:5.2.0;com.appsflyer:af-android-sdk:6.8.2;com.appsflyer:unity-wrapper:6.8.2;com.android.installreferrer:installreferrer:2.1;com.parse.bolts:bolts-android:1.4.0;com.facebook.android:facebook-core:[14.1, 15);com.facebook.android:facebook-applinks:[14.1, 15);com.facebook.android:facebook-login:[14.1, 15);com.facebook.android:facebook-share:[14.1, 15);com.facebook.android:facebook-gamingservices:[14.1, 15)" "-PUSE_JETIFIER=0" "-PDATA_BINDING_VERSION=4.0.1"
```

Alternatively, you can relies on the Gradle project from Unity and enable `mainTemplate.gradle` and `gradleTemplate.properties`. Should be able to find them in `Player Settings` > `Publishing Settings`
- `Custom Main Gradle Template` for `mainTemplate.gradle` 
- `Custom Gradle Properties Template` for `gradleTemplate.properties`.

This way, you will use the gradle from Unity, the JDK setup for Unity to resolve dependencies. Usually stabler.

Shawn
