### ISSUE TITLE
[Bug] Endless Google.RunOnMainThread.ExecuteAll

### ISSUE THREAD

**Issue by Watcher3056** [googlesamples/unity-jar-resolver#598]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.13f1
  * External Dependency Manager version: 1.2.172
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Admob, Facebook, Appsflyer, Appmetrica
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
- Go to Edit > Project Settings > Editor
- Uncheck "Reload Domain" & "Reload Scene"
- Launch Android Force Resolve or Launch Build Process(in this case it will stuck on Building Scene 0)
#### Please answer the following, if applicable:
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

![Unity_0cPrROFRhe](https://user-images.githubusercontent.com/53340768/219867397-59bdcfd8-bdbb-4659-96e6-3a45aad6981a.png)
![BJFaP48R5C](https://user-images.githubusercontent.com/53340768/219867400-9a096035-13b9-4216-b817-f725965c9453.png)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by paulinon** [comment]
Hi @Watcher3056,

Thanks for reporting the issue. While I try to replicate this, could you verify if the issue persists using the latest version of the resolver (1.2.175)?
