### ISSUE TITLE
Support for the new Google Maven repository

### ISSUE THREAD

**Issue by jkasten2** [googlesamples/unity-jar-resolver#60]
Android Support Library updates are now done through the Google Maven repository (https://maven.google.com) and new updates to the library are no longer released through the SDK manager.
https://developer.android.com/topic/libraries/support-library/setup.html

Please add support resolving through this as the latest 26.0.0 released Android Support library is only available through the new Maven repo.

Thanks.

**Comment by jkasten2** [comment]
It seems that this might be dependent on #28 as the maven repo will be remote instead of relying on local files on the system.

**Comment by stewartmiles** [comment]
This should be supported as of bd2258481db7130a4f6ae7b1969acf0fb488733e
