### ISSUE TITLE
[Bug] Android Resolver: Resolution stuck at 100% despite no libraries was downloaded

### ISSUE THREAD

**Issue by Watcher3056** [googlesamples/unity-jar-resolver#606]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.13f1
  * External Dependency Manager version: 1.2.175
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: FacebookSDK, Applsflyer, Appmetrica, Applovin MaxSDK(Mediations: Fb, Admob, Unity, IronSource, Fyber, Vungle, Pangle, Inmobi, Adcolony, HyprMx, Maio, Tapjoy, Mintegral, Yandex)
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
Click Android Resolver >> Resolver or Force Resolve - it will stuck at 100% like this
![Unity_fk3bMwwuNj](https://user-images.githubusercontent.com/53340768/230384535-e344bb56-4ed2-4a36-990a-b09fce30a37a.png)

#### Please answer the following, if applicable:
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by paulinon** [comment]
Hi @Watcher3056, 

Could you try if enabling both `Custom Main Gradle Template` and `Custom Gradle Properties Template` from your Player Settings > Publishing Settings makes any difference? If not, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that we could identify the cause of this behavior.

**Comment by Watcher3056** [comment]
1 hour passed, some libraries downloaded, but not sure if process is complete. Resolver blinks with some text periodically. Process is unclear, you should fix at least this. I will check again with options you mentioned.
https://user-images.githubusercontent.com/53340768/230424363-59bd0f09-20d5-4d57-89c6-be75ec94a77c.mp4

**Comment by Watcher3056** [comment]
Enabled both ```Custom Main Gradle Template``` and ```Custom Gradle Properties Template```, now resolution seems to have no effect at all, no libraries downloaded
![Unity_r38MINoVNh](https://user-images.githubusercontent.com/53340768/230426528-8776bf13-e7c2-43e6-89c5-277ddaa872ac.png)

**Comment by Watcher3056** [comment]
Tab back to project and libraries appeared somewhy.
![image](https://user-images.githubusercontent.com/53340768/230426948-d770e836-a263-473e-8f57-50d619aac9c7.png)

**Comment by Watcher3056** [comment]
Its not reliable when libraries downloads or not. Please reproduce it. Need help.

**Comment by paulinon** [comment]
Hi @Watcher3056,

I see that the resolution has succeeded. Enabling both Custom Main Gradle Template and Custom Gradle Properties Template in Player Settings helps resolves the dependency conflict by simply modifying a file, which prevents resolution from taking too long.

I'll be closing this for now. Let me know if an issue arises or if this solution isn't suitable with your use case so this could be reopened.

**Comment by Watcher3056** [comment]
Hi again, sorry but in my case resolution does not seems to have effect. Plugins/Android folder has no libraries and my build crashes because of method not found exception, which is means there is no suitable library was found.

**Comment by paulinon** [comment]
Hi @Watcher3056,

Apologies for the radio silence here. Could you try if updating the Unity editor version (the latest LTS version as of writing is 2021.3.24f1) makes any difference? If it doesn't, it would be helpful if you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as this could be used as a baseline for troubleshooting.
