### ISSUE TITLE
iOS custom pod spec file

### ISSUE THREAD

**Issue by xysverma** [googlesamples/unity-jar-resolver#61]
Is thr a way to specify a custom pod spec file like this and ensure that this file will be copied just like GoogleServices-Info.plist gets copied while using google sdks ?

pod 'Firebase/Messaging', :podspec => 'FirebaseMessaging.podspec.json'

This way i can exclude an unnecessary dependency which publisher of unitypackage has provided otherwise with it.

**Comment by sourabhverma** [comment]
@stewartmiles : Are both not possible ?
1) To specify a subspec like this
pod 'Firebase/Messaging', :podspec => 'FirebaseMessaging.podspec.json'

2) To copy subspec file.

**Comment by stewartmiles** [comment]
It's not possible right now without changing the code that generates the
Podfile.

**Comment by chbfiv** [comment]
I was also thinking of something along these lines.

In my case I need to modify the Podfile generated. I just turned generation off for now, but ideally we could provide a base template (or add additional Pod features to the tool).

specifically `use_frameworks!`

https://blog.cocoapods.org/CocoaPods-0.36/

**Comment by stewartmiles** [comment]
FYI Folks, support for this was added in fb663ee856272ca57fd1962ead459332cc3443c3
