### ISSUE TITLE
[Question] When to expect the next plugin release (1.2.176)?

### ISSUE THREAD

**Issue by KonStg** [googlesamples/unity-jar-resolver#614]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.2.14f1
  * External Dependency Manager version: 1.2.175
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver, VersionHandler
  * Plugins SDK in use: Firebase, Facebook, AppLovin
  * Platform you are using the Unity editor on: Mac (m1), Windows

### [REQUIRED] Please describe the question here:

We are using the 2022.2 version of unity, and ran into problem solved in https://github.com/googlesamples/unity-jar-resolver/pull/610 .
I see that the fix has already been poured into the main branch .
When can we expect the next module update approximately?

**Comment by chkuang-g** [comment]
1.2.176 is now released on Github. 
If your need the tgz package from Google API for Unity, it will take a couple of hours.

Cheers,
Shawn
