### ISSUE TITLE
GvhProjectSettings.xml is always checked out when we launch Unity

### ISSUE THREAD

**Issue by Verboton** [googlesamples/unity-jar-resolver#617]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: **2021.3.18f1**
  * External Dependency Manager version: **1.2.169**
  * Source you installed EDM4U: **not sure** (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: **not sure**  (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: **GoogleplayGame 0.11.01** (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: **Windows** (Mac, Windows, or Linux)

### [REQUIRED] Please describe the question here:
Hi,

Right now, each time we launch unity, the file GvhPojectSettings.xml is checked out without any changes in it.  Is there a way to prevent this?  We are trying to avoid leaving useless checked out files in our  perforce depot.

Thanks.

**Comment by paulinon** [comment]
Hi @Verboton,

Thanks for bringing this to our attention. Based on the information you provided, this issue looks similar to #524. We're currently working on a solution for this. That said, I'll be closing this for now. You may refer to the aforementioned thread for updates.
