### ISSUE TITLE
Downloaded libraries are not being removed

### ISSUE THREAD

**Issue by martino2k6** [googlesamples/unity-jar-resolver#62]
Using version 1.2.41.0 downloaded assets are not being removed from the Assets/Plugins/Android folder once their declarations have been removed from a script and the Editor re-opened. I have also tried to use Resolve Client Jars option to no avail.

Changing one of the Android settings (for example Prebuild With Gradle) does cause the assets to be cleared out.

**Comment by stewartmiles** [comment]
@martino2k6 which version of the plugin do you see this with and which version of Unity are you using?

Cheers,
Stewart

**Comment by martino2k6** [comment]
I'm using plugin version 1.2.41.0 with Unity 2017.1.0p1 on Windows.

**Comment by stewartmiles** [comment]
Ok I think I can see what's going on here.

We go to great lengths to avoid running a complete resolution if possible such that if all required dependencies are present we simply skip resolution entirely.  In the case of removing dependencies, all AARs / JARs are present so we're skipping resolution :/ 

Perhaps a better way for us to handle this is to store the previous set of resolved dependencies and compare that against the current - in memory set - and trigger a resolution based upon the delta.

**Comment by stewartmiles** [comment]
We have a patch lined up that I should be able to post later today.

**Comment by martino2k6** [comment]
Thank you for taking a look at this issue :)

**Comment by stewartmiles** [comment]
This is fixed by 76e7a4434801e277d09248d469e7130409e35c61
