### ISSUE TITLE
unitypackage decompress error[Bug] 

### ISSUE THREAD

**Issue by capitaljmedia** [googlesamples/unity-jar-resolver#625]
* Unity editor version: 2022.3.1
  * External Dependency Manager version: 1.2.176
  * Source you installed EDM4U: unitypackage 
  * Platform you are using the Unity editor on: Mac

Downloading either of the unitypackage files and trying to install them inside unity 2022 shows this error every time:
Failed to import package with error: Couldn't decompress package

**Comment by paulinon** [comment]
Hi @capitaljmedia,

Thanks for bringing this to our attention. Do you have enough disk space in your computer? It's possible that you don't have enough for Unity to decompress the file. Also, does the path of your `.unitypackage` file contain any non-ASCII characters?

If none of these scenarios apply to you, could you provide the OS version you're using so we could identify what's causing this?
