### ISSUE TITLE
[FR] Search for pod in /opt/homebrew/bin

### ISSUE THREAD

**Issue by henrique-rovio** [googlesamples/unity-jar-resolver#627]
### Feature proposal

* EDM4U Component: iOS Resolver

In Arm Macs, Homebrew installs into `/opt/homebrew`, with executables being located in `/opt/homebrew/bin` instead of /usr/local/bin.
If [POD_SEARCH_PATHS](https://github.com/googlesamples/unity-jar-resolver/blob/8ac27f1d586458172768bd9b7d241d3c8a7e34b8/source/IOSResolver/src/IOSResolver.cs#L445-L448) were to be expanded to also include `/opt/homebrew/bin`, then it'd automatically find cocoapod installations done via Homebrew.

**Comment by AlmostMatt** [comment]
I found another source confirming that M1 macs will install to /opt/homebrew/bin instead of /usr/local/bin
https://earthly.dev/blog/homebrew-on-m1/
So this feature request seems reasonable
