### ISSUE TITLE
Gradle failed to fetch dependencies.

### ISSUE THREAD

**Issue by vikasfuter** [googlesamples/unity-jar-resolver#63]
Gradle failed to fetch dependencies.

Failed to run 'Temp\PlayServicesResolverGradle\gradlew.bat -b Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle "-PANDROID_HOME=E:/kunal/sdk" "-PTARGET_DIR=E:\VikasJha\Office Project\Unity Projects\Ludo Projects\FirebaseDemo\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///E:/VikasJha/Office Project/Unity Projects/Ludo Projects/FirebaseDemo/Assets/Firebase/m2repository" "-PPACKAGES_TO_COPY=com.google.android.gms:play-services-base:11.2.0;com.google.firebase:firebase-common:11.2.0;com.google.firebase:firebase-core:11.2.0;com.google.firebase:firebase-app-unity:4.1.0;com.google.firebase:firebase-auth:11.2.0;com.google.firebase:firebase-auth-unity:4.1.0"'
stdout:
Starting a Gradle Daemon, 18 busy Daemons could not be reused, use --status for details

stderr:

FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: Unable to establish loopback connection

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

exit code: 1

UnityEngine.Debug:LogError(Object)
GooglePlayServices.PlayServicesResolver:LogDelegate(String, LogLevel)
Google.JarResolver.PlayServicesSupport:Log(String, LogLevel, Boolean)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__20(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__29()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by stewartmiles** [comment]
Looks related to https://github.com/gradle/gradle/issues/1747 or https://stackoverflow.com/questions/30867443/gradle-throws-unable-to-establish-loopback-connection

Sounds like we need to add a mode to disable the Gradle Daemon for some build environments (basically pass the `--no-daemon` flag) which will slow down resolution time but - hopefully - will make the process more reliable.

**Comment by stewartmiles** [comment]
I've worked around this in release 1.2.50 4c3e438a47fffb6bde0f08fdd2d137be257956f9
