### ISSUE TITLE
Force resolve failing at 0%, resulting in emptying everything in the plugin folder. Note that the same project works perfectly on my old computer, but my new computer is unable to do any resolve successfully. 

### ISSUE THREAD

**Issue by TextGuySemicolon** [googlesamples/unity-jar-resolver#645]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.11.1f3
  * External Dependency Manager version: 1.2.77
  * Source you installed EDM4U:. unity package (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: android resolver (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: firebase or gooblemobileads (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: window (Mac, Windows, or Linux)

### [REQUIRED] Please describe the question here:

Android dependency Force Resolve is failing on empty project, tested with firebase or Google mobile ads, it seems more like an issue on my new PC, as the exact same project can be resolve on my old computer.

**Comment by paulinon** [comment]
Hi @TextGuySemicolon,

Is enabling both Custom Main Gradle Template and Custom Gradle Properties Template from your Player Settings > Publishing Settings a suitable solution for your new computer? Otherwise, could you provide the operating systems of the computers you're using?
