### ISSUE TITLE
[Question] NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by TWBestATM** [googlesamples/unity-jar-resolver#656]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.1f
  * External Dependency Manager version: 1.2.177
  * Source you installed EDM4U: unitypackage
  * Features in External Dependency Manager in use:Android Resolver
  * Plugins SDK in use: Firebase, Admob
  * Platform you are using the Unity editor on:Windows

### [REQUIRED] Please describe the question here:
when I resolve I get the error
![image](https://github.com/googlesamples/unity-jar-resolver/assets/15358024/f728b7f7-df83-4a80-b2d5-4d8064399452)
what is that

**Comment by paulinon** [comment]
Hi @TWBestATM,

Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so we can identify what's causing this to happen? It's possible that there's a public variable in your code that hasn't been initialized when declared.
