### ISSUE TITLE
[Bug] Infinity resolving with applovin facebook adapter

### ISSUE THREAD

**Issue by Usslessvoid** [googlesamples/unity-jar-resolver#657]
* Unity editor version: 2021.3.25f1
  * External Dependency Manager version: 1.2.176
  * Source you installed EDM4U: applovin  .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: 

1. Appsflyer;
2. AppsflyerRevenue;
3. Appmetrica;
4. Play rewiew;
5. FacebookSDK 11.0,
6. ApplovinMAX;
7. Firebase 11.1(analytics, remote config, installations, crashlytics);
8. Aazon APS;

Applovin adapters:

1. AdColony;
2. ByteDance;
3. Chartboost;
4. Fyber;
5. GoogleAdMob;
6. GoogleAdManager;
7. InMobi;
8. IronSource;
9. Mintegral;
10. MobileFuse;
11. MyTarget;
12. Smaato;
13. UnityAds;
14. Vungle;
15. Yandex;
16. FACEBOOK

Platform I am using the Unity editor on: Mac

Full steps:
Open the project with some dependencies (especially facebook adapter and firebase) and run Force Resolve

What happened? How can we make the problem occur?
Resolution becomes ultra slow, and 4 hours (22nd attempt) were not enough for resolution, system.

When facebook adapter installed in project with firebase, analytics dependencies were not resolved in 4 hours. If you remove the Facebook adapter, everything is resolved normally in a couple of minutes.
In blank project with only applovin facebook adapter and applovin facebook adapter, resolution success in 17 seconds;
After Firebase it's up to 16 minutes; full sdks - infinity time.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.
Here is minimal project to reproduce https://drive.google.com/file/d/1UWbAibxDVQTnHaxo9yt-q8v3NWb3QJSu/view?usp=sharing

**Comment by paulinon** [comment]
Hi @Usslessvoid,

Enabling both Custom Main Gradle Template and Custom Gradle Properties Template from your Player Settings > Publishing Settings should be able to help you with this issue. The generated files can handle the resolution better than the custom script in the resolver.

Let me know if an issue arisses with this solution so this ticket can be reopened

**Comment by Usslessvoid** [comment]
@paulinon Thanks, it worked and will be tested soon. But I would like to know why there is such a difference in time and how the assembly with mainTemplate differs from the assembly without it.
