### ISSUE TITLE
Can't build for Android with error "CommandInvokationFailure: Unable to convert classes into dex format."

### ISSUE THREAD

**Issue by rener172846** [googlesamples/unity-jar-resolver#66]
Hi, I'm using this for my projects, and that's really good for many google services.
When I used v1.2.35, everything works well. But, in new versions I can't build for Android.
I need facebook and google signin functionality in my app so added FB SDK and some small plugins with this plugin.
Cause of that, I get an error for android build as following.

`CommandInvokationFailure: Unable to convert classes into dex format.
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Volumes/DATA/SDK/25.2.2(for 5.5.1f1)/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity_2017.1.0f3/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[

trouble writing output: Too many field references: 66848; max is 65536.
You may try using --multi-dex option.
References by package:
     3 android.accounts
    25 android.app
    14 android.arch.core.internal
  2282 android.arch.lifecycle
     1 android.content
    36 android.content.pm
    10 android.content.res
     3 android.database
    47 android.graphics
     2 android.media
     1 android.media.browse
     2 android.net
     6 android.net.wifi
    21 android.os
     3 android.print
    13 android.support.annotation
  2257 android.support.compat
  2257 android.support.coreui
  2257 android.support.coreutils
  2359 android.support.customtabs
  2257 android.support.design
   106 android.support.design.internal
   655 android.support.design.widget
  2257 android.support.fragment
  2463 android.support.graphics.drawable
  2257 android.support.graphics.drawable.animated
  2257 android.support.mediacompat
  2637 android.support.transition
  2257 android.support.v4
    13 android.support.v4.accessibilityservice
   943 android.support.v4.app
   113 android.support.v4.content
    13 android.support.v4.content.pm
    16 android.support.v4.content.res
    50 android.support.v4.graphics
    57 android.support.v4.graphics.drawable
     4 android.support.v4.hardware.display
    12 android.support.v4.hardware.fingerprint
    11 android.support.v4.internal.view
   428 android.support.v4.media
     8 android.support.v4.media.app
   378 android.support.v4.media.session
     7 android.support.v4.net
    37 android.support.v4.os
    52 android.support.v4.print
    98 android.support.v4.provider
    54 android.support.v4.text
     6 android.support.v4.text.util
   120 android.support.v4.util
   412 android.support.v4.view
   126 android.support.v4.view.accessibility
     8 android.support.v4.view.animation
   478 android.support.v4.widget
   399 android.support.v7.app
  2257 android.support.v7.appcompat
  2257 android.support.v7.cardview
     8 android.support.v7.content.res
    18 android.support.v7.graphics.drawable
  2257 android.support.v7.recyclerview
     1 android.support.v7.text
   124 android.support.v7.util
    85 android.support.v7.view
   270 android.support.v7.view.menu
  1585 android.support.v7.widget
    87 android.support.v7.widget.helper
     1 android.support.v7.widget.util
     1 android.system
     6 android.text
     1 android.text.util
    13 android.util
    26 android.view
     8 android.view.accessibility
     1 android.view.inputmethod
    15 android.widget
     2 bitter.jnibridge
   158 bolts
  2662 com.facebook
  2257 com.facebook.android
   170 com.facebook.appevents
    43 com.facebook.appevents.internal
    46 com.facebook.applinks
     9 com.facebook.devicerequests.internal
   574 com.facebook.internal
   190 com.facebook.login
    81 com.facebook.login.widget
    32 com.facebook.messenger
    43 com.facebook.places
   102 com.facebook.places.internal
    70 com.facebook.places.model
    51 com.facebook.share
   360 com.facebook.share.internal
   114 com.facebook.share.model
   124 com.facebook.share.widget
    53 com.facebook.unity
  2251 com.google.android.gms
    20 com.google.android.gms.actions
    19 com.google.android.gms.ads.identifier
  2304 com.google.android.gms.auth
     5 com.google.android.gms.auth.account
  2272 com.google.android.gms.auth.api
    68 com.google.android.gms.auth.api.accounttransfer
    96 com.google.android.gms.auth.api.credentials
     6 com.google.android.gms.auth.api.phone
    37 com.google.android.gms.auth.api.proxy
    50 com.google.android.gms.auth.api.signin
    30 com.google.android.gms.auth.api.signin.internal
  2251 com.google.android.gms.base
   102 com.google.android.gms.common
    98 com.google.android.gms.common.api
   336 com.google.android.gms.common.api.internal
    41 com.google.android.gms.common.data
    44 com.google.android.gms.common.images
   160 com.google.android.gms.common.internal
    35 com.google.android.gms.common.stats
    27 com.google.android.gms.common.util
    25 com.google.android.gms.dynamic
    20 com.google.android.gms.dynamite
     2 com.google.android.gms.dynamite.descriptors.com.google.android.gms.flags
    16 com.google.android.gms.flags.impl
     3 com.google.android.gms.iid
   660 com.google.android.gms.internal
     5 com.google.android.gms.location.places
     6 com.google.android.gms.security
  2299 com.google.android.gms.tasks
    23 com.google.firebase.iid
  2251 com.rener.trix
   205 com.unity3d.player
  2276 in.locomotion.plugins.login
    11 java.lang
    11 java.lang.annotation
     2 java.nio
     1 java.nio.channels
     6 java.util
     2 java.util.concurrent
     1 java.util.logging
    20 org.fmod
     1 org.json
]`

I have to add twitter signin funcationality, too. But haven't any solution just now.
According to my research, unity doesn't support multi-dex build yet.
So if possible, hope to make a choosable library interface (not the auto resolving all libraries) or at least reduce the library counts, because there are too many resolved libraries for only google signin.
Any suggestion will be welcome!
Thanks for your read.

**Comment by johnb003** [comment]
We built "Gradle prebuild" to solve this problem.

It uses Proguard to strip your dependencies.

Give it a try:
https://github.com/googlesamples/unity-jar-resolver/blob/master/gradle_prebuild.md

**Comment by rener172846** [comment]
Hi, thanks for your fast reply.
I have tried to use the gradle prebuild but still not work.
Followings are what did I do.

 - I have checked the "Prebuild With Gradle (Experimental)" setting on Assets -> Play Services Resolver -> Android Resolver -> Settings
 so the Unity auto resolving again. ( I think it's gradle prebuilding?)
 but during that I have another error as following:

`Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.

Error (1):

BUILD FAILED

Total time: 6.101 secs

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'GenGradle'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.google.android.gms:play-services-auth:LATEST.
     Searched in the following locations:
         file:/Volumes/DATA/SDK/Android/extras/google/m2repository/com/google/android/gms/play-services-auth/LATEST/play-services-auth-LATEST.pom
         file:/Volumes/DATA/SDK/Android/extras/google/m2repository/com/google/android/gms/play-services-auth/LATEST/play-services-auth-LATEST.jar
         file:/Volumes/Work/Work/Unity/Trix/Trix/Temp/GenGradle/sdk-manager/com/google/android/gms/play-services-auth/LATEST/play-services-auth-LATEST.jar
         file:/Volumes/DATA/SDK/Android/extras/android/m2repository/com/google/android/gms/play-services-auth/LATEST/play-services-auth-LATEST.pom
         file:/Volumes/DATA/SDK/Android/extras/android/m2repository/com/google/android/gms/play-services-auth/LATEST/play-services-auth-LATEST.jar
         file:/Volumes/Work/Work/Unity/Trix/Trix/Temp/GenGradle/sdk-manager/com/google/android/gms/play-services-auth/LATEST/play-services-auth-LATEST.jar
     Required by:
         project :
   > Could not find com.android.support:design:LATEST.
     Searched in the following locations:
         file:/Volumes/DATA/SDK/Android/extras/google/m2repository/com/android/support/design/LATEST/design-LATEST.pom
         file:/Volumes/DATA/SDK/Android/extras/google/m2repository/com/android/support/design/LATEST/design-LATEST.jar
         file:/Volumes/Work/Work/Unity/Trix/Trix/Temp/GenGradle/sdk-manager/com/android/support/design/LATEST/design-LATEST.jar
         file:/Volumes/DATA/SDK/Android/extras/android/m2repository/com/android/support/design/LATEST/design-LATEST.pom
         file:/Volumes/DATA/SDK/Android/extras/android/m2repository/com/android/support/design/LATEST/design-LATEST.jar
         file:/Volumes/Work/Work/Unity/Trix/Trix/Temp/GenGradle/sdk-manager/com/android/support/design/LATEST/design-LATEST.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Traceback (most recent call last):
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 476, in <module>
    sys.exit(main())
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 469, in main
    execute_gradle_build(build_path)
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 261, in execute_gradle_build
    raise RuntimeError("Failed running gradle build")
RuntimeError: Failed running gradle build

UnityEngine.Debug:LogError(Object)
GooglePlayServices.<RunGenGradleScript>c__AnonStoreyE:<>m__11(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
GooglePlayServices.CommandLineDialog:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()`

Honestly, I don't know the python as well, so please let me know what do I have to do in details.
Thanks again for your support.

**Comment by stewartmiles** [comment]
@johnb003 it looks like you're not handling the special `LATEST` version specification in the Gradle prebuild.  See https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/src/ResolverVer1_1.cs#L544 for the conversion to a loose Gradle version spec.

@rener172846 search your project sources for `LATEST`, and change any Android dependencies to reference version `+` instead of `LATEST`.  If you give it another try, Gradle should download the most recent version of each dependency.  Be aware this is potentially a bit dodgy as you could be running with packages that we haven't validated, so it would be preferable to pin to a specific version e.g what we use in the Firebase SDK `11.2.0`.

**Comment by rener172846** [comment]
@stewartmiles thanks, I have searched the  `LATEST` and find that in my another third party plugin.
I'm not sure why it wasn't issue when I used default resolve (not prebuild gradle).
Anyway, I have change that to specific version, and success to prebuild gradle. I have confirmed that with seeing MergedDependencies directory in Plugins->Android.
But I got another unfamiliar issue as following

<code>CommandInvokationFailure: Failed to re-package resources.
/Volumes/DATA/SDK/Android/build-tools/26.0.1/aapt package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "/Volumes/DATA/SDK/Android/platforms/android-26/android.jar" -F bin/resources.ap_ --extra-packages in.locomotion.plugins.login:com.rener.trix:com.facebook:com.facebook.android:com.twitter.sdk.android.tweetcomposer:com.twitter.sdk.android.core:com.twitter.sdk.android.unity -S "/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/GoogleLoginKit/res" -S "/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/MergedDependencies/res" -S "/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res" -S "/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-wrapper-7.10.0/res" -S "/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/tweet-composer-3.1.1/res" -S "/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/twitter-core-3.1.1/res" -S "/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/twitter-unity-3.1.1-release/res"

stderr[
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/layout/com_facebook_device_auth_dialog_fragment.xml:80: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <TextView>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/layout/com_facebook_device_auth_dialog_fragment.xml:80: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/layout/com_facebook_device_auth_dialog_fragment.xml: note: using v17 attributes; synthesizing resource com.rener.trix:layout/com_facebook_device_auth_dialog_fragment for configuration v17.
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/layout/com_facebook_smart_device_dialog_fragment.xml:94: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/layout/com_facebook_smart_device_dialog_fragment.xml:94: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <TextView>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/layout/com_facebook_smart_device_dialog_fragment.xml:83: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/layout/com_facebook_smart_device_dialog_fragment.xml:83: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <TextView>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/layout/com_facebook_smart_device_dialog_fragment.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <android.support.v7.widget.AppCompatImageView>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/layout/com_facebook_smart_device_dialog_fragment.xml: note: using v17 attributes; synthesizing resource com.rener.trix:layout/com_facebook_smart_device_dialog_fragment for configuration v17.
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/tweet-composer-3.1.1/res/layout/tw__composer_view.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <ImageView>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/tweet-composer-3.1.1/res/layout/tw__composer_view.xml: note: using v17 attributes; synthesizing resource com.rener.trix:layout/tw__composer_view for configuration v17.
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable/com_facebook_button_login_logo.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable/com_facebook_button_login_logo.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable/com_facebook_button_login_logo.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable/com_facebook_button_login_logo.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable/com_facebook_button_login_logo.xml: note: using v21 attributes; synthesizing resource com.rener.trix:drawable/com_facebook_button_login_logo for configuration v21.
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable/com_facebook_favicon_blue.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable/com_facebook_favicon_blue.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable/com_facebook_favicon_blue.xml:26: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable/com_facebook_favicon_blue.xml:26: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable/com_facebook_favicon_blue.xml: note: using v21 attributes; synthesizing resource com.rener.trix:drawable/com_facebook_favicon_blue for configuration v21.
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/tweet-composer-3.1.1/res/values/values.xml:46: note: using v17 attributes; synthesizing resource com.rener.trix:style/tw__ComposerCharCount for configuration v17.
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/tweet-composer-3.1.1/res/values/values.xml:80: note: using v17 attributes; synthesizing resource com.rener.trix:style/tw__ComposerTweetButton for configuration v17.
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/MergedDependencies/res/values/values.xml:2238: note: using v21 attributes; synthesizing resource com.rener.trix:style/Widget.Design.BottomSheet.Modal for configuration v21.
Failed to generate resource table for split ''
/Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/MergedDependencies/res/values/values.xml:1775: error: Error: No resource found that matches the given name (at 'android:background' with value '@drawable/abc_spinner_textfield_background_material').

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: /Volumes/DATA/SDK/Android/platforms/android-26/android.jar
applyFileOverlay for drawable
trying overlaySet Key=tw__ic_logo_default.png
trying overlaySet Key=tw__login_btn.xml
trying overlaySet Key=tw__login_btn_default.xml
trying overlaySet Key=tw__login_btn_disabled.xml
trying overlaySet Key=tw__login_btn_pressed.xml
trying overlaySet Key=tw__btn_composer_tweet.xml
trying overlaySet Key=tw__composer_close.png
trying overlaySet Key=tw__composer_logo_blue.png
trying overlaySet Key=tw__composer_logo_white.png
trying overlaySet Key=com_facebook_auth_dialog_background.xml
trying overlaySet Key=com_facebook_auth_dialog_cancel_background.xml
trying overlaySet Key=com_facebook_auth_dialog_header_background.xml
trying overlaySet Key=com_facebook_button_background.xml
trying overlaySet Key=com_facebook_button_icon.xml
trying overlaySet Key=com_facebook_button_icon_blue.png
trying overlaySet Key=com_facebook_button_icon_white.png
trying overlaySet Key=com_facebook_button_like_background.xml
trying overlaySet Key=com_facebook_button_like_icon_selected.png
trying overlaySet Key=com_facebook_button_login_background.xml
trying overlaySet Key=com_facebook_button_login_logo.xml
trying overlaySet Key=com_facebook_button_login_silver_background.xml
trying overlaySet Key=com_facebook_button_send_background.xml
trying overlaySet Key=com_facebook_button_send_icon_blue.png
trying overlaySet Key=com_facebook_button_send_icon_white.png
trying overlaySet Key=com_facebook_close.png
trying overlaySet Key=com_facebook_favicon_blue.xml
trying overlaySet Key=com_facebook_profile_picture_blank_portrait.png
trying overlaySet Key=com_facebook_profile_picture_blank_square.png
trying overlaySet Key=com_facebook_send_button_icon.xml
trying overlaySet Key=com_facebook_tooltip_black_background.9.png
trying overlaySet Key=com_facebook_tooltip_black_bottomnub.png
trying overlaySet Key=com_facebook_tooltip_black_topnub.png
trying overlaySet Key=com_facebook_tooltip_black_xout.png
trying overlaySet Key=com_facebook_tooltip_blue_background.9.png
trying overlaySet Key=com_facebook_tooltip_blue_bottomnub.png
trying overlaySet Key=com_facebook_tooltip_blue_topnub.png
trying overlaySet Key=com_facebook_tooltip_blue_xout.png
trying overlaySet Key=messenger_bubble_large_blue.png
trying overlaySet Key=messenger_bubble_large_white.png
trying overlaySet Key=messenger_bubble_small_blue.png
trying overlaySet Key=messenger_bubble_small_white.png
trying overlaySet Key=messenger_button_blue_bg_round.xml
trying overlaySet Key=messenger_button_blue_bg_selector.xml
trying overlaySet Key=messenger_button_send_round_shadow.png
trying overlaySet Key=messenger_button_white_bg_round.xml
trying overlaySet Key=messenger_button_white_bg_selector.xml
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
trying overlaySet Key=tw__activity_oauth.xml
trying overlaySet Key=tw__activity_composer.xml
trying overlaySet Key=tw__composer_view.xml
trying overlaySet Key=com_facebook_activity_layout.xml
trying overlaySet Key=com_facebook_device_auth_dialog_fragment.xml
trying overlaySet Key=com_facebook_login_fragment.xml
trying overlaySet Key=com_facebook_smart_device_dialog_fragment.xml
trying overlaySet Key=com_facebook_tooltip_bubble.xml
trying overlaySet Key=messenger_button_send_blue_large.xml
trying overlaySet Key=messenger_button_send_blue_round.xml
trying overlaySet Key=messenger_button_send_blue_small.xml
trying overlaySet Key=messenger_button_send_white_large.xml
trying overlaySet Key=messenger_button_send_white_round.xml
trying overlaySet Key=messenger_button_send_white_small.xml
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
trying overlaySet Key=com_facebook_button_text_color.xml
trying overlaySet Key=com_facebook_send_button_text_color.xml
applyFileOverlay for menu
applyFileOverlay for font
applyFileOverlay for mipmap
Processing image: res/drawable-xhdpi/app_banner.png
Processing image: res/drawable-mdpi/app_icon.png
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_icon_blue.png
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_icon_blue.png
    (processed image /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_icon_blue.png: 30% size of source)
    (processed image /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_icon_blue.png: 23% size of source)
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_icon_blue.png
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_icon_blue.png
    (processed image /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_icon_blue.png: 22% size of source)
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_icon_white.png
    (processed image /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_icon_white.png: 161% size of source)
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_icon_white.png
    (processed image /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_icon_blue.png: 14% size of source)
    (processed image /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_icon_white.png: 157% size of source)
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_icon_white.png
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_icon_white.png
    (processed image /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_icon_white.png: 162% size of source)
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_like_icon_selected.png
    (processed image /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_icon_white.png: 157% size of source)
    (processed image /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_like_icon_selected.png: 147% size of source)
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_like_icon_selected.png
    (processed image /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_like_icon_selected.png: 132% size of source)
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_like_icon_selected.png
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_like_icon_selected.png
    (processed image /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_like_icon_selected.png: 125% size of source)
Processing image: /Volumes/Work/Work/Unity/Trix/Trix/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/co<message truncated></code>

In fact I'm not sure is this the correct solution for my project. :(
Anyway, thanks for your support and please let me know if you have any solution.
Regards

**Comment by cobbpg** [comment]
I'm having the same problem with the latest Facebook SDK. The resource in question is referenced from appcompat-v7. None of the resources in the `drawable` folder make it into the merged dependencies. Just copying the contents of `res` from the original AAR into the merged folder seems to resolve this error.

**Comment by dbarla** [comment]
To build with Resolver inside, i tried everything. PreBuild Grade, update everything. Was a pain. One night (after 4 days with this) i decided to start over. I found that Lastest Facebook was having problems. Firebase Database Package was having problems (Unity 5.05.3f). Unity build was having problems and finally (issue tracker informs they are having problems with lastest SDK Tools), after all this, i ended having problems too (i was thinking on quitting game dev forever). BUT! What i did to solve this is, import each package one by one on a fresh project, take notes from where it fails and try to downgrade. Another thing, i was unable to build with the Resolver Folder inside the Project, so, i taked it out and i was capable to build again. Im not Android expert (or i wasn't after passing trough this, maybe i made an endurance test with SDK, NDK, JAR and AAR in that 4 days). Read the Logs on every try. Hope this helps someone.

**Comment by stewartmiles** [comment]
We removed this experimental feature in aa1a6b8e71ccf99bdf1f935851e9242a39d88bd4 .
