### ISSUE TITLE
[Bug] Non-secure network connections disabled in Player Settings

### ISSUE THREAD

**Issue by nanggiomientrung** [googlesamples/unity-jar-resolver#660]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2023.4f1
  * External Dependency Manager version: 1.2.169
  * Source you installed EDM4U: unitypackage
  * Features in External Dependency Manager in use: Android Resolver + VersionHandler
  * Plugins SDK in use: Google Play Games v0.11.01
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Just follow: https://forum.unity.com/threads/tutorial-authentication-with-google-play-games.1409151/
I dont use Unity services so just disable relevant code. (not affect)
#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
-  100%

What happened? How can we make the problem occur?
- It just happens after import unity package.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.
![Uploading GooglePlayServiceError.png…]()

**Comment by paulinon** [comment]
Hi @nanggiomientrung,

Apologies for the radio silence here. Could you share more screenshots that show the behavior you're facing? The attachment you provided doesn't seem to be working.

**Comment by nanggiomientrung** [comment]
Hi @paulinon, i will update github link here so you can check
Wait for me for fews days.
Thank you
