### ISSUE TITLE
[Bug] Failed to determine the most recently installed Android SDK version.

### ISSUE THREAD

**Issue by AbhijeetDeshmuk** [googlesamples/unity-jar-resolver#662]
Everytime i trying to create build using alttester it will show 

Failed to determine the most recently installed Android SDK version.

Android SDK Build-tools component is not found. Make sure all tools are installed in the SDK manager. Latest supported build-tools version is 30.0.2
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&).

**Comment by paulinon** [comment]
Hi @AbhijeetDeshmuk,

Please file a new ticket and follow the issue template including the needed information so we can have a better understanding of the issue. Thanks.
