### ISSUE TITLE
How to disable the window "Enable Android Auto-resolution"?

### ISSUE THREAD

**Issue by RocksteadyDog** [googlesamples/unity-jar-resolver#666]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.15f1
  * External Dependency Manager version: 1.2.177
  * Source you installed EDM4U: upm .tgz
  * Features in External Dependency Manager in use: Android Resolver,
  * Plugins SDK in use: Firebase, gpgs
  * Platform you are using the Unity editor on: Mac

### [REQUIRED] Please describe the question here:

The "Enable Android Auto-resolution" window opens periodically, I clicked disable but the window still opens periodically. How to disable the window "Enable Android Auto-resolution"

<img width="450" alt="1" src="https://github.com/googlesamples/unity-jar-resolver/assets/29661837/8372899e-8a8b-4a25-b6a8-42d9c11a13fd">

<img width="461" alt="2" src="https://github.com/googlesamples/unity-jar-resolver/assets/29661837/aa7661c7-06b8-4dff-a0b1-ce42c5402e38">

**Comment by AliAlbarrak** [comment]
This seems to be of the symptoms of #524

**Comment by RocksteadyDog** [comment]
> This seems to be of the symptoms of #524

I tried version 1.2.180 and so far everything is great!)
