### ISSUE TITLE
Android Prebuild with Gradle

### ISSUE THREAD

**Issue by Jur-Wind** [googlesamples/unity-jar-resolver#67]
Hi,

Im currently working on a large project with a few plugins. After adding the GoogleMobileAds plugin to the project it hits the lovely dex limit so i enabled the "Prebuild with Gradle"(awesome work btw). But i keep getting this error when i use the "Force Resolve" functionality.

Specs:
macOS Sierra 10.12.6
Unity 2017.1.1f1
Min API level: 16
Max API level: Auto
Installed Android SDK 25 with build tools 25.0.3.
Checked the Package Name(bundleID) in the Android Player Settings.

Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.

Error (1):
Traceback (most recent call last):
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 476, in <module>
    sys.exit(main())
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 468, in main
    generate_gradle_build(build_path, jsobj)
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 215, in generate_gradle_build
    ignore=shutil.ignore_patterns("*.meta"))
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 93, in merge_dir_tree
    shutil.copy2(s, d)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: u'/Users/jur/Documents/AppName/Temp/GenGradle/m2repository/.DS_Store'

UnityEngine.Debug:LogError(Object)
GooglePlayServices.<RunGenGradleScript>c__AnonStoreyE:<>m__11(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
GooglePlayServices.CommandLineDialog:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

I can't see the m2repository in de Temp folder is it missing or does it get removed after something fails?

Kind regards,

Jur

**Comment by johnb003** [comment]
It appears that the issue is copying the output is failing on one of the files that gets inserted by mac OS when you open a folder in the finder.

A work around for now is you can make sure you close any finder windows that browsed to this folder, and then delete these via the terminal:
find /Users/jur/Documents/AppName/Temp/ -name ".DS_Store" -depth -exec rm {} \;

It's really strange this is happening though, I'm guessing that the copy script doesn't have permission to deal with those files, and dies. I'll see if we can make this more robust.

Thanks for reporting.

**Comment by Jur-Wind** [comment]
Thanks for your quick reply!

I removed all the .DS_Store in my project and the error is now gone. Unfortunately i receive the next error:(

Error (1):
Traceback (most recent call last):
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 476, in <module>
    sys.exit(main())
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 468, in main
    generate_gradle_build(build_path, jsobj)
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 215, in generate_gradle_build
    ignore=shutil.ignore_patterns("*.meta"))
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 76, in merge_dir_tree
    paths = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'https://maven.google.com'

**Comment by johnb003** [comment]
Wow this is an interesting problem.

It appears you have an up-to-date unity plugin with an old script.
My guess is that this may be left-over from an older install??

I recommend deleting the entire PlayServicesResolver directory, and
installing this plugin again from Github.
We used to include those script files directly, and now they are bundled
with the DLL as resources that we extract before using, however if somehow
the old scripts are still present and didn't get cleaned up, it may use
those instead?

Whatever the case, a fresh clear and reinstall of this plugin should help.

**Comment by johnb003** [comment]
On second thought, it's definitely extracting the script. Anyway, try
updating anyway and see if that fixes it.

`John

**Comment by Jur-Wind** [comment]
I keep getting this error even with a new project.

- Create new project
- Switch to Android
- Import FirebaseAnalytics.unitypackage
- Import GoogleMobileAds.unitypackage
- Import play-services-resolver-1.2.50.0.unitypackage
- Build

**Comment by Jur-Wind** [comment]
When i remove the https://maven.google.com from GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml i run into the next error what i believe is an versioning problem:(

Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.

Error (1):
Starting a Gradle Daemon (subsequent builds will be faster)
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:preBuild UP-TO-DATE
:extractProguardFiles
:preReleaseBuild
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:prepareComAndroidSupportSupportCompat2520Library
:prepareComAndroidSupportSupportCoreUi2520Library
:prepareComAndroidSupportSupportCoreUtils2520Library
:prepareComAndroidSupportSupportFragment2520Library
:prepareComAndroidSupportSupportMediaCompat2520Library
:prepareComAndroidSupportSupportV42520Library
:prepareComGoogleAndroidGmsPlayServicesAds1122Library
:prepareComGoogleAndroidGmsPlayServicesAdsLite1122Library
:prepareComGoogleAndroidGmsPlayServicesBase1120Library
:prepareComGoogleAndroidGmsPlayServicesBasement1122Library
:prepareComGoogleAndroidGmsPlayServicesGass1122Library
:prepareComGoogleAndroidGmsPlayServicesTasks1120Library
:prepareComGoogleFirebaseFirebaseAnalytics1120Library
:prepareComGoogleFirebaseFirebaseAnalyticsImpl1120Library
:prepareComGoogleFirebaseFirebaseAnalyticsUnity410Library
:prepareComGoogleFirebaseFirebaseAppUnity410Library
:prepareComGoogleFirebaseFirebaseCommon1120Library
:prepareComGoogleFirebaseFirebaseCore1120Library
:prepareComGoogleFirebaseFirebaseIid1120Library
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:incrementalReleaseJavaCompilationSafeguard
:compileReleaseJavaWithJavac
:processReleaseJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForRelease
:transformClassesAndResourcesWithProguardForRelease
ProGuard, version 5.2.1
Reading input...
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.firebase/firebase-common/11.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.android.gms/play-services-basement/11.2.2/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Sdk/Android/extras/android/m2repository/com/android/support/support-annotations/25.2.0/support-annotations-25.2.0.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.android.gms/play-services-base/11.2.0/jars/classes.jar] (filtered)
Note: duplicate definition of program class [com.google.android.gms.internal.zzbcc]
Note: duplicate definition of program class [com.google.android.gms.internal.zzbce]
Note: duplicate definition of program class [com.google.android.gms.internal.zzbcd]
Note: duplicate definition of program class [com.google.android.gms.internal.zzbcf]
Note: duplicate definition of program class [com.google.android.gms.internal.zzbch]
Note: duplicate definition of program class [com.google.android.gms.internal.zzbcg]
Note: duplicate definition of program class [com.google.android.gms.internal.zzbcw]
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.firebase/firebase-iid/11.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.firebase/firebase-core/11.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.android.gms/play-services-ads-lite/11.2.2/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.android.support/support-fragment/25.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.android.gms/play-services-ads/11.2.2/jars/classes.jar] (filtered)
Note: duplicate definition of program class [com.google.android.gms.internal.zzehf]
Note: duplicate definition of program class [com.google.android.gms.internal.zzehh]
Note: duplicate definition of program class [com.google.android.gms.internal.zzehg]
Note: duplicate definition of program class [com.google.android.gms.internal.zzehj]
Note: duplicate definition of program class [com.google.android.gms.internal.zzehi]
Note: duplicate definition of program class [com.google.android.gms.internal.zzehk]
Note: duplicate definition of program class [com.google.android.gms.internal.zzehl]
Note: duplicate definition of program class [com.google.android.gms.internal.zzehm]
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.android.gms/play-services-gass/11.2.2/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.firebase/firebase-analytics-unity/4.1.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.firebase/firebase-app-unity/4.1.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.android.support/support-v4/25.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.android.support/support-core-utils/25.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.android.support/support-media-compat/25.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.android.support/support-compat/25.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.firebase/firebase-analytics-impl/11.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.android.support/support-core-ui/25.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.android.gms/play-services-tasks/11.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/exploded-aar/com.google.firebase/firebase-analytics/11.2.0/jars/classes.jar] (filtered)
Reading program jar [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/transforms/mergeJavaRes/release/jars/2/1f/main.jar] (filtered)
Reading program directory [/Users/jur/Documents/PlayServiceResolver/Temp/GenGradle/build/intermediates/classes/release] (filtered)
Reading library jar [/Users/jur/Sdk/Android/platforms/android-25/android.jar]
Reading library jar [/Users/jur/Sdk/Android/platforms/android-25/optional/org.apache.http.legacy.jar]
Note: duplicate definition of library class [android.net.http.HttpResponseCache]
Note: duplicate definition of library class [android.net.http.SslCertificate$DName]
Note: duplicate definition of library class [android.net.http.SslError]
Note: duplicate definition of library class [android.net.http.SslCertificate]
Note: duplicate definition of library class [org.apache.http.params.CoreConnectionPNames]
Note: duplicate definition of library class [org.apache.http.params.HttpConnectionParams]
Note: duplicate definition of library class [org.apache.http.params.HttpParams]
Note: duplicate definition of library class [org.apache.http.conn.scheme.SocketFactory]
Note: duplicate definition of library class [org.apache.http.conn.scheme.LayeredSocketFactory]
Note: duplicate definition of library class [org.apache.http.conn.scheme.HostNameResolver]
Note: duplicate definition of library class [org.apache.http.conn.ConnectTimeoutException]
Initializing...
Note: the configuration refers to the unknown class 'com.google.android.gms.crash.internal.api.CrashApiImpl'
Note: the configuration refers to the unknown class 'com.google.android.gms.common.internal.safeparcel.SafeParcelable'
Note: com.google.android.gms.internal.zzcap: can't find dynamically referenced class android.os.SystemProperties
Note: com.google.android.gms.internal.zzcdo: can't find dynamically referenced class com.google.android.gms.tagmanager.TagManagerService
Note: com.google.android.gms.internal.zzeej: can't find dynamically referenced class com.google.protobuf.ExtensionRegistry
Note: com.google.android.gms.internal.zzeek: can't find dynamically referenced class com.google.protobuf.Extension
Note: com.google.android.gms.internal.zzegc: can't find dynamically referenced class libcore.io.Memory
Note: com.google.android.gms.internal.zzegc: can't find dynamically referenced class org.robolectric.Robolectric
Note: com.google.android.gms.dynamite.DynamiteModule accesses a declared field 'MODULE_ID' dynamically
      Maybe this is program field 'com.google.android.gms.dynamite.descriptors.com.google.android.gms.ads.dynamite.ModuleDescriptor { java.lang.String MODULE_ID; }'
      Maybe this is program field 'com.google.android.gms.dynamite.descriptors.com.google.android.gms.flags.ModuleDescriptor { java.lang.String MODULE_ID; }'
Note: com.google.android.gms.dynamite.DynamiteModule accesses a declared field 'MODULE_VERSION' dynamically
      Maybe this is program field 'com.google.android.gms.dynamite.descriptors.com.google.android.gms.ads.dynamite.ModuleDescriptor { int MODULE_VERSION; }'
      Maybe this is program field 'com.google.android.gms.dynamite.descriptors.com.google.android.gms.flags.ModuleDescriptor { int MODULE_VERSION; }'
Note: com.google.android.gms.dynamite.DynamiteModule accesses a declared field 'sClassLoader' dynamically
      Maybe this is program field 'com.google.android.gms.dynamite.DynamiteModule$DynamiteLoaderClassLoader { java.lang.ClassLoader sClassLoader; }'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { com.google.android.gms.ads.AdRequest zza(android.content.Context,com.google.android.gms.ads.mediation.MediationAdRequest,android.os.Bundle,android.os.Bundle); }', but not the descriptor class 'com.google.android.gms.ads.mediation.MediationAdRequest'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { void requestBannerAd(android.content.Context,com.google.android.gms.ads.mediation.MediationBannerListener,android.os.Bundle,com.google.android.gms.ads.AdSize,com.google.android.gms.ads.mediation.MediationAdRequest,android.os.Bundle); }', but not the descriptor class 'com.google.android.gms.ads.mediation.MediationBannerListener'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { void requestBannerAd(android.content.Context,com.google.android.gms.ads.mediation.MediationBannerListener,android.os.Bundle,com.google.android.gms.ads.AdSize,com.google.android.gms.ads.mediation.MediationAdRequest,android.os.Bundle); }', but not the descriptor class 'com.google.android.gms.ads.AdSize'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { void requestBannerAd(android.content.Context,com.google.android.gms.ads.mediation.MediationBannerListener,android.os.Bundle,com.google.android.gms.ads.AdSize,com.google.android.gms.ads.mediation.MediationAdRequest,android.os.Bundle); }', but not the descriptor class 'com.google.android.gms.ads.mediation.MediationAdRequest'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { void requestInterstitialAd(android.content.Context,com.google.android.gms.ads.mediation.MediationInterstitialListener,android.os.Bundle,com.google.android.gms.ads.mediation.MediationAdRequest,android.os.Bundle); }', but not the descriptor class 'com.google.android.gms.ads.mediation.MediationInterstitialListener'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { void requestInterstitialAd(android.content.Context,com.google.android.gms.ads.mediation.MediationInterstitialListener,android.os.Bundle,com.google.android.gms.ads.mediation.MediationAdRequest,android.os.Bundle); }', but not the descriptor class 'com.google.android.gms.ads.mediation.MediationAdRequest'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { void requestNativeAd(android.content.Context,com.google.android.gms.ads.mediation.MediationNativeListener,android.os.Bundle,com.google.android.gms.ads.mediation.NativeMediationAdRequest,android.os.Bundle); }', but not the descriptor class 'com.google.android.gms.ads.mediation.MediationNativeListener'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { void requestNativeAd(android.content.Context,com.google.android.gms.ads.mediation.MediationNativeListener,android.os.Bundle,com.google.android.gms.ads.mediation.NativeMediationAdRequest,android.os.Bundle); }', but not the descriptor class 'com.google.android.gms.ads.mediation.NativeMediationAdRequest'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { void initialize(android.content.Context,com.google.android.gms.ads.mediation.MediationAdRequest,java.lang.String,com.google.android.gms.ads.reward.mediation.MediationRewardedVideoAdListener,android.os.Bundle,android.os.Bundle); }', but not the descriptor class 'com.google.android.gms.ads.mediation.MediationAdRequest'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { void initialize(android.content.Context,com.google.android.gms.ads.mediation.MediationAdRequest,java.lang.String,com.google.android.gms.ads.reward.mediation.MediationRewardedVideoAdListener,android.os.Bundle,android.os.Bundle); }', but not the descriptor class 'com.google.android.gms.ads.reward.mediation.MediationRewardedVideoAdListener'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { void loadAd(com.google.android.gms.ads.mediation.MediationAdRequest,android.os.Bundle,android.os.Bundle); }', but not the descriptor class 'com.google.android.gms.ads.mediation.MediationAdRequest'
Note: the configuration keeps the entry point 'com.google.ads.mediation.AbstractAdViewAdapter { com.google.android.gms.ads.InterstitialAd zza(com.google.ads.mediation.AbstractAdViewAdapter,com.google.android.gms.ads.InterstitialAd); }', but not the descriptor class 'com.google.android.gms.ads.InterstitialAd'
Note: the configuration keeps the entry point 'com.google.ads.mediation.MediationBannerAdapter { void requestBannerAd(com.google.ads.mediation.MediationBannerListener,android.app.Activity,com.google.ads.mediation.MediationServerParameters,com.google.ads.AdSize,com.google.ads.mediation.MediationAdRequest,com.google.ads.mediation.NetworkExtras); }', but not the descriptor class 'com.google.ads.mediation.MediationBannerListener'
Note: the configuration keeps the entry point 'com.google.ads.mediation.MediationBannerAdapter { void requestBannerAd(com.google.ads.mediation.MediationBannerListener,android.app.Activity,com.google.ads.mediation.MediationServerParameters,com.google.ads.AdSize,com.goog<message truncated>

**Comment by kenglou** [comment]
I'm having such problem too as I had deleted the old version and do a clean import and it seems like it can't access the maven.google.com. Any solution on this? I managed to build if using Android Studio but not from here.

Below are my error log:

```
Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.

Error (1):
Traceback (most recent call last):
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 476, in <module>
    sys.exit(main())
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 468, in main
    generate_gradle_build(build_path, jsobj)
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 215, in generate_gradle_build
    ignore=shutil.ignore_patterns("*.meta"))
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 76, in merge_dir_tree
    paths = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'https://maven.google.com'

UnityEngine.Debug:LogError(Object)
GooglePlayServices.<RunGenGradleScript>c__AnonStoreyE:<>m__11(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
GooglePlayServices.CommandLineDialog:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

**Comment by stewartmiles** [comment]
We removed this experimental feature in aa1a6b8e71ccf99bdf1f935851e9242a39d88bd4 .
