### ISSUE TITLE
[Question] Issue with Missing Registries After Accidental Deletion

### ISSUE THREAD

**Issue by JJunTing** [googlesamples/unity-jar-resolver#677]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.20f1
  * External Dependency Manager version: 1.2.169
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Firebase
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the question here:

Hello,

I accidentally removed my registries, and now whenever I modify the settings, the system displays the following warning:
"No registry found from any Registries.xml files."

Could you please assist me in resolving this issue? 

Thank you!

![02](https://github.com/googlesamples/unity-jar-resolver/assets/70137139/a685a7a3-26c4-4f93-8abc-fa5be3cbc460)
![01](https://github.com/googlesamples/unity-jar-resolver/assets/70137139/a61b62e7-9884-4dfc-b3f7-f12e1d1db876)

**Comment by argzdev** [comment]
Hey @JJunTing, I'm not sure how you can revert missing registries. I'm guessing you're going to have to reinstall the same version of the Unity SDK. Could you try changing to another version of the Unity SDK and see if that makes any difference? However, since this is experimental, make sure to backup your files before making any changes.

**Comment by JJunTing** [comment]
Hi, thanks for the reply. I'm working on another project now, so please
close the case first, if there's any new issue in the future, I will let
you know. Thanks friend.

ᐧ

**Comment by argzdev** [comment]
Okay, thanks for letting me know. I'll go ahead and close this thread.
