### ISSUE TITLE
[Bug] Wait for user code in Google.VersionHandlerImpl.dll to finish executing.

### ISSUE THREAD

**Issue by RampantDespair** [googlesamples/unity-jar-resolver#679]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: <ins>2021.3.25f1</ins>
  * External Dependency Manager version: <ins>1.2.177</ins>
  * Source you installed EDM4U: <ins>Unity Package Manager</ins>
  * Features in External Dependency Manager in use: <ins>VersionHandler</ins>
  * Plugins SDK in use: <ins>FacebookSDK and [Essential Kit](https://assetstore.unity.com/packages/tools/integration/cross-platform-native-plugins-essential-kit-mobile-ios-android-140111)</ins>
  * Platform you are using the Unity editor on: <ins>Windows</ins>

### [REQUIRED] Please describe the issue here:

When I launch my project, I get stuck on this window forever:
![image](https://github.com/googlesamples/unity-jar-resolver/assets/63611551/ae94a1a8-9c06-49e4-8def-8081764cc6df)
The only solution I found was to rename the `Google.VersionHandlerImpl.dll` file to something else, then launch the project, then revert the name back.
It only occurs on project launch, not during recompiles or reloads.
When it does happen, I cannot simply just close the project and reopen it, I'm stuck on this loop until I rename the file and open the project.

Here are my logs:
[Editor.log](https://github.com/googlesamples/unity-jar-resolver/files/14817892/Editor.log)
[upm.log](https://github.com/googlesamples/unity-jar-resolver/files/14817894/upm.log)

#### Please answer the following, if applicable:

What's the issue repro rate? (eg 100%, 1/5 etc)
The worst, it's completely random... It just happens sometimes :/

What happened? How can we make the problem occur?
I can't reproduce it, as I stated above it's completely random.
I don't know if it's possible to enable debug log for this dll, but if I could, I suppose I'd have more information (assuming that what I gave above is insufficient, which I suspect)

**Comment by paulinon** [comment]
Hi @RampantDespair,

Could you try if using the latest EDM4U [release](https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.179) or updating the Unity [editor](https://unity.com/releases/editor/qa/lts-releases?version=2021.3) makes any difference?

**Comment by RampantDespair** [comment]
@paulinon I will test it out and report back.
