### ISSUE TITLE
Unity 5.6 with Google Play Services and Firebase Messaging

### ISSUE THREAD

**Issue by TonyHoCF** [googlesamples/unity-jar-resolver#68]
I'm running into the issue of conflicting libraries when installing the latest Google Play Services and Firebase Messaging plugins.  Google Play Services requires the library play-services-auth-10.2.6 while Firebase Messaging requires play-services-base-11.2.0, according to the resolver.  I think the play services libraries need to use the same version, but the resolver will only download these versions.  Am I missing something?  I've tested this in an empty project as well.

**Comment by brockw** [comment]
Yeah I think I am getting the same issue. I get a strange mix of 10.2.6 and 11.4.0 libraries.

When I try to compile I get the already in type error.

Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/internal/zzm;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/zzc;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzalv;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzalw;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzalx;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzaly;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzalz;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzama;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzamb; 

![screen shot 2017-09-21 at 4 20 56 pm](https://user-images.githubusercontent.com/749542/30721366-e6eb6124-9ee8-11e7-9546-1e11f7bac299.png)

**Comment by stewartmiles** [comment]
@rampara @claywilkinson FYI

For the moment you need to change your references to Google Play Services to 11+ in all plugins that reference Android Dependencies.  See https://github.com/googlesamples/unity-jar-resolver/tree/master/sample/Assets/PlayServicesResolver/Editor for examples of how dependencies are specify by plugins.

**Comment by claywilkinson** [comment]
@stewartmiles  - The GPGS plugin is [using 10+](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Editor/GPGSDependencies.xml#L24)  - isn't that resolvable to 11+?

**Comment by stewartmiles** [comment]
@claywilkinson one can dream :) Unfortunately I think Gradle treats 10+ as 10.+.

**Comment by stewartmiles** [comment]
I've implemented a better solution to this in 0d57b1d36acbca0f743a4aca3e05bcd65f9ecd63 which works at the moment with the Gradle resolver (*not* prebuild right now).  This should resolve the current problem here.

**Comment by voxelbusters** [comment]
@brockw FYI, The new update of Cross Platform Native Plugins (under Review) uses 1.2.53.
