### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by RoberTrypucHuuuge** [googlesamples/unity-jar-resolver#681]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.10f1
  * External Dependency Manager version: 1.2.179
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Firebase
  * Platform you are using the Unity editor on: Mac and Windows

### [REQUIRED] Please describe the issue here:
There are 2 issues actually however the first one can't reproduce but it is making the main issue (second) to occur more frequent.
1) The entry in ProjectSettings.asset for android resolver is removed - less important
2) The Android build stack on building scene when auto resolve dependencies popup is shown - The main one.

#### Please answer the following, if applicable:
 100%

What happened? How can we make the problem occur?
It here is a fresh installation of the package, or in in some case (probably by switching between the platforms and maybe building on other platform (iOS in my case) the setup for auto resolve dependencies is removed (issue 1 less important, don't have 100% repro yet).
When trying to build Android  and the auto resolve dependencies popup is shown (with option to disable it) the build is tacking on building scene and never ends this, only killing Unity process can help.

**Comment by argzdev** [comment]
Hey @RoberTrypucHuuuge, thanks for reaching out. I'm not exactly sure what "the build is tacking on building scene" means. Do you mean to say is that the pop up blocks the build scene and it never ends? If so, could you provide steps to reproduce this behavior? Thanks!
