### ISSUE TITLE
Unity editor play delay

### ISSUE THREAD

**Issue by Woondal** [googlesamples/unity-jar-resolver#70]
When I play my game project on Unity editor it is delayed by about 10 sec at the beginning. (about right after the first Update() is called)

This delay disappears when I remove PlayServicesResolver from my project.

This issue does not happens on an empty(clean) project, so it may be related with checking assets..

I'm not sure exactly when this problem started, but it seems to have something to do with the latest builds.

This happens on both 1.2.50 and 1.2.52 version.

Now I'm rolling back and finding previous version free from this issue.

Unity version: 2017.1.1f1 (64bit)

**Comment by Woondal** [comment]
Disabling the 'Enable auto-resolution' option under Android Resolver setting resolved the issue.

But in this case, I have to run the resolution manually..

**Comment by stewartmiles** [comment]
10s seems pretty crazy, we do now refresh the set of project dependencies each time auto resolution executed.
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/src/XmlDependencies.cs#L49

This could be slow if the project has a huge number of assets.  10s sounds excessive.  Any chance you have an example project we can test with?

**Comment by Woondal** [comment]
I'm afraid I cannot share this project, instead I have tested it with the code you mentioned like this.

private List<string> FindFiles()
    {
        int loop1Count = 0;
        var key = "loopTime";

        var lastElapsed = 0f;
        var matchingFiles = new List<string>();
        var w = Stopwatch.StartNew();
        var lastTime = 0f;
        foreach( var assetGuid in AssetDatabase.FindAssets("t:Object") )
        {
            ++loop1Count;
            var dependencyFile = AssetDatabase.GUIDToAssetPath(assetGuid);
            foreach( var regex in fileRegularExpressions )
            {
                if( regex.Match(dependencyFile).Success )
                {
                    matchingFiles.Add(dependencyFile);
                }
            }
            MyDevTool.Watcher.Watch(key, w.ElapsedMilliseconds - lastTime);
            lastTime = w.ElapsedMilliseconds;
        }
        Debug.Log("Total Assets: " + loop1Count);
        Debug.Log("Total Elapsed: " + w.ElapsedMilliseconds);
        var t = MyDevTool.Watcher.GetItem(key);
        Debug.Log("Loop Time (Avrg/Min/Max): " + t.Avrg + " / " + t.Min + " / " + t.Max);

        matchingFiles.DebugLog();

        return matchingFiles;
    }


Result:
-----------------------------
Total Assets: 15915
Total Elapsed: 9557
Loop Time (Avrg/Min/Max): 0.598240653471568 / 0 / 25
List is empty!
-----------------------------

That code was causing the delay as you guessed.
I also measured each loop time to check if any specific file takes much time, but there was not. It seems to be related to just the number of assets. 
A large part of the number is graphic asset, but if this number is too excessive I had better reduce the number..

**Comment by stewartmiles** [comment]
Ok it sounds like we'll need to cache the set of *Dependencies.xml files in a Temp file and use that file to track the *Dependencies.xml files in the project.   Thanks for clarifying the problematic lump of code.

**Comment by Woondal** [comment]
Thank you too. Happy to hear that. I look forward to the improvement :)
