### ISSUE TITLE
Pod bundle_resources with pbxproj integration 

### ISSUE THREAD

**Issue by rlepinski** [googlesamples/unity-jar-resolver#71]
This is the same issue reported here https://github.com/googlesamples/unity-jar-resolver/issues/33

It still seems to be an issue only if you bypass the xcworkspace integration. The problem is when a pod specifies its resource bundle content instead of a prepackaged resource bundle. The Urban Airship pod makes use of this feature: https://github.com/urbanairship/ios-library/blob/master/UrbanAirship-iOS-SDK.podspec#L18

When building with pbxproj integration, it appears that the resources are completely ignored and missing from the  project. Ideally this project would generate a resource bundle with the provided info and add it to the project.

**Comment by stewartmiles** [comment]
@rlepinski any chance you could provide a sample project that demonstrates this?  Sounds like you're over at Urban Airship, any chance you have time to work on a patch?

"pod install" should end up dumping the resources into a temporary folder that we scrape resources from in here https://github.com/googlesamples/unity-jar-resolver/blob/master/source/IOSResolver/src/IOSResolver.cs#L2104

**Comment by rlepinski** [comment]
@stewartmiles Ill try to provide a sample project today or tomorrow that shows the issue. For fixing it, I can try to come up with a fix in the next few weeks. Thanks for the pointer, I am sure I will have follow up questions.

**Comment by rlepinski** [comment]
[GH-71.zip](https://github.com/googlesamples/unity-jar-resolver/files/1360285/GH-71.zip)

Sample project with UA pod

**Comment by johnb003** [comment]
In the plugin released with Firebase 4.2.1 we've updated this resolution to only happen during build.

**Comment by stewartmiles** [comment]
Fixed by eea4aba0672d6e5027770fc217f72785bb449065
