### ISSUE TITLE
[Bug] Unity EDM4U,  Firebase and Google Sign In Error: Cannot load DLL 'native-googlesignin'

### ISSUE THREAD

**Issue by bayramalibayrak** [googlesamples/unity-jar-resolver#719]
* Unity editor version: 2021.3.45f1
  * External Dependency Manager version: 1.2.183
  * Source you installed EDM4U: Githyb/googlesamples/unity-jar-resolver (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: _____ (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: Firebase(Auth - Remote Config- Messaging), RevenueCat, Google Sign In
  * Platform you are using the Unity editor on: Android/IOS

 I have a project file is mobile app. In my project tools is Firebase Auth, Remote Config and Messaging. My Google Sign In package stopped working after this jar update and I get this error:

`2024/11/20 19:19:05.811 27726 27790 Error Unity DllNotFoundException: Unable to load DLL 'native-googlesignin'. Tried the load the following dynamic libraries: Unable to load dynamic library 'native-googlesignin' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "native-googlesignin" not found
2024/11/20 19:19:05.811 27726 27790 Error Unity   at Google.Impl.GoogleSignInImpl.GoogleSignIn_Create (System.IntPtr data) [0x00000] in <00000000000000000000000000000000>:0 
2024/11/20 19:19:05.811 27726 27790 Error Unity   at Google.Impl.GoogleSignInImpl..ctor (Google.GoogleSignInConfiguration configuration) [0x00000] in <00000000000000000000000000000000>:0 
2024/11/20 19:19:05.811 27726 27790 Error Unity   at Google.GoogleSignIn.get_DefaultInstance () [0x00000] in <00000000000000000000000000000000>:0 
2024/11/20 19:19:05.811 27726 27790 Error Unity   at GoogleSignInManager.SignInWithGoogle () [0x00000] in <00000000000000000000000000000000>:0 
2024/11/20 19:19:05.811 27726 27790 Error Unity   at UnityEngine.Events.UnityEvent.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
2024/11/20 19:19:05.811 27726 27790 Error Unity   at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.Ex
`

What should I do?

**Comment by argzdev** [comment]
Hey @bayramalibayrak, thanks for reaching out. This looks like a [similar issue](https://github.com/googlesamples/google-signin-unity/issues/106#issuecomment-526860698). Could you try the solution provided in the thread? Also it would seem that you might get better assistance if you file in the Google Sign In repository.

That said, I'll go ahead and close this thread for now.
