### ISSUE TITLE
Android Maven dependencies not processed when using a x.y.z-foo version number.

### ISSUE THREAD

**Issue by martino2k6** [googlesamples/unity-jar-resolver#72]
I have some snapshot artifacts which I'm deploying locally on my machine for development, however the Jar Resolver (1.2.52.0) doesn't seem to be picking these up (Unity 2017.1.1f1).

C# script declaration snippet:
```
resolver.DependOn(
                "com.deltadna.android",
                "deltadna-sdk-notifications-google",
                "4.6.0-SNAPSHOT",
                repositories: new string[] { "C:\\Users\\Martin\\.m2\\repository" });
```

Unity output:
```
Resolving...
Reading com.deltadna.android:deltadna-sdk-notifications-google:4.6.0-SNAPSHOT from repository C:\Users\Martin\.m2\repository
Read metadata for com.deltadna.android:deltadna-sdk-notifications-google:4.6.0-SNAPSHOT found compatible versions (4.6.0-SNAPSHOT) from available versions (4.6.0-SNAPSHOT)
Artifact C:\Users\Martin\.m2\repository\com\deltadna\android\deltadna-sdk-notifications-google\4.6.0-SNAPSHOT not found for com.deltadna.android:deltadna-sdk-notifications-google:4.6.0-SNAPSHOT version 4.6.0-SNAPSHOT
```

Maven folder listing:
```
Martin@<redacted> MINGW64 ~/.m2/repository/com/deltadna/android/deltadna-sdk-notifications-google/4.6.0-SNAPSHOT
$ ls
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1.aar
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1.aar.md5
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1.aar.sha1
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1.pom
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1.pom.md5
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1.pom.sha1
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1-javadoc.jar
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1-javadoc.jar.md5
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1-javadoc.jar.sha1
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1-sources.jar
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1-sources.jar.md5
deltadna-sdk-notifications-google-4.6.0-20170926.130656-1-sources.jar.sha1
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2.aar
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2.aar.md5
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2.aar.sha1
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2.pom
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2.pom.md5
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2.pom.sha1
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2-javadoc.jar
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2-javadoc.jar.md5
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2-javadoc.jar.sha1
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2-sources.jar
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2-sources.jar.md5
deltadna-sdk-notifications-google-4.6.0-20170926.133341-2-sources.jar.sha1
maven-metadata.xml
maven-metadata.xml.md5
maven-metadata.xml.sha1
maven-metadata-remote.xml
maven-metadata-remote.xml.sha1
resolver-status.properties
```

Maven metadata XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>com.deltadna.android</groupId>
  <artifactId>deltadna-sdk-notifications-google</artifactId>
  <version>4.6.0-SNAPSHOT</version>
  <versioning>
    <snapshot>
      <timestamp>20170926.133341</timestamp>
      <buildNumber>2</buildNumber>
    </snapshot>
    <lastUpdated>20170926133341</lastUpdated>
  </versioning>
</metadata>
```

Let me know if you need any further details that could help you out. Thank you.

**Comment by stewartmiles** [comment]
@martino2k6 you're using the Gradle resolver?

Any chance you could give this a try with artifacts that don't have "-FOO" modifiers?  I'm guessing our artifact version number parsing is broken somewhere, e.g I know I'm guilty of making the assumption that artifacts are versioned `some-package-SOMEVERSION.ext` which is going to break with `some-package-SOMEVERSION-SNAPSHOT.txt` as `SNAPSHOT` will be picked up as the version.

Also, we now support dependency specification via XML files and are planning on deprecating support for programmatically specifying dependencies which is ugly, error prone and occasionally fails in random ways due to the non-deterministic initialization order.

**Comment by martino2k6** [comment]
Yes, this is using the Gradle resolver.

You're right, the `-SNAPSHOT` suffix is what makes it break. It'd be great if the Jar Resolver could support this as that would make our development pipeline simpler :)

I have noticed the new XML format, however currently it's easier for us to specify the dependencies in scripts as we need to change which dependencies are needed depending on user choice. I suspect we will be able to do this with the XML files as well by changing the declarations in there.

**Comment by stewartmiles** [comment]
@martino2k6 we were hoping to remove the API to change dependencies. 

I was wondering whether you could migrate to using the XML format and rewrite the XML files based upon the user's specified set of dependencies.  Would that work in your use case?

Also, for the `-SNAPSHOT` suffix, we're happy to accept patches 👍

**Comment by martino2k6** [comment]
If rewriting the XML and then being able to ask the resolver to reload the dependencies will work then that will be good for us :)

I'll see what I can do about a patch, I recall having issues compiling the project last time I cloned it.

**Comment by martino2k6** [comment]
I've started looking at moving to the XML format for our project and there's one thing which isn't clear to me yet from the documentation; How do I specify the location(s) of the Maven repo(s) to be used for fetching the dependencies? For example, if I'd like to test with locally deployed snapshots.

**Comment by martino2k6** [comment]
Never-mind, I have found an example in the sample project. My bad.

**Comment by martino2k6** [comment]
Seems to work fine with v1.2.56.0 when the dependencies are defined using the XML format.
