### ISSUE TITLE
[FR] Add Git Url possibility to the installation guide Readme

### ISSUE THREAD

**Issue by CoderGamester** [googlesamples/unity-jar-resolver#725]
### Feature proposal

* EDM4U Component: Package Manager

Add in the installation guide Readme.MD the instruction to install the package directly via Git URL
Will be helpful for more not experienced Unity devs.

In case one reads this ticket:
- Open Package Manager
- Click on the + icon on the top left corner of the "Package Manager" scren
- Click on "Install package from git url..."
- Paste: https://github.com/googlesamples/unity-jar-resolver.git?path=upm

![image](https://github.com/user-attachments/assets/e0b0640a-cc24-4d09-bcb4-9bd9b7025d8b)
![image](https://github.com/user-attachments/assets/bb8a8bba-699d-4142-a86d-6ed550c64725)

**Comment by divieirasilva** [comment]
This ticket helped me with tha installation process, thank you

**Comment by argzdev** [comment]
Hi @CoderGamester, thank you for this contribution! We appreciate every effort in making our repository better. I went ahead and created this pull request. Hopefully we can have this reviewed by our engineers soon. Thanks again!

**Comment by argzdev** [comment]
This is now merged, thanks again @CoderGamester! I'll go ahead and close this thread.
