### ISSUE TITLE
Can anyone help about the new dependency management ?

### ISSUE THREAD

**Issue by AdnanNazir** [googlesamples/unity-jar-resolver#73]
Hello Hi, 
I was using this code for dependency resolution.
`using System;
using System.Collections.Generic;
using UnityEditor;

/// Sample dependencies file.  Change the class name and dependencies as required by your project, then
/// save the file in a folder named Editor (which can be a sub-folder of your plugin).
///   There can be multiple dependency files like this one per project, the  resolver will combine them and process all
/// of them at once.
[InitializeOnLoad]
public class NativePluginDependencies : AssetPostprocessor {
    #if UNITY_ANDROID
    /// <summary>Instance of the PlayServicesSupport resolver</summary>
    public static object svcSupport;
    #endif  // UNITY_ANDROID

    /// Initializes static members of the class.
    static NativePluginDependencies() {

        //         NOTE:
        //        
        //               UNCOMMENT THIS CALL TO MAKE THE DEPENDENCIES BE REGISTERED.
        //           THIS FILE IS ONLY A SAMPLE!!

        RegisterDependencies();

    }

    /// <summary>
    /// Registers the dependencies needed by this plugin.
    /// </summary>
    public static void RegisterDependencies() {
        #if UNITY_ANDROID
        RegisterAndroidDependencies();
        #elif UNITY_IOS
        RegisterIOSDependencies();
        #endif
    }

    /// <summary>
    /// Registers the android dependencies.
    /// </summary>
    public static void RegisterAndroidDependencies() {

        // Setup the resolver using reflection as the module may not be
        // available at compile time.
        Type playServicesSupport = Google.VersionHandler.FindClass(
            "Google.JarResolver", "Google.JarResolver.PlayServicesSupport");
        if (playServicesSupport == null) {
            return;
        }
        svcSupport = svcSupport ?? Google.VersionHandler.InvokeStaticMethod(
            playServicesSupport, "CreateInstance",
            new object[] {
            "GooglePlayGames",
            EditorPrefs.GetString("AndroidSdkRoot"),
            "ProjectSettings"
        });

        // For example to depend on play-services-games version 9.6.0  you need to specify the
        // package, artifact, and version as well as the packageId from the SDK manager in case
        // a newer version needs to be downloaded to build.

        //        Google.VersionHandler.InvokeInstanceMethod(
        //            svcSupport, "DependOn",
        //            new object[] {
        //            "com.google.android.gms",
        //            "play-services-games",
        //            "9.6.0" },
        //            namedArgs: new Dictionary<string, object>() {
        //            {"packageIds", new string[] { "extra-google-m2repository" } }
        //        });

        // This example gets the com.android.support.support-v4 library, version 23.1 or greater.
        // notice it is in a different package  than the play-services libraries.

        Google.VersionHandler.InvokeInstanceMethod(
            svcSupport, "DependOn",
            new object[] { "com.android.support", "support-core-utils", "25.2.0" },
            namedArgs: new Dictionary<string, object>() {
            {"packageIds", new string[] { "extra-android-m2repository" } }
        });
    }

    /// <summary>
    /// Registers the IOS dependencies.
    /// </summary>
    public static void RegisterIOSDependencies() {

        // Setup the resolver using reflection as the module may not be
        // available at compile time.
        Type iosResolver = Google.VersionHandler.FindClass(
            "Google.IOSResolver", "Google.IOSResolver");
        if (iosResolver == null) {
            return;
        }

        // Dependencies for iOS are added by referring to CocoaPods.  The libraries and frameworkds are
        //  and added to the Unity project, so they will automatically be included.
        //
        // This example add the GooglePlayGames pod, version 5.0 or greater, disabling bitcode generation.

        Google.VersionHandler.InvokeStaticMethod(
            iosResolver, "AddPod",
            new object[] { "GooglePlayGames" },
            namedArgs: new Dictionary<string, object>() {
            { "version", "5.0+" },
            { "bitcodeEnabled", false },
        });
    }

    // Handle delayed loading of the dependency resolvers.
    private static void OnPostprocessAllAssets(
        string[] importedAssets, string[] deletedAssets,
        string[] movedAssets, string[] movedFromPath) {
        foreach (string asset in importedAssets) {
            if (asset.Contains("IOSResolver") ||
                asset.Contains("JarResolver")) {
                RegisterDependencies();
                break;
            }
        }
    }
}`
But it's not working now ! Can anyone help me format in the new dependency way ?
[Screenshot](http://prntscr.com/gst2ud)

Sorry I don't know much about android.

**Comment by stewartmiles** [comment]
Did you enable verbose logging?

Is your XML file named correctly and in the right place in your project see https://github.com/googlesamples/unity-jar-resolver#usage

**Comment by AdnanNazir** [comment]
I am doing it right but I think either the library isn't installed or I am having trouble in the URL. 

Here are Errors !

Gradle failed to fetch dependencies.

Failed to run 'Temp\PlayServicesResolverGradle\gradlew.bat -b Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle --no-daemon "-PANDROID_HOME=D:/Softwares/tools_r25.2.3-windows" "-PTARGET_DIR=C:\_\_CameraOpen\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/_/_CameraOpen/extra-google-m2repository;file:///C:/_/_CameraOpen/extra-android-m2repository" "-PPACKAGES_TO_COPY=support-core-utils:com.android.support:25.2.0;com.android.support:support-core-utils:25.2.0"'
stdout:

BUILD FAILED

Total time: 21.068 secs

stderr:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\_\_CameraOpen\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle' line: 270

* What went wrong:
A problem occurred evaluating root project 'PlayServicesResolverGradle'.
> Negative array index [-1] too large for array size 0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

exit code: 1

UnityEngine.Debug:LogError(Object)
GooglePlayServices.PlayServicesResolver:LogDelegate(String, LogLevel)
Google.JarResolver.PlayServicesSupport:Log(String, LogLevel, Boolean)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__20(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__29()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
_________________________________________________________________________


Resolution failed

Failed to fetch the following dependencies:
support-core-utils:com.android.support:25.2.0
com.android.support:support-core-utils:25.2.0


UnityEngine.Debug:LogError(Object)
GooglePlayServices.PlayServicesResolver:LogDelegate(String, LogLevel)
Google.JarResolver.PlayServicesSupport:Log(String, LogLevel, Boolean)
GooglePlayServices.ResolverVer1_1:LogMissingDependenciesError(List`1)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey17:<>m__26(List`1)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__20(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__29()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by stewartmiles** [comment]
From the command

`'Temp\PlayServicesResolverGradle\gradlew.bat -b Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle --no-daemon "-PANDROID_HOME=D:/Softwares/tools_r25.2.3-windows" "-PTARGET_DIR=C:__CameraOpen\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/_/CameraOpen/extra-google-m2repository;file:///C://_CameraOpen/extra-android-m2repository" "-PPACKAGES_TO_COPY=support-core-utils:com.android.support:25.2.0;com.android.support:support-core-utils:25.2.0"'`

There looks like a few problems in here:
- `C:__CameraOpen\Assets\Plugins\Android` doesn't look like a valid path.  What is the path of your CameraOpen project on your machine?  Perhaps something is going wrong with Mono's path manipulation?
- `file:///C:/_/CameraOpen/extra-google-m2repository` appears to point at an invalid Android SDK path.  Have you correctly configured the path of your Android SDK in Unity?

**Comment by AdnanNazir** [comment]
hello my project is in C:\_\_CameraOpen 
but I have configured the Android SDK properly. 
Can you tell if the dependency xml file is correct that I have included ?

**Comment by stewartmiles** [comment]
`C:__CameraOpen` is not a valid path.  `C:\__CameraOpen` is a valid Windows path, notice the `\`.

The path to your Android SDK according to the log you shared is currently pointing at `C:\__CameraOpen`, unless you've placed your Android SDK in your Unity project (a terrible idea), your Android SDK can't be configured correctly.

The command line specifies a couple of packages that the Android Resolver is attempting to fetch `support-core-utils:com.android.support:25.2.0` and `com.android.support:support-core-utils:25.2.0`if you specified though packages in your dependency xml file then yes, it's configured correctly.

**Comment by AdnanNazir** [comment]
Hello, sorry I meant C:\_\_CameraOpen 

Ofcourse I didn't have the SDK in my project :P, but I don't know why the dependencies can't be loaded ? Do I need to update my SDK or what ?

**Comment by stewartmiles** [comment]
Again `C:__CameraOpen` is not a valid windows path.

Here's a demonstration of this from the command line:

```
C:\>mkdir __CameraOpen

C:\>cd :__CameraOpen
The system cannot find the path specified.
```

I tried to reproduce your problem based upon the path you referenced.  I moved a project under the directory `C:\__CameraOpen` on my machine (ended up under `C:\__CameraOpen\unity test\analytics\client\unity\testapp`) then I selected the menu option `Assets > Play Services Resolver > Android Resolver > Force Resolve` which resulted in...

`Command completed: Successfully executed 'Temp\PlayServicesResolverGradle\gradlew.bat -b Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle --no-daemon "-PANDROID_HOME=C:/dev/adt/sdk" "-PTARGET_DIR=C:\__CameraOpen\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/__CameraOpen/Assets/Firebase/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-analytics:11.4.0;com.google.firebase:firebase-core:11.4.0;com.google.firebase:firebase-analytics-unity:4.2.0;com.google.android.gms:play-services-base:11.4.0;com.google.firebase:firebase-common:11.4.0;com.google.firebase:firebase-app-unity:4.2.0"'
stdout:
:copyPackages
Copied artifacts:
firebase-analytics-unity-4.2.0.aar
firebase-app-unity-4.2.0.aar
firebase-analytics-11.4.0.aar
firebase-core-11.4.0.aar
play-services-base-11.4.0.aar
firebase-common-11.4.0.aar
play-services-basement-11.4.0.aar
firebase-analytics-impl-11.4.0.aar
play-services-tasks-11.4.0.aar
firebase-iid-11.4.0.aar
support-v4-25.2.0.aar
support-compat-25.2.0.aar
support-media-compat-25.2.0.aar
`

This is a successful resolution.  Could you enable verbose logging under `Assets > Play Services Resolver > Android Resolver > Settings` run `Assets > Play Services Resolver > Android Resolver > Force Resolve` then share your logs?

**Comment by AdnanNazir** [comment]
I am sorry for still not being able to clear. 
Actually the escape letter was escaping path here (in github comment section)

[see screenshot](https://i.imgur.com/U6CP3j7.png)

**Comment by stewartmiles** [comment]
Hmm, if it works now this makes me wonder whether it's related to f19a6383b24b6cfb037b772ff1a04f953ae29e33 this is the only change I can imagine would make a difference.  The path you shared doesn't seem to contain apostrophes though :/  I guess if the latest version works, that's cool.  Any information you can share to help us root cause the issue to make sure we don't regress will be appreciated.

**Comment by AdnanNazir** [comment]
I do really want to help but I don't exactly know, what made it work perfectly alright?
I have just changed name of my project from _CameraOpen to CameraOpen

 and placed the dependency file from PlayServiceResolver>Editor to Scripts>Editor 

I am even unable to reproduce the issue with the previous version now. Can the issue arise when you don't have the required dependencies installed ? Locally in Android SDK ? I can only guess this, because other than that there is nothing that is changed. My Android SDK path was always correct on Unity Editor because I made android builds many time during all this.

**Comment by stewartmiles** [comment]
It's possible that dependencies resolution could fail if Android SDK manager integration is disabled (see https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/src/SettingsDialog.cs#L246 ) in which case is resolution fails we don't attempt to install the `extra-android-m2repository` repo required for the dependency using the Android SDK manager.  Lets chalk it up to something going wrong with the Android SDK and reopen if this comes up again.
