### ISSUE TITLE
Issue when using 26+ version support library dependencies

### ISSUE THREAD

**Issue by voxelbusters** [googlesamples/unity-jar-resolver#74]
We see an error when using support libraries >=26+ version. This happens when proguard is set.
The runtime-1.0.0.aar was supposed to define its own proguard details but looks like something is failing here by giving the below error.

Does any one have a suggestion?

`stderr[
Note: there were 11 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: android.arch.lifecycle.LifecycleRegistry: can't find superclass or interface android.arch.lifecycle.Lifecycle
...`

**Comment by stewartmiles** [comment]
Hi @voxelbusters ,

- You're talking about the [Android support libraries](https://developer.android.com/topic/libraries/support-library/index.html)?
- You're exporting a gradle project from Unity then attempting to build with proguard enabled in Android Studio?
- What is `runtime-1.0.0.aar` ?  I don't think that is coming from the support libraries, see the distributed set [here](https://developer.android.com/topic/libraries/support-library/packages.html).
- Any chance you have a test project you could share that replicates the problem?

Cheers,
Stewart

**Comment by voxelbusters** [comment]
@stewartmiles Yes. I was talking about Support Libraries.

Yes, it looks strange to me as well. Let me share you the log where Jar Resolver adds 2 aar files which are related to Android Architecture Components.

Please check the log below. I have only one Dependency File defined.

`
﻿﻿﻿Command completed: Successfully executed 'Temp/PlayServicesResolverGradle/gradlew -b Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle --no-daemon "-PANDROID_HOME=/Users/ayyappa/Library/Android/sdk" "-PTARGET_DIR=/Users/ayyappa/Documents/Projects/VoxelBusters/Products/NativePluginsRoot/Unity3d/Assets/Plugins/Android" "-PMAVEN_REPOS=" "-PPACKAGES_TO_COPY=com.google.android.gms:play-services-games:11.0+;com.google.android.gms:play-services-nearby:11.0+;com.google.android.gms:play-services-gcm:11.0+;com.android.support:support-v4:26.1+"'
stdout:
:copyPackages
Copied artifacts:
runtime-1.0.0.aar
common-1.0.0.jar
common-1.0.0.jar
play-services-games-11.0.4.aar
play-services-nearby-11.0.4.aar
play-services-gcm-11.0.4.aar
play-services-base-11.0.4.aar
play-services-basement-11.0.4.aar
play-services-drive-11.0.4.aar
play-services-tasks-11.0.4.aar
play-services-iid-11.0.4.aar
support-v4-26.1.0.aar
support-compat-26.1.0.aar
support-media-compat-26.1.0.aar
support-core-utils-26.1.0.aar
support-core-ui-26.1.0.aar
support-fragment-26.1.0.aar
support-annotations-26.1.0.jar


BUILD SUCCESSFUL

Total time: 12.694 secs

`

I have Play Services at 11.0+ and Support-v4 at 26.1+

**Comment by voxelbusters** [comment]
After digging further, looks like 26.1 is adding those files.
Please check for more info [here](https://developer.android.com/topic/libraries/architecture/release-notes.html#100_alpha_9-1_-_september_13_2017).

However, to make proguard work, looks like we need to add -dontwarn explicitly. This is really sad. Hope google fixes their proguard info.

**Comment by voxelbusters** [comment]
Finally found the reason.

This is the note from google release notes

> This is a special release to integrate the Support Library with Lifecycles from Architecture Components. If you are not using the Lifecycles library, you don’t need to update from 26.0.2. For more information, see the Architecture Components release notes.

As per it, I need to use 26.0.1+ instead of 26.1+. This makes it not dependent on Architecture libraries.

Anyways, Thanks @stewartmiles  for making find a solution.

Cheers,
VB Team
