### ISSUE TITLE
Failing to fetch repositories when one dependency is mentioned

### ISSUE THREAD

**Issue by voxelbusters** [googlesamples/unity-jar-resolver#81]
When there is only one dependency mentioned, its failing to resolve. 
Below line is where the issue happens by throwing " Negative array index [-1] too large for array size 0" error.
  ```
def maxVersion = sortVersionStrings(artifacts.collect {
                                          it.moduleVersion.id.version })[-1]

```

> Gradle failed to fetch dependencies.
> Failed to run 'Temp/PlayServicesResolverGradle/gradlew -b Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle --no-daemon "-PANDROID_HOME=/Users/ayyappa/Library/Android/sdk" "-PTARGET_DIR=/Users/ayyappa/Documents/Projects/VoxelBusters/Products/NativePluginsRoot/Unity3d/Assets/Plugins/Android" "-PMAVEN_REPOS=" "-PPACKAGES_TO_COPY=com.android.support:support-v4:24.2.1"'
> stdout:
> 
> BUILD FAILED
> 
> Total time: 2.033 secs
> 
> stderr:
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/ayyappa/Documents/Projects/VoxelBusters/Products/NativePluginsRoot/Unity3d/Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle' line: 288
> 
> * What went wrong:
> A problem occurred evaluating root project 'PlayServicesResolverGradle'.
> > Negative array index [-1] too large for array size 0
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> exit code: 1
> 
> UnityEngine.Debug:LogError(Object)
> GooglePlayServices.PlayServicesResolver:LogDelegate(String, LogLevel)
> Google.JarResolver.PlayServicesSupport:Log(String, LogLevel, Boolean)
> GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__20(Result)
> GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__2B()
> GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by voxelbusters** [comment]
Anyone else face the same issue?

**Comment by serge-14** [comment]
I have the same issue. So basically gradle will fail if you import only `com.android.support*` dependencies.

For example my project requires only `com.android.support:support-v4:23+`, then when we iterate over `versionLockedModuleIds`, script crashes when checking `~/^com\.google\.(android\.gms|firebase):.*/`, because of there is no module to match that pattern which should be locked to a specific version.

You may add check

```
if (artifacts.size() == 0) {
      return
    }
```

here

https://github.com/googlesamples/unity-jar-resolver/blob/237f55af3c18a045c7a94b2c3efb8b52a1734418/source/PlayServicesResolver/scripts/download_artifacts.gradle#L286

**Comment by martino2k6** [comment]
This is happening to me as well, however I'm trying to import more than one package from a local repository;
```
Command completed: Failed to run 'Temp\PlayServicesResolverGradle\gradlew.bat -b Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle --no-daemon "-PANDROID_HOME=C:/Android/android-sdk" "-PTARGET_DIR=C:\Users\Martin\Documents\unity-sdk\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/Users/Martin/.m2/repository" "-PPACKAGES_TO_COPY=com.deltadna.android:deltadna-sdk-notifications:4.6.0;com.deltadna.android:deltadna-sdk-notifications-redacted:4.6.0"'
stdout:

BUILD FAILED

Total time: 2.185 secs

stderr:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Martin\Documents\unity-sdk\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle' line: 270

* What went wrong:
A problem occurred evaluating root project 'PlayServicesResolverGradle'.
> Negative array index [-1] too large for array size 0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

exit code: 1

UnityEngine.Debug:Log(Object)
GooglePlayServices.PlayServicesResolver:LogDelegate(String, LogLevel)
Google.JarResolver.PlayServicesSupport:Log(String, LogLevel, Boolean)
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result)
GooglePlayServices.<RunAsync>c__AnonStorey1:<>m__0()
```

Using Unity 2017.1.1p4 with Unity Jar Resolver v1.2.52.0.

**Comment by stewartmiles** [comment]
Well you clearly need more dependencies :)

I'll take a look, thanks for reporting.
