### ISSUE TITLE
Bitcode attribute ignored

### ISSUE THREAD

**Issue by dwxw** [googlesamples/unity-jar-resolver#86]
Hello,

I'm playing with the new xml dependencies for cocoapods.  The bitcodeEnabled attribute is being ignored with it always being true.  I've had a quick looking in the code and can [see](https://github.com/googlesamples/unity-jar-resolver/blob/master/source/IOSResolver/src/IOSResolver.cs#L239) it's not setting the flag to false correctly.  I'd make a pull request but then I'd have to speak to legal first, so hopefully this is quicker. :) 

Should also add the code is looking for a 'bitcode' attribute, when I think you intended it to look for 'bitcodeEnabled'.

Otherwise the new xml format for iOS seems to works great.  Thanks again!
David.

**Comment by stewartmiles** [comment]
Oh wow that's embarrassing.  Happy to accept a pull request, lmk :)
