### ISSUE TITLE
Error Attempting Android SDK (Gradle Prebuild)

### ISSUE THREAD

**Issue by Bestlis** [googlesamples/unity-jar-resolver#88]
Hello!
When I try to use Prebuild with gradle it becomes to load sdk libraries but in a few minutes it show error.

I use Unity 5.6.4f1
Windows 7
Android SDK updated to last version.

Error:

Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.

Error (-1):
Traceback (most recent call last):
  File "<string>", line 475, in <module>
  File "<string>", line 467, in main
  File "<string>", line 214, in generate_gradle_build
  File "<string>", line 75, in merge_dir_tree
WindowsError: [Error 123] Syntax error in file name,: u'https://maven.google.com\\*.*'
generate_gradle_prebuild returned -1

UnityEngine.Debug:LogError(Object)
GooglePlayServices.<RunGenGradleScript>c__AnonStoreyE:<>m__11(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
GooglePlayServices.CommandLineDialog:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

When I try do to the same on Mac, I get another error:

Command completed: Failed to run '/usr/bin/python "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py" -c "Temp/config.json" -b "Temp/GenGradle" -o "Assets/Plugins/Android/MergedDependencies"'
stdout:

stderr:
Traceback (most recent call last):
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 476, in <module>
    sys.exit(main())
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 468, in main
    generate_gradle_build(build_path, jsobj)
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 215, in generate_gradle_build
    ignore=shutil.ignore_patterns("*.meta"))
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 76, in merge_dir_tree
    paths = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'https://maven.google.com'

exit code: 1

**Comment by Bestlis** [comment]
Any ideas?

**Comment by Bestlis** [comment]
Does anyone have solution?

**Comment by stewartmiles** [comment]
@Bestlis we have some issues with Gradle Prebuild at the moment.  I recommend you just disable the option for now.  If you're using a recent version of Unity you can instead export an Android Studio project and enable proguard to thin your project.

**Comment by Bestlis** [comment]
I disabled it. But if it disabled, I get 64K overflow. I use ,ultidex, but it split all facebook libraries, as the result, I get ClassNotFoundException.

When do you plan to six this issue?

**Comment by stewartmiles** [comment]
The official way to build an application when you exceed the dex limit is to:
- Export to Android Studio
- Enable proguard to strip unused symbols
- Build

If you still exceed the dex limit, yeah you need to use multi-dex.

The Gradle prebuild effectively - when it works - does the whole Android Studio / Proguard stripping process within Unity so that you don't need the export step.  If you're already at the dex limit in this state, you're going to be out of luck.

Right now the best guess I can give is that we'll revisit this at some point during Q1 next year since there is a workaround for the issue (see above).  If you want to take a crack at fixing the issue I recommend chatting with @johnb003 who is most familiar with this feature.

**Comment by gromilQaaaa** [comment]
faceing the same problem in unity. Can't resolve jars and can't build with proguard because lots of things get to much cutten
![asd](https://user-images.githubusercontent.com/5392680/36066469-c188d472-0eb2-11e8-844a-effb3caeb8bb.PNG)

**Comment by stewartmiles** [comment]
We removed this experimental feature in aa1a6b8e71ccf99bdf1f935851e9242a39d88bd4 .
