### ISSUE TITLE
Explosion of "custom" AARs?

### ISSUE THREAD

**Issue by sonpt** [googlesamples/unity-jar-resolver#94]
Hi,

I'm building a small plugin for Unity and I've incorporated the PlayServicesResolver into it to manage Android dependencies.
I have built some AAR files to use with the plugin, one of them has this ${applicationId} in its manifest since I'm using FileProvider. The resolver doesn't seem to explode this aar and replace the applicationId with the actual one. I tried putting the aar file into Assets/Plugins/Android but no luck.
Some specs:
- Unity 5.6.4 (we also tried 2017.2.0)
- PlayServicesResolver 1.2.59.
- MacOS Sierra 10.12.6.

What should I do to have my own aar files exploded by the resolver?
Thank you in advance and I'm sorry if I missed something obvious.

**Comment by stewartmiles** [comment]
You need to add the AAR as a dependency in a *Dependencies.xml file https://github.com/googlesamples/unity-jar-resolver#usage otherwise the resolve ignores it.

Also, if you have an AAR that you're dropping in the project you'll need to rename it to `.srcaar` to make Unity ignore the file when building your Android application.
https://github.com/googlesamples/google-signin-unity/ has a reasonably simple example of integration.

Cheers,
Stewart

**Comment by sonpt** [comment]
Thank you for your prompt reply!

I studied the google-signin-unity project and update my module's build.gradle like this

`apply plugin: 'com.android.library'
apply plugin: 'maven'

group "com.example.test_plugin"
project.ext.baseName = "my-android-library"

// Current version is 1.0.2
if (project.hasProperty("pluginVersion")) {
    project.version = project.pluginVersion  
} else {
    project.version '0-SNAPSHOT'
}
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 19
        versionName project.version
        archivesBaseName = project.ext.baseName
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false  // not recommended, should enable later on
    }
}

// Rename the .aar file to be .srcaar to work around
// having the local repo in a subdirectory in a Unity project.
// The jar resolver plugin handles the changing back from .srcaar
// to .aar
//
// This is done in 2 parts, first declare the .srcaar as an
// artifact, the second is a task to rename the aar -> srcaar.

artifacts {
    archives file("build/${baseName}-${version}.srcaar")
}

task renameLibrary() {
    doFirst {
        copy {
            from "${buildDir}/outputs/aar/${baseName}-release.aar"
            into "${buildDir}/outputs/scraar/"
            println "***Renaming .aar to .srcaar"
            rename {
                String fn ->
                    return fn.replace("release.aar", "${version}.srcaar")
            }
        }
    }

    doLast {
        configurations.archives.with {
            artifacts.remove artifacts.find { it.extension == "aar" }
        }
    }
}

dependencies {
    provided files('libs/UnityPlayer.jar')
    compile 'com.android.support:support-v4:22.1.+'
}

task build_all() {
    dependsOn assemble, renameLibrary
}`

After running the build_all task, I manually copied the exported my-android-library-1.0.2.scraar file into my Unity project at folder Assets/My_Plugin/Plugins/Android.
Then I updated the Dependencies.xml for the jar resolver to recognize the .scraar like this
`<dependencies>
  <androidPackages>
    <androidPackage spec="com.example.test-plugin:my-android-library:1.0.2">
      <repositories>
        <repository>Assets/My_Plugin/Plugins/Android</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
</dependencies>`

However, the resolver kept giving me the error "Missing Android component com.example.test-plugin:my-android-library:1.0.2@aar (Android SDK Packages: (none))", which means it couldn't locate the .scraar from the folder given in the repository tag.

What am I missing here? 

Again, thank you very much for your help!

**Comment by stewartmiles** [comment]
You also need to create a maven repo for the srcaar.  If you take a look folder and file structure in the google-signin plugin, you'll see it has a maven repository that references the srcaar.  The maven repo is required for gradle to discover the dependency.  If you want to debug this outside of Unity you can turn on verbose logging and copy the gradle command line generated by the Android Resolver into a command line.

**Comment by sonpt** [comment]
It works!
Thank you for pointing me the right direction. I had no experience with publishing artifacts to Maven repos before, so learned a lot this time. Obviously the build.gradle must contain an uploadArchives task, as done in the google-signin plugin.
I believe this piece of knowledge would benefit many other users, and it should be mentioned in more detail in the doc :)
Thanks again!

**Comment by stewartmiles** [comment]
@sonpt we would appreciate pull requests :)  I'm glad it worked out 👍

**Comment by sonpt** [comment]
@stewartmiles do you want me to update the README.md and send a pull request? 
If yes, will do so when I find time this weekend :)

**Comment by stewartmiles** [comment]
@sonpt if you could update README.md with a section that describes how to add custom AARs / JARs to a project that would be great.  Yeah feel free to send us a pull request.
