### ISSUE TITLE
Firebase and gradle build

### ISSUE THREAD

**Issue by RadekOlenski** [googlesamples/unity-jar-resolver#95]
Hi,
I have a massive problem with firebase and gradle build in Unity so I decided to ask You guys about it - maybe someone will know the solution.

So I will describe what i do and what the outcome is:

 1. I create new project in Unity, set it up for Android build (gradle), add keystores, set up custom gradle template - adding support for multidex
 2. Import Firebase Auth unitypackage (newest version 4.3.0), initial firebase config (adding google-services.json and GoogleService-Info.plist)
 3. Untick "Explode AARs" option in Android Play Service Resolver
 4. Force resolve in Android Resolver

And now I get really strange errors in console:

![gradle](https://user-images.githubusercontent.com/16166680/34009086-d76080b6-e107-11e7-8e6f-5336a151a754.PNG)

So at this point I try to build game - and it builds, but after start it throws exception related to Firebase Auth:

![logcat](https://user-images.githubusercontent.com/16166680/34009097-e0456778-e107-11e7-9456-fd0ce11516d5.PNG)

And that's basically it. I spent a lot of time trying to figure it out and make it work but I am just helpless. Also that problem concern not only Firebase Auth but basically every google service related lib (e.g. Firebase Analytics, or Google Sign-In) 

If anyone can help mi out there I will be really gratefull.
Thanks!

**Comment by stewartmiles** [comment]
Hi @RadekOlenski, looks like we missed this.  Do you have the rest of the exception in the stack trace?

The conflicts reported sound like the AARs are being included twice in your project.  In the screenshot you shared there is a project (from the exploded AAR) firebase-analytics-impl-license and an AAR of the same name. I'm guessing that this is true for the others as well.

Have you tried manually deleting all firebase-* and play-services-* files under Assets/Plugins/Android and running resolution again to resolve the duplicates?

**Comment by RadekOlenski** [comment]
Hi @stewartmiles, thanks for the response!

I've done some updates just now to firebase and resolver and the problem still exists. I can't really say if it has any impact on game, it all seems to work, the game is building and behaves well on device. But still, I'm wondering what can cause that strange warnings.

I tried to remove aar files manually as you mentioned, but as soon as I ran the resolution they appeared again and the warnings were still there.

Here is the full exception, it's the same one for every firebase lib or play services
![image](https://user-images.githubusercontent.com/16166680/35238290-543c6cee-ffad-11e7-9268-2e110bd2e086.png)

If you have any idea what can be wrong or if you feel that I really shouldn't be worried about it, please let me know.

Thanks!

**Comment by stewartmiles** [comment]
@RadekOlenski it's not just the .aar / .jar files, if explosion is enabled folders are created with the same name as the .aar / .jar.  For example...

`Assets/Plugins/Android/firebase-app-unity.aar`

will be exploded / unpacked into:

`Assets/Plugins/Android/firebase-app-unity`

and - if exploded - the original archive `Assets/Plugins/Android/firebase-app-unity.aar` will be deleted.

If something interrupts this process you could end up with the original archive file *and* the exploded folder which is leading to the Android Resolver detecting and warning you about duplicate packages.  The solution - as mentioned previously - would be to delete each .aar / .jar *and* folder of the same name allowing the Android Resolver repopulate the directory.

**Comment by RadekOlenski** [comment]
@stewartmiles I understand, conflicting exploded folders would make perfect sense but the problem is I get warnings with disabled explosion... I double checked and there are none of expolded folders anywhere in Assets folder. I tired to make resolution with enabled explosion but the result was the same - warnings in console and only .aar files in Assets/Plugins/Android/ without folders.

**Comment by RadekOlenski** [comment]
@stewartmiles I made some quick test right now - I created a clean project (newest Unity version 2017.3.0f3), changed platform to Android and imported .unitypackage of Firebase Analytics. It immediatly resulted with the same warnings just after resolution was done. 
I'm starting to think that this is a problem with Firebase package itself...

**Comment by stewartmiles** [comment]
@RadekOlenski I see, I just reproduced this.  It looks like a load of warnings are reported when the build system is set to "Gradle" in Unity 2017.3.   Thanks for reporting this 👍 As you point out it doesn't seem to break the build as it's complaining about non-existent folders (perhaps the Unity Asset Database is out of sync), but wow it's pretty spammy and annoying, we'll take a look.

**Comment by RadekOlenski** [comment]
@stewartmiles Great! Thanks for looking into this and good luck :)
