### ISSUE TITLE
Prebuild with Gradle error

### ISSUE THREAD

**Issue by LocDeveloper** [googlesamples/unity-jar-resolver#96]
Hi,

Unity 2017.2.0f3, Windows 10.
There is an issue when turning on Prebuild with Gradle (Android):

> Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.
Error (-1):
Traceback (most recent call last):
  File "<string>", line 475, in <module>
  File "<string>", line 467, in main
  File "<string>", line 214, in generate_gradle_build
  File "<string>", line 75, in merge_dir_tree
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: u'https://maven.google.com*.*'
generate_gradle_prebuild returned -1
UnityEngine.Debug:LogError(Object)
GooglePlayServices.<RunGenGradleScript>c__AnonStoreyE:<>m__11(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
GooglePlayServices.CommandLineDialog:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

I try to change url "https://dl.google.com/dl/android/maven2/" but not luck.any one can help.
Thank you in advance for any assistance.

**Comment by stewartmiles** [comment]
We removed this experimental feature in aa1a6b8e71ccf99bdf1f935851e9242a39d88bd4 .
